- modules/flowable-engine/src/test/java/org/activiti/engine/test/bpmn/subprocess/adhoc/AdhocSubProcessTest.java
- modules/flowable-engine/src/test/java/org/activiti/engine/test/history/HistoricProcessInstanceTest.java
- modules/flowable-engine/src/test/java/org/activiti/standalone/escapeclause/HistoricTaskQueryEscapeClauseTest.java
- modules/flowable-engine/src/test/java/org/activiti/standalone/escapeclause/TaskQueryEscapeClauseTest.java
- modules/flowable-engine/src/test/java/org/activiti/standalone/history/FullHistoryTest.java
This addresses Issue #[8 ](https://github.com/flowable/flowable-engine/issues/8) and makes the JUnit tests succeed on Windows.
> Account for nondeterministic ordering when timestamp orderby values are equal

- modules/flowable-engine/src/test/java/org/activiti/engine/test/api/runtime/ProcessInstanceSuspensionTest.java
Added an 'assertTrue()' so the 'e.getMessage().contains("is suspended")' statements had some value.
> Add missing assertTrue() when checking for contains()

- modules/flowable-engine/src/main/java/org/activiti/engine/impl/HistoricVariableInstanceQueryImpl.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/cmd/GetDataObjectCmd.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/cmd/SaveProcessDefinitionInfoCmd.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/history/DefaultHistoryManager.java
The details for each change:
- DefaultHistoryManager: remove check for activitiyId as already checked on line 265
- GetDataObjectCmd: remove check for variableEntity as already checked on line 93
- HistoricVariableInstanceQueryImpl: remove check for variableEntity as if it was null then the instanceof check on line 227 would have failed
- SaveProcessDefinitionInfoCmd: remove check for infoNode as already checked on line 48
> Remove redundant null checks

- modules/flowable-engine/src/main/java/org/activiti/engine/CandidateManager.java
- modules/flowable-engine/src/main/java/org/activiti/engine/DefaultCandidateManager.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/HistoricTaskInstanceQueryImpl.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/ProcessDefinitionQueryImpl.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/TaskQueryImpl.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java
Most projects will have their own user/group/role management, so will not need the IdmIdentityManager. This PR greatly simplifies the interface to implement for getGroupsForCandidateUser support in such cases.
> Add interface CandidateManager for getGroupsForCandidateUser

- modules/flowable-idm-engine/src/main/java/org/activiti/idm/engine/IdmEngineConfiguration.java
- modules/flowable-idm-engine/src/main/java/org/activiti/idm/engine/IdmEngines.java
- modules/flowable-idm-engine/src/main/java/org/activiti/idm/engine/impl/cfg/IdGenerator.java
- modules/flowable-idm-engine/src/main/java/org/activiti/idm/engine/impl/interceptor/CommandContextFactory.java
- modules/flowable-idm-engine/src/main/java/org/activiti/idm/engine/impl/persistence/entity/AbstractEntityManager.java
- modules/flowable-idm-engine/src/main/java/org/activiti/idm/engine/impl/persistence/entity/data/AbstractDataManager.java
- modules/flowable-idm-engine/src/main/java/org/activiti/idm/engine/test/ActivitiIdmRule.java
Motivated by the recent change of marcus-nl where 'dmn' was changed to 'idm' in the flowable-idm-engine project, this patch includes more of such changes for that same project.
After making the changes "mvn clean test" was run successfully.
> More dmn to idm changes

- modules/flowable-engine/src/main/java/org/activiti/engine/impl/AbstractVariableQueryImpl.java
- modules/flowable-engine/src/main/resources/org/activiti/db/mapping/entity/Execution.xml
- modules/flowable-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricTaskInstance.xml
- modules/flowable-engine/src/main/resources/org/activiti/db/mapping/entity/Task.xml
- modules/flowable-engine/src/test/java/org/activiti/engine/test/api/history/HistoricTaskAndVariablesQueryTest.java
- modules/flowable-engine/src/test/java/org/activiti/engine/test/api/runtime/ProcessInstanceAndVariablesQueryTest.java
- modules/flowable-engine/src/test/java/org/activiti/engine/test/api/task/TaskAndVariablesQueryTest.java
- modules/flowable-engine/src/test/resources/org/activiti/engine/test/api/history/HistoricTaskAndVariablesQueryTest.testOrQueryMultipleVariableValues.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/activiti/engine/test/api/task/TaskAndVariablesQueryTest.testOrQuery.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/activiti/engine/test/api/task/TaskAndVariablesQueryTest.testOrQueryMultipleVariableValues.bpmn20.xml
I addressed the same problem of Activiti/Activiti#988 (resolved with Activiti/Activiti#989) for Process Instance, Task and Historic Task queries.
I created a similar pull request for Activiti (Activiti/Activiti#1053), but this one is specific for flowable and can be merged directly.
> Remaining optimizations for 'or queries' with multiple process variable values

- modules/flowable-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/CallActivityBehavior.java
- modules/flowable-engine/src/test/java/org/activiti/engine/test/api/event/VariableEventsTest.java
- modules/flowable-engine/src/test/resources/org/activiti/engine/test/api/runtime/callActivity.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/activiti/engine/test/api/runtime/calledActivity.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/activiti/engine/test/api/runtime/processVariableEvent.bpmn20.xml
This change makes CallActivityBehavior consistent with the variable event behavior for starting a process via the API.
- Modeled DataObjects - send VARIABLE_CREATED event
- Variables passed in via API call or CallActivity send a VARIABLE_UPDATED event if the variable was modeled as a dataobject otherwise a VARIABLE_CREATED event is sent.
> Update CallActivityBehavior to send VARIABLE_UPDATED events.

- modules/flowable-engine/src/main/java/org/activiti/engine/impl/cmd/GetTaskFormModelCmd.java
An exception message was using a known null value.
Change:
`throw new ActivitiObjectNotFoundException("Task not found with id " + task.getId()); `
to
`throw new ActivitiObjectNotFoundException("Task not found with id " + taskId);`
> Do not deference a known null value

- modules/flowable5-compatibility/src/main/java/org/activiti/compatibility/DefaultActiviti5CompatibilityHandler.java
Partially created objects can be returned by the Double Checked Locking pattern when used in Java. An optimizing JRE may assign a reference to the baz variable before it calls the constructor of the object the reference points to.
The fix is to make the variable 'volatile'.
For more details refer to [this JavaWord article]( http://www.javaworld.com/javaworld/jw-02-2001/jw-0209-double.html) or this [discussion](http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html).
This code has been present since the file was created given the git history.
> Fix double checked locking pattern.

- modules/flowable-engine/src/main/java/org/activiti/engine/DynamicBpmnService.java
- modules/flowable-engine/src/main/java/org/activiti/engine/dynamic/BasePropertiesParser.java
- modules/flowable-engine/src/main/java/org/activiti/engine/dynamic/DefaultPropertiesParser.java
- modules/flowable-engine/src/main/java/org/activiti/engine/dynamic/DynamicProcessDefinitionSummary.java
- modules/flowable-engine/src/main/java/org/activiti/engine/dynamic/PropertiesParser.java
- modules/flowable-engine/src/main/java/org/activiti/engine/dynamic/PropertiesParserConstants.java
- modules/flowable-engine/src/main/java/org/activiti/engine/dynamic/ScriptTaskPropertiesParser.java
- modules/flowable-engine/src/main/java/org/activiti/engine/dynamic/UserTaskPropertiesParser.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/DynamicBpmnServiceImpl.java
- modules/flowable-engine/src/test/java/org/activiti/engine/test/bpmn/dynamic/DynamicCandidateGroupsTest.java
- modules/flowable-engine/src/test/java/org/activiti/engine/test/bpmn/dynamic/DynamicProcessDefinitionSummaryTest.java
- modules/flowable-engine/src/test/resources/org/activiti/engine/test/bpmn/dynamic/dynamic-bpmn-test-process.bpmn20.xml
* Helper method to reset an dynamic property to its original bpmn model value.
* Summary object to trace diffs between processDefinitionInfo and BpmnModel.
* Helper methods to set a Collection of Strings on candidategroups and candidateUsers.
* Unit / integration tests to check the newly added methods.
> Improvement to DynamicBpmnservice

- modules/flowable-cxf/src/main/java/org/flowable/engine/impl/webservice/CxfWSDLImporter.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/deployer/BpmnDeployer.java
- modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/cmd/GetVariablesFromFormSubmissionCmd.java
- modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/el/JsonNodeELResolver.java
- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/BpmnJsonConverter.java
- modules/flowable-ui-common/src/main/java/org/flowable/app/security/SecurityUtils.java
- modules/flowable-ui-task/flowable-ui-task-logic/src/main/java/org/flowable/app/service/runtime/FlowableAbstractTaskService.java
- modules/flowable-ui-task/flowable-ui-task-logic/src/main/java/org/flowable/app/service/runtime/PermissionService.java
Since the instanceof operator always returns false for null, there is no need to have an additional null check.
Here is an example of the change:
` if (x != null && x instanceof String) { ... }`
Becomes:
`if (x instanceof String) { ... }`
Also made a small change to one Javadoc instance that defined a parameter that did not exist.
> Remove unnecessary 'null' check before 'instanceof' expression.

- modules/flowable-camel/src/test/java/org/flowable/camel/CustomContextTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/SimpleProcessTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/error/route/OutboundErrorRoute.java
- modules/flowable-mule/src/test/java/org/flowable/mule/MuleHttpBasicAuthTest.java
- modules/flowable-mule/src/test/java/org/flowable/mule/MuleHttpTest.java
- modules/flowable-mule/src/test/java/org/flowable/mule/MuleVMTest.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/engine/EventResponse.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/engine/variable/RestVariable.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/identity/UserInfoRequest.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/identity/UserResponse.java
- modules/flowable-secure-javascript/src/main/java/org/flowable/scripting/secure/impl/SecureScriptContext.java
- modules/flowable5-camel-test/src/test/java/org/activiti/camel/CustomContextTest.java
- modules/flowable5-camel-test/src/test/java/org/activiti/camel/SimpleProcessTest.java
- modules/flowable5-camel-test/src/test/java/org/activiti/camel/error/route/OutboundErrorRoute.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ByteArrayEntity.java
- modules/flowable5-mule-test/src/test/java/org/activiti/mule/MuleHttpBasicAuthTest.java
- modules/flowable5-mule-test/src/test/java/org/activiti/mule/MuleHttpTest.java
- modules/flowable5-mule-test/src/test/java/org/activiti/mule/MuleVMTest.java
By using IntelliJ IDEA's code inspection, I find out all deprecated API usages, but still have [one](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-cdi/src/main/java/org/flowable/cdi/impl/annotation/StartProcessInterceptor.java#L58) I don't know how to fix it, It calls [startProcessByName](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-cdi/src/main/java/org/flowable/cdi/BusinessProcess.java#L222) has been annotated with deprecated.
> Clean up more deprecated usages

- modules/flowable-engine/src/main/java/org/flowable/engine/debug/ExecutionTreeNode.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/data/impl/util/ExecutionTreeStringBuilder.java
- modules/flowable-mule/src/test/java/org/flowable/mule/AbstractMuleTest.java
- modules/flowable-process-validation/src/main/java/org/flowable/validation/ValidationError.java
- modules/flowable-rest/src/test/java/org/flowable/rest/api/jpa/BaseJPARestTestCase.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/BaseSpringRestTestCase.java
Fixes occurrences of string concatenation used as the argument to an existing StringBuffer.append() or StringBuilder.append().   Turned them into chained append calls saving the cost of an extra StringBuffer or StringBuilder allocation.
Besides it looks nicer too.
> Fix mixture of append() and string concatenation

- modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/HistoricTaskQueryEscapeClauseTest.java
Make the testQueryByTaskNameLikeIgnoreCase() method match the same allocation strategy for the tasks ArrayList as other methods in the file.
> Add target for ArrayList allocation to testQueryByTaskNameLikeIgnoreCase()

- modules/flowable-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/AbstractAsyncJobExecutor.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/AcquireAsyncJobsDueRunnable.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/AsyncExecutor.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/DefaultAsyncJobExecutor.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/multitenant/ExecutorPerTenantAsyncExecutor.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/multitenant/SharedExecutorServiceAsyncExecutor.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/cfg/multitenant/MultiSchemaMultiTenantProcessEngineConfiguration.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/cfg/multitenant/TenantAwareDataSource.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/cmd/AcquireAsyncJobsDueCmd.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/cmd/UnacquireJobsCmd.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/cmd/UnacquireOwnedJobsCmd.java
- modules/flowable-engine/src/main/java/org/activiti/engine/impl/persistence/entity/JobEntityManager.java
- modules/flowable-engine/src/main/resources/org/activiti/db/mapping/entity/Job.xml
- modules/flowable-engine/src/test/java/org/activiti/engine/test/cfg/multitenant/DummyTenantInfoHolder.java
- only attempt to acquire new jobs if the queue has capacity.
- only attempt to acquire at most the number of jobs that fit in the queue.
- if there are still rejected jobs, unacquire them.
- option to unacquire all jobs by lock owner at startup.
> AsyncExecutor improvements

- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/persistence/deploy/DecisionTableCacheEntry.java
The variable `decisionTableEntity` was assigned to itself instead of using the method parameter `decisionTable`,
> Variable was assigned to itself

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/helper/SkipExpressionUtil.java
In PR#44 an unnecessary null check was added before the instanceof check; removing it.
> Remove unnecessary null check

- modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/CustomExtensionsConverterTest.java
- modules/flowable-bpmn-layout/src/main/java/org/flowable/bpmn/BPMNLayout.java
- modules/flowable-cdi/src/main/java/org/flowable/cdi/impl/FlowableExtension.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/agenda/ContinueProcessOperation.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/agenda/TakeOutgoingSequenceFlowsOperation.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/delegate/invocation/JavaDelegateInvocation.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/DefaultHistoryManager.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/HistoricActivityInstanceEntityImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/HistoricProcessInstanceEntityImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/HistoricVariableInstanceEntityManagerImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ModelEntityManagerImpl.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CancelCallActivityTest.java
- modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/cmd/GetVariablesFromFormSubmissionCmd.java
- modules/flowable-json-converter/src/test/java/org/flowable/editor/language/UserTaskConverterTest.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/BpmnDeployer.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/bpmn/helper/ScopeUtil.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/handler/ErrorEventDefinitionParseHandler.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/delegate/JavaDelegateInvocation.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/history/DefaultHistoryManager.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/EventSubscriptionEntityManager.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntity.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricActivityInstanceEntity.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricProcessInstanceEntity.java
Remove redundant and unneeded casts.  I am assuming that some of these are the product of renaming and rearranging of code.  
I was conservative in the changes primarily removing casts where the datatype was already declared to be the same or was defined as the type of a collection.
There are more removal possibilities but they were less obvious and may aid in code comprehension so I did not change them.
I ran the compile and test targets and they were clean.
> Remove redundant casts

- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/UserTaskXMLConverter.java
- modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/fs/FileSystemContentStorage.java
- modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/fs/SimpleFileSystemContentStorage.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/ValidateExecutionRelatedEntityCountCfgCmd.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryServiceTest.java
- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/BpmnJsonConverterUtil.java
- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/UserTaskJsonConverter.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/boot/AbstractProcessEngineConfiguration.java
Remove calls 'toString()' on a String object and remove call to String.format() where there are no arguments thus only the string is required.
> Redundant String.toString() and String.format() calls removed

- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/ValuedDataObjectXMLConverter.java
- modules/flowable-crystalball/src/main/java/org/flowable/crystalball/simulator/AbstractSimulationRun.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/asyncexecutor/ResetExpiredJobsRunnable.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/handler/StartEventParseHandler.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntity.java
Correct logging messages with mismatched number of placeholders and arguments.
I did **not** correct these as it is not clear as to the correct value/change is:
`org.flowable.engine.impl.asyncexecutor.AcquireAsyncJobsDueRunnable`
line 45: `log.info("{} starting to acquire async jobs due");`
`org.flowable.engine.impl.asyncexecutor.AcquireTimerJobsRunnable` has a similar problem at lines 49 and 115.
`org.flowable.engine.impl.asyncexecutor.ResetExpiredJobsRunnable` has a similar problem at lines 51 and 99.
> Logging messages with mismatch placeholders and arguments

- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/BpmnXMLConverter.java
Both `Transaction` and `AdhocSubProcess` are `SubProcess`'s subclasses, so if `subProcess instanceof Transaction == false` condition is `true`, the last condition `subProcess instanceof AdhocSubProcess` will never be touched, this may a potential issue.
> fix a never touched if branch

- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/CustomConfigRuntimeTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/RuntimeTest.java
- modules/flowable-dmn-json-converter/src/test/java/org/flowable/editor/dmn/converter/DmnJsonConverterTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/ProcessInstanceEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryServiceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/RuntimeServiceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/RuntimeVariablesTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskVariablesTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/usertask/TaskDueDateExtensionsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/history/HistoricVariableInstanceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/impl/calendar/MapBusinessCalendarManagerTest.java
- modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/shell/ShellTaskTest.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-integration/src/test/java/org/flowable/test/spring/boot/IntegrationAutoConfigurationTest.java
Addresses issue #49 from the [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154).
> Fix misordered arguments to assertXXX()

- userguide/src/en/ch01-Introduction.adoc
The Eclipse Designer supports Mars and Neon as stated later in Chapter 11.  This changes the introduction section to match.
> Make introduction match the Eclipse Installation section re: Versions

- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/engine/variable/QueryVariable.java
- modules/flowable-rest/src/test/java/org/flowable/rest/api/engine/variable/QueryVariableTest.java
The class org.flowable.rest.service.api.engine.variable..QueryVariable.java has two problems.
First, the `setOperation()` method is missing so when serializing the `QueryRequest` object with
JSONNode  the operation property is not present and instead only the `variableOperation` property exists.  So before the change `getOperation()` returns null and after the change the appropriate value is returned.
Second, after adding `setOperation()`, the reconstituting the object throws an exception about the `variableOperation` property:
```java
java.lang.IllegalArgumentException: Unrecognized field "variableOperation" (class org.flowable.rest.service.api.engine.variable.QueryVariable), not marked as ignorable (4 known properties: "value", "type", "name", "operation"])
at [Source: N/A; line: -1, …
```
> Fix serialization of rest QueryVariable class

- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/util/BitMaskUtil.java
Port the same change made in org.flowable.engine.common.impl.util.BitMaskUtil in the Version 6 code to the flowable5-engine module.
Not a big deal because it looks like the routines are never used.
> Fix misused && with ||

- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricTaskInstanceBaseResource.java
Remove the if test as the same variable is tested above at line 260 making the **then** branch of the **if** unneeded:
<pre>
if (nameLess) {
throw new FlowableIllegalArgumentException("Value-only query (without a variable-name) is not supported.");
}
</pre>
> Remove useless if test

- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java
The variable, `listeners` was dereferenced to find the size of the list and then it was checked for `null`.  Changed the order of the calls.
> Move dereference of variable after the null check

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/RescheduleTimerJobCmd.java
The exception message concatenates a known null value so simplify the message but including it as part of the literal message text.
Another alternative would be to reword the text but that option was not chosen.
> Ambiguous use of null in exception message

- modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/persistence/StrongUuidGenerator.java
- modules/flowable-ui-common/src/main/java/org/flowable/app/repository/UuidIdGenerator.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/StrongUuidGenerator.java
Partially created objects can be returned by the Double Checked Locking pattern when used in Java. An optimizing JRE may assign a reference to the baz variable before it calls the constructor of the object the reference points to.
The fix is to make the variable 'volatile'.
For more details refer to [this JavaWord article]( http://www.javaworld.com/javaworld/jw-02-2001/jw-0209-double.html) or this [discussion](http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html).
This is the same fix as PR  #56
> Fix double check locking pattern

- modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/impl/persistence/entity/UserEntityImpl.java
See the diff that now allocates `pictureByteArrayRef` if null.  The original code could generate a NPE.
> Correct test for null

- modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/util/DmnXMLUtil.java
Remove the assignment to the local variable `didWriteExtensionStartElement` in the return statement.
This now matches the similar routine in `org.flowable.bpmn.converter.util.BpmnXMLUtil.java` (lines 203-204) from which this code appears to have been derived.
<pre>
public static boolean writeExtensionElements(BaseElement baseElement, boolean didWriteExtensionStartElement, XMLStreamWriter xtw) throws Exception {
return writeExtensionElements(baseElement, didWriteExtensionStartElement, null, xtw);
}
</pre>
> Remove local variable in return statement

- modules/flowable-bpmn-layout/src/main/java/org/flowable/bpmn/BpmnAutoLayout.java
Change "shape=ellipse;perimter=ellipsePerimeter"  to "shape=ellipse;perimeter=ellipsePerimeter" based on  the fact the spelling of "perimter" looked wrong and the info on the web about mxgraph and [mxPerimeter](https://jgraph.github.io/mxgraph/docs/js-api/files/view/mxPerimeter-js.html).
Full disclosure: I did *not* test the change.
> Fix spelling of eclipse perimeter argument

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/NeedsActiveProcessDefinitionCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/ProcessDefinitionUtil.java
The null check is unreachable in `NeedsActiveProcessDefinitionCmd` because the call to `ProcessDefinitionUtil.getProcessDefinitionFromDatabase` does the same check.
Also changed the exception in `ProcessDefinitionUtil.getProcessDefinitionFromDatabase` to be the more specific version.
> Unreachable

- modules/flowable5-test/src/test/java/org/activiti/engine/test/api/history/HistoryServiceTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/api/runtime/RuntimeVariablesTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/api/task/TaskVariablesTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/history/HistoricVariableInstanceTest.java
- modules/flowable5-test/src/test/java/org/activiti/examples/bpmn/servicetask/ExpressionServiceTaskTest.java
Remove objects created where the value is never used.
In the process found that there was a cut-n-paste error in the `flowable5-test` module in the `org.activiti.examples.bpmn.servicetask.ExpressionServiceTaskTest` class where a variable was defined but not used.  Ported the version 6 version of the test method back to `flowable5-test`.
> Remove or fix useless object creation

- pom.xml
Arguments for upgrading:
- versions below 2.4.8 are affected by CVE-2016-6814
- 2.4.8 improves java 9 compatiblity
Note that the poms contained in  `modules\flowable-spring-boot` still use groovy 1.7.5, but I could not build them locally, so I did not try updating them.
> update groovy version to 2.4.8

- modules/flowable-rest/src/test/java/org/flowable/rest/api/engine/variable/QueryVariableTest.java
Reporting and fixing my own error (egg on my face) that resulting from cut-n-paste of the `assert` tests. The second set of checks should be on the new deserialized version and not the original variable.
> Fix cut-n-paste error in recently added test

- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/UserTaskJsonConverter.java
Candidate group and user IDs were being incorrectly coerced into Long values in the JSON converter.
> Fix XML import of models in the editor.

- modules/flowable-webapp-explorer2/src/main/webapp/editor-app/configuration/properties-message-scope-controller.js
Small fix to make predefined message definitions appear in the combo box of the boundary event.
> minor fix to prototype upgrade.

- modules/flowable-common-rest/src/main/java/org/flowable/rest/variable/StringRestVariableConverter.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/SimulationEventComparatorTest.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/playback/AbstractPlaybackTest.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/EventSubscriptionQueryImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetDataObjectsCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/NeedsActiveProcessDefinitionCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/event/logger/handler/TaskCompletedEventHandler.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/compatibility/IntermediateTimerEventRepeatCompatibilityTest.java
- modules/flowable-json-converter/src/test/java/org/flowable/editor/language/ServiceTaskConverterTest.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/ModelServiceImpl.java
- modules/flowable-ui-task/flowable-ui-task-rest/src/main/java/org/flowable/app/rest/runtime/variable/StringRestVariableConverter.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/cmd/GetNextIdBlockCmd.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntity.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricDetailEntityManager.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/api/event/JobEventsTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/api/event/ProcessInstanceEventsTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/bpmn/event/timer/StartTimerEventRepeatWithEndExpressionTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/bpmn/event/timer/StartTimerEventRepeatWithEndTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/bpmn/event/timer/StartTimerEventRepeatWithoutEndDateTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/bpmn/event/timer/compatibility/StartTimerEventRepeatCompatibilityTest.java
Miscellaneous cleanup:
(1) Unused imports
(2) Imports from the same package
(3) Unnecessary casts
(4) Use == for enum comparisons instead of equals()
etc.
> Misc. cleanup

- modules/flowable-cdi/src/test/java/org/flowable/cdi/test/api/BusinessProcessBeanTest.java
- modules/flowable-cdi/src/test/java/org/flowable/cdi/test/api/annotation/CompleteTaskTest.java
- modules/flowable-cdi/src/test/java/org/flowable/cdi/test/api/annotation/StartProcessTest.java
In the `flowable-cdi` module the package names for the resources changed from `org.activiti.cdi.test` to `org.flowable.cdi.test` but the java code annotations for the `@Deployment` annotation location did not change.  This request changes the names to match.  
I *did* not test the change but it looks correct.
> Fix resource package names for deployment resources

- modules/flowable-dmn-engine/src/test/resources/log4j.properties
Found the same issue in `flowable-dmn-engine`: change package from `activiti` to `flowable`.
> Fix package name in log4j.properties file

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/el/ExpressionManager.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/el/FlowableTypeConverter.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/TimerUtil.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/BoundaryTimerEventRepeatWithDurationAndEndTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/BoundaryTimerEventRepeatWithDurationTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/BoundaryTimerEventRepeatWithStartAndDurationTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/timer/BoundaryTimerEventRepeatWithDurationAndEndTest.testRepeatWithDurationAndEnd.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/timer/BoundaryTimerEventRepeatWithDurationTest.testRepeatWithDuration.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/timer/BoundaryTimerEventRepeatWithStartAndDurationTest.testRepeatWithStartAndDuration.bpmn20.xml
Problem
Flowable persists the repeat timer string to the timer jobs table.   Datetime strings are either formatted in ISO8601 local time or non-ISO8601 string.
Fix
Datetime strings returned in the API (new the timer API) should be in ISO8601 Zulu time.  Zulu time should be used (not localtime) in case you have multiple clients running in different timezones.
Details
If the repeat is specified as R/<duration>, flowable determines the start time using the duration and persists the repeat field as R/’start datetime string’/<duration>
TimerUtil.prepareRepeat() is the method that formats the string.  It was formatting it in ISO8601 local time. It has been updated it to use ISO 8601 Zulu time.
If the repeat is specified with either a startDate or endDate datetime variable such as, …
> ISO8601 Zulu time updates

- modules/flowable-engine/src/main/java/org/flowable/engine/delegate/event/FlowableEngineEventType.java
- modules/flowable-engine/src/main/java/org/flowable/engine/delegate/event/FlowableJobRescheduledEvent.java
- modules/flowable-engine/src/main/java/org/flowable/engine/delegate/event/impl/FlowableEventBuilder.java
- modules/flowable-engine/src/main/java/org/flowable/engine/delegate/event/impl/FlowableJobRescheduledEventImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/asyncexecutor/DefaultJobManager.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/JobEventsTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/event/JobEventsTest.testJobEntityEventsForRescheduleTimer.bpmn20.xml
Reschedule call should throw JOB_CANCELED event since existing timer is terminated and new timer created.
> Reschedule should throw job rescheduled event

- modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/util/DefaultClockImpl.java
Update DeafultClockImpl to support specified TimeZone.  If not specified, it will continue to use the JVM's TimeZone.  The CURRENT_TIME variable changed to protected to make it easier to extend if needed.
> Update DefaultClockImpl to support specified timezone

- modules/flowable-cxf/src/main/java/org/flowable/engine/impl/webservice/CxfWebServiceClient.java
- modules/flowable-cxf/src/main/java/org/flowable/engine/impl/webservice/CxfWebServiceClientFactory.java
- modules/flowable-cxf/src/test/java/org/flowable/engine/impl/webservice/WebServiceMockImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/transformer/AbstractTransformer.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/transformer/BigDecimalToString.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/transformer/BooleanToString.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/transformer/ComposedTransformer.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/transformer/DateToString.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/transformer/Identity.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/transformer/IntegerToLong.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/transformer/IntegerToString.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/transformer/LongToInteger.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/transformer/LongToString.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/webservice/WSOperation.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/webservice/WSService.java
- modules/flowable-osgi/src/main/java/org/flowable/osgi/blueprint/ClassLoaderWrapper.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/WebServiceActivityBehavior.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/transformer/AbstractTransformer.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/transformer/BigDecimalToString.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/transformer/BooleanToString.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/transformer/ComposedTransformer.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/transformer/DateToString.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/transformer/Identity.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/transformer/IntegerToLong.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/transformer/IntegerToString.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/transformer/LongToInteger.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/transformer/LongToString.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/webservice/WSOperation.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/webservice/WSService.java
Remove the {@inheritDoc} tag since Javadoc copies the super class' comment if no comment is present, a comment containing only an {@inheritDoc} adds nothing.
> Remove unnecessary {@inheritDoc} comments

- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/BpmnXMLConverter.java
- modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/xml/converter/DmnXMLConverter.java
The same change in the Bpmn and Dmn converters to use the JDK7 try syntax (eliminating the finally block) and explicitly made it clear the opening and re-opening of the stream.
> Use JDK7 try/closeable and unwind the code

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/JobEventsTest.java
If you look at the various Jenkins tests running that use MSSQL as the database, one particular test seemingly fails and passes randomly.  See for example this [test run](http://qa.flowable.org/job/Flowable6MSSQL/lastCompletedBuild/testReport/org.flowable.engine.test.api.event/JobEventsTest/testJobEntityEventsForRescheduleTimer/).  
The test is `org.flowable.engine.test.api.event.JobEventsTest.testJobEntityEventsForRescheduleTimer(JobEventsTest.java:174)`,   
The error message that is printed implies the dates are different but the `toString()` for each date looks exactly the same:
`expected:<Tue Mar 28 00:29:48 UTC 2017> but was:<Tue Mar 28 00:29:48 UTC 2017>`
To work around this problem the code was changed to ignore the milliseconds; thus instead of: …
> Standardize date equality check; fixes MSSQL based test

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoricProcessInstanceQueryVersionTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryServiceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/ProcessInstanceAndVariablesQueryTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/RuntimeVariablesTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskVariablesTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/compensate/CompensateEventTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/history/HistoricVariableInstanceTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/api/history/HistoricProcessInstanceQueryVersionTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/api/runtime/ProcessInstanceAndVariablesQueryTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/bpmn/event/compensate/CompensateEventTest.java
Fix when collection fields or variables whose contents are either queried and not updated, or updated and not queried. Such mismatched queries and updates are pointless.
> Fix mismatch query and update of collection

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/DataObjectImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetDataObjectCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetDataObjectsCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetTaskDataObjectCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetTaskDataObjectsCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/runtime/DataObject.java
- modules/flowable-engine/src/test/java/org/flowable/examples/variables/VariablesTest.java
Our REST API requires a SELF link to be included in each Data Object representation that is returned to the client. Adding the process id and execution id in support of building the link. This also brings the DataObject interface in line with what is exposed in the VariableInstance interface.
In addition, the access level modifier for the fields in the DataObjectImpl class have been updated to protected.
> Add process id and execution id to DataObject.

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/DataObjectImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetDataObjectCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetDataObjectsCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetTaskDataObjectCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetTaskDataObjectsCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/runtime/DataObject.java
- modules/flowable-engine/src/test/java/org/flowable/examples/variables/VariablesTest.java
Expose the id of the DataObject to be consistent with the id being exposed via the VariableInstance class. Exposing the id is helpful in our REST API since our Variable representation exposes HATEOS style links.
> Add id field to DataObject

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/ProcessInstanceEventsTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/runtime/subProcessWithTerminateEnd.bpmn20.xml
The merge of pull request 320 introduced regressions. We are no longer
receiving the activity cancelled events for a subprocess and task within
subprocess when the subprocess is cancelled via terminate end event.
This is not a fix but is a test case that reproduces the failure. The expected events are no longer received.
> test to reproduce bug introduced by merge of PR 320

- modules/flowable-content-engine-configurator/src/main/java/org/flowable/content/engine/configurator/ContentEngineConfigurator.java
- modules/flowable-content-spring-configurator/src/main/java/org/flowable/content/spring/configurator/SpringContentEngineConfigurator.java
- modules/flowable-dmn-engine-configurator/src/main/java/org/flowable/dmn/engine/configurator/DmnEngineConfigurator.java
- modules/flowable-dmn-spring-configurator/src/main/java/org/flowable/dmn/spring/configurator/SpringDmnEngineConfigurator.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/IdmEngineConfigurator.java
- modules/flowable-form-engine-configurator/src/main/java/org/flowable/form/engine/configurator/FormEngineConfigurator.java
- modules/flowable-form-spring-configurator/src/main/java/org/flowable/form/spring/configurator/SpringFormEngineConfigurator.java
- modules/flowable-spring/src/main/java/org/flowable/spring/configurator/SpringIdmEngineConfigurator.java
Hello!
I submitted an issue #337 yesterday. I wrote that they are no possibility to set the database type manually. But I was wrong. There was a bug: database type was not initialised in method "configure" children of the class
```java
org.flowable.engine.cfg.AbstractProcessEngineConfigurator
```
After I added initialisation it works when I creating process engine like this:
```java
ProcessEngineConfiguration cfg = new StandaloneProcessEngineConfiguration()
.setDatabaseType(ProcessEngineConfiguration.DATABASE_TYPE_DB2)
.setDataSourceJndiName("java:jboss/datasources/AS400DS")
.setDatabaseSchemaUpdate(ProcessEngineConfiguration.DB_SCHEMA_UPDATE_TRUE);
ProcessEngine processEngine = cfg.buildProcessEngine();
```
> Initialization database type from main configurator.

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/ProcessInstanceEventsTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/runtime/multipleSubprocessTerminateEnd.bpmn20.xml
Process defined with terminateEnd event.  When flow transitions to terminate end, we see an unexpected PROCESS_CANCELLED event. This regression was introduced by 330.  We now see both a PROCESS_CANCELLED and a PROCESS_COMPLETED_WITH_TERMINATE_END_EVENT.   Only
PROCESS_COMPLETED_WITH_TERMINATE_END_EVENT is expected.
This is just a test case to identify the regression.
> Test case to demonstrate regression introduced by 320/330.

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/DeadLetterJobQueryImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/JobQueryImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/SuspendedJobQueryImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/TimerJobQueryImpl.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/JobQueryImpl.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/TimerJobQueryImpl.java
It appears that the cut-n-paste of adding tenant support left the exception message referring to a job and not the tenant id.  Made changes to the exception messages to better match the form used in other messages in the same class.
> Improve exception message to match other uses in class

- modules/flowable-ui-idm/flowable-ui-idm-app/src/main/webapp/META-INF/context.xml
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/META-INF/context.xml
- modules/flowable-ui-task/flowable-ui-task-app/src/main/webapp/META-INF/context.xml
This patch fixes two Tomcat 8 startup warnings:
- org.apache.catalina.core.StandardContext.setPath A context path must
either be an empty string or start with a '/' and do not end with a '/'.
The path [/] does not meet these criteria and has been changed to []
- org.apache.catalina.startup.SetContextPropertiesRule.begin
[SetContextPropertiesRule]{Context} Setting property 'debug' to '100'
did not find a matching property."
> Fix Tomcat 8 startup warnings

- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/i18n/en.json
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/views/popover/formfield-edit-popover.html
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/views/templates/form-builder-element-template.html
- modules/flowable-ui-task/flowable-ui-task-app/src/main/webapp/workflow/views/templates/form-element-template.html
Expression field now has selectable font size.
Expression field displays expression text on initial step instead of empty message when expression is not empty allowing to use as label.
> Fixed missing placeholder for decimal field.  Changes to expression field display.

- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/i18n/en.json
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/i18n/pt-BR.json
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/views/popover/formfield-edit-popover.html
Add read-only property in form fields except to type expression and hyperlink.
This feature is required to reuse form fields in parsing / validation activities and so that the attachment type field can view the attached file and does not allow the user to delete the file.
> Add read-only property in form fields in formfield-edit-popover.html

- modules/flowable-ui-admin/src/main/webapp/scripts/process-instances-controllers.js
- modules/flowable-ui-admin/src/main/webapp/scripts/tasks-controllers.js
- modules/flowable-ui-idm/flowable-ui-idm-app/src/main/webapp/scripts/common/directives.js
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/scripts/common/directives.js
- modules/flowable-ui-task/flowable-ui-task-app/src/main/webapp/scripts/common/directives.js
I spotted these checks of numbers against `NaN` that don't seem to be correct. In JavaScript `NaN` is not equal to anything, not even itself. I've fixed these to use the built in `isNaN` function instead which should correctly check if they are `NaN`.
---
I found these issues through [lgtm.com](https://lgtm.com/projects/g/flowable/flowable-engine/alerts/), a service that analyzes open-source code to look for potential problems. (Full disclosure: I work for the company that operates it.)
> Fix some incorrect comparisons with NaN.

- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/editor-app/editor.html
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/views/app-definition.html
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/views/decision-table.html
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/views/form.html
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/views/process.html
I spotted these duplicate HTML element attributes (the attribute values are the same in all cases) so I thought I would remove the redundant ones.
---
I found these issues through [lgtm.com](https://lgtm.com/projects/g/flowable/flowable-engine/alerts/), a service that analyzes open-source code to look for potential problems. (Full disclosure: I work for the company that operates it.)
> Remove some duplicate HTML element attributes.

- README.md
The old URL pointed to "forums" and 404d when I tried to follow it.
> Fixed forum URL in Readme

- modules/flowable-ui-task/flowable-ui-task-app/src/main/webapp/workflow/scripts/controllers/render-form.js
- modules/flowable-ui-task/flowable-ui-task-app/src/main/webapp/workflow/views/templates/form-element-template.html
Fixed upload form-field to allow the same field ID to be used in multiple forms and when used as a readOnly field.
This fixes how the content-id(s) of the attached files is handled in flowable-task app.
See the discussion at https://forum.flowable.org/t/error-when-you-reuse-the-form-field-of-the-attachment-upload-type/522
> Fixed upload form-field to allow readOnly

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/context/Context.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/interceptor/CommandContextInterceptor.java
There is a potential error when compatibility handler is unset but it can be still referenced from the stack.
> CommandContextInterceptor simplification

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CallActivityTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/event/CallActivityTest.testCallActivity.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/event/CallActivityTest.testCallActivityTerminateEnd.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/event/CallActivityTest.testCalledActivity.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/event/CallActivityTest.testCalledActivityTerminateEnd.bpmn20.xml
Seeing two potential issues when Called Activity (External subprocess) is
defined with terminate end event. First, the process variables are not
returned to the calling process. Second, we are seeing an unexpected
PROCESS_COMPLETED event as we already received a
PROCESS_COMPLETED_WITH_TERMINATE_END_EVENT event. Included test recreates the
issues.
> Variables not set, extra event when CallActivity defined with terminate end event

- modules/flowable-ui-admin/pom.xml
Remove local overrides of library versions in admin ui application.  Appears to build locally but I have no ready way to test the application.
This was discussed briefly in the forum [post 616](https://forum.flowable.org/t/versions-of-jars-in-admin-war/616).
> Remove local overrides of library versions

- modules/flowable-http/pom.xml
- modules/flowable-mule/pom.xml
- modules/flowable5-mule-test/pom.xml
I noticed in some POMs that the surefire plugin [runOrder](http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#runOrder) parameter was set.  In three POMs (the attached changed files), the version of the surefire-plugin was overridden to a version prior to the version that supported the option.
The parent POM specifies version 2.7.1 which does support the option so removing the local overrides removes the error.
In addition it should be noted that other POMs specify a version *after* the one defined in the parent/root POM file. Specifically, `ui-admin`, `ui-idm`, `ui-modeler`, and `ui-task` specify version 2.16.
> Remove override of maven-surefire-plugin version

- modules/flowable-content-engine/pom.xml
- modules/flowable-dmn-engine/pom.xml
- modules/flowable-form-engine/pom.xml
All other modules are using Liquibase version 3.5.3; these 3 modules were specifying 3.4.1.  Built each module and ran unit tests.
> Remove override of Liquibase jar version

- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/RuntimeTest.java
- modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/util/DmnXMLUtil.java
- modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/de/odysseus/el/misc/BooleanOperations.java
- modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/de/odysseus/el/misc/NumberOperations.java
- modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/de/odysseus/el/tree/impl/Parser.java
- modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/de/odysseus/el/tree/impl/ast/AstBinary.java
- modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/de/odysseus/el/tree/impl/ast/AstUnary.java
- modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/de/odysseus/el/util/SimpleResolver.java
- modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/javax/el/BeanELResolver.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/AcquireJobsCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/async/AsyncHistoryJobHandler.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/async/json/transformer/TaskEndedHistoryJsonTransformer.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/test/HistoryTestHelper.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/HistoricActivityEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/compensate/CompensateEventTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/BoundaryTimerEventTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/jobexecutor/AsyncExecutorTest.java
- modules/flowable-engine/src/test/java/org/flowable/examples/groovy/GroovyScriptTest.java
- modules/flowable-engine/src/test/java/org/flowable/examples/mgmt/ManagementServiceTest.java
- modules/flowable-spring/src/main/java/org/flowable/spring/SpringAsyncExecutor.java
* Replace equals() on Enum compares as Enum constants are equal only when they have the same identity
* Fix missorted modifiers
* Remove unnecessary semicolon
* Remove unused imports
* Replace concatenations in log statements with parameterized log messages
> Cleanup after async history merge

- checkstyle/flowable-checkstyle.xml
- checkstyle/flowable-suppressions.xml
- pom.xml
This is the beginning of a using [Checkstyle](http://checkstyle.sourceforge.net/) for this project.
There is a new directory (`checkstyle`) with the definition of the checkstyle rules to apply (`flowable-checkstyle.xml`).  The `flowable-checkstyle.xml` file was cloned from the default standard default Java rules and then modified to reduce the number of issues (many related to Javadoc and scoping of variables for example).  The current indentation policy was added to the original file.
The second file is a list of files or directories to ignore (`flowable-suppressions.xml`). Examples here are the inclusion of `org\flowable\engine\common\impl\de` directory.
The list can be tweaked as needed; rules removed or added as seen appropriate by the team.
As it currently is coded the changes only …
> Basic Checkstyle implementation

- .travis.yml
- README.md
This is an initial attempt at using [Travis-CI](https://travis-ci.org/) with Flowable.   It provides a basic “smoke test” for any branches, pull requests, and pushes without going the whole Jenkins route.
The changes are pretty basic once the Travis account is setup for Flowable and repository is synced.
It is currently set to send email on failures and when the failure is corrected to the project members.  This can be adjusted.
I originally had it building with JDK 7 and JDK  8 (8 seems to be the default) but the JDK 7 version failed with a class version mismatch in the test file, `org.flowable.idm.engine.test.api.identity.authentication.jBCryptHashingt` so only JDK 8 is set in the `.travis.yml` file for now.  JDK 7 can be turned back on when the test is excluded  via POM changes; right …
> Initial Travis CI support

- modules/flowable-engine/src/main/java/org/flowable/engine/IdentityService.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/IdentityServiceImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/IdmEngineConfigurator.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/identity/IdentityServiceTest.java
- modules/flowable-engine/src/test/resources/flowable.cfg.xml
- modules/flowable-idm-api/src/main/java/org/flowable/idm/api/IdmIdentityService.java
- modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/impl/cmd/SaveUserCmd.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/IdentityServiceTest.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/identity/UserResource.java
- modules/flowable-ui-idm/flowable-ui-idm-logic/src/main/java/org/flowable/app/idm/service/ProfileServiceImpl.java
- modules/flowable-ui-idm/flowable-ui-idm-logic/src/main/java/org/flowable/app/idm/service/UserServiceImpl.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/IdentityService.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/IdentityServiceImpl.java
Update the rest of flowable module with new _updateUserPassword_ function. Current _saveUser_ function is not able to recognize either hashing is required or not
`User user = idmIdentityService.createUserQuery().userId("johndoe").singleResult();`
`user.setEmail("newemail@email.org");`
`idmIdentityService.saveUser(user);`
Above code will cause password encoder hashing existing hashed password 
Affected Modules:
flowable-engine, flowable-idm-api, flowable-idm-engine, flowable-rest, flowable-ui-idm, flowable5-engine
> added updateUserPassword function

- .travis.yml
Travis CI is moving to Ubuntu Trusty soon as the default.  This PR switches to Trusty.  Locally I have had two successful Travis-CI builds on this distro.
> Move Travis build machine to Trusty

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/variable/EntityManagerSessionImpl.java
A opened entityManager will not be closed when closeEntityManager is true.
> Bugfix for EntityManagerSessionImpl

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.bpmn20.xml
Different events are received depending on how the multi-instance user task is
cancelled.  We expect the events to be consistent no matter how
cancelled.  These tests reproduce the differences. One test cancels using
terminate end event, and one cancels the multi-instance user task by using
a message boundary event.
> Inconsistency with ACTIVITY_CANCELLED events for multi-instance usertask

- .travis.yml
Cannot use Oracle JDK7 on Trusty as it is not supported on that version of Linux.
> Add openjdk7 to travis given recent updates

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CallActivityTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.testCallActivityTerminateEnd.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.testCalledActivityTerminateEnd.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.testEmbeddedSubprocess.bpmn20.xml
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/PasswordEncoderTest.java
This push includes a test case to reproduce the problem where we are seeing an extra process completed event for an external subprocess.  This is being discussed in forum, https://forum.flowable.org/t/unexpected-event-received-when-callactivity-cancelled/775
The problem is as follows. Multi-instance user task defined in external subprocess.
When parent process flows to terminate end, we see an
unexpected PROCESS_COMPLETED_WITH_TERMINATE_END_EVENT for
the external subprocess. We expect only the PROCESS_CANCELLED
event (which we do do see).
The pull request includes a test case for external subprocess and embedded. It is the external subprocess test that will fail due to the extra event.
> Tests to reproduce bug where we see extra process completed with terminate end event

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.java
The ordering of the cancel events for the message boundary event, root of multi-instance user task, and multi-instance user task instances can vary.
> fix ordering issue in cancel call activity test

- modules/flowable-engine-common-api/src/main/java/org/flowable/engine/common/api/query/Query.java
Without fully qualified package name FlowableException is not found because of refactoring.
> Fix javadoc by fully qualifying reference to FlowableException

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/WebServiceActivityBehavior.java
Improve message of errors that occurs into web-service activity when importing documents as web-service description (WSDL).
The initial messages were not really relevant.
> Improve error messages of web-service activity when importing document (WSDL, ...)

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/callactivity/CallActivityAdvancedTest.java
This patch fixes so that subprocesses started by a call-activity create a 'starter' identity-link for the subprocess if the authorized user is set in the engine. This 'starter' identity-link will be the same as `startUserId `on the `ExecutionEntity`.
This behaviour mirrors how it works for starting a main process and makes call-activities consistent.
I have additionally included a unit test to verify this behaviour.
This was seen in Flowable-6.1.2 and previously discussed on the forum - https://forum.flowable.org/t/starter-identity-link-not-created-for-call-activity-process/823
Regards,
Paul
> Fixed that an indentity link for 'starter' is created for subprocesses

- modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/xml/converter/InputClauseXMLConverter.java
- modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/AdditionalConverterTest.java
When converting DMN XML to DMN model the properties id and label on input clauses were missing.
> added missing input clause id and label to DMN XML converter

- modules/flowable-ui-task/flowable-ui-task-conf/src/main/java/org/flowable/app/servlet/ContentDispatcherServletConfiguration.java
- modules/flowable-ui-task/flowable-ui-task-conf/src/main/java/org/flowable/app/servlet/DmnDispatcherServletConfiguration.java
- modules/flowable-ui-task/flowable-ui-task-conf/src/main/java/org/flowable/app/servlet/FormDispatcherServletConfiguration.java
because of this the MultipartResolver (needed for Spring MVC multipart/formdata handling) is not initialized for the form / dmn / content REST resources
> fixes #510 dispatchers not inheriting base dispatcher

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/ProcessInstanceEventsTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/event/ProcessInstanceEventsTest.testProcessInstanceEvents.bpmn20.xml
Hi,
I was upgrading an application from Activiti 5.21.0 to Flowable 6.1.2 and discovered a bug/regression.
In Activiti 5.21.0 an eventlistener could be defined in the process definition (in bpmn, not registered directly with the process engine) which listened to PROCESS_CANCELLED events when e.g. the process was deleted. This event was fired and received correctly.
In Flowable 6.1.2 this behaviour no longer worked. The PROCESS_CANCELLED event was not received in the eventlistener when the process was deleted.
I found that the issue was in `ExecutionEntityManagerImpl` when Calling `FlowableEventBuilder.createCancelledEvent(...) ` a null value was sent in for the `processDefinitionId`. This results in eventlisteners defined in the process definition not being invoked.
The fix is to send in …
> PROCESS_CANCELLED events not fired for eventlisteners defined in the process defintion

- modules/flowable-engine/src/main/resources/org/flowable/db/create/flowable.db2.create.engine.sql
- modules/flowable-engine/src/main/resources/org/flowable/db/upgrade/flowable.h2.upgradestep.6120.to.6200.history.sql
- modules/flowable-engine/src/main/resources/org/flowable/db/upgrade/flowable.mssql.upgradestep.6120.to.6200.history.sql
- modules/flowable-engine/src/main/resources/org/flowable/db/upgrade/flowable.mysql.upgradestep.6120.to.6200.history.sql
The 6.1.2 -> 6.2.0 upgrade scripts for h2, hsql and mysql had the wrong table names in the history upgrade scripts.
> Fix upgrade scripts for ACT_HI_VARINST

- modules/flowable-content-engine/src/main/java/org/flowable/content/engine/ContentEngines.java
There is also `buildFormEngine`, but I did not rename it because it is a protected method.
> ContentEngines: fix copy&paste errors

- modules/flowable-engine-common-api/src/main/java/org/flowable/engine/common/api/delegate/event/FlowableEngineEventType.java
- modules/flowable-engine/src/main/java/org/flowable/engine/delegate/event/AbstractFlowableEngineEventListener.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CancelCallActivityTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CancelUserTaskTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/TestHistoricActivityEventListener.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/TestVariableEventListener.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/v6/Flowable6ExecutionTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/StartTimerEventRepeatWithoutN.java
- modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/usertask/SkipExpressionUserTaskTest.java
- modules/flowable-engine/src/test/java/org/flowable/standalone/event/GetProcessOnDefinitionInitializedListener.java
Benefits:
* Typed callback methods.
* Provides a way to retrieve the execution.
This change also removes enumerated values that are no longer used from the FlowableEngineEventType class.
> Provide an abstract base class for a FlowableEventListener

- userguide/src/en/ch07b-BPMN-Constructs.adoc
Quartz has made some changes to their site. The previous location points to a 404 site. I think that the 2.x site should be OK for the trigger.
Maybe you want to update the `CronExpression` to the latest one as well.
> Point to new location of quartz cron trigger tutorial

- modules/flowable-http/src/main/java/org/flowable/http/impl/HttpActivityBehaviorImpl.java
- modules/flowable-http/src/test/java/org/flowable/http/HttpServiceTaskTest.java
Each header line is split only on first ':' everything before ':' is considered as name and everything after as value
Fixes #575 
I couldn't find a test that tests this behaviour. Is there something that actually tests this class?
> Correctly bind headers

- modules/flowable-camel/pom.xml
- modules/flowable5-camel-test/pom.xml
- pom.xml
This PR adds a `camel.version` property to the root pom and adds the Camel dependencies to `dependencyManagement`. Second commit upgrades Camel 2.17.1 to 2.19.3.
> Centralise Camel dependency and upgrade to latest

- userguide/src/en/ch13-UI.adoc
Change “Script form” to “Script format”.
See this [forum post](https://forum.flowable.org/t/doc-error-in-chapter-14-3-should-be-script-format-instead-of-script-form/998/2).
> Correct spelling

- distro/src/notice.txt
- modules/flowable-content-rest/pom.xml
- modules/flowable-dmn-rest/pom.xml
- modules/flowable-form-rest/pom.xml
- modules/flowable-ui-admin/pom.xml
The version of org.apache.httpcomponents.httpmime is defined in the parent pom but some modules downgraded the version.  I removed those specifications and reran the tests.
Updated `notice.txt` for httmpmime and for fileupload change in [PR 613](https://github.com/flowable/flowable-engine/pull/613) assuming that it will be accepted.
> Remove submodule version override of org.apache.httpcomponents.httpmime

- pom.xml
This fixes various CVEs see: https://commons.apache.org/proper/commons-fileupload/security-reports.html for details.
> update commons-fileupload version to 1.3.3

- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/repository/DeploymentResourceResource.java
I am doing some enhancements to the rest endpoints and I noticed the `FIXME`. I tried it out and I know why it is there, so I removed the `FIXME` and added an explanation and some links for it.
> Remove fixme and add explanation why the ** are needed

- modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/interceptor/LogInterceptor.java
The logging of new lines causes unnecessary and imho ugly blank lines like `2017-11-07 16:19:10,118 DEBUG [activiti-acquire-timer-jobs] org.activiti.engine.impl.interceptor.LogInterceptor -`
> LogInterceptor: remove logging of blank lines

- modules/flowable-ui-task/flowable-ui-task-app/src/main/webapp/workflow/scripts/controllers/render-form.js
Found the bug causing #636: in `render-form.js` the `Date` object is populated from a parsed ISO date without taking into account that JavaScript Date has zero-based months.
> Fix month off by one in rendered date fields (#636).

- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/cmd/AbstractExecuteDecisionCmd.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/persistence/deploy/DeploymentManager.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetDecisionTablesForProcessDefinitionCmd.java
This addition of code allows deploying DMN decision tables without a parent deployment id, which are still found during the execution of a decision task.
A post on the forum will be created shortly where the benefits and drawbacks of this approach can be discussed.
> Decision table without a parent deployment, but with the same key, are used as fallback.

- modules/flowable-cmmn-json-converter/src/main/java/org/flowable/cmmn/editor/constants/CmmnStencilConstants.java
- modules/flowable-cmmn-json-converter/src/main/java/org/flowable/cmmn/editor/json/converter/DecisionTaskJsonConverter.java
- modules/flowable-cmmn-json-converter/src/main/java/org/flowable/cmmn/editor/json/converter/ServiceTaskJsonConverter.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/DmnActivityBehavior.java
- modules/flowable-json-converter/src/main/java/org/flowable/editor/constants/StencilConstants.java
- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/DecisionTaskJsonConverter.java
- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/ServiceTaskJsonConverter.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/resources/stencilset_bpmn.json
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/resources/stencilset_cmmn.json
At the moment, when executing a decision task from a BPMN process, the result does not distinguish between an empty response (aka, no rules matched) and an error during the execution. This PR remedies this by throwing a FlowableException when the decision task failed to execute.
A colleague of mine opened up a discussion linked to this on the forum: https://forum.flowable.org/t/decision-task-option-to-throw-error-when-no-rule-matched/1194
Thanks!
> Throw a FlowableException when a decision task fails.

- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/editor-app/configuration/properties-assignment-controller.js
see #697 for more information.
The fallback behaviour makes sure that old models will get automatically 'upgraded' to use the type property.
> Fix bug with modeler that cannot save assignments for old models

- modules/flowable-cxf/pom.xml
- modules/flowable-ui-admin/flowable-ui-admin-app/pom.xml
- modules/flowable-ui-admin/pom.xml
- modules/flowable-ui-idm/pom.xml
- modules/flowable-ui-modeler/pom.xml
- modules/flowable-ui-task/pom.xml
- pom.xml
This could help to make the build more stable, as some asynchronous tests fail from time to time.
It only works for Junit 4 tests and only if the failed test does not affect state e.g. the running reused spring context, so I'm not sure how much it will help flowable. Enabling this feature made Apache Camel builds much more stable.
> rerun failing tests (up to two times) to make build more stable

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/ParallelMultiInstanceBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityManager.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.testMultiInstanceCompleteCondition.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.testMultiInstanceSequentialUserTaskEventsWithNormalCompletion.bpmn20.xml
The parallel multi-instance behavior sends an unexpected
ACTIVITY_CANCELLED event when a multi-instance user task completes
normally.
> Fix bug in parallel multi-instance behavior.

- modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/db/LogSqlExecutionTimePlugin.java
Spring Boot Applications have a default log level of info. This results in the execution time of sql statements being logged when the plugin is enabled. Updating the plugin's log level to avoid this.
> Change log level to debug in LogSqlExecutionTimePlugin.java.

- modules/flowable-dmn-json-converter/src/main/java/org/flowable/editor/dmn/converter/DmnJsonConverter.java
- modules/flowable-dmn-json-converter/src/test/java/org/flowable/editor/dmn/converter/DmnJsonConverterTest.java
Removed check on operator is "==" so that it gets added to the resulted dmn file when exporting.
And therefore fixed the issue with importing if the values contains a " "
> Issue #740 : Remove check that doesn't add "==" operator to export

- distro/src/notice.txt
- pom.xml
Recent non android (nowadays called `jre` versions by the guava team) versions require java 8.
> Update guava to version 23.6-android (latest java 7 compatible version)

- modules/flowable-ui-idm/flowable-ui-idm-conf/src/main/java/org/flowable/app/security/CustomPersistentRememberMeServices.java
Resolves the issue described in https://forum.flowable.org/t/different-sub-domain-name-usage-per-ui-app/1308
> Allow remember me cookie's domain to be set from application properties

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/parser/handler/MessageEventDefinitionParseHandler.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/MessageEventDefinitionWithExtensionElementsTest.java
be used.
Currently the behavior of MessageEventDefinitionParseHandler overwrites
the extension elements on a messageEventDefinition element with the
extension elements from the associated message element. This update
changes the beavior to add the extension elements from the message
element to the messageEventDefinition's extension elements.
For example:
`<intermediateCatchEvent id="ID_91ee51f3-481d-439c-a62d-8b382a1cfddf" >
<messageEventDefinition messageRef="ID_91ee51f3-481d-439c-a62d-8b382a1cfdde">
<extensionElements>
<xyzbpmn:promptDefinition promptRef="ID_91ee51f3-481d-439c-a62d-8b382a1cf7a1" required="true" defaultValueRef="ID_91ee51f3-481d-439c-a62d-8b382a1cf7a2">
<xyzbpmn:promptValueDefinition promptValueRef="ID_91ee51f3-481d-439c-a62d-8b382a1cf7a2"/> …
> Allow extension elements defined on a messageEventDefinition element to

- modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/app/rest/editor/AbstractModelBpmnResource.java
Add `filename*` parameter to `Content-Disposition` response header when
exporting BPMN file, in order to support unicode filename. See
https://tools.ietf.org/html/rfc6266 for more detail.
Tested in Firefox, Chrome and Edge.
P.S. I'm new to Java, so maybe I do something wrong.
> Support unicode filename when doing BPMN export

- modules/flowable-ui-admin/flowable-ui-admin-conf/pom.xml
- modules/flowable-ui-modeler/flowable-ui-modeler-conf/pom.xml
- modules/flowable-ui-task/flowable-ui-task-conf/pom.xml
In #801 @PascalSchumacher removed the `commons-fileupload` from all `ui` modules. However, we need that in some of the modules (the ones that use the `CommonsMultipartResolver`)
I am bringing back that dependency only in the modules that actually use that Multipart resolver
> Bring back commons-fileupload in apps that need it

- docs/userguide/src/en/bpmn/ch07b-BPMN-Constructs.adoc
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/constants/BpmnXMLConstants.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/ServiceTaskXMLConverter.java
- modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/ServiceTask.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/ServiceTaskExpressionActivityBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/parser/factory/DefaultActivityBehaviorFactory.java
- modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/servicetask/ExpressionServiceTaskTest.java
- modules/flowable-engine/src/test/java/org/flowable/standalone/validation/DefaultProcessValidatorTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/validation/invalidProcess.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/servicetask/ExpressionServiceTaskTest.testSetServiceLocalScopedResultWithParallelMultiInstance.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/servicetask/ExpressionServiceTaskTest.testSetServiceResultWithParallelMultiInstance.bpmn20.xml
- modules/flowable-json-converter/src/main/java/org/flowable/editor/constants/StencilConstants.java
- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/ServiceTaskJsonConverter.java
- modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/Problems.java
- modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/impl/ServiceTaskValidator.java
- modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/admin/app/rest/client/modelinfo/bpmn/ServiceTaskInfoMapper.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/mapper/ServiceTaskInfoMapper.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/resources/stencilset_bpmn.json
- modules/flowable-ui-task/flowable-ui-task-logic/src/main/java/org/flowable/app/service/editor/mapper/ServiceTaskInfoMapper.java
Fixes #806 
I know that there are multiple tasks that have the result variable. I am doing it for ServiceTask only for now. However, I want to extract a common class for tasks with a result variable, there is quite duplication accross those tasks
> Add support for saving result variable in the local scope #806

- modules/flowable-app-rest/src/main/resources/log4j.properties
- modules/flowable-ui-admin/flowable-ui-admin-app/src/main/resources/log4j.properties
- modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/log4j.properties
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/log4j.properties
- modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/log4j.properties
Logging the date in addition to the time is can be very helpful for non-development environments.
> Flowable Apps: Add date to log entries by using ISO-8601 date format.

- modules/flowable-dmn-json-converter/src/main/java/org/flowable/editor/dmn/converter/DmnJsonConverter.java
- modules/flowable-dmn-json-converter/src/test/java/org/flowable/editor/dmn/converter/DmnJsonConverterTest.java
- modules/flowable-dmn-json-converter/src/test/resources/org/flowable/editor/dmn/converter/decisiontable_empty_expressions.json
Due to a recent change '==' was prefixed to a '-' expression value.
When the expression value is '-' additional parsing should be skipped.
> fixes JSON to DMN parsing issue with 'ignore expression value'

- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/boot/FlowableProperties.java
When using classpath:location Spring expects the resources to exist and it fails if it doesn't find them.
However, when using classpath*:location Spring will not fail if the resources do not exist
> The definitions location prefix should be optional

- modules/flowable-cxf/src/main/java/org/flowable/engine/impl/webservice/CxfWSDLImporter.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/WebServiceActivityBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/parser/factory/DefaultXMLImporterFactory.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/parser/factory/XMLImporterFactory.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
When using web-service task in my process definition, it is needed to import WSDL of invoked web-services.
I need to use a custom URI resolver to find WSDLs of my services. So I should be able to customize `flowable-cxf` with my own URI resolver through a custom WSDL importer.
Please find here my contribution to be able to configure the WSDL importer at process engine configuration.
> Add capability to customize the WSDL importer of flowable-cxf

- modules/flowable-app-rest/pom.xml
- pom.xml
Flowable-root: Update jaxb-api version to 2.3.0 to match the version of the other jaxb dependencies. Move the jaxb-api dependency above the other jaxb dependency declarations.
Flowable-app-rest: Use jaxb-api version from flowable root.
> Improve jaxb-api dependency management

- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/RepetitionRuleTest.java
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/itemcontrol/RepetitionRuleTest.testRepetitionRuleWithExitCriteria.cmmn
As discussed with @jbarrez there's no clear definition on the need to reevaluate repetition condition when a Plan Item transitions to exit (exitCriterion), although it is clear for complete and terminate.
This PR just adds a test that corroborates the current behavior of the engine, which we think it is correct for the moment, which is that "on-exit" it doesn't need to evaluate the repetion rule.
> Added test case for repetition rule and exitCriterion on a task

- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-cmmn/src/main/resources/application.properties
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-content/src/main/resources/application.properties
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-dmn/src/main/resources/application.properties
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-form/src/main/resources/application.properties
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api/src/main/resources/application.properties
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/environment/FlowableLiquibaseEnvironmentPostProcessor.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
Flowable engines pull Liquibase and Spring Boot starts the autoconfiguration which causes failures.
Therefore we are disabling Liquibase per default. Users have to explicitly enable it by setting liquibase.enabled to true
> Add environment post processor to disable Liquibase auto configuration

- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/FlowableProperties.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ProcessEngineAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/cmmn/CmmnEngineAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/cmmn/FlowableCmmnProperties.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/dmn/DmnEngineAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/dmn/FlowableDmnProperties.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/form/FlowableFormProperties.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/form/FormEngineAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/process/FlowableProcessProperties.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
I did a mistake in #885 when I added the property to all of the engines properties separately. 
The property was already there, in the FlowableProperties
> Use single property to configure the schema update of all engines in the same time

- pom.xml
There is a potential data/message corruption bug in 3.2.2. Users should upgrade to 3.2.3 immediately and discontinue use of 3.2.2.
Source https://cxf.apache.org/
> Upgrade cxf version to 3.2.3

- modules/flowable-http/src/main/java/org/flowable/http/HttpActivityExecutor.java
See this pull request where the timeout was paired with connectionRequestTimeout. https://github.com/flowable/flowable-engine/pull/755
I left a comment there but it was after it had already been merged.
Referenced docs for http client:
https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/config/RequestConfig.html#getConnectionRequestTimeout()
Docs for connectionRequestTimeout: _"Returns the timeout in
milliseconds used when requesting a connection from the connection
manager."_
Docs for socketTimeout _"Defines the socket timeout (SO_TIMEOUT) in
milliseconds, which is the timeout for waiting for data or, put
differently, a maximum period inactivity between two consecutive data
packets)."_
So socket timeout more related to waiting for a response.
> Http task timeout best paired with socket timeout

- docs/userguide/src/en/bpmn/ch08-Forms.adoc
In the Flowable documentation (user guide), the type `double` is missing as supported type for form property
> The type 'double' was missing as supported type for form property

- modules/flowable-ldap/src/main/java/org/flowable/ldap/LDAPGroupCache.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ldap/FlowableLdapAutoConfiguration.java
- pom.xml
Reverse commits 9bb744eda1f05631139dd1cce5c347fb8ea290a7 and f11ca1474be8f4b6fb2356193d61c440a42f9f18
Builds were failing because flowable-ldap was missing from the check profile
> Add flowable-ldap module to the check profile

- modules/flowable-rest/src/test/java/org/flowable/rest/service/BaseSpringRestTestCase.java
- modules/flowable-ui-common/src/main/java/org/flowable/app/tenant/DefaultTenantProvider.java
- modules/flowable-ui-common/src/main/java/org/flowable/app/tenant/TenantProvider.java
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/META-INF/flowable-app/flowable-app.properties
- modules/flowable-ui-modeler/flowable-ui-modeler-conf/src/main/java/org/flowable/app/conf/ApplicationConfiguration.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/domain/editor/AbstractModel.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/model/editor/ModelRepresentation.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/repository/editor/ModelHistoryRepositoryImpl.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/repository/editor/ModelRepositoryImpl.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/AppDefinitionPublishService.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/ModelServiceImpl.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/resources/META-INF/liquibase/flowable-modeler-app-db-changelog.xml
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/resources/META-INF/modeler-mybatis-mappings/Model.xml
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/resources/META-INF/modeler-mybatis-mappings/ModelHistory.xml
This pull request adds tenant_id to modeler database tables and provides a TenantProvider interface through which the application access and applies tenancy.
The default tenant provider will look up the tenant id from the Environment (eg. app's properties file) and if not found uses the user's tenant_id (this was newly added by @martin-grofcik and is not yet supported in idm app) and uses null as last resort. This should be backwards compatible with existing installations which would neither have the tenant_id configuration property nor the user tenant_id. Also once tenant_id is implemented on users, the configuration property allows overriding this.
The mybatis xml files were updated to use spaces, as there was a mix of spaces and tabs in the file. Let me know if this is not ok.
I …
> Add modeler app multi tenancy support

- modules/flowable-ui-common/src/main/java/org/flowable/app/filter/FlowableCookieFilter.java
The cookies are encoded differently in the `AbstractRememberMeServices` from Spring Security 5. This PR aligns our `FlowableCookieFilter` with the encoding from Spring Security 5
> Align decode cookie method with the same method in AbstractRememberMeServices from Spring Security 5

- pom.xml
Such jars cause issues when being unpacked by maven dependency:unpack, it can also cause issues when deploying in a servlet container.
The jar / war is still self contained and can be run with java -jar and or deployed in a servlet container
As pointed out by @ruzkant prepending a launch script to the war can cause issues. For this reason this PR disables that.
The applications can still be run with `java -jar flowable-app.war` and / or be deployed in a servlet container which is sufficient.
If this PR is merged #926 can be closed without being merged
> Do not prepend a launch script to the Spring Boot jar / war

- modules/flowable-app-rest/pom.xml
- modules/flowable-ui-admin/flowable-ui-admin-app/pom.xml
- modules/flowable-ui-idm/flowable-ui-idm-app/pom.xml
- modules/flowable-ui-modeler/flowable-ui-modeler-app/pom.xml
- modules/flowable-ui-task/flowable-ui-task-app/pom.xml
Spring Boot 2.0 pulls hibernate-validator 6.0 which has been moved to a different group id.
The embedded tomcat needs to be a provided dependency
> Exclude correct hibernate validator from ui apps and make starter-tomcat a provided dependency

- docs/userguide/src/en/bpmn/ch05a-Spring-Boot.adoc
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/FlowableCmmnRule.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-starter/pom.xml
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-starter/src/main/java/flowable/FlowableStarterSampleApplication.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-starter/src/main/resources/application.properties
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-starter/src/main/resources/stageAfterTimer.cmmn
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-starter/src/main/resources/timerAfterStart.bpmn20.xml
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-starter/src/test/java/flowable/MixedAsyncExecutorsTest.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-starter/src/test/java/flowable/TestConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/pom.xml
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/AbstractSpringEngineAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ProcessEngineAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/cmmn/Cmmn.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/cmmn/CmmnEngineAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/process/Process.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/ProcessAndCmmnEngineAsyncExecutorTest.java
- modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/application.properties
New @Process and @Cmmn qualifiers are added which allow providing custom TaskExecutor and SpringRejectedJobsHandler
for the Process and CMMN Async Executors.
> Process and CMMN Engines should use dedicated async executors

- modules/flowable-app-rest/src/main/resources/application.properties
- modules/flowable-ui-admin/flowable-ui-admin-app/src/main/resources/application.properties
- modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/application.properties
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/application.properties
- modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/application.properties
When no JMX domain is given then each bean would be registered under the domain of name of the package of the class.
Each application should provide it's own domain which be default is the name of the application
> The JMX beans should be created under the name of the application

- modules/flowable-app-rest/pom.xml
- modules/flowable-ui-admin/flowable-ui-admin-app/pom.xml
- modules/flowable-ui-idm/flowable-ui-idm-app/pom.xml
- modules/flowable-ui-modeler/flowable-ui-modeler-app/pom.xml
- modules/flowable-ui-task/flowable-ui-task-app/pom.xml
The property migrator should not be a runtime dependency as it is required for the migration path to the new Spring Boot properties of the apps
Fixes #957
> Properties migrator should be compile dependency

- modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/autodeployment/AbstractAutoDeploymentStrategyTest.java
- modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/autodeployment/DefaultAutoDeploymentStrategyTest.java
- modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/autodeployment/ResourceParentFolderAutoDeploymentStrategyTest.java
- modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/autodeployment/SingleResourceAutoDeploymentStrategyTest.java
- modules/flowable-dmn-spring/src/test/java/org/flowable/spring/test/autodeployment/AbstractAutoDeploymentStrategyTest.java
- modules/flowable-dmn-spring/src/test/java/org/flowable/spring/test/autodeployment/DefaultAutoDeploymentStrategyTest.java
- modules/flowable-dmn-spring/src/test/java/org/flowable/spring/test/autodeployment/ResourceParentFolderAutoDeploymentStrategyTest.java
- modules/flowable-dmn-spring/src/test/java/org/flowable/spring/test/autodeployment/SingleResourceAutoDeploymentStrategyTest.java
- modules/flowable-form-spring/src/test/java/org/flowable/spring/test/autodeployment/AbstractAutoDeploymentStrategyTest.java
- modules/flowable-form-spring/src/test/java/org/flowable/spring/test/autodeployment/DefaultAutoDeploymentStrategyTest.java
- modules/flowable-form-spring/src/test/java/org/flowable/spring/test/autodeployment/ResourceParentFolderAutoDeploymentStrategyTest.java
- modules/flowable-form-spring/src/test/java/org/flowable/spring/test/autodeployment/SingleResourceAutoDeploymentStrategyTest.java
- modules/flowable-spring/src/test/java/org/flowable/spring/test/autodeployment/AbstractAutoDeploymentStrategyTest.java
- modules/flowable-spring/src/test/java/org/flowable/spring/test/autodeployment/DefaultAutoDeploymentStrategyTest.java
- modules/flowable-spring/src/test/java/org/flowable/spring/test/autodeployment/ResourceParentFolderAutoDeploymentStrategyTest.java
- modules/flowable-spring/src/test/java/org/flowable/spring/test/autodeployment/SingleResourceAutoDeploymentStrategyTest.java
- pom.xml
Unused stubbing is reported as an error by Mockito 2, so remove it were possible and make Mockito ignore it where easy removal is not possible.
> Upgrade Mockito version to 2.18.0

- ide-settings/idea/idea-code-style-configuration.xml
Before:
```java
switch(a):
case "test":
doSomethingWithTest();
break;
```
After:
```java
switch(a):
case "test":
doSomethingWithTest();
break;
```
> Indent case from switch in IDEA

- docs/public-api/tools/flowable-oas-generator/pom.xml
- docs/public-api/tools/flowable-slate/slate/source/includes/_rest-header.md
- docs/userguide/src/en/base/header-rest.adoc
- modules/flowable-app-rest/pom.xml
The swagger documentation was missing because we didn't change the locations of the api sources in the swagger-maven-plugin.
I have also created a feature request for the swagger-maven-plugin https://github.com/kongchen/swagger-maven-plugin/issues/620 to add an option for configuring the plugin to fail the build in case no classes were found in the locations of an api source
> Change the locations of the controllers for the swagger-maven-plugin

- modules/flowable-cdi/src/main/java/org/flowable/cdi/impl/event/CdiEventSupportBpmnParseHandler.java
The addition of a duplicate 'EndEvent' appears to be in error; removing second occurrence.
> Periodic code cleanups: remove duplicate addition of EndEvent

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/async/json/transformer/FormPropertiesSubmittedHistoryJsonTransformer.java
The variable `hasMoreFormProperties` is not updated inside of the loop; changed to a simple `true`.
> Periodic code cleanups: hasMoreFormProperties not updated in loop

- modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/static/workflow/scripts/controllers/processes.js
Create listener for the 'process-started-error' in static/workflow/scripts/controllers/processes.js which will create an alert.
> #1075 Server errors when starting a process from a form not triggering Alert

- modules/flowable-form-rest/src/main/java/org/flowable/form/rest/service/api/form/FormModelWithVariablesResource.java
Issue #968 points that `getFormModelWithVariablesByKeyAndParentDeploymentId` is being used with incorrect variable order.
> Issue#968 Fix variable order calling formService method

- modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/app/ModelCmmnResource.java
If this is not changed there is a clash with the path from the `ModelBpmnResource`
> Use correct path mapping for getting historic cmmn resource

- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/src/test/java/org/flowable/test/spring/boot/SecurityAutoConfigurationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/FlowableSecurityAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/RestApiAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ldap/FlowableLdapAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/FlowableSecurityAutoConfigurationTest.java
Rename the flowable SecurityAutoConfiguration to FlowableSecurityAutoConfiguration in order to be able to test it properly.
For some reason when used in tests the bean was being overriden by the Spring Boot SecurityAutoConfiguration
> Make sure Flowable Security auto configuration kicks in when the IdmIdentityService bean is present

- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/child/FieldExtensionParser.java
- modules/flowable-http/src/test/java/org/flowable/http/bpmn/HttpServiceTaskTest.java
- modules/flowable-http/src/test/java/org/flowable/http/bpmn/ParametrizedHttpResponseHandler.java
- modules/flowable-http/src/test/resources/org/flowable/http/bpmn/HttpServiceTaskTest.testGetWithParametrizedResponseHandler.bpmn20.xml
`FieldExtensionParser ` needs to handle `AbstractFlowableHttpHandler`, otherwise `AbstractFlowableHttpHandler` extensionElements don't get parsed.
> AbstractFlowableHttpHandler extensionElement support

- modules/flowable-http/src/main/java/org/flowable/http/HttpActivityExecutor.java
- modules/flowable-http/src/test/java/org/flowable/http/bpmn/BpmnThrowingRequestHandler.java
- modules/flowable-http/src/test/java/org/flowable/http/bpmn/BpmnThrowingResponseHandler.java
- modules/flowable-http/src/test/java/org/flowable/http/bpmn/HttpServiceTaskTest.java
- modules/flowable-http/src/test/resources/org/flowable/http/bpmn/HttpServiceTaskTest.testGetWithBpmnThrowingRequestHandler.bpmn20.xml
- modules/flowable-http/src/test/resources/org/flowable/http/bpmn/HttpServiceTaskTest.testGetWithBpmnThrowingResponseHandler.bpmn20.xml
Maybe I am mistaken, but it seems like `BpmnError`s thrown by `HttpRequestHandler` or `HttpResponseHandler` should be propagated instead of wrapped as `FlowableException` to allow custom implementations of these interfaces to affect the flow. Catching all `FlowableException`s with `<flowable:mapException>` does not seem like the proper solution since we cannot differentiate between different reasons that caused them to be thrown if we want to handle them differently: 
- Exception while invoking HttpRequestHandler
- Exception while invoking HttpResponseHandler
- HTTP exception occurred
- IO exception occurred
- Invalid URL exception occurred
Another way of catching exceptions from `HttpRequestHandler` or `HttpResponseHandler` would be to make a new `FlowableException` superclass, but …
> HttpResponseHandler & HttpRequestHandler BpmnError propagation

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/DeployCmd.java
When I use StrongUuidGenerator to generate uuid,orderByDeploymentId() may be wrong.
You used orderByDeploymenTime() in [if] at line 83,but used orderByDeploymentId() in [else] at line 91.
> Fix the the problem of method enableDuplicateFiltering() sometime will be invalid.

- docs/userguide/src/en/bpmn/ch05a-Spring-Boot.adoc
- docs/userguide/src/en/bpmn/ch07b-BPMN-Constructs.adoc
- modules/flowable-engine/src/main/java/org/flowable/engine/ProcessEngineConfiguration.java
- modules/flowable-engine/src/main/java/org/flowable/engine/cfg/MailServerInfo.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/MailActivityBehavior.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailSendTaskTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailServiceTaskTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailTestCase.java
- modules/flowable-engine/src/test/resources/flowable.cfg.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/mail/EmailSendTaskTest.testMissingToAddress.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/mail/EmailServiceTaskTest.testMissingToAddress.bpmn20.xml
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/FlowableMailProperties.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ProcessEngineAutoConfiguration.java
The mailServerForceTo can be used when testing processes without the need to adapt the BPMN model itself
> Add support for forcing a TO address when using the MailTask

- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/constants/BpmnXMLConstants.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/child/FlowableMapExceptionParser.java
- modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/MapExceptionEntry.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/helper/ErrorPropagation.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/error/mapError/BoundaryErrorMapTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/error/mapError/BoundaryErrorParentException.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/error/mapError/BoundaryEventChildException.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/error/mapError/ThrowNestedCustomExceptionDelegate.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/error/mapError/BoundaryErrorMapTest.testClassDelegateSingleInheritedMapWithRootCause.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/error/mapError/BoundaryErrorMapTest.testRootCauseSingleDirectMap.bpmn20.xml
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/bpmn/helper/ErrorPropagation.java
New feature as discussed [here](https://forum.flowable.org/t/extending-mapexception-to-allow-filtering-based-on-rootcause/2147).
This PR adds support for additional `mapException` filtering through a new attribute called `rootCause`. Only exceptions that were caused by the configured `rootCause` will be caught by the error `boundaryEvent`. 
Flag `includeChildExceptions` is still respected, so the combination of a specific exception to catch, what root cause of the exception to handle and whether child exceptions will be caught should all be compatible.
> rootCause mapException filtering

- pom.xml
Not currently relevant for flowable, but this version supports running JUnit 5 tests out of the box (no additional configuration required).
> Upgrade maven-surefire-plugin to version 2.22.0

- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailServiceTaskTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailTestCase.java
- modules/flowable-engine/src/test/resources/flowable.cfg.xml
* Remove the forceToEmailTenant from the test flowable.cfg.xml
* Create the required MailServerInfo within the needed tests
* Make sure that the initial mailServerInfo is reset after the Email tests (in case it was modified)
> Make sure the EmailServiceTaskTest can run green on all DBs

- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/el/JuelExpression.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/ServiceTaskDelegateExpressionActivityBehavior.java
If it's already a FlowableException do not wrap it into a new FlowableException. Until now when you throw a FlowableIllegalArgumentException it ends up in a 500 internal error.
> Do no wrap a FlowableException into a new FlowableException

- modules/flowable-spring-security/pom.xml
- modules/flowable-spring-security/src/main/java/org/flowable/spring/security/FlowableUser.java
- modules/flowable-spring-security/src/main/java/org/flowable/spring/security/FlowableUserDetails.java
- modules/flowable-spring-security/src/main/java/org/flowable/spring/security/FlowableUserDetailsService.java
- modules/flowable-spring-security/src/main/java/org/flowable/spring/security/GroupDetails.java
- modules/flowable-spring-security/src/main/java/org/flowable/spring/security/UserDto.java
- modules/flowable-spring-security/src/test/java/org/flowable/spring/security/FlowableUserDetailsServiceTest.java
- modules/flowable-spring-security/src/test/resources/flowable.idm.cfg.xml
- modules/flowable-spring-security/src/test/resources/log4j.properties
* Add test for testing the FlowableUserDetailsService
* Add UserDto and GroupDetails which are complying with Serializable
* Deprecate FlowableUser#getPrivileges as it is not required and returns only the User privileges and not the group ones
> Add FlowableUserDetails interface for extending the Spring Security UserDetails

- modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/static/scripts/app-cfg.js
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/scripts/app-cfg.js
- modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/static/scripts/app-cfg.js
Use current `window.location.pathname` to figure out the current context root instead of hardcoded context roots. Tested with Mozilla Firefox and Google Chrome.
> Change to dynamic context root for ui-idm-app #1022

- modules/flowable-app-rest/pom.xml
- modules/flowable-app-rest/src/main/resources/static/docs/index.html
The Swagger REST resources were missing from the flowable-rest application
> Swagger for the CMMN REST API should be part of the flowable-rest documentation

- distro/src/readme.html
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ProcessEngineAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/process/ProcessEngineAutoConfigurationTest.java
* When an IdGenerator bean qualified with @Process is present that this one would be used
* When a single IdGenerator bean is present then this one would be used
* When there are multiple IdGenerator beans then none would be used and the default StrongUuidGenerator would be used
> Support for using multiple IdGenerator beans in the Spring Context

- .travis.yml
Build on Java 10 passes, so lets keep it this way.
> Disallow Travis build failures on Java 10.

- modules/flowable-common-rest/src/main/java/org/flowable/common/rest/variable/JsonArrayRestVariableConverter.java
- modules/flowable-common-rest/src/main/java/org/flowable/common/rest/variable/JsonObjectRestVariableConverter.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/RestResponseFactory.java
Hi
We are using flowable-rest and want to use json variable types.
It seems that everything was put in place to support it, since we can use them in flowable-modeler and flowable-task, however in flowable-rest and flowable-admin it gives some troubles.
With this PR I try to fix three problems:
1.  Creating variables of type json doesn't work using REST. I.e. this fails:
```
curl --user admin:test -X PUT --header "Content-Type: application/json" http://localhost:8080/flowable-rest/service/runtime/process-instances/.../variables -d '[{"name": "input", "type": "json", "value": {"test": 123}}]'
```
This returns:
```
{"message":"Bad request","exception":"Variable 'input' has unsupported type: 'json'."}
```
2. Reading variables of type json will return them as `serializable`
3. Flowable-admin …
> Support JSON variables in the REST api

- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/compensate/CompensateEventTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/compensate/CompensateEventTest.testCompensateServiceTask.bpmn20.xml
I did not find a test case which only compensates a single service task (without a subprocess being involved). Based on the documentation in section 8.2.31 it appears for this use case the compensate throwing event should be defined like such:
`<intermediateThrowEvent id="throwCompensation">
<compensateEventDefinition activityRef="bookHotel" />
</intermediateThrowEvent>
`
where the value in activityRef refers to the activity id of the service task that completed and will have compensation run on it. However defining the definition in this manner does not produce the expected results as the compensation handler never executes.  
The attached test case shows that defining the compensate throwing event with the activityRef attribute having a value of the id of the service task that is the …
> Compensation Throwing Event for Service Task  - Documentation or Implementation Bug?

- distro/src/notice.txt
- modules/flowable-osgi/src/test/java/org/flowable/osgi/blueprint/BlueprintBasicTest.java
- pom.xml
Due to a bug `3.8.0` uses a OSGI BundleSymbolicName different from previous releases (see: https://issues.apache.org/jira/browse/LANG-1419).
> Update commons-lang3 version to 3.8.1

- distro/src/notice.txt
- docs/public-api/tools/flowable-oas-generator/pom.xml
- docs/userguide/src/en/bpmn/ch07b-BPMN-Constructs.adoc
- docs/userguide/src/en/cmmn/ch06-cmmn.adoc
- modules/flowable-app-engine/pom.xml
- modules/flowable-app-rest/pom.xml
- modules/flowable-cmmn-engine/pom.xml
- modules/flowable-crystalball/pom.xml
- modules/flowable-engine/pom.xml
- modules/flowable-groovy-script-static-engine/pom.xml
- modules/flowable-spring-boot/flowable-spring-boot-samples/pom.xml
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/pom.xml
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-integration/pom.xml
- modules/flowable-spring/pom.xml
- modules/flowable-ui-task/flowable-ui-task-conf/pom.xml
- modules/flowable-ui-task/flowable-ui-task-rest/pom.xml
- modules/flowable5-engine/pom.xml
- modules/flowable5-spring-test/pom.xml
- modules/flowable5-spring/pom.xml
- modules/flowable5-test/pom.xml
- pom.xml
Groovy 2.5+ does no longer provide a groovy-all jar, therefore replace the groovy-all with the groovy-jsr223 artifact (potentially breaking change for people using classes from other groovy modules e.g. groovy-xml as they will have to add these modules manually).
> Update Groovy to version 2.5.2

- modules/flowable-task-service-api/src/main/java/org/flowable/task/api/TaskInfoQuery.java
- modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/HistoricTaskInstanceQueryImpl.java
- modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/TaskQueryImpl.java
- modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/HistoricTaskInstance.xml
- modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/Task.xml
In Apache Syncope we embed Flowable as BPMN engine and we frequently need to query active forms, e.g. tasks where `FORM_KEY_ IS NOT NULL`.
We have a local extension of `TaskQueryImpl` with such a capability, but I thought it could be of general use.
> Adding support to query tasks with formKey

- docs/userguide/src/en/bpmn/ch14-UI.adoc
The LDAP initialization user is set by the Flowable IDM app only and
it is app specific. That's the reason why it has the prefix
`flowable.idm` and not `flowable.common.app.idm`.
As reference, it is set in the following method:
org.flowable.ui.idm.conf.Bootstrapper.initializeDefaultPrivileges
Both calls are refering to `flowable.idm.app.admin.user-id`.
> Fix documentation property for LDAP initialization user

- docs/userguide/src/en/bpmn/ch05a-Spring-Boot.adoc
- docs/userguide/src/en/bpmn/ch14-UI.adoc
- modules/flowable-ldap/src/main/java/org/flowable/ldap/LDAPConfiguration.java
- modules/flowable-ldap/src/main/java/org/flowable/ldap/LDAPQueryBuilder.java
- modules/flowable-ldap/src/main/java/org/flowable/ldap/impl/LDAPGroupQueryImpl.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ldap/FlowableLdapProperties.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/spring/boot/ldap/FlowableLdapPropertiesTest.java
- modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/flowable-default.properties
Currently it's not possible to see group details or assign a privilege
to a group in case you have more than one groups. Reason therefore is
that for the LDAPQueryBuilder the group id is ignored.
New behavior is that there is a new attribute to search groups by
the specified group-id. Therefore a new search query is introduced.
For the sample application the user needs to configure
`flowable.idm.ldap.query.group-by-id`.
> Add search for LDAP group by group id (resolves #763)

- modules/flowable-app-engine/src/main/resources/org/flowable/app/db/mapping/entity/AppDefinition.xml
This manifests in a way in which the apps are deployed without version number increases, because of the incorrect parameter causing the method AppDeployer.getMostRecentVersionOfAppDefinition to return null all the time.
> AppDeployer keeps publishing same version number

- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/FlowableSecurityAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/idm/IdmEngineAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ldap/FlowableLdapAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/FlowableSecurityAutoConfigurationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/idm/IdmEngineAutoConfigurationTest.java
Flowable should only configure the `UserDetailsService`.
Spring security performs a default configuration of the authentication provider using a provided `UserDetailsService` and `PasswordEncoder`
through the `InitializeUserDetailsBeanManagerConfigurer`.
In case a global `AuthenticationProvider` is configured then Spring Security uses that through the `InitializeAuthenticationProviderBeanManagerConfigurer`.
Doing this allows easier configuration of Flowable Spring Boot applications with a custom `UserDetailsService`
Add the possibility to use the Spring Security 5 `DelegatingPasswordEncoder` through a property
> Cleanup Flowable Spring Boot Security Auto configuration

- docs/userguide/src/en/bpmn/ch05a-Spring-Boot.adoc
- docs/userguide/src/en/bpmn/ch07a-BPMN-Introduction.adoc
- docs/userguide/src/en/bpmn/ch08-Forms.adoc
- docs/userguide/src/en/single/ch02-Engine.adoc
Three unrelated minor issues in the user guide documentation. I logged these [in the forum](https://forum.flowable.org/t/some-minor-issues-with-documentation/2916), and it was suggested I log a PR, so here it is.
The changes are:
1. Added explicit statement about adding dependency on Acuator starter.
1. Changed "[[10minutetutorial]]" to "[[bpm10minutetutorial]]" as link didn't work when the value started with a number rather than a letter. Also updated cross-reference to this.
1. Fixed minor typo ("build-in" -> "built-in").
One thing  to double-check in case I've messed up is the cross-reference in ch02-Engine.adoc: it didn't work for me, either with the old name or the new name, so I'm not sure if what I've done is quite right here. Also mentioning just in case this is referred to from …
> Minor user-guide documentation issues

- docs/userguide/src/en/bpmn/ch05a-Spring-Boot.adoc
Updated sample XML used in tutorial to have "kermit" initially set as assignee of user task, so that the cURL commands which are used later work correctly. Initially discussed here: https://forum.flowable.org/t/some-minor-issues-with-documentation/2916/6
> Set initial assignee in sample XML in tutorial

- modules/flowable-ui-idm/flowable-ui-idm-conf/src/main/java/org/flowable/ui/idm/security/CustomPersistentRememberMeServices.java
I noticed the cookies were not secure cookies when flowable is acting behind a load balancer. So I added a check for when the header `X_FORWARDED_PROTO` is set.
> added X_FORWARDED_PROTO==https for secure cookies when using a proxy

- modules/flowable-app-engine/src/main/java/org/flowable/app/engine/impl/db/AppDbSchemaManager.java
It appears that during the refactoring of database connections
(4f28b4f43cdfce3abac0497a9919d3bbabd7f306) and (5c2c28e4fe8b1a9f6a8bd551f41ed83105367f68) the code for closing the connections was moved into individual routines and is no longer needed
in the parent routine.
> Remove unused variable

- modules/flowable-engine/src/main/resources/org/flowable/db/create/flowable.hsql.create.engine.sql
As per the HSQL documentation, the 'default' clause is required before 'NOT NULL'. This fix is required to allow the HSQL database to be created for unit testing.
> HSQL create table command requires the 'default' before 'NOT NULL'.

- docs/public-api/tools/flowable-slate/slate/source/includes/_rest-header.md
ISO-8601 date without seconds is not accepted by the API.
> Updated Date query parameter example

- modules/flowable-ui-admin/flowable-ui-admin-app/src/main/resources/static/display/displaymodel.html
Just removed execution and mapping info after successful execution of state change or migration.
https://github.com/flowable/flowable-engine/issues/1415
> flowable-1415 hide state/migration buttons after execution

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/async/json/transformer/CaseInstanceEndHistoryJsonTransformer.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/async/AsyncCmmnHistoryTest.java
CaseInstanceEndHistoryJsonTransformer wasn't updating the state correctly and the case was still active. Fixed unit test.
> Update case state on case instance end

- distro/src/notice.txt
- pom.xml
MyBatis 3.5.0 release notes: https://github.com/mybatis/mybatis-3/releases/tag/mybatis-3.5.0
MyBatis-Spring 2.0.0 release notes: https://github.com/mybatis/spring/releases/tag/mybatis-spring-2.0.0
> Update MyBatis to version 3.5.0 and MyBatis-Spring to version 2.0.0

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskServiceTest.java
We are seeing a NPE when attempting to save a task in the following manner after upgrading to version 6.4.1 from 6.4.0. Attached is a test case to illustrating the NPE.
Task flowableTask = taskService.createTaskQuery().taskId(task.id()).includeIdentityLinks().singleResult();
flowableTask.setDueDate(dueDate);
...
taskService.saveTask(flowableTask);
In stepping through the call path it appears the original persistent state of the task entity has a null value since finding a task using this query does not result in the task entity being stored in the cache (and the original persistent state being populated). The NPE occurs in the TaskEntityManagerImpl.wasPersisted() method as a result of no null check prior to calling getOriginalPersistentState(). Adding a null check resolves the NPE, …
> BUG - NPE when attempting to save a task 

- docker/all-in-one/Dockerfile
Current download URL of Tomcat server used in [`Dockerfile`](https://github.com/flowable/flowable-engine/commit/972ae04a36683e1f55b6d5ff2d114243d6e7cba2#diff-72b672a534ff193a81d25496b5d02d1b) (`flowable/all-in-one` docker image)  returns 404:
http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.34/bin/apache-tomcat-8.5.34.tar.gz
Thus, building the docker image now fails.
Apparently, this Apache mirror site keeps only recent versions. 
The PR updates the download url so that it uses [http://archive.apache.org](http://archive.apache.org) , instead of [http://www-eu.apache.org](http://www-eu.apache.org).  
This should ensure reproducible future builds.
> Update Tomcat server download URL used in Dockerfile of flowable/all-in-one Docker image.

- pom.xml
CXF now works with Java 11, see: https://cxf.apache.org/docs/33-migration-guide.html
If this pull request is merged it should be possible to enable the CXF tests on Java 11 (for https://github.com/flowable/flowable-engine/pull/1249).
> Update CXF to version 3.3.0

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryServiceTaskLogTest.java
http://qa.flowable.org/job/Flowable6Postgres_AsyncHistory/466/testReport/junit/org.flowable.engine.test.api.history/HistoryServiceTaskLogTest/queryForTaskLogEntriesByLogNumber_TaskService__HistoryService__ManagementService__ProcessEngineConfiguration_/
> async history ordering test fix

- docs/userguide/src/en/dmn/ch05-Deployment.adoc
In the existing example, only the `addClasspathResource` method was used. This method  uses the classpath string to create the InputStream internally and to name the resource. In the other methods available, like addInputStream, you must provide in two parameters the resource name and the resource variable to get the bytes from the definition. In these cases, if you don't set the resource name with a .dmn suffix, the deployment does not recognize the resource as a DMN definition. In the existing example, the  name of the deployment was set without a suffix and that was also misleading.
> Clarify DMN Deployment definition example

- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/BpmnRestApiInterceptor.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/RestResponseFactory.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/RestUrls.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricTaskLogCollectionResource.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricTaskLogEntryBaseResource.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricTaskLogEntryQueryRequest.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricTaskLogEntryResponse.java
- modules/flowable-rest/src/test/java/org/flowable/rest/conf/ApplicationConfiguration.java
- modules/flowable-rest/src/test/java/org/flowable/rest/conf/ApplicationWithTaskLogging.java
- modules/flowable-rest/src/test/java/org/flowable/rest/conf/engine/EngineConfigurationWithTaskLogging.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricTaskLogCollectionResourceTest.java
- modules/flowable-rest/src/test/resources/org/flowable/rest/api/history/HistoricTaskLogCollectionResourceTest.bpmn20.xml
- Added resource to hold REST query method at `/history/historic-task-log-entries`
- Modified test configuration to allow enabling task history logging
> Expose method to query task log entries

- lgtm.yml
Here is an [LGTM](https://lgtm.com/projects/g/flowable/flowable-engine/overview/) config which classifies anything under `**/src/main/resources/static/libs/` as library code. This should remove about 400 alerts.
@jbarrez This is as we discussed. I'm happy to add more paths as needed, if you feel there are more alerts coming from library code. Let me know.
> Config to remove LGTM alerts from library code

- docs/userguide/src/en/base/header-rest.adoc
Note in the explanation of the Paging and sorting section to clarify how to use the "start" parameter. It can be understood as "page number" instead of "offset".
> REST doc clarification about the start parameter

- pom.xml
This reverts commit 3ff0874f6715f065d233723f7de3f5889e905480.
The reason is that the tests in the different UI apps are now failing due to conflicting versions of ByteBuddy. We are importing the spring-boot-dependencies in the pom and the apps are using that. This leads to having Mockito 2.24.0 and ByteBuddy 1.7.11 (defined in the spring-boot-dependencies). Mockito 2.24.0 needs ByteBuddy 1.9.7.
Tests are also failing on Java 12 EA when using Mockito 2.24.0 with ByteBuddy 1.9.7. Failure is: "Mockito cannot mock this class: interface java.util.Map. Mockito can only mock non-private & non-final classes."
> Revert "Update Mockito to version 2.24.0 (#1571)"

- modules/flowable-camel-cdi/src/test/java/org/flowable/camel/cdi/named/CdiCustomContextTest.java
- modules/flowable-camel-cdi/src/test/java/org/flowable/camel/cdi/named/CdiCustomNonDefaultNamedContextTest.java
- modules/flowable-camel-cdi/src/test/java/org/flowable/camel/cdi/std/CdiSimpleProcessTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/DecisionTaskJsonConverterTest.java
- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricVariableInstanceCollectionResourceTest.java
- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricVariableInstanceQueryResourceTest.java
- modules/flowable-content-engine/src/test/java/org/flowable/content/engine/test/ContentItemTest.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/replay/ReplayEventLogTest.java
- modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/test/history/HistoryTest.java
- modules/flowable-http/src/test/java/org/flowable/http/cmmn/CmmnHttpTaskTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/IdentityServiceTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/PasswordEncoderTest.java
- modules/flowable-idm-spring/src/test/java/org/flowable/spring/test/authentication/SpringPasswordEncoderTest.java
- modules/flowable-json-converter/src/test/java/org/flowable/editor/language/DecisionTaskConverterTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/api/history/HistoricDetailCollectionResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricDetailQueryResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricVariableInstanceCollectionResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricVariableInstanceQueryResourceTest.java
For example, instead of "assertEquals(true, <sometest>"
use "assertTrue(<sometest>)"
> Simplify Junit assertion'

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryServiceTaskLogTest.java
Looks like lots of changes but they are just space changes
to make the code match a standard format.  For example,
replace "if(" with "if (".
> Standards: remove unnecessary semicolon.

- modules/flowable-engine/pom.xml
- modules/flowable-entitylink-service-api/pom.xml
- modules/flowable-entitylink-service/pom.xml
- modules/flowable-http/pom.xml
- modules/flowable-identitylink-service-api/pom.xml
- modules/flowable-identitylink-service/pom.xml
- modules/flowable-job-service-api/pom.xml
- modules/flowable-job-service/pom.xml
- modules/flowable-job-spring-service/pom.xml
- modules/flowable-mule/pom.xml
- modules/flowable-spring/pom.xml
- modules/flowable-task-service-api/pom.xml
- modules/flowable-task-service/pom.xml
- modules/flowable-ui-admin/flowable-ui-admin-app/pom.xml
- modules/flowable-ui-admin/pom.xml
- modules/flowable-ui-idm/pom.xml
- modules/flowable-ui-modeler/pom.xml
- modules/flowable-ui-task/pom.xml
- modules/flowable-variable-service-api/pom.xml
- modules/flowable-variable-service/pom.xml
- modules/flowable5-engine/pom.xml
- modules/flowable5-mule-test/pom.xml
- modules/flowable5-spring-test/pom.xml
Alphabetical test run order is already defined in root POM.
> Remove unnecessary maven-surefire-plugin configuration in modules.

- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/RestResponseFactory.java
Tenant Id attribute not returned for REST API /identity/users #1479
> Fix for issue #1479

- modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/engine/variable/QueryVariable.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/engine/variable/QueryVariable.java
Fixes "Unsupported variable query operation: EQUALS" (fixes #1437)
Not sure this is correct, my knowledge of Swagger/OpenAPI is limited.
>   Fix Swagger/OpenAPI queryVariable operation enum case

- modules/flowable-dmn-json-converter/src/main/java/org/flowable/editor/dmn/converter/DmnJsonConverterUtil.java
It seems there are 9 possible values and they are all accounted
for in the test.
> Remove duplicated string "ALL OFF"

- modules/flowable-cmmn-engine/pom.xml
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/FlowableCmmnTestCase.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/async/AsyncCmmnHistoryTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/PlanItemInstanceQueryTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/RuntimeServiceTest.java
- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/db/DbSqlSession.java
- pom.xml
Fix for SQL Server is to make sure that the databaseType is set on the ListQueryParameterObject when listing without cache
Adapt test cases to use time without milliseconds. The reason for this is that SQL Server rounds the milliseconds
> Fix querying with order by on SQL Server + add profile for running tests with SQL Server on CI

- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/BoundaryEventJsonConverter.java
- modules/flowable-json-converter/src/test/java/org/flowable/editor/language/BoundaryEventGraphicInfoTest.java
- modules/flowable-json-converter/src/test/resources/test.boundaryeventgraphicinfo.json
When converting an (java) bpmnmodel to json the boundary event must take the parents graphicalinfo into account.
> Fix for boundary event graphicalinfo calculation.

- modules/flowable-ui-common/src/main/java/org/flowable/ui/common/model/UserRepresentation.java
- modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/static/i18n/en.json
- modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/static/i18n/es.json
- modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/static/i18n/fr.json
- modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/static/scripts/idm-user-mgmt-controller.js
- modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/static/views/idm-user-mgmt.html
- modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/static/views/popup/idm-user-create.html
- modules/flowable-ui-idm/flowable-ui-idm-logic/src/main/java/org/flowable/ui/idm/model/UpdateUsersRepresentation.java
- modules/flowable-ui-idm/flowable-ui-idm-logic/src/main/java/org/flowable/ui/idm/service/UserService.java
- modules/flowable-ui-idm/flowable-ui-idm-logic/src/main/java/org/flowable/ui/idm/service/UserServiceImpl.java
- modules/flowable-ui-idm/flowable-ui-idm-rest/src/main/java/org/flowable/ui/idm/rest/app/IdmUsersResource.java
I'm extending a previous pull request by @mattydebie ( https://github.com/flowable/flowable-engine/pull/1444 ). To make it easier to accept the PRs, I've decided to take a more gradual approach and split this into the non-controversial part of being able to edit the tenant ID within IDM and the work-in-progress part where the tenant ID is passed along with the requests.
> Add the ability to set and edit Tenant ID for users in IDM

- modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/static/scripts/idm-user-mgmt-controller.js
- modules/flowable-ui-idm/flowable-ui-idm-logic/src/main/java/org/flowable/ui/idm/service/UserServiceImpl.java
I noticed that the code which creates users does not check for duplicate user IDs and attempts to create such a duplicate. This ends with an exception complaining about violations of DB constraints.
This PR does the following:
1. Check that an user with this ID does not already exist and if it does, throw an exception. I left the duplicate email check in place for backwards compatibility.
2. Changes the UI error message a bit to reflect the nature of the error
3. Slightly change handling of blank email field, the original code ignores it if it's null (likely for creation of email-less service accounts such as 'rest'), but UI sends an empty String if no email is entered. Curiously, it also sends null if the address is invalid. So let's check it with StringUtils instead so that duplicate …
> Improve user creation checks in IDM

- modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/CmmnRestResponseFactory.java
- modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/caze/HistoricCaseInstanceBaseResource.java
- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricCaseInstanceCollectionResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricProcessInstanceCollectionResourceTest.java
I have noticed that the Rest API /cmmn-api/cmmn-history/historic-case-instances?includeCaseVariables=true is not working.
The result is returned without any case variables being included - the parameter is being ignored.
It seems that the implementation for the parameter includeCaseVariables is missing. I have added the missing logic, by repeating the same code from the historic-process-instances Rest API.
Please let me know if anything else is needed.
Thanks,
Paul
> Fixed support for includeCaseVariables when retrieving historic cases

- modules/flowable-ui-idm/flowable-ui-idm-logic/src/main/java/org/flowable/ui/idm/service/UserServiceImpl.java
I omitted to change the way newly-created users are fetched in the previous PR #1712, so this is a little bugfix. Let's fetch them by the ID (necessarily unique because of DB constraints) instead of email. Presently the code is throwing an error if there are multiple service accounts without an email, because the query returns more than a single result.
> Fix fetching of the new user after creation

- distro/src/notice.txt
- pom.xml
With this update the travis build passes on Java 13.
> Update Groovy to version 2.5.7.

- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/DefaultAsyncJobExecutor.java
- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/cmd/UnacquireOwnedJobsCmd.java
Relates to this forum post: https://forum.flowable.org/t/unacquire-jobs-when-asyncexecutor-shutdown-method-is-called/3855
Also, found that the unacquire method is called on the start of the AsyncExecutor. This PR, makes it to be called on the shutdown as well.
> Add support for unaqcuiring jobs on AsyncExecutor shutdown

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/HttpClientConfig.java
- modules/flowable-engine/src/main/java/org/flowable/engine/cfg/HttpClientConfig.java
- modules/flowable-http/src/main/java/org/flowable/http/bpmn/impl/HttpActivityBehaviorImpl.java
- modules/flowable-http/src/main/java/org/flowable/http/cmmn/impl/CmmnHttpActivityBehaviorImpl.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/FlowableHttpProperties.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ProcessEngineAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/cmmn/CmmnEngineAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/cmmn/CmmnEngineAutoConfigurationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/process/ProcessEngineAutoConfigurationTest.java
Motivation was to be able to set the 'useSystemProperties' setting on the http client builder. This enables the configuration of proxy settings through system properties (amongst other things).
> Http task configuration through spring boot, config to use system properties

- modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/DisplayJsonClientResource.java
> Fix sub-process track bug in flowable-admin module (#1767)

- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/ProcessTaskTest.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CaseInstanceHelperImpl.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CaseTaskTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CmmnRuntimeServiceTest.java
- modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/engine/test/MixedDeploymentTest.java
- modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/test/runtime/DecisionTaskTest.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/cmd/AbstractExecuteDecisionCmd.java
- modules/flowable-engine-common-api/src/main/java/org/flowable/common/engine/api/scope/ScopeTypes.java
- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/AbstractEngineConfiguration.java
- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/DefaultTenantProvider.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/CallActivityBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/StartProcessInstanceCmd.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/callactivity/CallActivityAdvancedTest.java
- modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/cmd/AbstractGetFormInstanceModelCmd.java
- modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/cmd/GetFormModelCmd.java
- modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/cmd/GetFormModelWithVariablesCmd.java
- modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/FormInstanceTest.java
- modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/FormModelTest.java
* introduce new getter and setter for defaultTenantProvider
* migrate existing getter usages to defaultTenantProvider
* implement fallback for existing defaultTenantValue getter and setter
* deprecate AbstractEngineConfiguration#setDefaultTenantValue in favor of AbstractEngineConfiguration#setDefaultTenantProvider
> replace AbstractEngineConfiguration defaultTenantValue with defaultTenantProvider

- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/i18n/en.json
Before this change the description of the documentation package was a copy of the description of the name package.
> Flowable-modeler: Fix description documentation package.

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/changestate/ChangeStateForMultiInstanceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceMigrationCallActivityTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceMigrationMultiInstanceTest.java
- pom.xml
Update code because of breaking change related to extraction of map values with a single parameter (see: joel-costigliola/assertj-core#1469).
> Update AssertJ to version 3.13.2.

- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/BoundaryTimerEventTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/BoundaryTimerNonInterruptingEventTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/DurationTimeTimerEventTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/InstantTimeTimerEventTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/IntermediateTimerEventRepeatWithEndTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/IntermediateTimerEventTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/compatibility/StartTimerEventRepeatCompatibilityTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/gateway/InclusiveGatewayTest.java
This should fix occasional test failures observed in builds of recent pull requests.
> Make some timer tests more stable in slow environments (e.g. Travis CI).

- docs/userguide/src/en/bpmn/ch05a-Spring-Boot.adoc
- docs/userguide/src/zh_CN/bpmn/ch05a-Spring-Boot.adoc
- modules/flowable-app-rest/src/main/java/org/flowable/rest/app/properties/RestAppProperties.java
- modules/flowable-app-rest/src/main/java/org/flowable/rest/conf/PropertyBasedCorsFilter.java
- modules/flowable-app-rest/src/main/java/org/flowable/rest/conf/SecurityConfiguration.java
Background: I have a number of web applications built on the micro-frontend pattern that need process and decision engine support. I'd like to use the out-of-the-box Flowable rest container to fulfil that need but currently it does not provide CORS support. So I have to re-package the jar and container just to add a tiny amount of what I'd say is really just configuration.
This PR modifies the `SecurityConfiguration` to add the Spring CORS filter configured via application properties.
> Add declarative CORS support

- modules/flowable-jms-spring-executor/pom.xml
- modules/flowable-jms-spring-executor/src/test/java/org/flowable/test/spring/executor/jms/SpringJmsTest.java
Code changes are not required. Imho using `java.time.Duration` is more readable.
> Update Awaitility to version 4.0.0.

- modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/cmd/GetVariablesFromFormSubmissionCmd.java
- modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/FormInstanceTest.java
- modules/flowable-form-engine/src/test/resources/org/flowable/form/engine/test/deployment/form_with_dates.form
Check type of input when attempting to parse dates in the forms engine (#1915)
> Check input type for dates in form engine

- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/AbstractEngineConfiguration.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
Our use of flowable requires some default mybatis type handlers to be overriden. Based upon the mybatis documentation the only way to do this is by specifying the overides in the mapping file as documented here:
https://mybatis.org/mybatis-3/configuration.html#typeHandlers
This PR therefore introduces new methods to allow for the location of the mybatis mapping file to be chosen.
Change-Id: Iff9af696a950c5d79b0ea4c2fa96582a5c3b1842
> Allow MyBatis mapping file to be customized.

- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/cmd/UnacquireOwnedJobsCmd.java
We had the requirement to check which jobs were unacquired by the AsyncExecutor and did not find a way to do it from the logs(the database selection is hard to be performed as the systems on which we are operating are productive and it is hard to access them).
The intention here is to add some logging in order to know which jobs are unacquired by the current AsyncExcutor.
> Add logging to UnacquireOwnedJobsCmd

- modules/flowable-common-rest/src/main/java/org/flowable/common/rest/api/RequestUtil.java
- modules/flowable-content-engine-configurator/src/test/java/org/flowable/content/engine/configurator/test/ContentEngineConfiguratorTest.java
- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/util/ReflectUtil.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/util/ReflectUtil.java
substring(x) defaults to the end of the string
* Unit tests: existing test passes
> Remove redundant length (second) argument on substring()

- docs/userguide/src/en/bpmn/ch15-REST.adoc
- docs/userguide/src/zh_CN/bpmn/ch15-REST.adoc
Fixes BPMN Deadletter-jobs REST API documentation regarding Deadletter Jobs resuming.
Replace execute action with move action in the payload (only 'move' action is supported)
> Fixes BPMN Deadletter-jobs REST API documentation

- pom.xml
Building the `flowable-app-rest` docker container produced the following warnings:
```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.flowable:flowable-app-rest:war:6.5.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-resources-plugin is missing. @ org.flowable:flowable-app-rest:[unknown-version], /home/tstephen/git/flowable-engine/modules/flowable-app-rest/pom.xml, line 503, column 19
[WARNING] 'build.plugins.plugin.version' for com.spotify:dockerfile-maven-plugin is missing. @ org.flowable:flowable-app-rest:[unknown-version], /home/tstephen/git/flowable-engine/modules/flowable-app-rest/pom.xml, line 528, column 19
[WARNING] 'build.plugins.plugin.version' for …
```
> remove warnings due to unspecified plugin versions

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/CompletePlanItemInstanceOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/StateTransition.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CasePageTaskTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/PlanItemCompletionTest.java
Use terminate state on automatically finished plan items if their parent stage or case plan model gets auto-completed, even for case pages as it would leave such plan items in complete state, although they have never been actually completed.
> Terminate child plan items on parent stage auto-completion, instead of completing them.

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/EvaluateCriteriaOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/util/ExpressionUtil.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/util/PlanItemInstanceContainerUtil.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/AutoCompleteEvaluationTest.java
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/AutoCompleteEvaluationTest.testAutoCompleteCondition.cmmn
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/PlanItemCompletionTest.testComplexCompletionWithAutocompletion.cmmn
Support the evaluation of an optional auto-complete condition on a case plan model or stage at runtime whenever the plan item is evaluated for completion.
> support auto-complete condition for case plan model and stage

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/EvaluateCriteriaOperation.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/AutoCompleteEvaluationTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CaseCompletableReEvaluationTest.java
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/CaseCompletableReEvaluationTest.testCaseReEvaluationOfCompletableFlag.cmmn
The case plan model completable flag once set, might be false again later as child plan items state might change. This fix re-evaluates the completable flag and compares it, even if it was set once already.
> re-evaluate case plan model completable flag

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/AbstractFlowableCmmnTestCase.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/AutoCompleteEvaluationTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CaseCompletableReEvaluationTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CaseCompletionExitSentryTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/PlanItemCompletionTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/StageCompletionExitSentryTest.java
> Optimize CMMN unit tests with a more robust lookup for plan item instances used for starting or triggering

- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnXmlConstants.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/RepetitionRuleXmlConverter.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/PlanItemControlExport.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/RepetitionRuleExtendedAttributesConverterTest.java
- modules/flowable-cmmn-converter/src/test/resources/org/flowable/test/cmmn/converter/repetitionRuleExtension.cmmn
- modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/RepetitionRule.java
With the extended attributes, the repetition rule can be controlled in a more fine-grained way, for instance avoiding to create endless instances, if an entry-criterion with an if-part is satisfied.
> Extend the repetition rule with additional attributes

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/HandleHistoryCleanupTimerJobCmd.java
While manually testing the CMMN history cleanup feature, I stumbled upon the following exception, and noticed that no cleanup had happened for the cases (no problem at all with a similar manual test of the BPMN history cleanup feature): `org.flowable.common.engine.api.FlowableException: No job handler registered for type cmmn-history-cleanup in job config for engine: bpmn`
After investigation, I found out that the cleanup timer job was missing the CMMN scope type. Problem appears to be solved when this scope type is properly set.
* Unit tests: NO (but would gladly do so when we identify how to reproduce the issue in an automated test)
> fix scope type of job handling CMMN history cleanup

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/AbstractFlowableCmmnTestCase.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/PlanItemRepetitionWithCollectionVariableAndConditionTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/PlanItemRepetitionWithCollectionVariableTest.java
making tests predictable, independent of the result order, if the DB is super fast.
> make plan item completion utility function independent of the returned order

- modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/repository/CaseDefinitionQuery.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/repository/CaseDefinitionQueryImpl.java
- modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/mapping/entity/CaseDefinition.xml
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/authorization/StartAuthorizationTest.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/ProcessDefinitionQueryImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/repository/ProcessDefinitionQuery.java
- modules/flowable-engine/src/main/resources/org/flowable/db/mapping/entity/ProcessDefinition.xml
- modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/authorization/StartAuthorizationTest.java
When startableByUserOrGroups is used then the process and cmmn CandidateManager(s) will not be invoked to get the groups for the authorized user
> Add startableByUserOrGroups to the ProcessDefinitionQuery and CaseDefinitionQuery

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/PlanItemInstanceEntityManagerImpl.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/StateTransition.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/CrossBoundaryActivationWithExitEventTypeCombinationTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/OrphanEventListenerRemovalCombinedWithRepetitionTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/StageTest.java
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/itemcontrol/CrossBoundaryActivationWithExitEventTypeCombinationTest.testCrossBoundaryActivationWithExitEventTypeCombinationTest.cmmn
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/itemcontrol/OrphanEventListenerRemovalCombinedWithRepetitionTest.testRemovalOfOrphanedEventListeners.cmmn
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/itemcontrol/OrphanEventListenerRemovalCombinedWithRepetitionTwoTest.testRemovalOfOrphanedEventListeners.cmmn
Also terminate orphaned plan items in waiting-for-repetition state, if their parent gets terminated, but adapt the search for orphaned event listeners, if such plan items have repetition, as they might get activated later on again.
> Fixing removal of remaining plan item in waiting for repetition state

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/AbstractMovePlanItemInstanceToTerminalStateOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/CmmnOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/EvaluateCriteriaOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/callback/DefaultInternalCmmnJobManager.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/PlanItemInstanceBuilder.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/PlanItemInstanceBuilderImpl.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/PlanItemInstanceEntityManager.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/PlanItemInstanceEntityManagerImpl.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/AbstractCmmnDynamicStateManager.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/util/ExpressionUtil.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/DynamicPlanItemNameWithRepetitionBasedOnJsonArrayTest.java
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/itemcontrol/DynamicPlanItemNameWithRepetitionBasedOnJsonArrayTest.testDynamicNameWithRepetitionCollectionNoFallbackExpression.cmmn
Create a builder API for plan item instance creation with a new mode for silent name expression evaluation.
> Turn complex create method into builder API for plan item instance creation

- modules/flowable-engine/src/main/java/org/flowable/engine/history/HistoricProcessInstanceQuery.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/ExecutionQueryImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/HistoricProcessInstanceQueryImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/ProcessInstanceQueryImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/runtime/ProcessInstanceQuery.java
- modules/flowable-engine/src/main/resources/org/flowable/db/mapping/entity/Execution.xml
- modules/flowable-engine/src/main/resources/org/flowable/db/mapping/entity/HistoricProcessInstance.xml
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/ProcessInstanceQueryTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/history/HistoricProcessInstanceTest.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricProcessInstanceBaseResource.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricProcessInstanceCollectionResource.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricProcessInstanceQueryRequest.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/BaseProcessInstanceResource.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/ProcessInstanceCollectionResource.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/ProcessInstanceQueryRequest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricProcessInstanceCollectionResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/ProcessInstanceCollectionResourceTest.java
Added support for processInstance BusinessKeyLike to HistoricProcessInstaceQuery and ProcessInstanceQuery including REST api. This is discussed at https://forum.flowable.org/t/proposal-for-new-method-processinstancebusinesskeylike-to-historicprocessinstancequery/4886
> Added support for BusinessKeyLike to (Historic)ProcessInstanceQuery

- docs/docusaurus/docs/cmmn/ch03-API.md
- docs/docusaurus/website/versioned_docs/version-6.4.2/bpmn/ch11-History.md
FWIW, `completeable` really should be `completable` but it is this way 124 times in ~33 files (doc, java, and sql).  The correct spelling is also found 184 times in ~24 files (most often in CMMN related files).  Obviously no changes were made for this inconsistency.
> Spelling fixes

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/deploy/DeploymentManager.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/deploy/ProcessDefinitionInfoCache.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/deploy/ProcessDefinitionInfoCacheObject.java
- modules/flowable-engine/src/test/java/org/flowable/standalone/deploy/CustomProcessDefinitionInfoCache.java
- modules/flowable-engine/src/test/java/org/flowable/standalone/deploy/CustomProcessDefinitionInfoCacheTest.java
- modules/flowable-engine/src/test/resources/org/flowable/standalone/deploy/custom.procedefinitioninfo.cache.test.flowable.cfg.xml
- modules/flowable-engine/src/test/resources/org/flowable/standalone/deploy/processDefinitionInfoCacheTest.bpmn20.xml
Support for custom ProcessDefinitionInfoCache very much like ProcessDefinitionCache
so that it can be leveraged in distributed environment as discussed [here](https://forum.flowable.org/t/distributed-cache-for-processdefinitioninfocache/2419) 
> add support for custom ProcessDefinitionInfo cache

- modules/flowable-ui-modeler/flowable-ui-modeler-conf/src/main/java/org/flowable/ui/modeler/conf/DatabaseConfiguration.java
This corrects the immediate problem with [Jira-2054](https://github.com/flowable/flowable-engine/issues/2054)
but does *not* address the issue of whether CockroachDB should also be added.
> JIRA-2054 Add Maria DB to Modeler code base

- modules/flowable-json-converter/src/main/java/org/flowable/editor/constants/StencilConstants.java
- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/MailTaskJsonConverter.java
- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/ServiceTaskJsonConverter.java
- modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/i18n/en.json
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/resources/stencilset_bpmn.json
A slightly modified copy of https://github.com/flowable/flowable-engine/commit/7a27027ac779073ad2785d92c5ff4236b8f251bc (which added `htmlVar`) to add `textVar` as well.
> Flowable Modeler: Add textVar field to Mail Task (closes #2018).

- k8s/flowable/templates/ingress.yaml
- k8s/flowable/values.yaml
The existing Helm chart can be configured via the sslRedirect property to serve both http and https. However this is limited by using a self-signed certificate. 
This PR adds an extra property to the `values.yaml` (disabled by default) and the necessary changes to the ingress to allow LetsEncrypt certificates to be issued.
To take advantage of this you will need to install a cert manager to your cluster:
```
kubectl create namespace cert-manager
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.12.0/cert-manager.yaml
```
and then `apply` a ClusterIssuer resource such as this:
```
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
name: letsencrypt-prod
namespace: cert-manager
spec:
acme: …
```
> add support for letsencrypt cert issuer

- modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/mail/EmailSendTaskTest.java
As originally written the test will always return false.
> Lower case the test string for contains() to ever be true

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/CaseTaskActivityBehavior.java
- modules/flowable-event-registry/src/test/java/org/flowable/eventregistry/test/DefaultEventRegistryTest.java
Removed unused imports
Simplified static import of `assertThat` (ran unit test locally without error after change)
> More import updates

- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/process/ProcessEngineRestConfiguration.java
* Unit tests:  NO
With the @ConditionalOnMissingBean a custom project could override the bean to customize and configure the Rest Engine
> Enable to override ProcessEngineRestConfiguration Bean with a custom one

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/changestate/ChangeStateTest.java
Tests in `modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/changestate/ChangeStateTest.java` depends on `modules/flowable-engine/src/main/java/org/flowable/engine/impl/runtime/ChangeActivityStateBuilderImpl.java` where the processVariables and localVariables are stored in a HashMap. Tests are using iterators to get the values in the HashMap.  However, HashMap does not guarantee any specific order of entries. Tests can fail if the iteration order changes.
This PR proposes to fix the test by changing HashMap to LinkedHashMap that make the iteration order deterministic.
> Use LinkedHashMap for deterministic iterations

- docs/public-api/tools/flowable-rest-asciidoc/pom.xml
- modules/flowable-mule/pom.xml
- qa/dbclean/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskQueryTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/history/HistoricTaskInstanceTest.java
- modules/flowable-task-service-api/src/main/java/org/flowable/task/api/TaskInfoQuery.java
- modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/HistoricTaskInstanceQueryImpl.java
- modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/HistoricTaskInstanceQueryProperty.java
- modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/TaskQueryImpl.java
- modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/TaskQueryProperty.java
- add property for category
- add method to the interface
- add implementations
- add usage in tests
- category is an optional field and allows to 'tag' tasks as belonging to a certain category
- corresponding tag is flowable:category
- see #2113
> Add order by method for sorting tasks by category

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/ServiceTaskExpressionActivityBehavior.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/servicetask/TriggerableServiceTaskTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/servicetask/TriggerableServiceTaskTest.testExpression.bpmn20.xml
A ServiceTask with an expression should also be triggerable:
The org.flowable.engine.impl.bpmn.behavior.ServiceTaskExpressionActivityBehavior
class would just not call leave when triggerable is true (in execute()) and leaves in trigger().
https://forum.flowable.org/t/how-to-use-triggerable/3016
> ServiceTask with expression triggerable

- modules/flowable-app-engine-spring/src/test/java/org/flowable/app/spring/test/autodeployment/DefaultAutoDeploymentStrategyTest.java
- modules/flowable-app-engine-spring/src/test/java/org/flowable/app/spring/test/autodeployment/SpringAutoDeployTest.java
- modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/cfg/ForceCloseMybatisConnectionPoolTest.java
- modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/persistence/EntitiesTest.java
- modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/repository/CaseDefinitionCategoryTest.java
- modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/repository/CaseDefinitionQueryTest.java
- modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/repository/CustomAppModelTest.java
- modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/repository/DeploymentQueryTest.java
- modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/repository/DeploymentTest.java
- modules/flowable-event-registry-spring/src/test/java/org/flowable/eventregistry/spring/test/autodeployment/DefaultAutoDeploymentStrategyTest.java
- modules/flowable-event-registry-spring/src/test/java/org/flowable/eventregistry/spring/test/autodeployment/ResourceParentFolderAutoDeploymentStrategyTest.java
- modules/flowable-event-registry-spring/src/test/java/org/flowable/eventregistry/spring/test/autodeployment/SingleResourceAutoDeploymentStrategyTest.java
- modules/flowable-event-registry-spring/src/test/java/org/flowable/eventregistry/spring/test/autodeployment/SpringAutoDeployTest.java
- modules/flowable-form-engine/pom.xml
- modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/DeploymentQueryTest.java
- modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/DeploymentTest.java
- modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/ForceCloseMybatisConnectionPoolTest.java
- modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/FormInstanceTest.java
- modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/FormModelTest.java
- modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/OptionFormFieldTest.java
- modules/flowable-form-spring/src/test/java/org/flowable/spring/test/autodeployment/DefaultAutoDeploymentStrategyTest.java
- modules/flowable-form-spring/src/test/java/org/flowable/spring/test/autodeployment/ResourceParentFolderAutoDeploymentStrategyTest.java
- modules/flowable-form-spring/src/test/java/org/flowable/spring/test/autodeployment/SingleResourceAutoDeploymentStrategyTest.java
- modules/flowable-form-spring/src/test/java/org/flowable/spring/test/autodeployment/SpringAutoDeployTest.java
I noticed in some recent pushes some files with a mix of assertion styles.   It appeared that the Assertj Fluent style was the newer preferred format so I started updating the mixed files and then expanded to the entire package level.   
If this is acceptable I will continue to make similar changes in other packages time permitting.
> Use assertj fluent style

- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/CaseCustomExtensionElementXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/CasePageTaskCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/CaseStartEventXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/CaseTaskCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/CmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/CompletionNeutralConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/EventListenerWithEventTypeXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/ExitCriteriaBlockingExpressionCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/ExitCriteriaNonBlockingCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/ExitSentryExtendedAttributesConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/GenericEventListenerCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/JavaTaskCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/MilestoneCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/NestedStagesCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/ParentCompletionConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/ProcessTask2CmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/ProcessTaskCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/RepetitionRuleExtendedAttributesConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/ScriptServiceTaskCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/SignalEventListenerCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/SimpleCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/SimpleDiCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/SimpleExtensionElementsCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/TimerEventListenerCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/UserEventListenerCmmnXmlConverterTest.java
Another iteration of moving to Assertj Fluent style.
@filiphr I tried to use `.extracting` more often in this PR.
> Use assertj fluent style in flowable-cmmn-converter module

- distro/src/notice.txt
- modules/flowable-ui-admin/flowable-ui-admin-logic/pom.xml
- modules/flowable-ui-admin/flowable-ui-admin-rest/pom.xml
- modules/flowable-ui-common/pom.xml
- modules/flowable-ui-idm/flowable-ui-idm-rest/pom.xml
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/pom.xml
- modules/flowable-ui-modeler/flowable-ui-modeler-rest/pom.xml
- modules/flowable-ui-task/flowable-ui-task-conf/pom.xml
- modules/flowable-ui-task/flowable-ui-task-logic/pom.xml
- modules/flowable-ui-task/flowable-ui-task-rest/pom.xml
- pom.xml
Flowable does not use `High Performance Primitive Collections for Java` (https://github.com/carrotsearch/hppc) so this dependency can be removed.
> Remove unused jackson-datatype-hppc dependency.

- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/HistoricCaseInstanceQueryImplTest.java
This is a single file as I had to touch the majority of lines in
the file to move from old style `AssertThat` to the newer style.
In addition the formatting within the file was inconsistent causing
more changes.
> Use assertj fluent style in flowable-cmmn-engine (part 3)

- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/CmmnHistoryServiceDisableTaskLogTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/CmmnHistoryServiceTaskLogTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/HistoricCaseInstanceInvolvementTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/HistoricDataEngineDeleteTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/HistoricPlanItemInstanceQueryTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/HistoryDataDeleteTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/HistoryServiceTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/MilestoneHistoryServiceTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/PlanItemInstanceHistoryServiceTest.java
Breaking the changes into groups to make review easier.
This finishes off the `org.flowable.cmmn.test.history` package.
> Use assertj fluent style in flowable-cmmn-engine (part 4)

- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/CompletionNeutralTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/CrossBoundaryActivationWithExitEventTypeCombinationTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/DynamicPlanItemNameWithRepetitionBasedOnJsonArrayTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/DynamicPlanItemNameWithRepetitionTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/ManualActivationRuleTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/OrphanEventListenerRemovalCombinedWithRepetitionTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/PlanItemRepetitionManualActivationMaxCountTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/PlanItemRepetitionMaxCountTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/PlanItemRepetitionMaxInstanceCountWithNumberTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/PlanItemRepetitionOnPartMaxCountTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/PlanItemRepetitionOnPartMaxCountUnlimitedTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/PlanItemRepetitionWithCollectionVariableAndConditionDynamicNameTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/PlanItemRepetitionWithCollectionVariableAndConditionTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/PlanItemRepetitionWithCollectionVariableTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/RepetitionRuleTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/RequiredRuleTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/StageRepetitionMaxCountTest.java
Breaking the changes into groups to make review easier.
This is all the code in the `org.flowable.cmmn.test.itemcontrol` package.
> Use assertj fluent style in flowable-cmmn-engine (part 5)

- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/listener/AvailableConditionTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/listener/PlanItemInstanceLifecycleListenerTest.java
Breaking the changes into groups to make review easier.
This is all the code in the `org.flowable.cmmn.test.listener` package.
> Use assertj fluent style in flowable-cmmn-engine (part 6)

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/dynamic/MoveExecutionEntityContainer.java
The test in `org.flowable.engine.test.api.runtime.changestate.ChangeStateForGatewaysTest#testSetCurrentActivityToMultipleActivitiesForParallelGateway` can fail due to a different iteration order of HashMap. The test failure is presented as follows.
`org.junit.ComparisonFailure: expected:<task1> but was:<task2>` when executing `assertEquals("task1", ((FlowableActivityEvent) event).getActivityId());`
The root cause of this failure lies in the following stack trace:
java.util.HashMap$Values.iterator(HashMap.java:968)
java.util.AbstractCollection.toArray(AbstractCollection.java:137)
java.util.ArrayList.<init>(ArrayList.java:178)
org.flowable.engine.impl.dynamic.MoveExecutionEntityContainer.getMoveToFlowElements(MoveExecutionEntityContainer.java:180)
The specification about HashMap says that …
> Use LinkedHashMap for deterministic order

- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/AbstractProcessEngineIntegrationTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/BpmnTimerTaskTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/CaseTaskTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/ChangeStateProcessTaskTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/CmmnEngineConfiguratorAsyncHistoryTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/CmmnEngineConfiguratorAsyncJobTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/CmmnTimerTaskTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/HumanTaskTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/ProcessTaskTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/SignalEventTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/StagePropagationTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/validate/CaseWithFormTest.java
> Use assertj fluent style in flowable-cmmn-engine-configurator.

- modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/autodeployment/AbstractAutoDeploymentStrategyTest.java
- modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/autodeployment/DefaultAutoDeploymentStrategyTest.java
- modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/autodeployment/ResourceParentFolderAutoDeploymentStrategyTest.java
- modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/autodeployment/SingleResourceAutoDeploymentStrategyTest.java
- modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/autodeployment/SpringAutoDeployTest.java
- modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/el/SpringCustomBeanTest.java
- modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/junit4/SpringJunit4Test.java
- modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/jupiter/CmmnSpringJunitJupiterTest.java
> Use assertj fluent style in flowable-cmmn-spring.

- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/AbstractConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/CaseTaskJsonConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/DecisionTaskJsonConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/ExitCriterionOnStageConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/HttpTaskJsonConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/MailTaskJsonConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/PlanItemControlConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/ProcessTaskJsonConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/ScriptTaskConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/SentryConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/SentryOnPartAssociationsConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/SentryOnPartConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/SimpleConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/StageConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/TaskJsonConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/UserEventListenerConverterTest.java
> Use assertj fluent style in flowable-cmmn-json-converter.

- modules/flowable-content-engine/src/test/java/org/flowable/content/engine/test/ContentItemTest.java
- modules/flowable-content-engine/src/test/java/org/flowable/content/engine/test/ForceCloseMybatisConnectionPoolTest.java
> Use assertj fluent style in flowable-content-engine.

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/ActivityEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/AttachmentEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CallActivityTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CancelCallActivityTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CancelUserTaskTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CommentEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/DatabaseEventLoggerTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/DeploymentEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/ErrorThrowingEventListenerTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/ExecutionEventsTest.java
Working on the `org.flowable.engine.test.api.event` package.
> Use assertj fluent style in flowable-engine.  Part 1

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/FlowableEventDispatcherTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/FlowableProcessTerminatedEventImplTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/GroupEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/HistoricActivityEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/IdentityLinkEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/JobEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/MessageThrowingEventListenerTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/ModelEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/ProcessDefinitionEventsTest.java
Working on the `org.flowable.engine.test.api.event` package.
> Use assertj fluent style in flowable-engine.  Part 2

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/ProcessDefinitionScopedEventListenerTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/ProcessInstanceEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/ProcessInstanceNameListenerTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/SignalThrowingEventListenerTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/TaskEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/TransactionEventListenerTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/UncaughtErrorEventTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/UserEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/VariableEventsTest.java
This finishes the `org.flowable.engine.test.api.event` package.
> Use assertj fluent style in flowable-engine.  Part 3

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/DatabaseEventLoggerTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/TransactionEventListenerTest.java
Small updates to the `org.flowable.engine.test.api.event` package; this should be the final pass for the package.
> Use assertj fluent style in flowable-engine.  Part 4

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoricProcessInstanceAndVariablesQueryTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoricProcessInstanceQueryAndWithExceptionTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoricProcessInstanceQueryTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoricProcessInstanceQueryVersionTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoricTaskAndVariablesQueryTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryLevelServiceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryServiceDisableTaskLogTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryServiceTaskLogTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryServiceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/NonCascadeDeleteTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/ProcessInstanceLogQueryTest.java
All files in the `org.flowable.engine.test.api.history` package are included.
> Use assertj fluent style in flowable-engine.

- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/el/function/AbstractFlowableShortHandExpressionFunction.java
This PR proposes to use `getDeclaredMethods` to fix problems described in #2203 
I am happy to discuss more if interested.
> Use getDeclaredMethods to exclude inherited methods

- modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/static/workflow/scripts/controllers/render-form.js
In the flowable-task ui, only the user id or group id will be sent to the backend api when a user save or complete a task that a people or group field is used in the form. But the backend service will check the posted data type, it will discard the data if the data type is not a Map. So the selected user or group can not be set to the process variables.  
> Change the posted value of people/group fields from userid/groupid to user/group object when save/complete a task to match the backend api's need

- docs/userguide/src/en/bpmn/ch05a-Spring-Boot.adoc
Add missing '}' in spring boot dependency in JPA support section
> Add missing '}' in dependency

- modules/flowable-idm-spring/src/test/java/org/flowable/spring/test/authentication/SpringPasswordEncoderTest.java
- modules/flowable-idm-spring/src/test/java/org/flowable/spring/test/engine/SpringIdmEngineTest.java
All test files in the `flowable-idm-spring` module.
Converted a mixture of Junit 4 and 5 and assertj code into all Junit 5 and assertj statements.
> Use assertj fluent style in flowable-idm-spring module.

- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/ForceCloseMybatisConnectionPoolTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/GetPropertiesTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/GroupQueryEscapeClauseTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/GroupQueryTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/IdentityServiceTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/PasswordEncoderTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/PrivilegesTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/TokenQueryTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/UserEntityTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/UserQueryEscapeClauseTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/UserQueryTest.java
All test files in the `org.flowable.idm.engine.test` package are included.
Converted a mixture of Junit 4 and 5 and `assertj` code into all Junit 5 and  `assertj` statements.
> Use assertj fluent style in flowable-idm-engine.

- modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/fs/FileSystemContentStorage.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/BoundaryCancelEventActivityBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/IntermediateThrowCompensationEventActivityBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/async/json/transformer/ProcessInstanceEndHistoryJsonTransformer.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/CommentEntityImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityImpl.java
- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/BpmnJsonConverter.java
- modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/persistence/entity/VariableScopeImpl.java
Found occurrences of the same statement(s) at end of both `then`/`else` clauses of an `if` statement.
Moved a single copy of the code to after the end of the `if`.
> Move the same statement(s) at end of both then/else clauses to end of if

- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/async/AsyncTaskTest.java
In recent push `fail()` was used instead of `assertThatThrownBy`.
> Use fluent style for exception test.

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/listener/CmmnListenerNotificationHelper.java
- modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/ImplementationType.java
A new implementation type instance was added to CmmnListenerNotificationHelper in order to get an instance from a listener as it happens in ListenerNotificationHelper.
> Added instance implementation type and CmmnListenerNotificationHelper updated

- modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/flowable-default.properties
Since the default email address is "valid", unconfigured systems used for tests may (or not) be sending outgoing emails by default and they may reach (or not) flowable.org mail servers and they may be (or not) pissing off flowable.org admins 
> Change the property flowable.idm.app.admin.email to an example email 

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/DecisionTaskActivityBehavior.java
- modules/flowable-dmn-api/src/main/java/org/flowable/dmn/api/DecisionExecutionAuditContainer.java
- modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/test/runtime/DecisionTaskTest.java
- modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/test/runtime/DmnTaskTest.java
- modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/bpmn/test/runtime/DmnTaskTest.cfg.xml
- modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/bpmn/test/runtime/DmnTaskTest.firstHit.dmn
- modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/bpmn/test/runtime/DmnTaskTest.oneDecisionTaskProcess.bpmn20.xml
- modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/bpmn/test/runtime/DmnTaskTest.outputOrder.dmn
- modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/bpmn/test/runtime/DmnTaskTest.ruleOrder.dmn
- modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/cmmn/test/runtime/DecisionTaskTest.oneDecisionTaskCase.cmmn
- modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/cmmn/test/runtime/DecisionTaskTest.outputOrder.dmn
- modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/cmmn/test/runtime/DecisionTaskTest.ruleOrder.dmn
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/hitpolicy/AbstractHitPolicy.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/hitpolicy/HitPolicyOutputOrder.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/hitpolicy/HitPolicyRuleOrder.java
- modules/flowable-engine/src/main/java/org/flowable/engine/ProcessEngineConfiguration.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/DmnActivityBehavior.java
Behavior before:
Execution a decision table with the hit policy rule order and output order resulted in either an array or the element, depending on how many rows are hit.
The user of the Decision/DMN task now needs to lookup which of both exists and pick it accordingly.
Behavior after:
For decision table with the hit policy rule order and output order the result is always returned as an array. Independent on how much entries are hit.
> fix decision table result for hit policies with multiple entries

- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricProcessInstanceQueryResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricTaskLogCollectionResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/identity/UserCollectionResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/identity/UserPictureResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/repository/ModelResourceSourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/ProcessInstanceQueryResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/ProcessInstanceVariableResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/TaskAttachmentResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/TaskResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/TaskVariablesCollectionResourceTest.java
Various test files in the `org.flowable.rest.service.api` directory.
There were 10 files in the directory that had a mix of styles so I just updated those files in this PR.
> Use assertj fluent style in flowable-rest module.

- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/task/CmmnTaskQueryTest.java
- modules/flowable-task-service-api/src/main/java/org/flowable/task/api/TaskInfoQuery.java
- modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/HistoricTaskInstanceQueryImpl.java
- modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/TaskQueryImpl.java
- modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/HistoricTaskInstance.xml
- modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/Task.xml
Add support to filter Tasks by caseDefinitionKey for both: TaskQuery and HistoricTaskInstanceQuery
> Support Task Queries by caseDefinitionKey

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/ExitPlanItemInstanceOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/TerminateCaseInstanceOperation.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CompleteWithExitSentryByMilestoneTest.java
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/CompleteWithExitSentryByMilestoneTest.testExitSentryCompletion.cmmn
Fixing case exit sentry with completion semantics, triggered by a milestone to run a completion evaluation on the spot and not relying on the completion flag
> fixing case exit sentry with completion semantics

- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/ExitSentryCompletionExceptionTest.java
In recently pushed code `fail()` syntax was used instead of `assertThatThrownBy()`.
> Use assertj fluent assertThatThrownBy() instead of fail()

- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/CaseCustomExtensionElementXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/CasePageTaskCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/CaseTaskCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/HumanTaskSameDeploymentCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/JavaTaskCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/ProcessTask2CmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/RepetitionRuleExtendedAttributesConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/ScriptServiceTaskCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/SendEventTaskXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/TaskBlockingExpressionCmmnXmlConverterTest.java
Small improvements for more idiomatic assertj style.
> Use assertj fluent style in flowable-cmmn-converter module.

- modules/flowable-content-rest/pom.xml
- modules/flowable-content-rest/src/test/java/org/flowable/content/rest/service/api/BaseSpringContentRestTestCase.java
- modules/flowable-content-rest/src/test/java/org/flowable/content/rest/service/api/content/ContentItemCollectionResourceTest.java
- modules/flowable-content-rest/src/test/java/org/flowable/content/rest/service/api/content/ContentItemResourceTest.java
Added `net.javacrumbs.json-unit` dependency so `assertThatJson` was available.
> Use assertj fluent style in flowable-content-rest module.

- modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/engine/test/MixedDeploymentTest.java
- modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/test/history/HistoryTest.java
- modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/test/runtime/DecisionTaskTest.java
- modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/test/runtime/DmnTaskTest.java
The module had a mix of assertion styles.
> Use assertj fluent style in flowable-dmn-engine-configurator module.

- modules/flowable-event-registry/src/test/java/org/flowable/eventregistry/test/deployment/DeploymentQueryTest.java
- modules/flowable-event-registry/src/test/java/org/flowable/eventregistry/test/deployment/DeploymentTest.java
The module had a mix of assertion styles even in the same file.
> Use assertj fluent style in flowable-event-registry module.

- modules/flowable-event-registry-rest/pom.xml
- modules/flowable-event-registry-rest/src/test/java/org/flowable/eventregistry/rest/service/api/repository/ChannelDefinitionResourceTest.java
- modules/flowable-event-registry-rest/src/test/java/org/flowable/eventregistry/rest/service/api/repository/DeploymentCollectionResourceTest.java
- modules/flowable-event-registry-rest/src/test/java/org/flowable/eventregistry/rest/service/api/repository/DeploymentResourceResourceTest.java
- modules/flowable-event-registry-rest/src/test/java/org/flowable/eventregistry/rest/service/api/repository/DeploymentResourceTest.java
- modules/flowable-event-registry-rest/src/test/java/org/flowable/eventregistry/rest/service/api/repository/DeploymentResourcesResourceTest.java
- modules/flowable-event-registry-rest/src/test/java/org/flowable/eventregistry/rest/service/api/repository/EventDefinitionResourceTest.java
- modules/flowable-event-registry-rest/src/test/java/org/flowable/eventregistry/rest/service/api/runtime/EventInstanceCollectionResourceTest.java
The module had a mix of assertion styles.
Added `net.javacrumbs.json-unit` dependency so `assertThatJson` was available.
> Use assertj fluent style in flowable-event-registry-rest module.

- modules/flowable-dmn-engine/pom.xml
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/impl/el/util/CollectionUtilTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/cfg/ForceCloseMybatisConnectionPoolTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/deployment/DeploymentQueryTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/deployment/DeploymentTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/history/HistoryNoneTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/history/HistoryTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/CalculationsTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/CollectionsContainsAnyTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/CollectionsContainsReversedTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/CollectionsContainsTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/CollectionsNotContainsAnyTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/CollectionsNotContainsTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/CustomConfigRuntimeTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/CustomHitPoliciesEngineConfigTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/DecisionTableExecutionFallBackTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/HitPolicyAnyTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/HitPolicyCollectTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/HitPolicyFirstTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/HitPolicyOutputOrderTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/HitPolicyPriorityTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/HitPolicyRuleOrderTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/HitPolicyUniqueTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/RuntimeTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/StandaloneRuntimeTest.java
Added `net.javacrumbs.json-unit` dependency so `assertThatJson` was available.
> Use assertj fluent style in flowable-dmn-engine module.

- modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/authorization/StartAuthorizationTest.java
- modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/servicetask/ExpressionServiceTaskTest.java
- modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/tasklistener/TaskListenerTest.java
- modules/flowable-engine/src/test/java/org/flowable/examples/variables/VariablesTest.java
In the `org.flowable.examples` package there were 4 files that had a mixture of unit testing styles within the same file.    They now all are using assertj tests.
> Use assertj fluent style in flowable-engine module.

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/ProcessInstanceQueryTest.java
- modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/AbstractVariableQueryImpl.java
While converting a test file that contained various forms of assertions to `assertj` I found an example of a cut-n-paste that didn't test the method that the author thought it did.  So when I changed the method name to the correct method name and reran the test a NPE was generated instead of the expected `FlowableIllegalArgumentException`.   Looking in the source file I noticed that all other "ignore case" methods checked for `null` before trying `value.toLowerCase()` except in the case being tested.  This fixes that error.
* Unit tests: Yes.
> Use assertj fluent style in flowable-engine module and add check to prevent NPE.

- modules/flowable-http/src/test/java/org/flowable/http/bpmn/HttpServiceTaskTest.java
- modules/flowable-http/src/test/java/org/flowable/http/bpmn/async/HttpServiceTaskAsyncTest.java
- modules/flowable-http/src/test/java/org/flowable/http/bpmn/cfg/HttpServiceTaskCfgTest.java
- modules/flowable-http/src/test/java/org/flowable/http/bpmn/validation/HttpServiceTaskValidationTest.java
- modules/flowable-http/src/test/java/org/flowable/http/cmmn/CmmnHttpTaskTest.java
There was a mixture of assertion styles that now all use assertj.  The conversion was complicated by a local function named `assertEquals()`.
> Use assertj fluent style in flowable-http module.

- docs/docusaurus/docs/bpmn/ch05a-Spring-Boot.md
- docs/docusaurus/docs/bpmn/ch14-Applications.md
- docs/userguide/src/en/bpmn/ch05a-Spring-Boot.adoc
- docs/userguide/src/en/bpmn/ch14-Applications.adoc
- docs/userguide/src/zh_CN/bpmn/ch05a-Spring-Boot.adoc
- docs/userguide/src/zh_CN/bpmn/ch13-UI.adoc
- docs/userguide/src/zh_CN/bpmn/ch14-Applications.adoc
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/MailActivityBehavior.java
- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/cfg/mail/MailServerInfo.java
- modules/flowable-engine/src/main/java/org/flowable/engine/ProcessEngineConfiguration.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/MailActivityBehavior.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/FlowableMailProperties.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ProcessEngineAutoConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- modules/flowable5-compatibility/src/main/java/org/flowable/compatibility/DefaultProcessEngineFactory.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/ProcessEngineConfiguration.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/MailActivityBehavior.java
Set SSL SMTP port when SSL is enabled for email server connections (fixes #2343)
I was able to manually test this fix as it applies to a Flowable 6.5.x BPMN XML use-case with an Email Task. The SSL SMTP port could be customized as needed.
> Set SSL SMTP port when SSL is enabled for email server connections (fixes #2343)

- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/ExecutionActiveActivitiesCollectionResourceTest.java
This was found in a recent run of a PR with JDK11.
> Fix test to ignore order of entries.

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CallActivityTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/FlowableEventDispatcherTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryServiceTaskLogTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/identity/IdentityServiceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/RuntimeActivityInstanceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/changestate/ChangeStateForGatewaysTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/changestate/ChangeStateTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceMigrationBatchTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceMigrationTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskServiceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/servicetask/ServiceTaskDelegateExpressionTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/history/HistoricActivityInstanceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/history/HistoricVariableInstanceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/json/JsonTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/logging/ServiceTaskLoggingTest.java
- modules/flowable-engine/src/test/java/org/flowable/standalone/calendar/DurationHelperTest.java
- modules/flowable-engine/src/test/java/org/flowable/standalone/rules/RulesDeployerTest.java
After further review of recent changes found small idiomatic changes to assertj style.
> Use assertj fluent style in flowable-engine module

- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/FlowableJpaAutoConfigurationTest.java
Remove the `@Ignore` annotation from a test because Spring Boot is sufficiently past the release that contained the bug that required ignoring the test.
> Remove test @Ignore because Spring Boot is updated

- modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/cfg/ForceCloseMybatisConnectionPoolTest.java
- modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/persistence/EntitiesTest.java
- modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/repository/CaseDefinitionQueryTest.java
- modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/repository/CustomAppModelTest.java
- modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/repository/DeploymentQueryTest.java
Update assertj code in `org.flowable.app.engine.test` package to use more idiomatic and less redudant assertj constructs.
For example, there is no need to test for `notNull` before `isInstanceOf` as the latter includes the former.
> Update assertj fluent style in flowable-app-engine module.

- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/ForceCloseMybatisConnectionPoolTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/IdentityServiceTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/PrivilegesTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/TokenQueryTest.java
- modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/UserQueryTest.java
A very few updates/consistency changes for the `org.flowable.idm.engine.test.api.identity` package in assertj usage.
> Update assertj fluent style in flowable-idm-engine module.

- modules/flowable-form-engine-configurator/src/test/java/org/flowable/form/engine/test/AbstractFlowableFormEngineConfiguratorTest.java
- modules/flowable-form-engine-configurator/src/test/java/org/flowable/form/engine/test/MixedDeploymentTest.java
- modules/flowable-form-engine-configurator/src/test/java/org/flowable/form/engine/test/ProcessWithFormTest.java
Converted files in `org.flowable.form.engine.test` to assertj.  In the process fixed ordering of imports and removed an unused public variable.
> Use assertj fluent style in flowable-form-engine-configurator module.

- modules/flowable-form-engine/pom.xml
- modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/DeploymentQueryTest.java
- modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/DeploymentTest.java
- modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/FormInstanceTest.java
Various assertj consistency changes in the `org.flowable.form.engine.test` package.   Also added `net.javacrumbs.json-unit` to `pom.xml` so `assertThatJson()` could be used.
> Update assertj fluent style in flowable-form-engine module.

- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/AbstractProcessEngineIntegrationTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/BpmnTimerTaskTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/CaseTaskTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/ChangeStateProcessTaskTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/CmmnEngineConfiguratorAsyncHistoryTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/CmmnTimerTaskTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/EntityLinkDeletionTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/ExternalWorkerCombinedScopeTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/HumanTaskTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/ProcessTaskTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/SignalEventTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/StagePropagationTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/form/PlanItemInstanceTransitionBuilderFormTest.java
- modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/validate/CaseWithFormTest.java
Assertj updates to the `org.flowable.cmmn.test` package.   The changes are minor; things like
- using `isZero()`
- removing null checks before `hasSize()` tests
- a few formatting changes so the code agreed with the majority format (that is `.` starting a line and not ending it)
- removing unnecessary `L` (long) on `hasSize()` and `isEqualTo()` statements
- etc.
No real substantial logic changes.
> Update assertj fluent style in flowable-cmmn-engine-configurator module.

- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-app/src/test/java/org/flowable/test/spring/boot/app/AppSampleApplicationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-form/src/test/java/org/flowable/test/spring/boot/FormSampleApplicationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-jpa-all/src/test/java/org/flowable/test/spring/boot/JpaApplicationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-ldap/src/test/java/flowable/SampleLdapApplicationRestTest.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-process/src/test/java/org/flowable/test/spring/boot/BasicApplicationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-1.5.x/src/test/java/org/flowable/test/spring/boot/RestApiApplicationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/src/test/java/org/flowable/test/spring/boot/RestApiSecurityApplicationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/src/test/java/org/flowable/test/spring/boot/SecurityAutoConfigurationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api/src/test/java/org/flowable/test/spring/boot/RestApiApplicationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-starter/src/test/java/flowable/MixedAsyncExecutorsTest.java
Updates to `org.flowable.test.spring.boot` package.
- use `hasSize()`
- correct spelling
- use `isZero()`
- simplify a few code constructs
- correct usage of `containsExactlyInAnyOrder`
> Update assertj fluent style in flowable-spring-boot-samples module.

- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/AllEnginesAutoConfigurationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/FlowableJpaAutoConfigurationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/ProcessAndCmmnEngineAsyncExecutorTest.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/eventregistry/EventRegistryAutoConfigurationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/process/ProcessAsyncHistoryExecutorTest.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/process/ProcessEngineAutoConfigurationTest.java
Minor changes to the `org.flowable.test.spring.boot` package.  
The most noticeable change other than removing unused variables is the correcting of two method names to not duplicate existing code in `FlowableJpaAutoConfigurationTest`.
> Update assertj fluent style in flowable-spring-boot-starters module.

- modules/flowable-camel-cdi/pom.xml
- modules/flowable-camel-cdi/src/test/java/org/flowable/camel/cdi/named/CdiCustomContextTest.java
- modules/flowable-camel-cdi/src/test/java/org/flowable/camel/cdi/named/CdiCustomNonDefaultNamedContextTest.java
- modules/flowable-camel-cdi/src/test/java/org/flowable/camel/cdi/std/CdiAsyncPingTest.java
- modules/flowable-camel-cdi/src/test/java/org/flowable/camel/cdi/std/CdiCamelVariableBodyMapTest.java
- modules/flowable-camel-cdi/src/test/java/org/flowable/camel/cdi/std/CdiCamelVariableBodyTest.java
- modules/flowable-camel-cdi/src/test/java/org/flowable/camel/cdi/std/CdiSimpleProcessTest.java
> Use assertj fluent style in flowable-camel-cdi module

- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/CaseTaskJsonConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/CriterionConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/DecisionTaskJsonConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/HttpTaskJsonConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/MailTaskJsonConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/ProcessTaskJsonConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/SentryOnPartAssociationsConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/SimpleConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/StageConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/TaskJsonConverterTest.java
- modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/UserEventListenerConverterTest.java
Minor updates to `org.flowable.cmmn.editor` package.  Two biggest changes is removing `isNotNull` test before `isInstanceOf` as it is covered in the later test and combing "only have specific keys" tests.
> Update assert fluent style in flowable-cmmn-json-converter module.

- modules/flowable-content-engine-configurator/pom.xml
- modules/flowable-content-engine-configurator/src/test/java/org/flowable/content/engine/configurator/test/ContentEngineConfiguratorTest.java
> Use assertj fluent style in flowable-content-engine-configurator module.

- modules/flowable-content-spring/pom.xml
- modules/flowable-content-spring/src/test/java/org/flowable/spring/test/engine/SpringContentEngineTest.java
> Use assertj fluent style in flowable-content-spring module.

- modules/flowable-camel/pom.xml
- modules/flowable-camel/src/test/java/org/flowable/camel/AsyncPingTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/AsyncProcessTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/CamelVariableBodyMapTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/CamelVariableBodyTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/CustomContextTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/EmptyProcessTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/ErrorHandlingTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/ErrorMapExceptionTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/ParallelProcessTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/SimpleProcessTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/SimpleSpringProcessTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/examples/initiator/InitiatorCamelCallTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/examples/multiinstance/MultiInstanceTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/examples/ping/PingPongTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/exception/CamelExceptionTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/revisited/AsyncProcessRevisitedTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/revisited/ParallelProcessRevisitedTest.java
- modules/flowable-camel/src/test/java/org/flowable/camel/variables/CamelVariableTransferTest.java
> Use assertj fluent style in flowable-camel module.

- modules/flowable-cxf/pom.xml
- modules/flowable-cxf/src/test/java/org/flowable/engine/impl/webservice/WSDLImporterTest.java
- modules/flowable-cxf/src/test/java/org/flowable/engine/impl/webservice/WebServiceTaskTest.java
- modules/flowable-cxf/src/test/java/org/flowable/engine/test/bpmn/sendtask/WebServiceSimplisticTest.java
- modules/flowable-cxf/src/test/java/org/flowable/engine/test/bpmn/sendtask/WebServiceTest.java
- modules/flowable-cxf/src/test/java/org/flowable/engine/test/bpmn/servicetask/WebServiceSimplisticTest.java
- modules/flowable-cxf/src/test/java/org/flowable/engine/test/bpmn/servicetask/WebServiceTaskTest.java
For the most part a straightforward conversion of the module to assertj style once the jar was added to the POM.  Especially true after Filip fixed a test that wasn't working at all. 👍
> Use assertj fluent style in flowable-cxf module.

- modules/flowable-cdi/src/test/java/org/flowable/cdi/test/api/annotation/BusinessKeyTest.java
- modules/flowable-cdi/src/test/java/org/flowable/cdi/test/api/annotation/CompleteTaskTest.java
- modules/flowable-cdi/src/test/java/org/flowable/cdi/test/api/annotation/ProcessIdTest.java
- modules/flowable-cdi/src/test/java/org/flowable/cdi/test/api/annotation/StartProcessTest.java
- modules/flowable-cdi/src/test/java/org/flowable/cdi/test/api/annotation/TaskIdTest.java
I missed a subdirectory in the recent update to the `flowable-cdi` module.  This fixes the oversight.
> Update assertj fluent style in flowable-cdi module.

- modules/flowable-content-rest/src/test/java/org/flowable/content/rest/service/api/BaseSpringContentRestTestCase.java
Update a file that was over looked when the module was originally converted to assertj.
> Update assertj fluent style in flowable-content-rest module.

- modules/flowable-dmn-rest/pom.xml
- modules/flowable-dmn-rest/src/test/java/org/flowable/dmn/rest/service/api/BaseSpringDmnRestTestCase.java
- modules/flowable-dmn-rest/src/test/java/org/flowable/dmn/rest/service/api/decision/DmnRuleServiceResourceTest.java
- modules/flowable-dmn-rest/src/test/java/org/flowable/dmn/rest/service/api/history/HistoricDecisionExecutionAuditDataResourceTest.java
- modules/flowable-dmn-rest/src/test/java/org/flowable/dmn/rest/service/api/history/HistoricDecisionExecutionCollectionResourceTest.java
- modules/flowable-dmn-rest/src/test/java/org/flowable/dmn/rest/service/api/repository/DecisionTableCollectionResourceTest.java
- modules/flowable-dmn-rest/src/test/java/org/flowable/dmn/rest/service/api/repository/DecisionTableModelResourceTest.java
- modules/flowable-dmn-rest/src/test/java/org/flowable/dmn/rest/service/api/repository/DecisionTableResourceDataResourceTest.java
- modules/flowable-dmn-rest/src/test/java/org/flowable/dmn/rest/service/api/repository/DecisionTableResourceTest.java
- modules/flowable-dmn-rest/src/test/java/org/flowable/dmn/rest/service/api/repository/DmnDeploymentCollectionResourceTest.java
- modules/flowable-dmn-rest/src/test/java/org/flowable/dmn/rest/service/api/repository/DmnDeploymentResourceDataResourceTest.java
- modules/flowable-dmn-rest/src/test/java/org/flowable/dmn/rest/service/api/repository/DmnDeploymentResourceTest.java
Fairly straight forward conversion once assertj and json-unit jars were added to the pom.
Also removed unused imports and fixed a test that was using the wrong variable (probably a cut-n-paste issue).
> Use assertj fluent style in flowable-dmn-rest module.

- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/HistoricDataDeleteTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/exclusive/ExclusiveTaskTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/exclusive/ExclusiveTimerEventTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/servicetask/CallServiceInServiceTaskTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/servicetask/DynamicServiceTaskTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/servicetask/RepeatingServiceTaskTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/servicetask/ServiceTaskDelegateExpressionTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/servicetask/ServiceTaskVariablesTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/servicetask/TriggerableServiceTaskTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/usertask/DisabledDefinitionInfoCacheTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/usertask/DynamicUserTaskTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/usertask/ImportExportTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/usertask/InitiatorTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/usertask/TaskAssignmentCandidateTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/usertask/TaskAssignmentExtensionsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/usertask/TaskDueDateExtensionsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/usertask/TaskPriorityExtensionsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/usertask/UserTaskTest.java
In the process of making consistency changes in the flowable-engine module I found files that needed conversion to assertj in the `org.flowable.engine.test.bpmn` package.  
There are additional files for this module pending but in an attempt to keep the review manageable only this package is in this PR.
> Update assertj fluent style in flowable-engine module.

- modules/flowable-engine-configurator/pom.xml
- modules/flowable-engine-configurator/src/test/java/org/flowable/engine/configurator/test/DeploymentTest.java
- modules/flowable-engine-configurator/src/test/java/org/flowable/engine/configurator/test/ProcessTest.java
Once `assertj` was added to the pom the conversion to `assertj` format was straight forward.
> Use assertj fluent style in flowable-engine-configurator module.

- modules/flowable-event-registry/src/test/java/org/flowable/eventregistry/test/DefaultEventRegistryDataChangeDetectorShutdownTest.java
- modules/flowable-event-registry/src/test/java/org/flowable/eventregistry/test/DefaultEventRegistryDataChangeDetectorTest.java
Remove unneeded `isnotNull()` test as it is covered in the following `isInstanceOf()` test.
> Update assertj fluent style in flowable-event-registry module.

- modules/flowable-event-registry-json-converter/src/test/java/org/flowable/eventregistry/converter/EventJsonConverterTest.java
Found a single file in this module that needed to be converted to `assertj`.   Also removed an unused method definition.
> Use assertj fluent style in flowable-event-registry-json-converter module.

- modules/flowable-ui-admin/flowable-ui-admin-logic/src/main/java/org/flowable/ui/admin/service/engine/AbstractEncryptingService.java
- modules/flowable-ui-admin/flowable-ui-admin-logic/src/main/java/org/flowable/ui/admin/service/engine/CaseDefinitionService.java
- modules/flowable-ui-admin/flowable-ui-admin-logic/src/main/java/org/flowable/ui/admin/service/engine/FlowableClientService.java
- modules/flowable-ui-admin/flowable-ui-admin-logic/src/main/java/org/flowable/ui/admin/service/engine/ProcessDefinitionService.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/AppDefinitionExportService.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/AppDefinitionImportService.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/AppDefinitionPublishService.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/FlowableDecisionServiceService.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/FlowableDecisionTableService.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/FlowableModelQueryService.java
- modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/ModelServiceImpl.java
- modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/app/CaseModelsResource.java
- modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/app/DecisionServicesResource.java
- modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/app/DecisionTablesResource.java
- modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/app/FormsResource.java
Changes to use `java.nio.charset.StandardCharsets.UTF_8` instead of local strings or constants.
In the process cleaned up imports (unused and ordering) and some small code changes.
> Use java.nio.charset.StandardCharsets.UTF_8 as appropriate

- modules/flowable-dmn-json-converter/src/main/java/org/flowable/dmn/editor/converter/DmnJsonConverterUtil.java
In the `if` test for `boolean` the first clause tests the ***value*** for `true`; the second clause tests the ***type*** for `false`.  As `expressionType` is the returned value and not the input this is obviously wrong.  The PR corrects the variable name in the second clause.
> Correct variable name

- modules/flowable-app-engine-rest/src/test/java/org/flowable/app/rest/service/api/repository/AppDefinitionCollectionResourceTest.java
- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/repository/CaseDefinitionCollectionResourceTest.java
- modules/flowable-event-registry-rest/src/test/java/org/flowable/eventregistry/rest/service/api/repository/ChannelDefinitionCollectionResourceTest.java
- modules/flowable-event-registry-rest/src/test/java/org/flowable/eventregistry/rest/service/api/repository/EventDefinitionCollectionResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/repository/ProcessDefinitionCollectionResourceTest.java
The variable `baseUrl` should be `url` and the code was replicated in multiple modules.
> Fix unused variable reference copied in multiple modules

- modules/flowable-engine/src/main/java/org/flowable/engine/delegate/event/impl/BpmnModelEventDispatchAction.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/DefaultInternalJobManager.java
In the first case the variable value as set in the line just above and in the second case the same value was set 3 lines previously.
> Remove redundant code

- modules/flowable-cmmn-engine-configurator/src/main/java/org/flowable/cmmn/engine/configurator/CmmnEngineConfigurator.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/CaseTaskActivityBehavior.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/HumanTaskActivityBehavior.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/TaskActivityBehavior.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/listener/ExpressionPlanItemLifecycleListener.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/data/impl/MybatisCaseInstanceDataManagerImpl.java
- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/el/function/AbstractFlowableVariableExpressionFunction.java
- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/interceptor/TransactionContextInterceptor.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java
Remove unnecessary `casts` where the variable is already defined of the same type or the method returns the required variable type.
There are many other casts that could be removed but these are the simplest ones to see and verify.
> Remove obvious redundant and unneeded casts

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/db/ProcessDbSchemaManager.java
- modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/impl/db/IdmDbSchemaManager.java
Any `String.indexOf()` expressions can be replaced with a call to the `String.contains()` method available in Java 5 and newer versions.  It makes the intent of the code clearer.
> Replace String.indexOf() with contains()

- modules/flowable-ui-admin/flowable-ui-admin-frontend/src/main/resources/static/admin/i18n/en.json
- modules/flowable-ui-admin/flowable-ui-admin-frontend/src/main/resources/static/admin/i18n/fr.json
- modules/flowable-ui-admin/flowable-ui-admin-frontend/src/main/resources/static/admin/i18n/pt-BR.json
The `en.json` file in the `flowable-ui-admin` module was originally committed on June 30, 2016.  In the process the name `Activiti` was not changed.  This PR corrects that oversight.  Better late than never.
> Update product name

- modules/flowable-jmx/pom.xml
- modules/flowable-jmx/src/test/java/org/flowable/management/jmx/DefaultManagementAgentTest.java
- modules/flowable-jmx/src/test/java/org/flowable/management/jmx/DefaultManagementMBeanAssemblerTest.java
- modules/flowable-jmx/src/test/java/org/flowable/management/jmx/DeploymentsJMXClientTest.java
- modules/flowable-jmx/src/test/java/org/flowable/management/jmx/JobExecutorJMXClientTest.java
- modules/flowable-jmx/src/test/java/org/flowable/management/jmx/MBeanInfoAssemblerTest.java
- modules/flowable-jmx/src/test/java/org/flowable/management/jmx/mbeans/JobExecutorMBeanTest.java
- modules/flowable-jmx/src/test/java/org/flowable/management/jmx/mbeans/ProcessDefinitionsTest.java
Straight forward conversion to assertj fluent style in `flowable-jmx` module was the necessary dependency was added to `pom.xml'.
> Use assertj fluent style in flowable-jmx module.

- modules/flowable-content-rest/src/test/java/org/flowable/content/rest/service/api/BaseSpringContentRestTestCase.java
- modules/flowable-form-json-converter/pom.xml
- modules/flowable-form-json-converter/src/test/java/org/flowable/editor/form/converter/FormJsonConverterTest.java
- modules/flowable-form-rest/pom.xml
- modules/flowable-form-rest/src/test/java/org/flowable/form/rest/service/BaseSpringRestTestCase.java
- modules/flowable-form-rest/src/test/java/org/flowable/form/rest/service/api/runtime/FormInstanceCollectionResourceTest.java
- modules/flowable-groovy-script-static-engine/pom.xml
- modules/flowable-groovy-script-static-engine/src/test/java/org/flowable/examples/groovy/GroovyStaticScriptTest.java
- modules/flowable-jms-spring-executor/pom.xml
- modules/flowable-jms-spring-executor/src/test/java/org/flowable/test/spring/executor/jms/SpringJmsTest.java
- modules/flowable-mule/pom.xml
- modules/flowable-mule/src/test/java/org/flowable/mule/MuleHttpBasicAuthTest.java
- modules/flowable-mule/src/test/java/org/flowable/mule/MuleHttpTest.java
- modules/flowable-mule/src/test/java/org/flowable/mule/MuleVMTest.java
Straight forward conversion of some smaller modules after updating the `pom.xml`.
Modules touched are:
- flowable-content-rest
- flowable-form-json-converter
- flowable-form-rest
- flowable-groovy-script-static-engine
- flowable-jms-spring-exectuor
- flowable-mule
> Use assert fluent style in secondary modules.

- modules/flowable-app-engine/src/main/java/org/flowable/app/engine/test/impl/AppTestHelper.java
This file is obviously a clone of similar files in other modules.  The variable:
`public static final String[] APP_RESOURCE_SUFFIXES = new String[] { "app" };` 
has only one entry so the array index reference should be `0` and not `1`.
FWIW, additional refactoring could be done as the `for each` loop a few lines above only ever has one iteration.
> Array index out of bounds

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/SetProcessInstanceBusinessKeyCmd.java
The command for setting the business key on a process instance did not properly handle the case of a process instance started via the v5 compatibility layer. The existing code tried to lookup the process instance in the v6 cache. If this did not succeed, it did not fallback to v5, but exitedthrew with an exception instead. This fix provides an additional fallback to the v5 by dispatching the business key update down to the v5 compatibility layer.
> Fix v5 compat issues when setting business key on process instance

- modules/flowable-app-engine-api/src/main/java/org/flowable/app/api/AppEngineConfigurationApi.java
- modules/flowable-app-engine/src/main/java/org/flowable/app/engine/test/AppDeployment.java
- modules/flowable-cdi/src/main/java/org/flowable/cdi/BusinessProcessEvent.java
- modules/flowable-cdi/src/main/java/org/flowable/cdi/annotation/ProcessVariable.java
- modules/flowable-cdi/src/main/java/org/flowable/cdi/annotation/event/AssignTask.java
- modules/flowable-cdi/src/main/java/org/flowable/cdi/annotation/event/CompleteTask.java
- modules/flowable-cdi/src/main/java/org/flowable/cdi/annotation/event/CreateTask.java
- modules/flowable-cdi/src/main/java/org/flowable/cdi/annotation/event/DeleteTask.java
- modules/flowable-cdi/src/main/java/org/flowable/cdi/annotation/event/EndActivity.java
- modules/flowable-cdi/src/main/java/org/flowable/cdi/annotation/event/StartActivity.java
- modules/flowable-cdi/src/main/java/org/flowable/cdi/annotation/event/TakeTransition.java
- modules/flowable-cdi/src/main/java/org/flowable/cdi/impl/context/ContextAssociationManager.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/CmmnDeployment.java
- modules/flowable-cmmn-image-generator/src/main/java/org/flowable/cmmn/image/CaseDiagramGenerator.java
- modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/HasAssociations.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/playback/CheckStatus.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/test/DmnDeployment.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/test/DmnDeploymentAnnotation.java
- modules/flowable-event-registry/src/main/java/org/flowable/eventregistry/test/ChannelDeploymentAnnotation.java
- modules/flowable-event-registry/src/main/java/org/flowable/eventregistry/test/EventDeploymentAnnotation.java
- modules/flowable-form-api/src/main/java/org/flowable/form/api/FormEngineConfigurationApi.java
- modules/flowable-form-engine/src/main/java/org/flowable/form/engine/test/FormDeploymentAnnotation.java
- modules/flowable-jmx/src/main/java/org/flowable/management/jmx/ManagementAgent.java
- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/AsyncExecutor.java
- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/FailedJobCommandFactory.java
- modules/flowable-job-spring-service/src/main/java/org/flowable/spring/job/service/SpringRejectedJobsHandler.java
- modules/flowable-variable-service-api/src/main/java/org/flowable/variable/api/types/VariableType.java
- modules/flowable-variable-service-api/src/main/java/org/flowable/variable/api/types/VariableTypes.java
Typically the redundant modifiers are `public` or `static` for interfaces or interface components. Some of the files modified already had `public` removed for some of the items; this just completes and standardizes them.
> Remove unneeded public modifiers on interfaces

- modules/flowable-crystalball/pom.xml
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/examples/tutorial/step01/FirstSimulationRunTest.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/process/SimulationRunTaskTest.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/SimpleEventCalendarTest.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/SimpleSimulationRunTest.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/SimulationEventComparatorTest.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/MultiInstanceScriptEventHandlerTest.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/ScriptEventHandlerTest.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/playback/PlaybackProcessStartTest.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/playback/PlaybackRunTest.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/replay/ReplayEventLogTest.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/replay/ReplayRunTest.java
Convert multiple styles in the `flowable-crystalball` module to fluent assertj.
> Use assertj fluent style in flowable-crystalball module.

- modules/flowable-dmn-spring-configurator/pom.xml
- modules/flowable-dmn-spring-configurator/src/test/java/org/flowable/dmn/spring/configurator/test/DecisionTaskWithSpringBeanTest.java
Use assertj in `flowable-dmn-spring-configurator` module.
> Use assertj fluent styte in flowable-dmn-spring-configurator module.

- modules/flowable-ui/flowable-ui-modeler-conf/src/main/java/org/flowable/ui/modeler/conf/ModelerBootstrapper.java
- modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/FlowableDecisionServiceService.java
- modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/FlowableDecisionTableService.java
There is no need to assign the result to `decisionTableModel` as the method `DecisionTableModelConversionUtil.convertModelToV3` internally resets the parameter to that value.   It is all the more confusing as the method does set the variable and does return the variable.
The only other use of the method (found [here](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/AppDefinitionImportService.java#L314))  does not use the returned variable value.
Found two other similar method calls this time for the `DecisionTableModelConversionUtil.convertModel` method; made the same type of change.
> Value is already assigned

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/data/impl/MybatisSentryPartInstanceDataManagerImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/data/impl/cachematcher/ExecutionByProcessInstanceMatcher.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/data/impl/cachematcher/ExecutionsByParentExecutionIdEntityMatcher.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/data/impl/cachematcher/ExecutionsByProcessInstanceIdEntityMatcher.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/data/impl/cachematcher/ExecutionsByRootProcessInstanceMatcher.java
- modules/flowable-eventsubscription-service/src/main/java/org/flowable/eventsubscription/service/impl/persistence/entity/data/impl/cachematcher/EventSubscriptionsByExecutionIdMatcher.java
- modules/flowable-eventsubscription-service/src/main/java/org/flowable/eventsubscription/service/impl/persistence/entity/data/impl/cachematcher/EventSubscriptionsBySubScopeIdMatcher.java
- modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/impl/persistence/entity/data/impl/cachematcher/HistoricIdentityLinksByProcInstMatcher.java
- modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/impl/persistence/entity/data/impl/cachematcher/IdentityLinksByProcessInstanceMatcher.java
- modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/impl/persistence/entity/data/impl/cachematcher/IdentityLinksByTaskIdMatcher.java
- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/data/impl/cachematcher/ExternalWorkerJobsByExecutionIdMatcher.java
- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/data/impl/cachematcher/JobsByExecutionIdMatcher.java
- modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/persistence/entity/data/impl/cachematcher/HistoricVariableInstanceByProcInstMatcher.java
- modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/persistence/entity/data/impl/cachematcher/HistoricVariableInstanceByTaskIdMatcher.java
- modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/persistence/entity/data/impl/cachematcher/VariableInstanceByExecutionIdMatcher.java
- modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/persistence/entity/data/impl/cachematcher/VariableInstanceByTaskIdMatcher.java
Remove the redundant cast to `String` in `equals()` method called on a string value.  The `equals` method ensures the value is of a `String` type.
> Remove redundant cast to String in equals() method call

- modules/flowable-app-engine/src/main/java/org/flowable/app/engine/test/FlowableAppRule.java
- modules/flowable-content-engine/src/main/java/org/flowable/content/engine/test/FlowableContentRule.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/test/FlowableDmnRule.java
- modules/flowable-event-registry/src/main/java/org/flowable/eventregistry/test/FlowableEventRule.java
- modules/flowable-form-engine/src/main/java/org/flowable/form/engine/test/FlowableFormRule.java
- modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/test/FlowableIdmRule.java
Remove and/or fix Javadoc comments about `setCurrentTime(Date)` method in `Rule` classes.   The comments are removed when the method does not exist in the class.
> Remove/fix javadoc comments about setCurrentTime(Date) method

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
- modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/replay/ReplayRunTest.java
- modules/flowable-engine-configurator/src/main/java/org/flowable/engine/configurator/ProcessEngineConfigurator.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/VariableEventsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/ProcessInstanceQueryTest.java
- modules/flowable-image-generator/src/main/java/org/flowable/image/impl/DefaultProcessDiagramGenerator.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/ProcessInstanceDiagramResource.java
Remove explicit types to parametrized methods that can be unambiguously inferred by the compiler.  Should make the code more readable.
A side effect is the reordering of imports in one module to match project standards.
> Remove explicit arg types to parametrized methods

- modules/flowable-dmn-json-converter/src/main/java/org/flowable/dmn/editor/converter/DmnJsonConverter.java
- modules/flowable-ui/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/app/AbstractModelBpmnResource.java
Using parametrized log messages are more efficient that using concatenation. 
A side effect of this change is the proper ordering of imports in one of the files.
> Use parametrized log messages instead of concatenation

- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/cfg/multitenant/TenantAwareDataSource.java
- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/multitenant/ExecutorPerTenantAsyncExecutor.java
We observed two issues in regards to non-thread-safe maps in the multi schema tenant isolation. This came into picture when tenants were added or removed dynamically at runtime. As the maps in ```TenantAwareDataSource``` and ```ExecutorPerTenantAsyncExecutor``` are both not synchronized, we observed phantoms reads. Hence, the maps have been converted into ```ConcurrentHashMap``` which offer the required synchronization.
> Fix concurrency issue in multi schema tenant isolation

- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/multitenant/SharedExecutorServiceAsyncExecutor.java
In this Pull Request, the following logic has been added to the start of the `SharedExecutorServiceAsyncExecutor`:
- Set the `isActive` property to `true`
- Initialize the `JobEntityManager`
- Initialize the async job execution thread pool
As a result, the [issue](https://forum.flowable.org/t/problems-starting-shared-async-executor/6057) has been fixed that asynchronous jobs were not processed even though the executor had been started.
* Unit tests: No
> Fix Start of the SharedExecutorServiceAsyncExecutor

- modules/flowable-event-registry-rest/pom.xml
The net.javacrumbs.json-unit:json-unit-assertj:jar was defined in the pom.xml twice; removing the extra copy.
> Remove duplicate dependency

- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/DefaultAsyncJobExecutor.java
> Execute shutdown() to stop taskExecutor instead of start() in DefaultAsyncJobExecutor

- modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/mapping/entity/CaseInstance.xml
- modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/mapping/entity/HistoricCaseInstance.xml
- modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/mapping/entity/PlanItemInstance.xml
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/HistoricCaseInstanceQueryImplTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CaseInstanceQueryImplTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/PlanItemInstanceQueryTest.java
- modules/flowable-engine/src/main/resources/org/flowable/db/mapping/entity/Execution.xml
- modules/flowable-engine/src/main/resources/org/flowable/db/mapping/entity/HistoricProcessInstance.xml
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoricProcessInstanceQueryTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoricTaskAndVariablesQueryTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/ExecutionQueryTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/ProcessInstanceQueryTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskQueryTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/history/HistoricVariableInstanceTest.java
- modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/HistoricTaskInstance.xml
- modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/Task.xml
- modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/QueryVariableValue.java
- modules/flowable-variable-service/src/main/resources/org/flowable/variable/service/db/mapping/entity/HistoricVariableInstance.xml
Do not merge yet.
This is an idea showing a possible way to implement notEquals for different types and null values in the DB.
This is done only for the `CaseInstanceQuery`. If the idea is accepted we should apply this logic to other queries as well
> When querying for variable not equals different types and null should be properly handled

- modules/flowable-dmn-rest/src/main/java/org/flowable/dmn/rest/service/api/repository/DecisionTableCollectionResource.java
- modules/flowable-dmn-rest/src/main/java/org/flowable/dmn/rest/service/api/repository/DecisionTableModelResource.java
- modules/flowable-dmn-rest/src/main/java/org/flowable/dmn/rest/service/api/repository/DecisionTableResource.java
- modules/flowable-dmn-rest/src/main/java/org/flowable/dmn/rest/service/api/repository/DecisionTableResourceDataResource.java
Add missing `@Deprecated`
Fix `@deprecated use {@link } instead.` javadoc as the link was pointing at the same file that it was located in.
> Fix deprecated methods

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/context/BpmnOverrideContext.java
- modules/flowable-ui/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/AbstractClientResource.java
- modules/flowable-ui/flowable-ui-task-logic/src/main/java/org/flowable/ui/task/service/runtime/FlowableAppDefinitionService.java
- modules/flowable-ui/flowable-ui-task-logic/src/main/java/org/flowable/ui/task/service/runtime/FlowableCaseInstanceService.java
Instead of using a `new` to allocate a collection then using `addAll()` or equivalent to add values, use a single parametrized constructor that also may be more performant.
A side effect is the reordering of some imports to match project standards.
> Use single parametrized constructor call

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/impl/CmmnTestRunner.java
- modules/flowable-engine/src/test/java/org/flowable/standalone/history/FullHistoryTest.java
Remove useless check:
- `errors == null` can never be true because it is allocated above as `new ArrayList<>()`
- if `i != 3` the only other value of `i` is 3
Also minor correction of long literal should use uppercase `L`
> Remove useless comparison

- docs/docusaurus/docs/cmmn/ch08-REST.md
Fix for issue raised in this forum [post](https://forum.flowable.org/t/includecasevariables-in-docs-should-be-includecasevariables/6829): `includeCaseVariables` instead of `includecaseVariables`  (upper case the `C`).
> Docs: includeCaseVariables instead of includecaseVariables

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/DefaultCmmnHistoryManager.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/async/AbstractAsyncCmmnHistoryManager.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/agenda/EvaluateConditionalEventsOperation.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/BoundaryConditionalEventActivityBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/EventSubProcessConditionalStartEventActivityBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/IntermediateCatchConditionalEventActivityBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/MailActivityBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/BpmnLoggingSessionUtil.java
The null-check is redundant as `instanceof` operator implies non-nullity.
> Remove null check before instanceOf

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/ProcessInstanceQueryTest.java
`expectedIds` is left over from my refactoring to `assertj` in May.
> Remove unused/dead code

- .github/workflows/java-ea.yml
- .github/workflows/main.yml
Every time a pom changes the cache is invalidated. Failed builds do not affect the cache. This should avoid the cache corruption problems on travis ci.
> Cache maven repository to speed-up github actions builds.

- modules/flowable-app-engine-spring/src/test/java/org/flowable/app/spring/test/autodeployment/SpringAutoDeployTest.java
- modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/cfg/ForceCloseMybatisConnectionPoolTest.java
- modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/persistence/EntitiesTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/cfg/ForceCloseMybatisConnectionPoolTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/persistence/EntitiesTest.java
- modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/autodeployment/SpringAutoDeployTest.java
- modules/flowable-content-engine/src/test/java/org/flowable/content/engine/test/ForceCloseMybatisConnectionPoolTest.java
- modules/flowable-content-engine/src/test/java/org/flowable/content/engine/test/persistence/EntitiesTest.java
- modules/flowable-cxf/src/test/java/org/flowable/engine/impl/webservice/WSDLImporterTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/impl/el/util/CollectionUtilTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/cfg/ForceCloseMybatisConnectionPoolTest.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/persistence/EntitiesTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/cfg/ForceCloseMybatisConnectionPoolTest.java
- modules/flowable-event-registry/src/test/java/org/flowable/eventregistry/test/db/EntitiesTest.java
- modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/ForceCloseMybatisConnectionPoolTest.java
- modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/persistence/EntitiesTest.java
- modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/src/test/java/org/flowable/test/spring/boot/SecurityAutoConfigurationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/spring/boot/environment/FlowableDefaultPropertiesEnvironmentPostProcessorTest.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/spring/boot/ldap/FlowableLdapPropertiesTest.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/app/AppEngineAutoConfigurationTest.java
- modules/flowable-spring-security/src/test/java/org/flowable/spring/security/SpringSecurityAuthenticationContextTest.java
Convert JUnit4 tests to JUnit5.  If this type of PR is acceptable there are a little more than 100 other files that can be converted easily.
In the process of converting moved a `package` statement that was before the license header to its proper place after the header.
> Convert JUnit4 tests to JUnit5

- modules/flowable-app-engine-rest/src/main/java/org/flowable/app/rest/service/api/repository/AppDefinitionCollectionResource.java
- modules/flowable-app-engine-rest/src/main/java/org/flowable/app/rest/service/api/repository/AppDeploymentCollectionResource.java
- modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/repository/DeploymentCollectionResource.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/el/ELExecutionContextBuilder.java
- modules/flowable-dmn-rest/src/main/java/org/flowable/dmn/rest/service/api/repository/DmnDeploymentCollectionResource.java
- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/calendar/DefaultBusinessCalendar.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/diagram/ProcessDiagramLayoutFactory.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/EventInstanceBpmnUtil.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskQueryTest.java
- modules/flowable-engine/src/test/java/org/flowable/standalone/cfg/CustomMybatisMapperTest.java
- modules/flowable-event-registry-rest/src/main/java/org/flowable/eventregistry/rest/service/api/repository/DeploymentCollectionResource.java
- modules/flowable-form-rest/src/main/java/org/flowable/form/rest/service/api/repository/FormDefinitionCollectionResource.java
- modules/flowable-form-rest/src/main/java/org/flowable/form/rest/service/api/repository/FormDeploymentCollectionResource.java
- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/util/JsonConverterUtil.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/repository/DeploymentCollectionResource.java
When most (if not all) of a variable is using primitive operations there is no need to wrap them in an Object type.
> Use primitive type instead of wrapper object

- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/async/AsyncCmmnHistoryTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryServiceTaskLogTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/RecordRuntimeActivitiesTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/callactivity/CallActivityAdvancedTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/signal/SignalEventTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/cfg/executioncount/VerifyDatabaseOperationsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/db/ProcessInstanceSuspensionTest.java
- modules/flowable-engine/src/test/java/org/flowable/standalone/history/async/AsyncHistoryTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/api/form/FormServiceTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/bpmn/callactivity/CallActivityAdvancedTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/bpmn/event/signal/SignalEventTest.java
- modules/flowable5-test/src/test/java/org/activiti/engine/test/bpmn/gateway/InclusiveGatewayTest.java
- modules/flowable5-test/src/test/java/org/activiti/standalone/history/FullHistoryTest.java
Instead of doing pieces here and there I grepped the source and changed all lower case `l` literal to uppercase `L` literal as needed.
In some cases it isn't even needed and as side benefit I improved one of the `assertThat()` tests.
As an added bonus I removed a single occurrence of a duplicated semi-colon.
> Use uppercase l for long literal values

- distro/src/notice.txt
- docs/userguide/src/en/bpmn/ch07b-BPMN-Constructs.adoc
- docs/userguide/src/en/cmmn/ch06-cmmn.adoc
- docs/userguide/src/zh_CN/bpmn/ch07b-BPMN-Constructs.adoc
- docs/userguide/src/zh_CN/cmmn/ch06-cmmn.adoc
- pom.xml
According to https://mail-archives.apache.org/mod_mbox/groovy-dev/201906.mbox/%3C1561798530556-0.post%40n5.nabble.com%3E it won't be long until the GA release, so let's see if it is a seamless update for flowable.
Currently using `3.0.0-rc-3`.
> Update Groovy to version 3.0

- distro/src/notice.txt
- pom.xml
This version of Groovy supports Java 16.
> Update Groovy to version 3.0.6.

- modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/GraphicInfo.java
- modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/GraphicInfo.java
- modules/flowable-dmn-model/src/main/java/org/flowable/dmn/model/GraphicInfo.java
…er对象是在IntegerCache.cache产生，会复用已有对象，这个区间内的Integer值可以直接使用==进行判断，但是这个区间之外的所有数据，都会在堆上产生，并不会复用已有对象，这是一个大坑，推荐使用equals方法进行判断。
Integer a = 235;
Integer b = 235;
if (a.equals(b)) {
// code
}
> 所有的包装类对象之间值的比较，全部使用equals方法比较。 

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
Currently ProcessEngineConfiguration always creates EventRegistryEngineConfigurator as the default event registry, even when using the SpringProcessEngineConfiguration, which overrides the createDefaultEventRegistryEngineConfigurator() method.
> Use the EventRegistryEngineConfigurator produced by a method in ProcessEngineConfiguration

- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/hitpolicy/HitPolicyPriority.java
In the line of code:
```
if (outputValues != null || !outputValues.isEmpty())
```
the `||` should be `&&` because of `outputValues` is `null` then the next clause will generate a NPE.
> The 'or' should be 'and'

- modules/flowable-ui/flowable-ui-modeler-frontend/src/main/resources/static/modeler/editor-app/configuration/properties.js
Due to a wrong configuration boolean properties couldn't be modified in modeler because the checkbox component couldn't be rendered
> Fixing a modeler problem: property checkboxes are invisible

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/TerminateCaseInstanceOperation.java
The code reads:
```
CompletionEvaluationResult completionEvaluationResult = PlanItemInstanceContainerUtil
.shouldPlanItemContainerComplete(commandContext, caseInstance, true);
```
where the last parameter to the method is whether the container is autocomplete or not.
Note that the previous line of code reads:
```
boolean isAutoComplete = getPlanModel(caseInstance).isAutoComplete();
```
but the variable `isAutoComplete` is never used and thus a dead store.  I assumed that instead of always passing `true` the variable should be used in its place.
I didn't find a test that exercised the code directly.
> Use isAutoComplete variable

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityImpl.java
See [comment in commit](https://github.com/flowable/flowable-engine/commit/e43101f1aaa2b463d6a71a21419c8ada69b70663#r44002698) which reads in part:
This is going to throw a NPE as processDefinition is null (line 1391); I believe instead of processDefinition.getId() it should just be processDefinitionId
> Use processDefinitionId to avoid NPE

- modules/flowable-cxf/src/test/java/org/flowable/engine/impl/webservice/WSDLImporterTest.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/hitpolicy/HitPolicyOutputOrder.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/hitpolicy/HitPolicyPriority.java
- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/AbstractEngineConfiguration.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/ProcessInstanceHistoryLogImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/helper/ScopeUtil.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/data/impl/MybatisActivityInstanceDataManager.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceMigrationTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/message/MessageIntermediateEventTest.java
- modules/flowable-ui/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/app/FormsResource.java
JDK 8 introduced the faster `List.sort()` method.  In more recent versions of the JDK, `Collections.sort()` now just calls `List.sort()` so changing the method reduces on indirect method call in the chain.
> Replace Collections.sort() with List.sort()

- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricProcessInstanceBaseResource.java
This is a redundant operation since any boxed value will first be auto-unboxed before boxing the value again.
The method `queryRequest.getProcessDefinitionVersion()` returns an `Integer`.
> Remove boxing of already boxed value

- pom.xml
This ensures that the same versions of the groovy-jsr223 and the groovy artifact are used by flowable-spring-boot components.
Spring Boot 2.3 dependency management manages the groovy artifact to 2.5. Therefore Flowable `6.6.0` Spring Boot components use version `3.0.6` of the `groovy-jsr223` artifact and version `2.5.13` of the `groovy` artifact .
> Add the groovy artifact to dependency management.

- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/history/HistoryLevel.java
When investigating a forum post on history level it appears that in Spring Boot both `flowable.history-level=NONE` and `flowable.history-level=none` have the same effect.
In a Flowable cfg.xml file the same isn't true; `<property name="history" value="none" />` is OK but `<property name="history" value="NONE" />` generates a `FlowableIllegalArgumentException: Illegal value for history-level: NONE` message.
This PR just changes the equals to ignore the case so both function the same.
> Use equalsIgnoreCase()

- distro/src/notice.txt
- modules/flowable-ui/flowable-ui-admin-logic/pom.xml
- modules/flowable-ui/flowable-ui-admin-rest/pom.xml
- modules/flowable-ui/flowable-ui-common/pom.xml
- modules/flowable-ui/flowable-ui-idm-conf/pom.xml
- modules/flowable-ui/flowable-ui-idm-logic/pom.xml
- modules/flowable-ui/flowable-ui-idm-rest/pom.xml
- modules/flowable-ui/flowable-ui-modeler-logic/pom.xml
- modules/flowable-ui/flowable-ui-modeler-rest/pom.xml
- modules/flowable-ui/flowable-ui-task-conf/pom.xml
- modules/flowable-ui/flowable-ui-task-logic/pom.xml
- modules/flowable-ui/flowable-ui-task-rest/pom.xml
- pom.xml
The `json.org` classed were removed from flowable in f301804b5de89bd9fc434440b737f6b7a6b7dae9 and de6f97c1d648605e695ded4d70871856729723f9
I could not find any usage of `json.org`.
`jackson-datatype-json-org` uses the `org.json:json` artifact whose license it not compatible with the Apache license (see: https://www.apache.org/legal/resolved.html#category-x).
> Remove no longer necessary jackson-datatype-json-org dependency.

- modules/flowable-app-engine-spring/src/test/java/org/flowable/app/spring/test/autodeployment/SpringAutoDeployTest.java
- modules/flowable-app-engine/src/main/java/org/flowable/app/engine/AppEngine.java
- modules/flowable-app-engine/src/main/java/org/flowable/app/engine/AppEngines.java
- modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/autodeployment/SpringAutoDeployTest.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/DmnEngineConfiguration.java
- modules/flowable-dmn-spring/src/test/java/org/flowable/spring/test/autodeployment/SpringAutoDeployTest.java
- modules/flowable-event-registry-rest/src/main/java/org/flowable/eventregistry/rest/service/api/management/EventRegistryEngineResource.java
- modules/flowable-form-engine/src/main/java/org/flowable/form/engine/test/FlowableFormRule.java
- modules/flowable-ui/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/AppDeploymentsClientResource.java
- modules/flowable-ui/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/CmmnDeploymentsClientResource.java
- modules/flowable-ui/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/DecisionTableDeploymentsClientResource.java
Inspired by the recent [PR ](https://github.com/flowable/flowable-engine/pull/2726) by @vzickner, fix occurrences where the wrong (engine) name was used in exceptions, logging, comments, etc.
> Fix wrong engine name

- distro/src/notice.txt
- pom.xml
Spring Framework 5.2.12 notes: https://github.com/spring-projects/spring-framework/releases/tag/v5.2.12.RELEASE
Spring Security 5.3.6 notes: https://github.com/spring-projects/spring-security/releases/tag/5.3.6.RELEASE
Spring Boot 2.37 notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.3.7.RELEASE
Spring Boot has the most dependency updates and those that Flowable uses have been updated to match.
This PR supersedes the individual update PRs: PR #2738 and PR #2732
> Update Spring Framework, Security, Boot and friends

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/async/json/transformer/TaskEndedHistoryJsonTransformer.java
The variable, `historicTaskInstance` is null that is being sent to `setEndProperties`.  Use the newly created `historicTaskInstanceEntity` instead.
> Use newly created variable in place of null value

- distro/src/notice.txt
- pom.xml
Release notes at: https://github.com/spring-projects/spring-boot/releases/tag/v2.3.8.RELEASE
Updated associated dependencies as listed in the release notes.
> Update to SpringBoot 2.3.8 (and dependencies)

- modules/flowable-http/src/test/java/org/flowable/http/bpmn/cfg/HttpServiceTaskCfgSpringWebClientTest.java
Remove unused import that is new as a result of today's merge to master.
> Chore: remove unused import from recent push

- modules/flowable-content-rest/src/test/java/org/flowable/content/rest/service/api/BaseSpringContentRestTestCase.java
- modules/flowable-dmn-rest/src/test/java/org/flowable/dmn/rest/service/api/BaseSpringDmnRestTestCase.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/SerializableVariablesDiabledTest.java
Remove duplicated `catch` clauses;  `ClientProtocolException` extends `IOException` so the additional `catch` is redundant.
> Chore: remove duplicated catch clauses

- modules/flowable-crystalball/src/main/java/org/flowable/crystalball/simulator/SimulationEventComparator.java
Use the static `Integer.compare()` method  where more verbose or less efficient constructs was used.
> Chore: use Integer.compare() instead of multiple ifs

- distro/src/notice.txt
- pom.xml
All dependency changes noted in the Release Notes are already met.  See https://github.com/spring-projects/spring-security/releases/tag/5.4.4
> Upgrade Spring Security to 5.4.4

- distro/src/notice.txt
- pom.xml
Upgrade Spring Framework to 5.3.4.   All dependency changes have already been made.  See release notes [here](https://github.com/spring-projects/spring-framework/releases/tag/v5.3.4).
> Upgrade Spring 5.3.4

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/ProcessInstanceMigrationValidationCmd.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceMigrationTest.java
I was getting a NullPointerExecption on migrations when upgrading to 6.6.0.
I found that the ProcessInstanceMigrationDocument was not getting initialized - simple fix!
> Initialize ProcessInstanceMigrationDocument correctly

- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/event/TaskAssignedEventTest.java
- modules/flowable-content-rest/src/test/java/org/flowable/content/rest/service/api/BaseSpringContentRestTestCase.java
- modules/flowable-dmn-rest/src/test/java/org/flowable/dmn/rest/service/api/BaseSpringDmnRestTestCase.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/SerializableVariablesDiabledTest.java
This is embarrassing as I'm the reason for the unused imports because of push removing duplicated catch clauses.
> Chore: remove unused imports

- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/JobInfoEntityManagerImpl.java
As the code currently is written a call to `getJobServiceConfiguration()` results in infinite recursion.  I think the intent was to call `getServiceConfiguration` which is part of `AbstractServiceEngineEntityManager`.
FWIW, `JobInfoEntityManagerImpl` extends `AbstractJobServiceEngineEntityManager` which extends `AbstractServiceEngineEntityManager`.
> Fix infinite recursion

- distro/src/notice.txt
- modules/flowable-app-engine-rest/pom.xml
- modules/flowable-cmmn-rest/pom.xml
- modules/flowable-content-rest/pom.xml
- modules/flowable-dmn-rest/pom.xml
- modules/flowable-event-registry-rest/pom.xml
- modules/flowable-form-rest/pom.xml
- modules/flowable-http/pom.xml
- modules/flowable-rest/pom.xml
- pom.xml
See Spring Boot release notes at: https://github.com/spring-projects/spring-boot/releases/tag/v2.4.4
See Spring Framework release notes at: https://github.com/spring-projects/spring-framework/releases/tag/v5.3.5
Updated dependencies and added `jetty.version` property to simplify future changes.
> Upgrade to Spring Boot 2.4.4 and Spring Framework 5.3.5

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/parser/handler/ReactivateEventListenerParseHandler.java
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/reactivation/Simple_Reactivation_Test_Case.cmmn.xml
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/reactivation/Simple_Reactivation_Test_Case_Multi_Reactivation_Elements.cmmn.xml
Add ignore for completion rule and availability condition to the reactivation listener at runtime through its parser to avoid Design to add those rules when exporting.
> add special behaviour for the reactivation listener through parser

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/PlanItemEvaluationResult.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/AbstractDeleteCaseInstanceOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/AbstractEvaluationCriteriaOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/CompleteCaseInstanceOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/util/PlanItemInstanceContainerUtil.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/AbstractFlowableCmmnTestCase.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/TerminateChildPlanItemsOnAutoCompletionTest.java
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/Case_And_Stage_Completion_With_Child_Items_Test.cmmn.xml
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/Case_Completion_With_Child_Items_Test.cmmn.xml
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/Stage_Completion_With_Child_Items_Test.cmmn.xml
Making sure that not yet ended child plan items are terminated rather than completed on case and stage completion.
> Terminate child plan items on parent completion

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/CmmnEngineAgenda.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/DefaultCmmnEngineAgenda.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/ReactivateCaseInstanceOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/ReactivatePlanItemInstanceOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/CmmnHistoryManager.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/CompositeCmmnHistoryManager.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/DefaultCmmnHistoryManager.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/async/AsyncCmmnHistoryManager.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/StateTransition.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/reactivation/SimpleCaseReactivationTest.java
Instead of reusing existing plan items for reactivation, new ones are created with the same data and activated using a new reactivation operation similar to the create one.
> recreate new plan items for reactivation, not reusing existing ones

- distro/src/notice.txt
- pom.xml
Upgrade to Spring Framework 5.3.6
Release notes are [here](https://github.com/spring-projects/spring-framework/releases/tag/v5.3.6).
Upgraded reactor-netty version to 1.0.6 as that is the version that is part of the dependency upgrade to Reactor 2020.0.6.
> Upgrade to Spring Framework 5.3.6

- distro/src/notice.txt
- pom.xml
Upgrade to Spring Security 5.4.6
Release notes are [here](https://github.com/spring-projects/spring-security/releases/tag/5.4.6).
No dependency changes are needed.
> Upgrade to Spring Security 5.4.6

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/CmmnEngineAgenda.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/DefaultCmmnEngineAgenda.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/AbstractEvaluationCriteriaOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/CmmnOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/CreateRepeatedPlanItemInstanceOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/AbstractFlowableCmmnTestCase.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/PlanItemRepetitionWithCollectionVariableAndConditionTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/PlanItemRepetitionWithCollectionVariableTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/reactivation/SimpleCaseReactivationTest.java
fixing and testing bug where plan items won't be created in history on a collection repetition operation
> fixing bug on historic plan item instances not being created on collection based repetition

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
- modules/flowable-engine/src/test/java/org/flowable/examples/variables/VariablesTest.java
In recent pushes:
- one duplicate import (in cmmn-engine merge)
- two unused imports (in flowable-engine test file)
> Chore: remove duplicate and unused imports

- modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/util/BpmnXmlConverterTestExtension.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/CmmnHistoryHelper.java
- modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/caze/CaseInstanceResource.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/DmnEngineConfiguration.java
- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/db/LiquibaseBasedSchemaManager.java
- modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/impl/ExecutionListenerValidator.java
- modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/impl/OperationValidator.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/cmmn/CmmnEngineAutoConfigurationTest.java
This supersedes this [PR](https://github.com/flowable/flowable-engine/pull/2928).
> Remove unused imports from pushes on April 27, May 14, and June 8, 2021.

- distro/src/notice.txt
- pom.xml
Release notes:  https://github.com/spring-projects/spring-framework/releases/tag/v5.3.7
No dependency updates that are part of Flowable.
> Upgrade to Spring Framework 5.3.7

- distro/src/notice.txt
- pom.xml
I ran `mvn clean test` on the `distro` profile without any errors after making the changes in the Spring Framework 5.3.7 update [PR](https://github.com/flowable/flowable-engine/pull/2925).   [That is because the Security update is dependent on the Framework update.] I kept the two updates separate incase there is a reason unknown to me not to apply this update at this time.  
The Release notes are here:  https://github.com/spring-projects/spring-security/releases/tag/5.5.0
> Upgrade to Spring Security 5.5.0

- modules/flowable-app-rest/src/test/java/org/flowable/rest/app/FlowableRestApplicationSecurityTest.java
- modules/flowable-cxf/pom.xml
- modules/flowable-event-registry-spring/pom.xml
- modules/flowable-jms-spring-executor/pom.xml
- modules/flowable-rest/pom.xml
- modules/flowable-ui/flowable-ui-app/src/test/java/org/flowable/ui/application/FlowableUiApplicationSecurityTest.java
- pom.xml
The Spring Boot Release Notes are [here]( https://github.com/spring-projects/spring-boot/releases/tag/v2.5.0).   
I made the dependency updates that I found in the release notes and ran locally "mvn clean test" with no errors (distro profile).
FWIW, none of the jars that were changed are listed in distro/src/notice.txt. 
I **did **not** do** the following upgrades as they caused compile errors in flowable.http.common (and maybe else where):
- Upgrade to HttpClient5 5.0.4
- Upgrade to HttpCore5 5.1.1
There is a big jump from the version 4 jars currently used in the project and version 5.
> Upgrade to Spring Boot 2.5.0

- modules/flowable-ui/flowable-ui-admin-frontend/src/main/resources/static/admin/i18n/zh-CN.json
FORM-INSTANCES-EMPTY means "这个流程实例没有表单实例." instead of "这个流程实例没有子流程."
> Rename FORM-INSTANCES-EMPTY value.

- distro/src/notice.txt
- modules/flowable-app-engine-rest/pom.xml
- modules/flowable-cmmn-rest/pom.xml
- modules/flowable-content-rest/pom.xml
- modules/flowable-dmn-rest/pom.xml
- modules/flowable-event-registry-rest/pom.xml
- modules/flowable-form-rest/pom.xml
- modules/flowable-rest/pom.xml
- pom.xml
Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.5.1
Includes the SpringFramework in this [PR](https://github.com/flowable/flowable-engine/pull/2950) which I will now close.
> Upgrade to Spring Boot 2.5.1

- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/constants/BpmnXMLConstants.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/BaseBpmnXMLConverter.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/BoundaryEventXMLConverter.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/child/ErrorEventDefinitionParser.java
- modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/ErrorEventDefinition.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/helper/ErrorPropagation.java
- modules/flowable-json-converter/src/main/java/org/flowable/editor/constants/StencilConstants.java
- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/BaseBpmnJsonConverter.java
- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/BoundaryEventJsonConverter.java
- modules/flowable-json-converter/src/test/resources/test.boundaryerrorvariable.json
- modules/flowable-ui/flowable-ui-modeler-frontend/src/main/resources/static/modeler/i18n/en.json
- modules/flowable-ui/flowable-ui-modeler-logic/src/main/resources/stencilset_bpmn.json
Motive for this feature is to enable generic BPMN error handling without the need to know in workflow design-time which error code will be thrown. 
ErrorEventDefinition gets three new properties:
- String errorVariableName, name of the variable containing error code, default null
- Boolean errorVariableTransient, whether variable should be transient, default true
- Boolean errorVariableLocalScope, whether variable should be stored in local scope, default true
If errorVariableName is not set nothing gets injected, this way backward compatibility is maintained, else, error code is stored into named variable. Scope and transience depends on flags.
Unit testing and documentation is missing since these are just proposed changes.
> injecting error code into execution on boundary / start error event

- modules/flowable-case-validation/src/main/java/org/flowable/cmmn/validation/CaseValidatorFactory.java
- modules/flowable-case-validation/src/test/java/org/flowable/cmmn/validation/validator/impl/HumanTaskValidatorTest.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/PlanFragmentCmmnXmlConverterTest.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/EvaluateVariableEventListenersOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/AbstractFlowableCmmnTestCase.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/agenda/EvaluateVariableListenerEventDefinitionsOperation.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/jobexecutor/BulkMoveTimerJobsToExecutableJobsTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/jobexecutor/BulkUpdateJobLockTest.java
- modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/ValidatorSetFactory.java
- remove unused imports
- correct missorted modifiers
- use parameterized logging instead of concatenation
- remove concatenation of empty string
- remove dup semicolon
> Chore: small code cleanups

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/CmmnEngineAgenda.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/DefaultCmmnEngineAgenda.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/CmmnOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/InitPlanModelInstanceOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/InitStageInstanceOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/ReactivateCaseInstanceOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/ReactivatePlanModelInstanceOperation.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/reactivation/PreventDoublePlanItemInitializationTest.java
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/reactivation/Double_Plan_Item_Reactivation_Test.cmmn.xml
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/reactivation/Double_Stage_Reactivation_Test.cmmn.xml
fixing bug when a stage or waiting state plan item was directly related to a reactivation listener and got initialized twice
> Preventing double reactivation on directly linked plan items

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/CallActivityBehavior.java
* Declare "variables" HashMap inline to avoid it being accidentally used further down
* Use already retrieved eventDispatcher instead of fetching it again from process engine configuration
> Minor cleanup of CallActivityBehavior

- distro/src/notice.txt
- modules/flowable-app-engine-rest/pom.xml
- modules/flowable-cmmn-rest/pom.xml
- modules/flowable-content-rest/pom.xml
- modules/flowable-dmn-rest/pom.xml
- modules/flowable-event-registry-rest/pom.xml
- modules/flowable-form-rest/pom.xml
- modules/flowable-rest/pom.xml
- modules/flowable5-compatibility-testdata/pom.xml
- pom.xml
Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.5.3
Ran `mvn clean test` locally without error.
This replaces the Spring Framework upgrade (https://github.com/flowable/flowable-engine/pull/2982) as this includes that dependency update.
> Upgrade to Spring Boot 2.5.3

- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/AcquireAsyncJobsDueRunnable.java
- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/AcquireTimerJobsRunnable.java
- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/ResetExpiredJobsRunnable.java
Update the logging level for some exception cases from error to warn in the job service.
Cause:
These errors occur in our k8s environment when the primary database server fails over to a secondary. This failover can take up to a few seconds to occur resulting in the database being inaccessible during that time.
Justification:
Often an error message in the logs is an indicator that a system administrator must perform some investigation and work to resolve the issue. However, here that is not the case since the the logic will retry. To reduce the amount of information that a system administrator needs to look through, we would like to update the logging here to warn to reflect that an immediate action isn't required. If the warning continues, then a system administrator should investigate. …
> Update logging levels in job service.

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/helper/EscalationPropagation.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/escalation/BoundaryEscalationEventTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/escalation/BoundaryEscalationEventTest.testCatchEscalationOnCallActivitySuspendedParent.child.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/escalation/BoundaryEscalationEventTest.testCatchEscalationOnCallActivitySuspendedParent.parent.bpmn20.xml
In this contribution, an issue is fixed when boundary escalation events on call activities get triggered even if the process instance they belong to is suspended.
With the fix, escalation propagation results in an error when the corresponding catching execution is suspended.
> Fix for escalation propagation to suspended execution

- distro/src/notice.txt
- modules/flowable-cxf/pom.xml
- modules/flowable-event-registry-spring/pom.xml
- modules/flowable-jms-spring-executor/pom.xml
- pom.xml
Update dependencies and release notes can be found here: https://github.com/spring-projects/spring-boot/releases/tag/v2.5.4
> Move to Spring Boot 2.5.4

- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/constants/BpmnXMLConstants.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/export/DefinitionsRootExport.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/parser/DefinitionsParser.java
- modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/ExporterAndVersionTest.java
- modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/BpmnModel.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/DefinitionsRootExport.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/ExporterAndVersionTest.java
- modules/flowable-dmn-model/src/main/java/org/flowable/dmn/model/DmnDefinition.java
- modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/xml/constants/DmnXMLConstants.java
- modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/xml/converter/DmnXMLConverter.java
- modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/AdditionalConverterTest.java
BPMN, CMMN and DMN all support the 'exporter' and 'exporterVersion' attribute. This would allow modeler / designer implementations to fill these with appropriate values
> Add support for exporter and exporterVersion attributes for BPMN, CMMN and DMN

- modules/flowable-engine/src/main/resources/org/flowable/db/create/flowable.mysql.create.engine.sql
Table ACT_EVT_LOG fail to create when mysql sql_mode is STRICT_TRANS_TABLES. And cause the next sql not executed.
> fail to create table ACT_EVT_LOG on mysql

- scripts/start-admin.sh
- scripts/start-idm.sh
- scripts/start-modeler.sh
- scripts/start-ui.sh
These scripts are now obsolete after the UI refactoring in the last release.
> Chore: remove scripts made obsolete by UI refactoring

- distro/src/notice.txt
- pom.xml
Spring Boot 2.5.5 and Spring Framework 5.3.10 and various other dependency updates.
Release Notes:  https://github.com/spring-projects/spring-boot/releases/tag/v2.5.5
Successful run of `mvn clean test` locally
> Upgrade to SpringBoot 2.5.5 and SpringFramework 5.3.10

- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/AbstractEngineConfiguration.java
- modules/flowable-ui/flowable-ui-modeler-conf/src/main/java/org/flowable/ui/modeler/conf/ModelerDatabaseConfiguration.java
Added DB2/LINUXPPC64LE to the database type list to fix the "Couldn't deduct database type from database product name" error found during testing on PPC. Interestingly, the type is present in `modules/flowable5-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java` but absent in 2 other locations. I'm assuming it's just an oversight.
Fixes https://github.com/flowable/flowable-engine/issues/3031
> Added DB2/LINUXPPC64LE detection

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/DecisionTaskActivityBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/AddCommentCmd.java
The method returns false for null so there is no need to check for it.
Part of the periodic check of the code base.
> Remove unnecessary null check before method call

- docs/docusaurus/docs/dmn/ch02-Configuration.md
This replaces this [PR](https://github.com/flowable/flowable-engine/pull/3079) which has no activity in over 3 weeks.
> Doc: Typo change from "DMNEngines" to "DmnEngines"

- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskCollectionResource.java
Per [issue 3104](https://github.com/flowable/flowable-engine/issues/3104) change the API description of `dueOn` to `dueDate` to match the code and the use in the [unit test](https://github.com/flowable/flowable-engine/blob/822c3e87a5dc03bc52652e7f5bef8b322bba917d/modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/TaskCollectionResourceTest.java#L328).
Looking at the unit test it appears not to expect any milliseconds in the date in answer to the the second part of the original issue.
Fixes #3104
> Issue 3104: fix parameter name in API description

- distro/src/notice.txt
The upgrade to 2.5.7 also updated Spring Framework; this updates the `notice.txt` file
> Upgrade to SpringBoot 2.5.7; forgot to update the notice.txt

- modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/xml/converter/DMNDIExport.java
- modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/DiagramDiTest.java
As of now IDs of DRD DI in decision services are changing for every export. This isn’t handy in case you would like to commit a DRD model on a VCS since you have unnecessary changes. This PR keeps existing IDs in case they are already available and re-uses them. Exporting a DRD twice will result in exactly the same DRD as before.
> change DMNDI ids to static IDs instead of UUIDs

- distro/src/notice.txt
- pom.xml
Quoting from the announcement:  Spring Framework 5.3.15 includes 17 fixes and improvements as a recommended upgrade for all Spring production scenarios.
Release notes:  https://github.com/spring-projects/spring-framework/releases/tag/v5.3.15
FWIW, there is a fix to help use the newer  h2 2.0.x jar.
> Upgrade to SpringFramework 5.3.15

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/HumanTaskActivityBehavior.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/deployer/CmmnDeployer.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/authorization/StartAuthorizationTest.java
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/authorization/StartAuthorizationTest.testExpressionsInCandidateStarters.cmmn
- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/assignment/CandidateUtil.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/deployer/BpmnDeploymentHelper.java
- modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/authorization/StartAuthorizationTest.java
- modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/authorization/StartAuthorizationTest.testExpressionsInCandidateStarters.bpmn20.xml
Allowing expressions to be resolved in the candidateStarterUser and candidateStarterGroup fields in CMMN and BPMN + Unit tests + moving extractCandidates function to Util class in flowable-engine-common
> Allowing expressions to be resolved in the candidateStarters

- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/multitenant/TenantAwareResetExpiredJobsRunnable.java
In this increment, [the issue](https://forum.flowable.org/t/tenant-aware-reset-expired-jobs-runnable-neglects-timer-jobs/8930) is fixed when timer jobs don't get unlocked after the corresponding lock expiration.
> Fix: add timer job entity manager to TenantAwareResetExpiredJobsRunnable

- pom.xml
This version is also used by Spring Boot 2.6.x.
Version 5 can not be used, because it requires Java 11.
> Update HikariCP to version 4.0.3.

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/CaseInstanceMigrationCmd.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/CaseInstanceMigrationValidationCmd.java
I tried to apply a case migration to all instances based on a specific case definition. Found out it wasn't working if I use the approach with just the case definition id – it's checking if the case definition is null, but then it's just setting it to null.
> Add missing caseDefinitionId for case migration

- distro/src/notice.txt
- modules/flowable-app-engine-rest/pom.xml
- modules/flowable-cmmn-rest/pom.xml
- modules/flowable-content-rest/pom.xml
- modules/flowable-dmn-rest/pom.xml
- modules/flowable-event-registry-rest/pom.xml
- modules/flowable-event-registry-spring/pom.xml
- modules/flowable-form-rest/pom.xml
- modules/flowable-http/pom.xml
- modules/flowable-jms-spring-executor/pom.xml
- modules/flowable-osgi/src/test/java/org/flowable/osgi/blueprint/BlueprintBasicTest.java
- modules/flowable-rest/pom.xml
- pom.xml
Release Notes:  
Spring Boot: https://github.com/spring-projects/spring-boot/releases/tag/v2.6.4
Spring Security: https://github.com/spring-projects/spring-security/releases/tag/5.6.2
Spring Framework: : https://github.com/spring-projects/spring-framework/releases/tag/v5.3.16
Supersedes update to Spring Security: https://github.com/flowable/flowable-engine/pull/3222
> Upgrade to Spring Boot 2.6.4

- modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/CmmnRuntimeService.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/AddEventListenerCommand.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/DispatchEventCommand.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/RemoveEventListenerCommand.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CmmnRuntimeServiceImpl.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/event/CmmnRuntimeEventListenerSupportTest.java
Add support to register and remove event listeners directly through the CMMN runtime service as well as dispatching an event.
> add event support to the CMMN runtime, same as in the process runtime

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/CaseTaskActivityBehavior.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/callback/ChildCaseInstanceStateChangeCallback.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CompleteCaseTaskByManualTerminationTest.java
Fixing a bug where the case task plan item was not ended and stayed in active state if its referenced child case was manually terminated.
> fix bug to end a case task plan item

- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CompleteCaseTaskByManualTerminationTest.java
Class had both assertj and old junit assertions; most tests use assertj so converted the `assertEquals()` to `assertThat()`
> Chore: use only one test framework

- modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/event/FlowableCaseStageEndedEvent.java
- modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/event/FlowableCaseStageStartedEvent.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/CmmnOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/CompletePlanItemInstanceOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/ExitPlanItemInstanceOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/InitStageInstanceOperation.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/event/FlowableCaseStageEndedEventImpl.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/event/FlowableCaseStageStartedEventImpl.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/event/FlowableCmmnEventBuilder.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/event/CaseStageEndedEventTest.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/event/CaseStageStartedEventTest.java
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/event/Case_Stage_Event_Test_Case.cmmn
- modules/flowable-engine-common-api/src/main/java/org/flowable/common/engine/api/delegate/event/FlowableEngineEventType.java
The same way we support case starting and ending events, we also want to support such events specific to stages as they represent an important state of a case lifecycle.
> add support for stage starting and ending events

- distro/src/notice.txt
- pom.xml
Upgrade Spring Framework to 5.3.19
Release notes: https://github.com/spring-projects/spring-framework/releases/tag/v5.3.19
Note this also fixes [Spring Framework Data Binding Rules Vulnerability (CVE-2022-22968)](https://spring.io/blog/2022/04/13/spring-framework-data-binding-rules-vulnerability-cve-2022-22968)
> Update to Spring 5.3.19

- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/migration/CaseInstanceMigrationTest.java
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/one-task-expression-name-v2.cmmn.xml
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/one-task-expression-name.cmmn.xml
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/dynamic/AbstractDynamicStateManager.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceMigrationTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/runtime/migration/one-task-rename-v2.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/runtime/migration/one-task-rename-v3.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/runtime/migration/one-task-rename.bpmn20.xml
When migrating a process instance, User Tasks were renamed without evaluating the name through the ExpressionManager. Descriptions were not migrated so far. This PR addresses these points.
> Improve user task name migration and allow migration of user task descriptions

- distro/src/notice.txt
- pom.xml
Spring Framework 5.3.20 includes 14 fixes and improvements
See: https://github.com/spring-projects/spring-framework/releases/tag/v5.3.20
In addition, the release include fixes for 2 vulnerabilities:
CVE-2022-22970
“Spring Framework DoS via Data Binding to MultipartFile or Servlet Part”
Denial of Service (DoS) attack in Spring MVC or Spring WebFlux applications that handle file uploads and rely on data binding to set a MultipartFile or javax.servlet.Part to a field in a model object.
Severity: [Medium]
CVE-2022-22971
“Spring Framework DoS with STOMP over WebSocket”
Denial of service (DoS) attack by authenticated users in Spring applications with a STOMP over WebSocket endpoint.
Severity: [Medium]
> Update to Spring Framework 5.3.20

- distro/src/notice.txt
- modules/flowable-app-engine-rest/pom.xml
- modules/flowable-cmmn-rest/pom.xml
- modules/flowable-content-rest/pom.xml
- modules/flowable-dmn-rest/pom.xml
- modules/flowable-event-registry-rest/pom.xml
- modules/flowable-form-rest/pom.xml
- modules/flowable-http/pom.xml
- modules/flowable-rest/pom.xml
- pom.xml
Update to Spring Boot 2.6.7
Release Notes:  https://github.com/spring-projects/spring-boot/releases/tag/v2.6.7
Includes update to Spring Security
> Update to Spring Boot 2.6.7

- docs/docusaurus/docs/bpmn/ch15-REST.md
- docs/userguide/src/en/bpmn/ch15-REST.adoc
- docs/userguide/src/zh_CN/bpmn/ch15-REST.adoc
The docs currently state that the latest parameter can only be used in combination with the "key(Like)" parameter but I've found it also works with the "resourceName(Like)" parameter.
> Updated "List of process definitions" docs

- distro/src/notice.txt
- pom.xml
Release Notes: https://github.com/spring-projects/spring-security/releases/tag/5.6.4
Fixes 2 CVEs:
- [CVE-2022-22975: Authorization Bypass in RegexRequestMatcher](https://spring.io/blog/2022/05/15/cve-2022-22975-authorization-bypass-in-regexrequestmatcher)
- [CVE-2022-22976: BCrypt skips salt rounds for work factor of 31](https://spring.io/blog/2022/05/15/cve-2022-22976-bcrypt-skips-salt-rounds-for-work-factor-of-31)
> Update to Spring Security 5.6.4

- modules/flowable-common-rest/src/test/java/org/flowable/common/rest/exception/BaseExceptionHandlerAdviceTest.java
Code was just pushed today without the license header
> Chore: Add missing license header block

- modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/test/runtime/DmnTaskTest.java
- modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/bpmn/test/runtime/DmnTaskTest.oneDecisionService-2.dmn
- modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/bpmn/test/runtime/DmnTaskTest.oneDecisionService-3.dmn
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/DmnDecisionServiceImpl.java
Having a DecisionService result with a single outcome decision with no results caused an issue when trying to compose variables to put on the execution context.
This is fixed now by not adding 'empty results' to the Decision Service result.
> fixes AIOBE when having single output decision in decision service with no results

- distro/src/notice.txt
- pom.xml
Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.6.8
Note: I did **not** upgrade to MySQL 8.0.29 from 8.0.19 because there was some reason in previous updates not to move off 8.0.19.
> Update to SpringBoot 2.6.8

- distro/src/notice.txt
- modules/flowable-app-engine-rest/pom.xml
- modules/flowable-cmmn-rest/pom.xml
- modules/flowable-content-rest/pom.xml
- modules/flowable-dmn-rest/pom.xml
- modules/flowable-event-registry-rest/pom.xml
- modules/flowable-form-rest/pom.xml
- modules/flowable-http/pom.xml
- modules/flowable-rest/pom.xml
- pom.xml
Update Spring Boot to 2.6.9,  Security to 5.6.6 and Spring Framework to 5.3.21
Release notes for Spring Boot: https://github.com/spring-projects/spring-boot/releases/tag/v2.6.9
Release notes for Security: https://github.com/spring-projects/spring-security/releases/tag/5.6.6
Release notes for Framework: https://github.com/spring-projects/spring-framework/releases/tag/v5.3.21
This supersedes PR https://github.com/flowable/flowable-engine/pull/3349
BTW, there is a Spring Boot 2.7.1 that is also available; see https://github.com/spring-projects/spring-boot/releases/tag/v2.7.1
What is the plan to move to the 2.7.x branch?
> Chore update Spring Boot, Spring Security and Framework dependencies

- modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/task/HistoricTaskInstanceBaseResource.java
- modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/task/HistoricTaskInstanceCollectionResource.java
- modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/task/HistoricTaskInstanceQueryRequest.java
- modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskBaseResource.java
- modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskCollectionResource.java
- modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskQueryRequest.java
- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricTaskInstanceCollectionResourceTest.java
- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricTaskInstanceQueryResourceTest.java
- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/TaskCollectionResourceTest.java
- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/TaskQueryResourceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskQueryTest.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricTaskInstanceBaseResource.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricTaskInstanceCollectionResource.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricTaskInstanceQueryRequest.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskBaseResource.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskCollectionResource.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskQueryRequest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/TaskCollectionResourceTest.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/TaskQueryResourceTest.java
- modules/flowable-task-service-api/src/main/java/org/flowable/task/api/TaskInfoQuery.java
- modules/flowable-task-service-api/src/main/java/org/flowable/task/api/TaskInfoQueryWrapper.java
- modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/HistoricTaskInstanceQueryImpl.java
- modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/TaskQueryImpl.java
- modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/HistoricTaskInstance.xml
- modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/Task.xml
* Added 'taskCategoryIn' query method
* Added 'taskCategoryNotIn' query method
* Added 'withoutCategory' to query for tasks without category
> Extend TaskQuery capabilities for category

- distro/src/notice.txt
- pom.xml
Release Notes:  https://github.com/spring-projects/spring-framework/releases/tag/v5.3.22
No relevant dependency updates.
> Update to Spring Framework 5.3.22

- modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/ReceiveTask.java
Hello ,Is the (setValues()) method type of the receiveTask wrong, The current input parameter is ManualTask.
ManualTask should not appear in this location, Perhaps this is the negligence of your developers
This will cause us to always call the method of the parent class when we want to call the setValues method
> ReceiveTask  setValues() method type question

- modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/CmmnRuntimeService.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/AbstractCaseInstanceIdentityLinkCmd.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/RemoveCaseInstanceAssigneeCmd.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/RemoveCaseInstanceOwnerCmd.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/SetCaseInstanceAssigneeCmd.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/SetCaseInstanceOwnerCmd.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CmmnRuntimeServiceImpl.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CaseInstanceIdentityLinksTest.java
- modules/flowable-engine/src/main/java/org/flowable/engine/RuntimeService.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/RuntimeServiceImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/AbstractProcessInstanceIdentityLinkCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/RemoveProcessInstanceAssigneeCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/RemoveProcessInstanceOwnerCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/SetProcessInstanceAssigneeCmd.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/SetProcessInstanceOwnerCmd.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/ProcessInstanceIdentityLinksTest.java
Add direct support to set and remove the owner and assignee of a case or process through their runtime services.
> Set owner and assignee on cases and processes through runtime service directly

- modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/runtime/CaseInstanceBuilder.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CaseInstanceBuilderImpl.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CaseInstanceHelperImpl.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/interceptor/StartCaseInstanceBeforeContext.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/StartCaseWithIdentityLinksTest.java
Adding support within the case builder API to set the owner and / or assignee at case start time to be in sync with the runtime service allowing to set / change and remove owner and assignee directly.
> support owner and assignee within case builder API

- distro/src/notice.txt
- pom.xml
Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.7.4
This PR replaces the update to the SpringFramework https://github.com/flowable/flowable-engine/pull/3465
> Chore: Upgrade to SpringBoot 2.7.4 and dependencies

- modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/BaseBpmnJsonConverter.java
Issue:
After bpmn diagram import to modeler UI Boundary Error Event properties are dropped
Cause:
Json converter implemented in that way so that if error code is not set, then all properties are ignored
Details:
Modeler export works fine and exports all properties regardless if error code is set or not. Workflow application works in the same way and regardless if error code is set or not, it uses all set properties. Issue occurs only on diagram import to modeler UI. There are two scenarios how to use boundary error event based on BpmnError code:
1. Add error code for boundary error event and flowable based on that will do navigation. For that solution multiple boundary error events are needed and this makes diagram hard to read. Negative side - all possible error codes need to have …
> Boundary Error Event properties import issue

- modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/mapping/entity/CaseInstance.xml
- modules/flowable-engine/src/main/resources/org/flowable/db/mapping/entity/HistoricProcessInstance.xml
Fixes #3474 
There is a wrong alias in these mapper.xml: [CaseInstance.xml](https://github.com/flowable/flowable-engine/blob/main/modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/mapping/entity/CaseInstance.xml), [HistoricProcessInstance.xml](https://github.com/flowable/flowable-engine/blob/main/modules/flowable-engine/src/main/resources/org/flowable/db/mapping/entity/HistoricProcessInstance.xml). `A_OR${index}` doesn't exist.
> fix sql syntax error

- distro/src/notice.txt
- modules/flowable-app-engine/pom.xml
- modules/flowable-app-rest/pom.xml
- modules/flowable-cmmn-engine/pom.xml
- modules/flowable-content-engine/pom.xml
- modules/flowable-dmn-engine/pom.xml
- modules/flowable-engine/pom.xml
- modules/flowable-event-registry/pom.xml
- modules/flowable-form-engine/pom.xml
- modules/flowable-idm-engine/pom.xml
- modules/flowable-ui/flowable-ui-app/pom.xml
- modules/flowable5-compatibility-test/pom.xml
- modules/flowable5-compatibility-testdata/pom.xml
- modules/flowable5-engine/pom.xml
- modules/flowable5-test/pom.xml
- pom.xml
- qa/dbclean/pom.xml
Upgrade to Spring Boot 2.7.5 and dependencies.
See Release Notes at: https://github.com/spring-projects/spring-boot/releases/tag/v2.7.5
Note the mysql connector jar has moved its location in Maven (see https://mvnrepository.com/artifact/com.mysql/mysql-connector-j/8.0.31) and that is the reason for all the mysql changes.
This PR supersedes https://github.com/flowable/flowable-engine/pull/3497 which will be closed.
> Chore: Upgrade to Spring Boot 2.7.5 and dependencies

- distro/src/notice.txt
- pom.xml
Release Notes: https://github.com/spring-projects/spring-security/releases/tag/5.7.5
This release fixes two CVEs:
- https://tanzu.vmware.com/security/cve-2022-31690
- https://tanzu.vmware.com/security/cve-2022-31692
> Upgrade to Spring Security 5.7.5

- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/AbstractEngineConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/AllEnginesAutoConfigurationTest.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/resources/mappers/CustomMybatisBpmnXmlMapper.xml
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/resources/mappers/CustomMybatisCmmnXmlMapper.xml
Prior to this change a custom my batis mapper was supposed to be added to the lead engine. However, with this we can now easily register custom mappers with any engine and they will be automatically registered with the lead engine.
> Allow registration of custom my batis mappers through any engine configuration

- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/child/ScriptInfoParser.java
- modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/EventListenerConverterTest.java
- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/scripting/AbstractScriptEvaluator.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/http/DefaultBpmnHttpActivityDelegate.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/http/handler/ScriptHttpHandler.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/listener/ScriptTypeExecutionListener.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/listener/ScriptTypeTaskListener.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/parser/factory/DefaultListenerFactory.java
- modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/executionlistener/ExecutionListenerTest.java
- modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/executionlistener/ScriptTypeExecutionListenerTest.java
- modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/tasklistener/ScriptTaskListenerTest.java
- modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/tasklistener/TaskListenerTest.java
- modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/executionlistener/ExecutionListenerTest.testThrowBpmnErrorCatchBoundaryEventSubProcessMultiInstanceSequential.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/executionlistener/ScriptTypeExecutionListenerTest.testExecutionListener.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/executionlistener/ScriptTypeExecutionListenerTest.testThrowNonFlowableException.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/tasklistener/TaskListenerTypeScript.bpmn20.xml
- modules/flowable-http/pom.xml
- modules/flowable-http/src/test/java/org/flowable/http/bpmn/HttpServiceTaskTest.java
- modules/flowable-http/src/test/resources/org/flowable/http/bpmn/HttpServiceTaskTest.testGetWithScriptRequestHandlerGroovy.bpmn20.xml
- modules/flowable-secure-javascript/src/main/java/org/flowable/scripting/secure/listener/SecureJavascriptTaskListener.java
Please note that the expression evaluation might fail, in case the script language supports expressions too in its syntax, like groovy. Therefore, it is recommended to set the script as string.
> Changed AbstractScriptEvaluator to take string as script

- README.md
AdoptOpenJDK was succeeded by Eclipse Adoptium in July 2021.
https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/
> Replace AdoptOpenJDK info with Eclipse Adoptium

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/ParallelMultiInstanceBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/data/impl/MybatisHistoricDetailDataManager.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/data/impl/cachematcher/HistoricDetailsByProcessInstanceIdEntityMatcher.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/data/impl/cachematcher/HistoricDetailsByTaskInstanceIdEntityMatcher.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceVariableAggregationTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.testLoopVariablesWithBoundaryOnSubprocess.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.testLoopVariablesWithSubprocessWhenProcessIsDeleted.bpmn20.xml
When a parallel multi instance execution is interrupted or deleted then we need to transform the temporary runtime variables into permanent historic variables
fixes #3536
> Make sure that Parallel multi instance local variables are properly transformed

- modules/flowable-http-common/src/main/java/org/flowable/http/common/impl/apache/ApacheHttpComponentsFlowableHttpClient.java
- modules/flowable-http-common/src/main/java/org/flowable/http/common/impl/apache/client5/ApacheHttpComponents5FlowableHttpClient.java
- modules/flowable-http-common/src/main/java/org/flowable/http/common/impl/spring/reactive/SpringWebClientFlowableHttpClient.java
- modules/flowable-http/src/test/java/org/flowable/http/FlowableHttpClientArgumentProvider.java
- modules/flowable-http/src/test/java/org/flowable/http/FlowableHttpClientTest.java
Added support for optional request body to the DELETE operation.
Added tests for http DELETE requests with and without body
> feature: request body for HTTP DELETE

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/impl/CmmnHistoryTestHelper.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/test/HistoryTestHelper.java
* Makes it a lot clearer why a test failed.
> Extend error message in HistoryTestHelper with more context information

- ide-settings/eclipse/Preferences-Java-CodeStyle-OrganizeImports.importorder
Eclipse preferences to order imports in same way as the IntelliJ settings do.
> other: Eclipse organize imports order

- distro/src/notice.txt
- pom.xml
Spring Security Release Notes: https://github.com/spring-projects/spring-security/releases/tag/5.8.0
Spring Framework Release Notes: https://github.com/spring-projects/spring-framework/releases/tag/v5.3.24
Spring Boot Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.7.6
Ran locally: `mvn clean test` without issue
Note that the biggest change is in the versioning of **hsqldb**: from 2.3.2 to 2.7.1
This PR supersedes https://github.com/flowable/flowable-engine/pull/3530
> Upgrade to Spring Framework 5.3.24, Spring Security 5.8.0 and Spring Boot 2.7.6

- distro/src/notice.txt
- pom.xml
Release Notes: https://github.com/spring-projects/spring-framework/releases/tag/v5.3.25
> Upgrade to Spring Framework 5.3.25 for 6.x branch

- distro/src/notice.txt
- pom.xml
Release Notes:  https://github.com/spring-projects/spring-security/releases/tag/5.8.2
> Upgrade to Spring Security 5.8.2 for flowable6.x branch

- distro/src/notice.txt
- pom.xml
Release Notes:
version 3.0.4: https://github.com/spring-projects/spring-boot/releases/tag/v3.0.4
version 3.0.5: https://github.com/spring-projects/spring-boot/releases/tag/v3.0.5
> Upgrade to Spring Boot 3.0.5

- modules/flowable-engine/src/main/java/org/flowable/engine/delegate/event/impl/FlowableEventBuilder.java
- modules/flowable-engine/src/main/java/org/flowable/engine/delegate/event/impl/FlowableVariableEventImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/EventUtil.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/VariableEventsTest.java
- modules/flowable-variable-service-api/src/main/java/org/flowable/variable/api/event/FlowableVariableEvent.java
- modules/flowable-variable-service/src/main/java/org/flowable/variable/service/event/impl/FlowableVariableEventBuilder.java
- modules/flowable-variable-service/src/main/java/org/flowable/variable/service/event/impl/FlowableVariableEventImpl.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/delegate/event/impl/ActivitiEventBuilder.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/delegate/event/impl/ActivitiVariableEventImpl.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/db/DbSqlSession.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntity.java
- modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/TaskEntity.java
This pull request adds the instance ID variable to VariableEvents. This can be helpful if someone wants to modify a variable within a VariableEvent, for example, when the variable has been updated.
> Add variable instance id to VariableEvents

- distro/src/notice.txt
- pom.xml
Spring Security release notes: https://github.com/spring-projects/spring-security/releases/tag/6.0.3
Spring Framework release notes: https://github.com/spring-projects/spring-framework/releases/tag/v6.0.8
The Security update fixes the following CVE:
[cve-2023-20862: Empty SecurityContext Is Not Properly Saved Upon Logout](https://spring.io/security/cve-2023-20862)
The Framework updates fixes the following CVE:
[cve-2023-20863: Spring Expression DoS Vulnerability](https://spring.io/security/cve-2023-20863)
> Upgrade to Spring Security 6.0.3 and Spring Framework 6.0.8

- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricTaskInstanceQueryResourceTest.java
- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/management/JobCollectionResourceTest.java
- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/repository/CaseDefinitionIdentityLinksResourceTest.java
- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/CaseInstanceCollectionResourceTest.java
- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/EventSubscriptionResourceTest.java
The `@Test` annotation is not used in JUnit3 tests: 
<pre>
public class MyTest extends TestCase {
@Test
public void testFoo() { }
}
</pre>
should be 
<pre>
public class MyTest extends TestCase {
public void testFoo() { }
}
</pre>
> Chore: remove @Test from Junit3 tests

- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/constants/BpmnXMLConstants.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/UserTaskXMLConverter.java
- modules/flowable-bpmn-converter/src/main/resources/org/flowable/impl/bpmn/parser/flowable-bpmn-extensions.xsd
- modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/UserTaskConverterTest.java
- modules/flowable-bpmn-converter/src/test/resources/usertaskmodel.bpmn
- modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/UserTask.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnXmlConstants.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/HumanTaskXmlConverter.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/HumanTaskExport.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/HumanTaskVariableCompleterCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/resources/org/flowable/test/cmmn/converter/humanTaskCompleterVariableName.cmmn
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/HumanTaskActivityBehavior.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/HumanTaskTest.java
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/HumanTaskTest.testHumanTaskCompleterVariableName.cmmn
- modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/HumanTask.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/TaskHelper.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/usertask/UserTaskTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/usertask/UserTaskTest.userTaskCompleterVariableName.bpmn20.xml
When modeling processes, it is often useful to know the user who completed a task. For instance when modeling reviews, we often want to reassign a task back to the original completer of a task.
Potentially, we could also add an additional flag which allows us to store this variable locally (i.e. as a task variable) which may useful in some cases.
> Add ability to store completer of HumanTasks and UserTasks in a variable

- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/el/VariableContainerELResolver.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/el/JsonVariableContainerExpressionTest.java
* The VariableContainerElResolver missed an else branch to return a value for plain VariableContainers (Handled VariableScope only). This prevented creation of nested json variables when no VariableScope, but a simple VariableContainer has been used.
> Fix VariableContainerELResolver to return a value for plain VariableContainer

- distro/src/notice.txt
- pom.xml
This release includes a fix for [CVE-2023-20883: Spring Boot Welcome Page DoS Vulnerability](http://spring.io/security/cve-2023-20883).
Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v3.0.7
Supersedes https://github.com/flowable/flowable-engine/pull/3651
> Upgrade to Spring Boot 3.0.7

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java
As part of https://github.com/flowable/flowable-engine/pull/3481 the variable, `execution` was added to the debug message but no placeholder was added.
It would appear that the `id` of the `execution` is logged.   
The output of `execution` would be the default `toString()` and would provide little or no additional information thus the decision to remove it to make the number of placeholders match the number of arguments.
> Chore: mismatch of logging placeholders and arguments

- modules/flowable-engine/src/test/java/org/flowable/engine/test/el/ExpressionManagerTest.java
The constructor `new Float(double value)` has been deprecated since JDK 9 and is marked for removal.  Here is the relevant code in the JDK:
<pre>
/**
* Constructs a newly allocated {@code Float} object that
* represents the argument converted to type {@code float}.
*
* @param   value   the value to be represented by the {@code Float}.
*
* @deprecated
* It is rarely appropriate to use this constructor. Instead, use the
* static factory method {@link #valueOf(float)} method as follows:
* {@code Float.valueOf((float)value)}.
*/
@Deprecated(since="9", forRemoval = true)
public Float(double value) {
this.value = (float)value;
}
</pre>
> Chore: replace API marked for removal

- distro/src/notice.txt
- pom.xml
Spring Boot is significantly out of date; it is currently at 2.7.9.  Below is the release date and release notes for the various versions that bring the project up to version 2.7.15.
<pre>
Date of Release        Release Notes
============           ==============
Feb 23                 https://github.com/spring-projects/spring-boot/releases/tag/v2.7.9
Mar 23                 https://github.com/spring-projects/spring-boot/releases/tag/v2.7.10
Apr 20                 https://github.com/spring-projects/spring-boot/releases/tag/v2.7.11
May 18                 https://github.com/spring-projects/spring-boot/releases/tag/v2.7.12
Jun 22                 https://github.com/spring-projects/spring-boot/releases/tag/v2.7.13
Jul 20 …
> Upgrade to Spring Boot 2.7.15 for 6.x track

- modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/HistoricCaseInstanceMigrationBuilder.java
When `flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/HistoricCaseInstanceMigrationBuilder.java` was created from `flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/CaseInstanceMigrationBuilder.java`, the Javadoc parameter name was changed to `historicCaseInstanceMigrationDocument` but the method signature was not.   This fixes that oversight.   Now the Javadoc can find the parameter.
> Chore: fix parameter name to match Javadoc

- distro/src/notice.txt
- pom.xml
Fixes [CVE-2023-34042](https://spring.io/security/cve-2023-34042).
Release Notes: https://github.com/spring-projects/spring-security/releases/tag/6.1.4
> Upgrade to Spring Security 6.1.4

- distro/src/notice.txt
- pom.xml
Fixes [CVE-2023-34042](https://spring.io/security/cve-2023-34042).
Release Notes:
5.8.3 https://github.com/spring-projects/spring-security/releases/tag/5.8.3
5.8.4 https://github.com/spring-projects/spring-security/releases/tag/5.8.4
5.8.5 https://github.com/spring-projects/spring-security/releases/tag/5.8.5
5.8.6 https://github.com/spring-projects/spring-security/releases/tag/5.8.6
5.8.7 https://github.com/spring-projects/spring-security/releases/tag/5.8.7
> Upgrade to Spring Security 5.8.7

- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/hitpolicy/AbstractHitPolicy.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/hitpolicy/ComposeDecisionResultBehavior.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/hitpolicy/HitPolicyAny.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/hitpolicy/HitPolicyCollect.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/hitpolicy/HitPolicyOutputOrder.java
- modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/hitpolicy/HitPolicyUnique.java
- modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/drd/DecisionServiceTest.java
- modules/flowable-dmn-engine/src/test/resources/org/flowable/dmn/engine/test/runtime/decisionServiceStackUpdate.dmn
When having encapsulated decision tables with a hit policy of the type ComposeDecisionResultBehavior the decision table result can be different from the last valid rule result.
Before the execution stack got updated after rule execution.
But with some hit policies, for example Collection SUM, there are additional calculations performed. 
The result was not put on the stack. Causing issues with decisions depending on these decisions.
This is fixed now.
> DecisionService execution stack not updating

- distro/src/notice.txt
- pom.xml
Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v3.1.4
> Upgrade to Spring Boot 3.1.4

- pom.xml
Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.7.16
> Upgrade to Spring Boot 2.7.16 for flowable6.x branch

- distro/src/notice.txt
- pom.xml
**Spring Boot:**
Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v3.1.5
**Spring Security:**
Release Notes:  https://github.com/spring-projects/spring-security/releases/tag/6.1.5
**Spring Framework:**
Includes 34 fixes and documentation improvements of which 7 are fixes for regressions. There are no Flowable related dependency updates.
Release Notes: https://github.com/spring-projects/spring-framework/releases/tag/v6.0.13
> Upgrade to Spring Boot 3.1.5, Security 6.1.5 and Spring Framework 6.0.13

- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/db/LiquibaseBasedSchemaManager.java
The LiquibaseBasedSchemaManager does not handle the "create" schema update option.
If the database schema update approach is set for the process engine by passing ProcessEngineConfiguration.DB_SCHEMA_UPDATE_CREATE to the SpringProcessEngineConfiguration instance, then this is applied to the DmnEngineConfiguration by the DmnEngineConfigurator. The LiquibaseBasedSchemaManager does not handle this schema update option so the DMN database tables are not created.
This change fixes the LiquibaseBasedSchemaManager's handling of create schema update option.
Closes #3771
> Fixed LiquibaseBasedSchemaManager handling of create schema update

- modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/CmmnRuntimeService.java
- modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/runtime/CaseInstanceStartEventSubscriptionBuilder.java
- modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/runtime/CaseInstanceStartEventSubscriptionDeletionBuilder.java
- modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/runtime/CaseInstanceStartEventSubscriptionModificationBuilder.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnXmlConstants.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/AbstractCaseStartEventSubscriptionCmd.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/DeleteCaseInstanceStartEventSubscriptionCmd.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/ModifyCaseInstanceStartEventSubscriptionCmd.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/RegisterCaseInstanceStartEventSubscriptionCmd.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/deployer/CmmnDeployer.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CaseInstanceStartEventSubscriptionBuilderImpl.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CaseInstanceStartEventSubscriptionDeletionBuilderImpl.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CaseInstanceStartEventSubscriptionModificationBuilderImpl.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CmmnRuntimeServiceImpl.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/AbstractFlowableCmmnTestCase.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/eventregistry/DynamicCaseStartEventRegistryDeploymentTest.java
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/eventregistry/DynamicCaseStartEventRegistryDeploymentTest.eventRegistryDynamicStartTestCase.cmmn
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/eventregistry/DynamicCaseStartEventRegistryDeploymentTest.eventRegistryStaticStartTestCase.cmmn
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/eventregistry/DynamicCaseStartEventRegistryDeploymentTest.sendTestEventCase.cmmn
- modules/flowable-eventsubscription-service/src/main/java/org/flowable/eventsubscription/service/EventSubscriptionService.java
- modules/flowable-eventsubscription-service/src/main/java/org/flowable/eventsubscription/service/impl/EventSubscriptionServiceImpl.java
- modules/flowable-eventsubscription-service/src/main/java/org/flowable/eventsubscription/service/impl/persistence/entity/EventSubscriptionEntityManager.java
- modules/flowable-eventsubscription-service/src/main/java/org/flowable/eventsubscription/service/impl/persistence/entity/EventSubscriptionEntityManagerImpl.java
- modules/flowable-eventsubscription-service/src/main/java/org/flowable/eventsubscription/service/impl/persistence/entity/data/EventSubscriptionDataManager.java
- modules/flowable-eventsubscription-service/src/main/java/org/flowable/eventsubscription/service/impl/persistence/entity/data/impl/MybatisEventSubscriptionDataManager.java
- modules/flowable-eventsubscription-service/src/main/java/org/flowable/eventsubscription/service/impl/persistence/entity/data/impl/cachematcher/EventSubscriptionsByScopeDefinitionIdAndScopeStartEventMatcher.java
- modules/flowable-eventsubscription-service/src/main/resources/org/flowable/eventsubscription/service/db/mapping/entity/EventSubscription.xml
Add support for dynamic, manually created event subscriptions with any combination of correlation parameter values for an event-registry based case start.
Check List:
Unit tests: YES
Documentation: NO
> Support manual event subscription based case event-registry start 

- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/DeadLetterJobQueryImpl.java
- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/ExternalWorkerJobQueryImpl.java
- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/HistoryJobQueryImpl.java
- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/SuspendedJobQueryImpl.java
- modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/TimerJobQueryImpl.java
getHandlerTypes should be implemented by all the different job queries, not just the default JobQueryImpl
> fix: add getHandlerTypes() for the different Job Queries

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/StageActivityBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/delegate/DelegateExecution.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/UserTaskActivityBehavior.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ActivityInstanceEntityManagerImpl.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntity.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityImpl.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/RuntimeActivityInstanceTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/oneTaskProcessWithBeanExpression.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/oneTaskProcessWithExpression.bpmn20.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/runtime/ServiceTaskWithNameExpression.bpmn20.xml
> added expression resolver for activity name

- modules/flowable-batch-service/src/main/java/org/flowable/batch/service/BatchServiceConfiguration.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/AbstractServiceConfiguration.java
- modules/flowable-engine-common/src/test/java/org/flowable/common/engine/impl/ServiceConfiguratorTest.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
- modules/flowable-entitylink-service/src/main/java/org/flowable/entitylink/service/EntityLinkServiceConfiguration.java
- modules/flowable-eventsubscription-service/src/main/java/org/flowable/eventsubscription/service/EventSubscriptionServiceConfiguration.java
- modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/IdentityLinkServiceConfiguration.java
- modules/flowable-job-service/src/main/java/org/flowable/job/service/JobServiceConfiguration.java
- modules/flowable-task-service/src/main/java/org/flowable/task/service/TaskServiceConfiguration.java
- modules/flowable-variable-service/src/main/java/org/flowable/variable/service/VariableServiceConfiguration.java
Add support for ServiceConfigurator to Variable, Task, IdentityLink, EntityLink, EventSubscription and Batch ServiceConfiguration to allow customisation at init time.
The implementation follows the logic of JobServiceConfiguration that already has support for ServiceConfigurator.
> feat: ServiceConfigurator support for various service configurations

- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/constants/BpmnXMLConstants.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/export/BPMNDIExport.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/parser/BpmnEdgeParser.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/parser/BpmnShapeParser.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/util/BpmnXMLUtil.java
- modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/LabelDiagramConverterTest.java
- modules/flowable-bpmn-converter/src/test/resources/labelProcess.bpmn
- modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/GraphicInfo.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnDiBoundsXmlConverter.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnDiEdgeXmlConverter.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnDiLabelXmlConverter.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnXmlConstants.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnXmlConverter.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/ConversionHelper.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/CmmnDIExport.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/LabelCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/resources/org/flowable/test/cmmn/converter/labelCase.cmmn
- modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/CmmnDiEdge.java
- modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/CmmnDiShape.java
- modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/GraphicInfo.java
Add parsing for diagram labels in xml for bpmn shapes and cmmn edges and shapes
> Add parsing for diagram labels in xml

- modules/flowable-batch-service/pom.xml
- modules/flowable-entitylink-service/pom.xml
- modules/flowable-eventsubscription-service/pom.xml
- modules/flowable-identitylink-service/pom.xml
- modules/flowable-job-service/pom.xml
- modules/flowable-task-service/pom.xml
- modules/flowable-variable-service/pom.xml
This PR fixes kind of trivial bug in generated OSGi wiring `Import-Package` metadata (#3844).
If you don't like the global `flowable.osgi.import.defaults` definition, I have a different branch https://github.com/pavelhoral/flowable-engine/tree/fix-osgi-wiring that updates all respective pom.xml files to fix the tests.
Fixes #3844
> Fix broken OSGi wiring (#3844)

- distro/src/notice.txt
- modules/flowable-event-registry-spring/src/main/java/org/flowable/eventregistry/spring/kafka/KafkaChannelDefinitionProcessor.java
- modules/flowable-http/pom.xml
- modules/flowable-rest/pom.xml
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/AllEnginesAutoConfigurationTest.java
- pom.xml
The following dependencies have been upgraded:
* Spring Boot 3.2.2
* Spring Framework 6.1.3
* Spring Security 6.2.1
* Spring AMQP 3.1.1
* Spring Kafka 3.1.1
* Spring LDAP 3.2.1
* Reactor Netty 1.1.15
* SLF4J 2.0.11
* Groovy 4.0.17
* JUnit Jupiter 5.10.1
* Mockito 5.7.0
* Byte Buddy 1.14.11
* Testcontainer 1.19.3
* Artemis 2.31.2
* Http Client5 5.2.3
* Hibernate Core 6.4.1.Final
* Spring Data JPA 3.2.2
The assertion in `AllEnginesAutoConfigurationTest` has been changed to use `containsExactlyInAnyOrder` since the order there isn't important, and it seems like the beans are created in a different order now.
The `AppEngineConfiguration` is going to anyways order all the available contributors before applying them. The configurators are only the ones that have been registered during bean …
> Spring Boot 3.2 and other dependencies upgrade

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/AbstractServiceConfiguration.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
- modules/flowable-entitylink-service/src/main/java/org/flowable/entitylink/service/EntityLinkServiceConfiguration.java
- modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/IdentityLinkServiceConfiguration.java
- modules/flowable-job-service/src/main/java/org/flowable/job/service/JobServiceConfiguration.java
- modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/persistence/entity/HistoricTaskInstanceEntityManagerImpl.java
History check in the historic task instance entity manager is not needed since history level on the engine could be none, but on the definition level it could be task or higher
> Remove not needed historyLevel from service configurations and remove history check in historic task instance entity manager

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/eventregistry/CmmnEventRegistryEventConsumer.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/eventregistry/BpmnEventRegistryEventConsumer.java
- modules/flowable-event-registry/src/main/java/org/flowable/eventregistry/impl/consumer/BaseEventRegistryEventConsumer.java
Behavior stays the same, throw nicer exception instead of NPE
> Improve exception message for "Start a new instance only when no other instance already exists" event without correlation parameters

- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/FlowableJobConfiguration.java
- modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/process/ProcessEngineAutoConfigurationTest.java
Fixes #3901 by making sure the `DefaultAsyncTaskExecutor` is started.
Fixes #3875
**Check List:**
- Unit tests: YES
- Documentation: NA
> #3901: Make sure DefaultAsyncTaskExecutor is started

- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/constants/BpmnXMLConstants.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/BaseBpmnXMLConverter.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/BpmnXMLConverter.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/SequenceFlowXMLConverter.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/child/ElementNameParser.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/parser/ExtensionElementsParser.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/util/BpmnXMLUtil.java
- modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/NameWithNewLineTest.java
- modules/flowable-bpmn-converter/src/test/resources/nameWithNewLineTestProcess.bpmn
- modules/flowable-bpmn-converter/src/test/resources/nameWithoutNewLineTestProcess.bpmn
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnXmlConstants.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/ConversionHelper.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/ExtensionElementsXMLConverter.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/PlanItemDefinitionXmlConverter.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/AbstractPlanItemDefinitionExport.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/util/CmmnXmlUtil.java
- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/NameWithNewLineTest.java
- modules/flowable-cmmn-converter/src/test/resources/org/flowable/test/cmmn/converter/nameWithNewLineTestCase.cmmn
- modules/flowable-cmmn-converter/src/test/resources/org/flowable/test/cmmn/converter/nameWithoutNewLineTestCase.cmmn
If an element name has any newlines, save it in an extension element instead of in an attribute because new lines are changed into spaces when xml attribute is **parsed**
> Save element name in extension element if it has any new lines

- modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/query/BaseNativeQuery.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/identity/GroupQueryTest.java
The generated ORDER BY clause is incorrect, leading to syntax errors in the resulting query. The ELSE branch in lines 64-55 did it correctly (but I refactored the code to combine the code).
I'm not set up to add/run tests for this, but I think this change should be looked at ASAP since the bug breaks a lot of queries.
> Fix order by clause missing "order by"

- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CaseInstanceQueryImplTest.java
- modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/CmmnRestResponseFactory.java
- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/CaseInstanceVariableResourceTest.java
- modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/TaskVariablesCollectionResourceTest.java
- modules/flowable-common-rest/src/main/java/org/flowable/common/rest/variable/UUIDRestVariableConverter.java
- modules/flowable-dmn-rest/src/main/java/org/flowable/dmn/rest/service/api/DmnRestResponseFactory.java
- modules/flowable-rest/src/main/java/org/flowable/rest/service/api/RestResponseFactory.java
- modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/ProcessInstanceVariableResourceTest.java
> Support UUID value type in flowable-rest API (#3856)

- modules/flowable-engine/src/main/java/org/flowable/engine/impl/dynamic/AbstractDynamicStateManager.java
- modules/flowable-engine/src/main/java/org/flowable/engine/impl/dynamic/MoveExecutionEntityContainer.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/AbstractProcessInstanceMigrationEventRegistryConsumerTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceMigrationEventRegistryEventSubprocessTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceMigrationEventSubProcessTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/runtime/migration/non-interrupting-eventregistry-event-subprocess.bpmn20.xml
> Fixed missing subscriptions after migration of an active embedded non interrupting event sub process (#3928)

- modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/ScriptServiceTaskCmmnXmlConverterTest.java
- modules/flowable-cmmn-converter/src/test/resources/org/flowable/test/cmmn/converter/script-task-expression-field.cmmn
- modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/ScriptServiceTask.java
Not throwing the exception aligns this with the way it works for BPMN, where no exception is thrown by the model. There will eventually be an exception thrown when the script is executed
> Use cmmn script task expression value if no string value is missing and do not throw exception if field is missing

- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/deployer/CmmnDeployer.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/repository/DeploymentTest.java
This aligns the CmmnDeployer with the BpmnDeployer
> Do not perform Cmmn Validation on already deployed models

- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/DeleteCandidateTaskListener.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskIdentityLinksTest.java
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/task/TaskIdentityLinksTest.testDeleteCandidates.bpmn20.xml
- modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/persistence/entity/TaskEntityImpl.java
Handle removal of task identity links by calling the appropriate methods from the task assignment manager, same as when adding identity links.
I haven't found any existing unit tests related to this functionality to modify and creating the entire test from scratch would be out of scope for this simple change. Please correct me if I'm wrong.
> Handle deleting task candidates

- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/BpmnXMLConverter.java
- modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/FlowableXMLStreamReader.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnXmlConverter.java
- modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/FlowableXMLStreamReader.java
- modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/deployer/CmmnDeployer.java
- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/repository/DeploymentTest.java
- modules/flowable-cmmn-engine/src/test/resources/flowable.cmmn.cfg.xml
- modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/repository/DeploymentTest.testCaseDefinitionWithEmptyCDATA.cmmn
- modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/deployment/BpmnDeploymentTest.java
- modules/flowable-engine/src/test/resources/flowable.cfg.xml
- modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/deployment/BpmnDeploymentTest.testBpmnWithEmptyCDATA.bpmn20.xml
There is a bug in the default Java XML Stream Reader in which an empty CDATA throws an IndexOutOfBoundsException when the schema is being validated. Therefore, we are creating our own delegating FlowableXMLStreamReader and handle the edge case for an empty CDATA.
> Make sure that empty CDATA is properly parsed

- modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/task/CmmnTaskServiceTest.java
- modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskServiceTest.java
- modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/impl/persistence/entity/IdentityLinkEntityManagerImpl.java
> added a deleted() check if an IdentityLink is already deleted or not.

- modules/flowable-camel/src/main/java/org/flowable/camel/CamelBehavior.java
- modules/flowable-camel/src/main/java/org/flowable/camel/SpringCamelBehavior.java
- modules/flowable-camel/src/main/java/org/flowable/camel/impl/CamelBehaviorBodyAsMapImpl.java
- modules/flowable-camel/src/main/java/org/flowable/camel/impl/CamelBehaviorCamelBodyImpl.java
- modules/flowable-camel/src/main/java/org/flowable/camel/impl/CamelBehaviorDefaultImpl.java
Use a synchronized block to determine the default camelContextObj. Do not use class field for the TargetType
> Rewrite Camel Behavior to be more multi instance resilient
