flowable/flowable-engine

modules/flowable-engine/src/main/java/org/activiti/engine/delegate/event/ActivitiEventType.java
modules/flowable-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/DefaultJobManager.java
modules/flowable-engine/src/test/java/org/activiti/engine/test/api/event/JobEventsTest.java

This pull request is not in the flowable fork. Here is a new request to add the functionality. 
https://github.com/Activiti/Activiti/pull/1020

Add support for TIMER_SCHEDULED event.

---

modules/flowable-engine/src/main/java/org/activiti/engine/impl/util/ProcessInstanceHelper.java
modules/flowable-idm-engine/src/main/java/org/activiti/idm/engine/impl/cfg/IdGenerator.java

Minor fixes

---

modules/flowable-idm-engine/pom.xml

flowable-idm-engine pom:
- maven dependency slf4j-log4j12 should be in test scope. this prevents users from inheriting it. junit should also be test scope.
- use consistent indentation.

slf4j-log4j12 and junit should be in test scope + fix indentation

---

userguide/src/en/ch04-API.adoc

Added a footnote indicating the modified version is only used in Version 5.

Update doc due to removal of JUEL in version 6

---

distro/src/readme.html

Fix spelling mistake in readme.html (flowable5)

fix small spelling mistake

---

modules/flowable-engine-common/src/main/java/org/activiti/engine/common/impl/transaction/TransactionContextAwareTransactionFactory.java

Remove duplicate null check by making the smallest change possible.

Remove duplicate null check

---

modules/flowable-engine/src/test/java/org/activiti/engine/test/cfg/executioncount/VerifyDatabaseOperationsTest.java
modules/flowable-engine/src/test/java/org/activiti/standalone/escapeclause/HistoricTaskQueryEscapeClauseTest.java
modules/flowable-ui-idm/flowable-ui-idm-conf/src/main/java/org/activiti/app/security/CustomDaoAuthenticationProvider.java
modules/flowable-ui-task/flowable-ui-task-logic/src/main/java/org/activiti/app/model/runtime/RestVariable.java
modules/flowable5-compatibility/src/main/java/org/activiti/compatibility/DefaultActiviti5CompatibilityHandler.java
modules/flowable5-engine/src/main/java/org/activiti5/engine/impl/persistence/entity/VariableScopeImpl.java

Remove unnecessary semicolons via static code inspection.

Remove unnecessary semicolons

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/json/XML.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/cfg/executioncount/VerifyDatabaseOperationsTest.java
modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/cmd/GetFormModelCmd.java
modules/flowable-osgi/src/main/java/org/flowable/osgi/OsgiScriptingEngines.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/email/MockEmailTransport.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/util/json/XML.java

Minor change to add missing whitespace to message text.

Add missing whitespace in messages

---

modules/flowable5-engine/src/main/java/org/activiti/engine/impl/HistoricVariableInstanceQueryImpl.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/cmd/SaveProcessDefinitionInfoCmd.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/event/logger/EventLogger.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/jobexecutor/TimerDeclarationImpl.java

Remove redundant comparison to null as already know to be non-null.

Remove redundant null check

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/AttachmentEventsTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/mail/EmailSendTaskTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/mail/EmailServiceTaskTest.java
modules/flowable-ui-common/src/main/java/org/flowable/app/util/XmlUtil.java

Ran the engine test suite without error for the test changes.
Changed a comment link to the new user guide location.

Minor renaming and link fixing

---

userguide/src/en/flowable.css

CSS uses just 'color' and not 'font color'

---

modules/flowable-engine/src/main/java/org/flowable/engine/delegate/package.html
modules/flowable-engine/src/main/java/org/flowable/engine/form/package.html
modules/flowable-engine/src/main/java/org/flowable/engine/history/package.html
modules/flowable-engine/src/main/java/org/flowable/engine/package.html
modules/flowable-engine/src/main/java/org/flowable/engine/repository/package.html
modules/flowable-engine/src/main/java/org/flowable/engine/runtime/package.html
modules/flowable-engine/src/main/java/org/flowable/engine/task/package.html
modules/flowable5-engine/src/main/java/org/activiti/engine/delegate/package.html
modules/flowable5-engine/src/main/java/org/activiti/engine/form/package.html
modules/flowable5-engine/src/main/java/org/activiti/engine/history/package.html
modules/flowable5-engine/src/main/java/org/activiti/engine/package.html
modules/flowable5-engine/src/main/java/org/activiti/engine/repository/package.html
modules/flowable5-engine/src/main/java/org/activiti/engine/runtime/package.html
modules/flowable5-engine/src/main/java/org/activiti/engine/task/package.html

Fix names of packages and qualify the version 5 packages as version 5.

Update references in package.html files

---

modules/flowable-ui-common/src/main/java/org/flowable/app/filter/FlowableCookieFilter.java
modules/flowable-ui-task/flowable-ui-task-rest/src/main/java/org/flowable/app/rest/runtime/AbstractRelatedContentResource.java

In one case ".map" was included twice and in the other "png".
Question: In the skipAuthenticationCheck() method should "'tif", "tiff", and "jpeg" be included also?

Duplicate condition in if stmt or condition

---

modules/flowable-ui-common/src/main/java/org/flowable/app/filter/FlowableCookieFilter.java

@tijsrademakers  Added more extensions per comment in PR#87.

Add more extensions to skipAuthenticationCheck

---

modules/flowable-engine/src/main/java/org/flowable/engine/ManagementService.java

Small corrections for new methods in `ManagementService`.

Fix JavaDoc for recently added rescheduled methods

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/cfg/executioncount/VerifyDatabaseOperationsTest.java
modules/flowable5-test/src/test/java/org/activiti/engine/test/api/mgmt/JobQueryTest.java
modules/flowable5-test/src/test/java/org/activiti/engine/test/cache/ProcessDefinitionCacheTest.java

Addresses issue #10 from [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154/5).

Remove unnecessary semicolon

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/servicetask/ServiceTaskVariablesTest.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/ShellActivityBehavior.java

Addresses issue #7 from [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154/5).

Remove unnecessary "null" check before "equals()" call

---

modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/ValuedDataObject.java
modules/flowable-content-rest/src/main/java/org/flowable/rest/content/PutAwareCommonsMultipartResolver.java
modules/flowable-dmn-rest/src/main/java/org/flowable/rest/dmn/service/api/PutAwareCommonsMultipartResolver.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/SuspensionState.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/condition/ConditionUtil.java
modules/flowable-engine/src/test/java/org/flowable/examples/variables/VariablesTest.java
modules/flowable-form-rest/src/main/java/org/flowable/rest/form/PutAwareCommonsMultipartResolver.java
modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/impl/persistence/entity/UserEntityManagerImpl.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/PutAwareCommonsMultipartResolver.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/components/scope/StatefulObject.java
modules/flowable-ui-admin/src/main/java/org/flowable/admin/domain/ServerConfig.java
modules/flowable-ui-common/src/main/java/org/flowable/app/filter/FlowableCookieFilter.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/SuspensionState.java

Addresses issue #13 from the [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154).

Simplify "if" statement to single assignment or return

---

modules/flowable5-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/AsyncJobUtil.java

Addresses issue #15 from the [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154).

Remove unnecessary return statement

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/alfresco/AlfrescoStartEventXMLConverter.java
modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/alfresco/AlfrescoUserTaskXMLConverter.java
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/DataObject.java
modules/flowable-content-engine/src/main/java/org/flowable/content/engine/ContentEngineConfiguration.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/EventBasedGatewayActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/IntermediateCatchTimerEventActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/HistoricVariableInstanceEntityImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/TaskEntityImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/data/impl/MybatisDeadLetterJobDataManager.java
modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/impl/persistence/entity/TokenEntityImpl.java
modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/impl/persistence/entity/UserEntityImpl.java
modules/flowable-ldap/src/main/java/org/flowable/ldap/LDAPConfigurator.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/integration/IntegrationActivityBehavior.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/DeploymentEntityManager.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntity.java

Addresses issue #23  from the [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154).
In addition I added missing @Override annotations while editing the file.  This is part of issue #22 of the same standards.

Remove method that is identical to its super method

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/CompleteTaskWithFormCmd.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetStartFormModelCmd.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetTaskFormModelCmd.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/StartProcessInstanceWithFormCmd.java
modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/cmd/GetFormInstanceModelCmd.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskCollectionResource.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/boot/AbstractProcessEngineConfiguration.java

Addresses issue #35  from the [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154).

Use "addAll()" instead of manual copy of array contents

---

modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/BpmnModel.java
modules/flowable-engine-common/src/main/java/org/flowable/engine/common/AbstractEngineConfiguration.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/ModelQueryImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/db/DbSqlSession.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/VariableScopeImpl.java
modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/impl/db/DbSqlSession.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/ModelQueryImpl.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/handler/StartEventParseHandler.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/VariableScopeImpl.java

Remove '== true' from conditions as they are unnecessary.

Remove "== true" from condition

---

modules/flowable-bpmn-layout/src/main/java/org/flowable/bpmn/BPMNLayout.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/db/DbSqlSession.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/json/XML.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/tenant/TenancyTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/variables/VariablesTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/deployment/MessageEventsAndNewVersionDeploymentsTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/deployment/MessageEventsAndNewVersionDeploymentsWithTenantIdTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/deployment/SignalEventsAndNewVersionDeploymentsTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/history/HistoricTaskInstanceTest.java
modules/flowable-image-generator/src/main/java/org/flowable/image/impl/DefaultProcessDiagramCanvas.java
modules/flowable-image-generator/src/main/java/org/flowable/image/impl/DefaultProcessDiagramGenerator.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/db/DbSqlSession.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/juel/AstBinary.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/juel/AstChoice.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/util/json/XML.java

Addresses issue #4 from the [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154).

Multiple variables in one declaration

---

modules/flowable-ui-admin/src/main/java/org/flowable/admin/service/engine/FlowableClientService.java
modules/flowable-ui-admin/src/main/java/org/flowable/admin/service/engine/ProcessDefinitionService.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/AppDefinitionExportService.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/AppDefinitionImportService.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/AppDefinitionPublishService.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/AppDefinitionServiceImpl.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/BpmnDisplayJsonConverter.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/FlowableModelQueryService.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/ModelImageService.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/ModelServiceImpl.java
modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/app/rest/editor/ModelResource.java
modules/flowable-ui-task/flowable-ui-task-conf/src/main/java/org/flowable/app/servlet/WebConfigurer.java
modules/flowable-ui-task/flowable-ui-task-logic/src/main/java/org/flowable/app/service/runtime/FlowableProcessDefinitionService.java
modules/flowable-ui-task/flowable-ui-task-logic/src/main/java/org/flowable/app/service/runtime/FlowableTaskActionService.java
modules/flowable-ui-task/flowable-ui-task-logic/src/main/java/org/flowable/app/service/runtime/FlowableTaskService.java

Addresses issue #26 from the [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154).

Replace string concatenation in logging call with {}

---

modules/flowable-crystalball/src/main/java/org/flowable/crystalball/simulator/impl/DeployClasspathResourcesEventHandler.java
modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/interceptor/AbstractCommandContext.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/interceptor/RetryInterceptor.java
modules/flowable-ldap/src/main/java/org/flowable/ldap/LDAPIdentityServiceImpl.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/interceptor/CommandContext.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/interceptor/RetryInterceptor.java

Addresses issue #27  from the [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154).
Some of the changes were obvious, others I made an arbitrary decision that I can change if needed.

Fix where number of placeholders does not mactch arguments in log call

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/export/BPMNDIExport.java
modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/fs/FileSystemContentStorage.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/variable/JPAEntityMappings.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoricProcessInstanceAndVariablesQueryTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryServiceTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/ProcessInstanceAndVariablesQueryTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/ProcessInstanceQueryTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/tenant/TenancyTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/cfg/executioncount/GenerateVariablesDelegate.java
modules/flowable-engine/src/test/java/org/flowable/examples/mgmt/TablePageQueryTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/cfg/CustomMybatisMapperTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/cfg/CustomMybatisXMLMapperTest.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/variable/JPAEntityMappings.java

Addresses issue #33 from the [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154).

Use String.valueOf() in place of concatation with empty string

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/NonCascadeDeleteTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/repository/LaneExtensionTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/v6/Flowable6ExecutionTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/v6/Flowable6Test.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/concurrency/OptimisticLockingExceptionTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/jobexecutor/JobExecutorExceptionsTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/subprocess/SubProcessTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/ExecutionQueryEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/HistoricProcessInstanceQueryEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/HistoricTaskQueryEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/HistoricVariableInstanceEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/ProcessInstanceQueryEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/TaskQueryEscapeClauseTest.java

Addresses issue #50  from the [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154).

Fix Junit4 annotations in Junit3 tests

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.java
modules/flowable-secure-javascript/src/test/java/org/flowable/test/scripting/secure/SecureScriptingBaseTest.java
modules/flowable-ui-admin/src/main/java/org/flowable/admin/conf/SecurityConfiguration.java
modules/flowable-ui-modeler/flowable-ui-modeler-conf/src/main/java/org/flowable/app/conf/SecurityConfiguration.java
modules/flowable-ui-task/flowable-ui-task-conf/src/main/java/org/flowable/app/conf/SecurityConfiguration.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/BpmnActivityBehavior.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessDefinitionStateCmd.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/db/ActivitiVersion.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/scripting/JuelScriptEngineFactory.java

Addresses issue #32 from the [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154).

Simplify "Arrays.asList()" with too few arguments

---

modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/replay/ReplayEventLogTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/ActivityEventsTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/v6/Flowable6ExecutionTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/form/FormDataResourceTest.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/jobexecutor/SpringAsyncExecutorTest.java

Addresses issue #51  from the [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154).
This is a further simplification to the changes made in #108

Simplify JUnit assertion

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/compensate/CompensateEventTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/compensate/CompensateEventTest.SubProcess1.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/compensate/CompensateEventTest.SubProcess2.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/compensate/CompensateEventTest.testCompensateTwoSubprocesses.bpmn20.xml

Add unit test to test that call activities receive the compensation event.

Verify that all call activities receive the compensation event

---

modules/flowable-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntity.java
modules/flowable-engine/src/test/java/org/activiti/engine/test/bpmn/event/compensate/CompensateEventTest.java
modules/flowable-engine/src/test/resources/org/activiti/engine/test/bpmn/event/compensate/CompensateEventTest.SubProcess1.bpmn20.xml
modules/flowable-engine/src/test/resources/org/activiti/engine/test/bpmn/event/compensate/CompensateEventTest.SubProcess2.bpmn20.xml
modules/flowable-engine/src/test/resources/org/activiti/engine/test/bpmn/event/compensate/CompensateEventTest.testCompensateTwoSubprocesses.bpmn20.xml

All call activities should receive the compensation event; added a junit test to verify the change.

All call activities should receive the compensation event

---

modules/flowable5-test/src/test/java/org/activiti/standalone/deploy/CustomDeploymentCache.java

This makes the same version 6 correction in the flowable5-test module code.

Correct variable comparison to itself

---

modules/flowable5-test/src/test/java/org/activiti/engine/test/api/runtime/ProcessInstanceSuspensionTest.java

Port PR #16  to flowable5-test module.

Add missing assertTrue() when checking for contains()

---

modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/resources/stencilset_bpmn.json

Change default target namespace used in Modeler to flowable

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/ValidateV5EntitiesCmd.java

Use parameterized log message instead of concatenation

---

modules/flowable-idm-engine/src/test/resources/log4j.properties

Change package from `activiti` to `flowable`.

Fix package name in log4j.properties file

---

modules/flowable-ui-admin/src/main/webapp/i18n/en.json
modules/flowable-ui-admin/src/main/webapp/scripts/app.js
modules/flowable-ui-admin/src/main/webapp/scripts/deployments-controllers.js
modules/flowable-ui-admin/src/main/webapp/scripts/process-instance-controllers.js
modules/flowable-ui-admin/src/main/webapp/styles/style.css
modules/flowable-ui-admin/src/main/webapp/views/decision-table.html
modules/flowable-ui-common/src/main/java/org/flowable/app/filter/FlowableCookieFilter.java
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/editor-app/popups/select-shape.html
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/editor-app/stencil-controller.js
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/scripts/common/providers-config.js
modules/flowable-ui-task/flowable-ui-task-app/src/main/webapp/scripts/common/providers-config.js

* fixed http interceptor; this caused not handling errors correctly
* fixed cookie filter; when user had no privileges a redirect was executed twice
* added deployment and parent deployment id to decision table deployment admin app
* angular controller name fix
* small name fixes

Fixes #180 & #184

---

userguide/src/en/ch02-GettingStarted.adoc
userguide/src/en/ch03-Configuration.adoc
userguide/src/en/ch11-IDM.adoc

More updates to the documentation.
BTW, I think that Chapter 3, section entitled, "Creating the database tables" should include references to the identity tables now that they are split out into a separate module.

Userguide updates

---

modules/flowable-engine/src/main/java/org/flowable/engine/ManagementService.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/ManagementServiceImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/asyncexecutor/DefaultJobManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/asyncexecutor/JobManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/RescheduleTimerJobCmd.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/BoundaryTimerEventTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/IntermediateTimerEventTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/timer/BoundaryTimerEventTest.testRescheduleRepeatBoundaryTimer.bpmn20.xml

Reschedule will delete the current timer and create a new timer.  The newly created timer should be returned by the reschedule call.

Reschedule should return newly created timer

---

modules/flowable-app-rest/src/main/java/org/flowable/rest/servlet/ContentDispatcherServletConfiguration.java
modules/flowable-app-rest/src/main/java/org/flowable/rest/servlet/DmnDispatcherServletConfiguration.java
modules/flowable-app-rest/src/main/java/org/flowable/rest/servlet/FormDispatcherServletConfiguration.java
modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/export/BPMNDIExport.java
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/BpmnModel.java
modules/flowable-cdi/src/main/java/org/flowable/cdi/impl/CdiCommandInvoker.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/RuleEngineExecutorImpl.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/mvel/MvelExecutionContext.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/mvel/MvelExecutionContextBuilder.java
modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/CustomConfigRuntimeTest.java
modules/flowable-dmn-spring/src/test/java/org/flowable/spring/test/junit4/SpringJunit4Test.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/child/BaseChildElementParser.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/child/InputClauseParser.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/child/InputEntryParser.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/child/InputExpressionParser.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/child/OutputClauseParser.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/child/OutputEntryParser.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/util/DmnXMLUtil.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/parser/handler/AbstractBpmnParseHandler.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/calendar/AdvancedCycleBusinessCalendar.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/calendar/CronExpression.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/calendar/DefaultBusinessCalendar.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetIdentityLinksForTaskCmd.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/history/HistoricTaskInstanceTest.java
modules/flowable-osgi/src/main/java/org/flowable/osgi/Extender.java
modules/flowable-osgi/src/main/java/org/flowable/osgi/blueprint/BundleDelegatingClassLoader.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/management/TableResourceTest.java
userguide-dmn/src/en/ch05-Deployment.adoc
userguide-dmn/src/en/ch06-DMN-Introduction.adoc
userguide/src/en/ch13-UI.adoc

* Remove unused imports
* Remove unnecessary casts
* Spelling corrections in documentation
* Correct ordering of modifiers
* Multiple variables in one declaration
etc.

Miscellaneous updates

---

modules/flowable-json-converter/src/main/java/org/activiti/editor/language/json/converter/BpmnJsonConverter.java
modules/flowable-json-converter/src/test/java/org/activiti/editor/language/EventSubprocessSequenceFlowTest.java
modules/flowable-json-converter/src/test/resources/test.eventsubprocesssequenceflow.json

Sequenceflows inside a EventSubprocess where not stored in the BPMNmodel.
* Implemented fix for the problem described in title.
* Added tests to verify behavior.

Nullpointer fix for sequenceflows inside a EventSubprocess 

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/ExecutionQueryTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/runtime/executionLocalization.bpmn20.xml

…localization values for Process/Subprocess elements

Update ExecutionQueryTest to validate support for multiple modeled

---

userguide-dmn/src/en/ch03-API.adoc
userguide-form/src/en/ch03-API.adoc
userguide-form/src/en/ch05-Deployment.adoc
userguide/src/en/ch02-GettingStarted.adoc
userguide/src/en/ch07b-BPMN-Constructs.adoc
userguide/src/en/ch14-REST.adoc
userguide/src/en/ch17-Advanced.adoc

More minor changes; spelling and an example correction

Documentation changes

---

userguide-form/src/en/ch02-Configuration.adoc
userguide-form/src/en/ch03-API.adoc
userguide-form/src/en/ch04-Spring.adoc

Replace references to DMN that were missed when the doc was cloned.

Replace references of DMN with Form

---

modules/flowable-content-engine/src/main/java/org/flowable/content/engine/ContentEngineConfiguration.java

Per discussion in the [forum](http://forum.flowable.org/t/mybatis-is-compiled-with-version-6/375), this reverts the previous change.

Moved to new Liquibase version and reverted the schema change

---

modules/flowable5-engine/src/main/java/org/activiti/engine/IdentityService.java

Corrected `@returns` to `@return`.

Correct @return javadoc

---

modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/xml/converter/IndentingXMLStreamWriter.java
modules/flowable5-engine/src/main/java/org/activiti/engine/runtime/JobQuery.java
modules/flowable5-engine/src/main/java/org/activiti/engine/runtime/TimerJobQuery.java
modules/flowable5-engine/src/main/java/org/activiti/engine/task/TaskInfoQuery.java
modules/flowable5-engine/src/main/java/org/activiti/engine/task/TaskQuery.java

Fix occurrences of @deprecated javadoc tag but missing @Deprecated annotation

Add missing @Deprecated annotation

---

modules/flowable-engine/src/test/java/org/flowable/standalone/validation/DefaultProcessValidatorTest.java
modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/ValidatorSetFactory.java
modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/ValidatorSetNames.java
modules/flowable5-test/src/test/java/org/activiti/standalone/validation/DefaultProcessValidatorTest.java

Changed the name of a constant to FLOWABLE_EXECUTABLE_PROCESS.
Ran the flowalble-engine and flowable5-engine tests to validate.

Another rename of a constant

---

modules/flowable-json-converter/src/main/java/org/activiti/editor/language/json/converter/BpmnJsonConverter.java
modules/flowable-json-converter/src/test/java/org/activiti/editor/language/CollapsedSubWithSubSequenceFlowTest.java
modules/flowable-json-converter/src/test/resources/test.cswesfs.json

* now removing sequenceflows from a collapsed subprocess if they assigned to a subprocess.
* added test to verify

Fix for #277

---

modules/flowable-ldap-configurator/src/test/resources/flowable-context-ldap-group-cache.xml
modules/flowable-ldap-configurator/src/test/resources/flowable-context.xml
modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/META-INF/flowable-ui-app/flowable-ui-app.properties
modules/flowable-ui-idm/flowable-ui-idm-conf/src/main/java/org/flowable/app/conf/FlowableIdmEngineConfiguration.java

This change will allow the value of the email attribute in LDAP to be set on the user object.

Add email LDAP attribute

---

modules/flowable-ui-task/flowable-ui-task-app/src/main/webapp/workflow/scripts/workflow-app.js
modules/flowable-ui-task/flowable-ui-task-app/src/main/webapp/workflow/scripts/workflow-directives.js

Fix coment user and change user filter

Fix in comment user and filter in task

---

modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/Activity.java
modules/flowable-engine/src/main/java/org/flowable/engine/debug/ExecutionTreeBfsIterator.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/BusinessRuleTaskActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/UserTaskJsonConverter.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/BusinessRuleTaskActivityBehavior.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java

Change is when calling some method in a loop (e.g. collection.add(x)) replace it with calling a bulk method (e.g. collection.addAll(listOfX).

Use bulk operation instead of interation

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/el/ExpressionManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/el/JuelExpression.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/el/ExpressionManagerTest.java

Enable expression resolving without process context

expression manager without process context

---

modules/flowable-engine/src/test/java/org/flowable/examples/test/MatcherAssert.java
modules/flowable-engine/src/test/java/org/flowable/examples/test/OneTaskProcessTest.java

An example of process driven process testing and semi automatic test generator

Process test example

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable5-compatibility/src/main/java/org/flowable/compatibility/DefaultProcessEngineFactory.java

(cherry picked from commit 861b8cb)

allowing expression manager change for Flowable5

---

docker/config/postgres.yml
modules/flowable-app-rest/src/main/docker/postgres.yml
modules/flowable-dmn-rest/src/main/java/org/flowable/rest/dmn/service/api/repository/DmnDeploymentCollectionResource.java
modules/flowable-form-rest/src/main/java/org/flowable/rest/form/service/api/repository/FormDeploymentCollectionResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/repository/DeploymentCollectionResource.java
modules/flowable-ui-admin/src/main/docker/postgres.yml
modules/flowable-ui-idm/flowable-ui-idm-app/src/main/docker/postgres.yml
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/docker/postgres.yml
modules/flowable-ui-task/flowable-ui-task-app/src/main/docker/postgres.yml

- changed exposed public port postgres to avoid conflicts
- fixed swagger annotations to support file select in swagger ui (for deployments)

Docker postgres exposed port and swagger ui fixes

---

modules/flowable-form-rest/src/main/java/org/flowable/rest/form/service/api/repository/FormDefinitionCollectionResource.java

was mapped to /form-repository/forms should be /form-repository/form-definitions

fixed form-definitions REST resource mapping

---

userguide/src/en/ch17-Advanced.adoc

Stab at improving the issue raised in issue #361.

Attempt to correct issue #361

---

modules/flowable-cxf/src/test/java/org/flowable/engine/impl/webservice/AbstractWebServiceTaskTest.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/cmd/AbstractExecuteDecisionCmd.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/cmd/ExecuteDecisionSingleResultCmd.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/mvel/MvelExecutionContext.java
modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/StandaloneRuntimeTest.java
modules/flowable-dmn-spring/src/test/java/org/flowable/spring/test/junit4/SpringJunit4Test.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/child/OutputValuesParser.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/util/DmnXMLUtil.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/xml/converter/BaseDmnXMLConverter.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/xml/converter/DmnXMLConverter.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/el/AbstractExpressionManager.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CancelCallActivityTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskQueryTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/groovy/GroovyScriptTest.java
modules/flowable-ui-admin/src/main/java/org/flowable/admin/app/rest/client/DeploymentsClientResource.java
modules/flowable-ui-admin/src/main/java/org/flowable/admin/service/engine/DeploymentService.java
modules/flowable-ui-admin/src/main/java/org/flowable/admin/service/engine/FlowableClientService.java
modules/flowable-ui-admin/src/main/java/org/flowable/admin/service/engine/ProcessDefinitionService.java

* Remove unused imports
* Correct missorted modifiers
* Use `try` with resources instead of `try finally`
* Simplified some JUnit assertions
* Removed or commented out some unused code

Small code cleanup

---

eclipse/Preferences-Java-CodeStyle-Formatter.xml
eclipse/Preferences-Java-Editor-Templates.xml
eclipse/h2-server.launch

Made a few changes to the Eclipse preference files.  Most notably product name change and indentation from 2 to 4 spaces.
Note: I don't typically use Eclipse but I think the changes are self evident.

Changes to Eclipse preferences

---

distro/src/notice.txt

Made some minor version changes in notice.txt file.
It appears the file needs a further and more complete review, for example, where is carrotsearch used?
I would also help to label the columns in the table; the last two are obvious but it isn't always clear to me as to the meaning of the first two columns.   I would be happy to update this PR as directed.

Minor version changes

---

modules/flowable-http/src/main/java/org/flowable/http/HttpActivityBehavior.java
modules/flowable-http/src/main/java/org/flowable/http/impl/HttpActivityBehaviorImpl.java
modules/flowable-http/src/test/java/org/flowable/http/HttpExecutionListener.java
modules/flowable-http/src/test/java/org/flowable/http/HttpServiceTaskTest.java
modules/flowable-http/src/test/java/org/flowable/http/HttpServiceTaskTestCase.java
modules/flowable-http/src/test/java/org/flowable/http/HttpServiceTaskTestServer.java
modules/flowable-http/src/test/java/org/flowable/http/cfg/HttpServiceTaskCfgTest.java
modules/flowable-http/src/test/java/org/flowable/http/examples/HttpServiceTaskExampleTest.java
modules/flowable-http/src/test/java/org/flowable/http/validation/HttpServiceTaskValidationTest.java

* Remove unused imports
* Remove unnecessary casts
* Remove unnecessary toStrings()
* Simplify asserts in Junit tests
* Use diamond operator
* Use bulk operand instead of iteration

Code cleanup

---

modules/flowable-mule/pom.xml
pom.xml

This was discussed in this [form post](https://forum.flowable.org/t/spring-version-in-mule-module/633/6).

Upgrade Mule and Spring Mule versions

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CallActivityTest.java

Potential issue in that I do not see ACTIVITY_CANCELLED event when the
parent process is deleted.  I see the ACTIVITY_CANCELLED event for the
user task within the external subprocess and the PROCESS_CANCELLED for the
external subprocess, but not the ACTIVITY_CANCELLED for the call activity.
Included test recreates the issue

Activity cancelled event not received for Call Activity when parent deleted

---

modules/flowable-engine/src/main/resources/org/flowable/db/create/flowable.h2.create.engine.sql

See this [forum post](https://forum.flowable.org/t/adv-handler-cfg-id--column/656l).

Remove extra column in ACT_RU_SUSPENDED_JOB table

---

modules/flowable-app-rest/pom.xml
modules/flowable-ui-task/flowable-ui-task-app/pom.xml

added flowable http dependency to task app

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/child/MultiInstanceParser.java
modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/export/MultiInstanceExport.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/MultiInstanceTaskConverterTest.java
modules/flowable-bpmn-converter/src/test/resources/multiinstancemodel.bpmn

Added a new "collection" extension element of type string as an
alternative to the "collection" attribute so we can support complex
CDATA values.

474 - Multi-instance collection syntax proposal

---

modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/CollapsedSubProcessConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/SubProcessMultiDiagramConverterTest.java
modules/flowable-cdi/src/main/java/org/flowable/cdi/impl/event/CdiExecutionListener.java
modules/flowable-cdi/src/main/java/org/flowable/cdi/impl/event/CdiTaskListener.java
modules/flowable-content-engine/src/main/java/org/flowable/content/engine/ContentEngines.java
modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/engine/test/AbstractFlowableDmnEngineConfiguratorTest.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/DmnEngineConfiguration.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/hitpolicy/HitPolicyUnique.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/test/DmnTestHelper.java
modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/AbstractFlowableDmnTest.java
modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/CustomConfigRuntimeTest.java
modules/flowable-dmn-json-converter/src/main/java/org/flowable/editor/dmn/converter/DmnJsonConverterUtil.java
modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/db/CustomMybatisTypeAliasConfig.java
modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/interceptor/TransactionContextInterceptor.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/helper/ErrorPropagation.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/IdmEngineConfigurator.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/identity/IdentityServiceTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskIdentityLinksTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/v6/AbstractFlowable6Test.java
modules/flowable-form-engine-configurator/src/main/java/org/flowable/form/engine/configurator/FormEngineConfigurator.java
modules/flowable-form-engine-configurator/src/test/java/org/flowable/form/engine/test/AbstractFlowableFormEngineConfiguratorTest.java
modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/IdentityServiceTest.java
modules/flowable-jms-spring-executor/src/main/java/org/flowable/spring/executor/jms/MessageBasedJobManager.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/model/editor/decisiontable/DecisionTableExpressionRepresentation.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/AppDefinitionImportService.java
modules/flowable-ui-task/flowable-ui-task-logic/src/main/java/org/flowable/app/service/runtime/FlowableAppDefinitionService.java
modules/flowable-ui-task/flowable-ui-task-rest/src/main/java/org/flowable/app/rest/runtime/TaskFormResource.java
modules/flowable5-compatibility/src/main/java/org/flowable/compatibility/DefaultFlowable5CompatibilityHandler.java

Usual changes
* unused imports
* dup semi-colons
* use bulk operations
* better Junit method names
* etc.

Misc. code cleanups

---

modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/cfg/standalone/StandaloneMybatisTransactionContext.java
modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/el/FlowableElContext.java
modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/el/ParsingElContext.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/agenda/AgendaSessionFactory.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/context/Context.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/async/AsyncHistorySessionFactory.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/CommandContextUtil.java
modules/flowable-engine/src/main/java/org/flowable/engine/test/profiler/ProfilingDbSqlSessionFactory.java
modules/flowable-form-spring/src/test/java/org/flowable/spring/test/autodeployment/SpringAutoDeployTest.java
modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/impl/util/CommandContextUtil.java

Small changes after recent flurry of pushes
- unused imports
- unnecessary casts
- explicit type can be replaced with <> (I missed one) :(

More janitorial tasks

---

modules/flowable-ldap-configurator/src/main/java/org/flowable/ldap/LDAPConfigurator.java
modules/flowable-ldap-configurator/src/test/resources/flowable-context.xml

The commit148f4f2 introduced a regression in project flowable-ldap-configurator: unit tests fail, and perhaps the LDAP integration is no more working.

[IDM] Fix a regression about LDAP integration

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CallActivityTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CancelCallActivityTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/CancelUserTaskTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/event/CancelUserTaskEventsTest.bpmn20.xml

Added test case for user task cancellation scenario. Also added validation of execution ids for various cancelled event tests.

Activity cancelled testing updates

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/constants/BpmnXMLConstants.java
modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/child/MultiInstanceParser.java
modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/export/MultiInstanceExport.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/MultiInstanceTaskConverterTest.java
modules/flowable-bpmn-converter/src/test/resources/multiinstancemodel.bpmn
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/MultiInstanceLoopCharacteristics.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/parser/handler/AbstractActivityBpmnParseHandler.java
modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/impl/FlowElementValidator.java

Rebased on latest code with PR 506
https://github.com/flowable/flowable-engine/pull/506

512 Multi-instance collection syntax proposal - revised

---

tooling/archetypes/flowable-archetype-unittest/src/main/resources/archetype-resources/src/test/java/MyUnitTest.java
tooling/archetypes/flowable-archetype-unittest/src/main/resources/archetype-resources/src/test/resources/my-process.bpmn20.xml

Originally was just going to change the package name on the Task import but also changed product name in the sample BPMN file.

Fix package name and sample BPMN 

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/constants/BpmnXMLConstants.java
modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/child/FlowableCollectionParser.java
modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/child/MultiInstanceParser.java
modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/export/MultiInstanceExport.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/MultiInstanceTaskConverterTest.java
modules/flowable-bpmn-converter/src/test/resources/multiinstancemodel.bpmn
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/AbstractFlowableCollectionHandler.java
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/FlowableCollectionHandler.java
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/MultiInstanceLoopCharacteristics.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/helper/ClassDelegateCollectionHandler.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/helper/DelegateExpressionCollectionHandler.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/parser/handler/AbstractActivityBpmnParseHandler.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/delegate/FlowableCollectionHandler.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/multiinstance/JSONCollectionHandler.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.testParallelUserTasksCustomCollectionExpressionExtension.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.testParallelUserTasksCustomCollectionExpressionExtensionDelegateExpression.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.testParallelUserTasksCustomCollectionStringExtension.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.testParallelUserTasksCustomCollectionStringExtensionDelegateExpression.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.testParallelUserTasksCustomExtensionsCollection.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.testParallelUserTasksCustomExtensionsCollectionDelegateExpression.bpmn20.xml
modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/Problems.java
modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/impl/FlowElementValidator.java

Updated handler syntax (attribute rather than element) and added class and delegate implementation support as delegate handler classes

520 revised - Add support for revised syntax collectionString parsing function

---

modules/flowable-rest/src/main/java/org/flowable/rest/service/api/repository/DeploymentCollectionResource.java
modules/flowable-ui-admin/src/main/webapp/scripts/app.js
modules/flowable-ui-idm/flowable-ui-idm-app/src/main/webapp/scripts/idm-app.js
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/scripts/app.js
modules/flowable-ui-task/flowable-ui-task-app/src/main/webapp/scripts/landing-app.js
modules/flowable-ui-task/flowable-ui-task-app/src/main/webapp/workflow/scripts/workflow-app.js

* fixes URL query parameter encoding issues when deploying
* fixes AngularJS translate encoding issues

encoding / Chinese character issues

---

modules/flowable-idm-engine/src/main/resources/org/flowable/idm/db/mapping/entity/User.xml

when i use fllowing code,there is a problem with mybaits mapping;
`processEngine.getIdentityService() .createUserQuery().memberOfGroups(groupIds).list()`

--Fixed query with groupIds

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/child/MultiInstanceParser.java
modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/replay/ReplayRunTest.java
modules/flowable-dmn-api/src/main/java/org/flowable/dmn/api/DmnDecisionTableQuery.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/RuleEngineExecutorImpl.java
modules/flowable-dmn-model/src/main/java/org/flowable/dmn/model/BuiltinAggregator.java
modules/flowable-dmn-model/src/main/java/org/flowable/dmn/model/HitPolicy.java
modules/flowable-engine-common-api/src/main/java/org/flowable/engine/common/api/delegate/event/FlowableEngineEvent.java
modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/query/AbstractNativeQuery.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/BoundaryEventActivityBehavior.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/multiinstance/JSONCollectionHandler.java
modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/PasswordEncoderTest.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/DeadLetterJobEntityManager.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/HistoryJobEntityManager.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/JobEntityManager.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/SuspendedJobEntityManager.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/TimerJobEntityManager.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/AbstractNativeQuery.java
modules/flowable-ui-task/flowable-ui-task-logic/src/main/java/org/flowable/app/service/runtime/PermissionService.java
modules/flowable-variable-service/src/main/java/org/flowable/variable/service/delegate/Expression.java
modules/flowable5-engine/src/main/java/org/activiti/engine/delegate/event/impl/ActivitiProcessStartedEventImpl.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/juel/SimpleContext.java

Small changes
* new explicit type can be replaced with <>
* unused import
* import from the same package
* use Collections.singletonList()
* small javadoc fixes

Small code cleanups

---

modules/flowable-job-service/src/main/java/org/flowable/job/service/TimerJobQuery.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/DeadLetterJobQueryImpl.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/HistoryJobQueryImpl.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/JobQueryImpl.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/TimerJobQueryImpl.java
modules/flowable-job-service/src/main/resources/org/flowable/job/db/mapping/entity/Job.xml
modules/flowable-job-service/src/main/resources/org/flowable/job/db/mapping/entity/TimerJob.xml

I have also removed the the old deprecated methods (that are no longer in the API) from the implementations.
See my other comments in #546 as well. There are some other discrepancies in the API

Fix #546 remove obsolete methods from different JobQuery implementations

---

userguide/src/en/ch13-UI.adoc
userguide/src/en/ch17-Advanced.adoc

Spelling corrections

---

modules/flowable-bpmn-converter/src/main/resources/org/flowable/impl/bpmn/parser/flowable-bpmn-extensions-5.18.xsd
modules/flowable-bpmn-converter/src/main/resources/org/flowable/impl/bpmn/parser/flowable-bpmn-extensions-6.0.xsd

Only added it to last version of 5 (5.18) and to 6

565 add customResource syntax to xsd

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/gateway/InclusiveGatewayTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/gateway/InclusiveGatewayTest.testInsideEventSubProcessBug.bpmn20.xml

as asked by @jbarrez  I added a testcase here for issue #582

issue #582 inclusive gateway in a subprocess

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/gateway/ParallelGatewayTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/gateway/ParallelGatewayTest.testNonTerminatingEndEventShouldNotRemoveSubscriptions.bpmn20.xml

issue #587 submit test case for non terminating end evt that removes subs

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java

Annotates the `CmmnEngineConfigurationApi` implementation methods in `CmmnEngineConfiguration`.

Add @Override to interface implementation methods

---

modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/BooleanDataObject.java
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/DateDataObject.java
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/DoubleDataObject.java
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/IntegerDataObject.java
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/LongDataObject.java
modules/flowable-json-converter/src/main/java/org/flowable/editor/constants/StencilConstants.java
modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/BpmnJsonConverterUtil.java
modules/flowable-json-converter/src/test/java/org/flowable/editor/language/ValuedDataObjectConverterTest.java
modules/flowable-json-converter/src/test/resources/test.valueddataobjectmodel.json
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/editor-app/configuration/properties-data-properties-controller.js
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/editor-app/configuration/properties.js
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/editor-app/configuration/properties/data-properties-display-template.html
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/editor-app/configuration/properties/data-properties-popup.html
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/editor-app/configuration/properties/data-properties-write-template.html
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/i18n/en.json
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/index.html
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/ModelImageService.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/resources/stencilset_bpmn.json

Added view and translation elements
Also fixed some conversion errors in model setValue()
https://github.com/flowable/flowable-engine/issues/592

592 Add Data Object support for Modeler

---

modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/editor-app/configuration/toolbar-default-actions.js

Behavior and icon are mismatch for vertical and horizontal alignment tools in BPMN editor toolbar.

Fix vertical and horizontal alignment tools in modeler

---

modules/flowable-spring/src/main/java/org/flowable/spring/SpringProcessEngineConfiguration.java

Allow subclass to add custom AutoDeploymentStrategy, like SpringDmnEngineConfiguration.

Change visibility of deploymentStrategies

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/ParallelMultiInstanceBehavior.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/MultiInstanceUserTaskEventsTest.java

activities due to a condition.

Send ActivityCancelled events when a mult-instance ends with active

---

distro/src/notice.txt
modules/flowable-cmmn-json-converter/pom.xml
modules/flowable-cmmn-json-converter/src/main/java/org/flowable/cmmn/editor/json/converter/CmmnJsonConverter.java
modules/flowable-json-converter/pom.xml
modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/BpmnJsonConverter.java
modules/flowable-json-converter/src/test/java/org/flowable/editor/language/CollapsebleSubprocessTest.java
modules/flowable-json-converter/src/test/java/org/flowable/editor/language/EventSubprocessSequenceFlowTest.java
modules/flowable-json-converter/src/test/java/org/flowable/editor/language/json/converter/BpmnJsonConverterTest.java
pom.xml

removing 
```
<dependency>		
<groupId>math.geom2d</groupId>		
<artifactId>javaGeom</artifactId>		
<version>0.11.1</version>		
</dependency>
```

#701 Remove JavaGeom dependency

---

modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/webapp/scripts/controllers/processes.js

Issue #711: Duplicate process does not work

---

modules/flowable-spring/src/main/java/org/flowable/spring/impl/test/CleanTestExecutionListener.java

Currently the build on travis fails for time to time and is is always the same cause
```
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.995 s <<< FAILURE! - in org.flowable.spring.test.jobexecutor.SpringAsyncExecutorTest
[ERROR] org.flowable.spring.test.jobexecutor.SpringAsyncExecutorTest  Time elapsed: 1.132 s  <<< ERROR!
org.flowable.engine.common.api.FlowableOptimisticLockingException: Execution[ id '29' ] - activity 'boundarytimer1 - parent '26' was updated by another transaction concurrently
at org.flowable.engine.common.impl.db.DbSqlSession.flushUpdates(DbSqlSession.java:501)
at org.flowable.engine.common.impl.db.DbSqlSession.flush(DbSqlSession.java:292)
at org.flowable.engine.common.impl.interceptor.CommandContext.flushSessions(CommandContext.java:193)
at …
```

Try to fix spring async executor test failures on travis

---

modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/app/rest/editor/ModelResource.java

Issue#719: change bpmn name and key does not change process name and identifier

---

docs/userguide/src/en/dmn/ch07-REST.adoc

* endpoint in current documentation was not up to date anymore
* added single result endpoint

corrected DMN REST API rule executions documentation

---

modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/app/rest/editor/ModelsResource.java

Issue#771: Duplicating bpmn name and key does not change duplicated process name and identifier

---

modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/boot/AbstractProcessEngineAutoConfiguration.java

For disable idmEngine and don't create identity tables

For disable idmEngine

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.simpleMultiInstanceWithCollectionVariable.bpmn20.xml

* Display the name of the collection variable when null
* Display the name and value of the collection variable when not a collection
The only thing which I am not sure is whether to actually display the entire `collectionVariable` in the illegal argument exception (it was displayed before already)

Improve error message for collection variable in Multi Instance

---

modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-actuator/pom.xml
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-actuator/src/test/java/org/flowable/test/spring/boot/ActuatorApplicationTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-basic/pom.xml
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-basic/src/test/java/org/flowable/test/spring/boot/BasicApplicationTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-custom-mybatis-mapper/pom.xml
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-custom-mybatis-mapper/src/test/java/org/flowable/test/spring/boot/CustomMyBatisMappersApplicationTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-jpa/pom.xml
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-jpa/src/test/java/org/flowable/test/spring/boot/JpaApplicationTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/pom.xml
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/src/main/java/flowable/Application.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/src/test/java/org/flowable/test/spring/boot/RestApiSecurityApplicationTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/src/test/java/org/flowable/test/spring/boot/SecurityAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api/pom.xml
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api/src/test/java/org/flowable/test/spring/boot/RestApiApplicationTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/pom.xml

This adds actual spring boot tests in the boot samples. By actual I mean using the spring boot infrastructure

Using spring boot test in the boot samples

---

modules/flowable-dmn-spring-configurator/src/main/java/org/flowable/dmn/spring/configurator/SpringDmnEngineConfigurator.java
modules/flowable-dmn-spring/pom.xml
modules/flowable-dmn-spring/src/main/java/org/flowable/dmn/spring/SpringDmnEngineConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-dmn/pom.xml
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-dmn/src/main/java/flowable/DmnSampleApplication.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-dmn/src/main/resources/application.properties
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-dmn/src/test/java/org/flowable/test/spring/boot/dmn/DmnSampleApplicationTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-dmn/src/test/resources/simple.dmn.xml
modules/flowable-spring-boot/flowable-spring-boot-samples/pom.xml
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/pom.xml
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/boot/condition/ConditionalOnDmnEngine.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/boot/dmn/DmnEngineAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/boot/dmn/DmnEngineServicesAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/boot/dmn/FlowableDmnProperties.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/resources/META-INF/spring.factories
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/test/java/org/flowable/test/spring/boot/dmn/DmnEngineAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/test/resources/dmn/risk_rating_spec_example.dmn
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/test/resources/dmn/simple.dmn.xml
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/test/resources/dmn/strings_1.dmn11
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/test/resources/dmn/strings_2.dmn11.xml

Add auto configuration for the Dmn Engine

Add auto configuration for the Dmn Engine

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/IdentityServiceImpl.java
modules/flowable-idm-spring/pom.xml
modules/flowable-idm-spring/src/main/java/org/flowable/idm/spring/SpringIdmEngineConfiguration.java
modules/flowable-idm-spring/src/test/java/org/flowable/spring/test/authentication/SpringPasswordEncoderTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-basic/src/test/java/org/flowable/test/spring/boot/BasicApplicationTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-basic/src/test/java/org/flowable/test/spring/boot/BasicApplicationWithoutIdmOldPropertyTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-basic/src/test/java/org/flowable/test/spring/boot/BasicApplicationWithoutIdmTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/src/test/java/org/flowable/test/spring/boot/SecurityAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api/src/test/java/org/flowable/test/spring/boot/RestApiAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/boot/FlowableProperties.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/boot/ProcessEngineAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/boot/condition/ConditionalOnIdmEngine.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/boot/idm/FlowableIdmProperties.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/boot/idm/IdmEngineAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/java/org/flowable/spring/boot/idm/IdmEngineServicesAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/main/resources/META-INF/spring.factories
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-starter-basic/src/test/java/org/flowable/test/spring/boot/idm/IdmEngineAutoConfigurationTest.java
modules/flowable-spring/src/main/java/org/flowable/spring/configurator/SpringIdmEngineConfigurator.java

Moves the creation of the Idm engine into a separate auto configuration

Add auto configuration for the Idm engine

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/RuntimeServiceTest.java

Propagate process instance deploymentId to the created process instance

Process instance deploymentId

---

modules/flowable-ui-task/flowable-ui-task-app/src/main/webapp/workflow/views/templates/form-element-template.html

Template had validation css classes already on the elements. This caused issues when view was rendered initially.

fixed initial form rendering validation indicators

---

modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/FlowableProperties.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ProcessEngineAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/SecurityAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/cmmn/CmmnEngineAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/cmmn/FlowableCmmnProperties.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/content/ContentEngineAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/content/FlowableContentProperties.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/dmn/DmnEngineAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/dmn/FlowableDmnProperties.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/form/FlowableFormProperties.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/form/FormEngineAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/process/FlowableProcessProperties.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json

Add properties that are used in the apps
Security should only kick in if spring-security is there
UserDetails should be created only if there are none defined

Auto configuration cleanup

---

modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-actuator/src/test/java/org/flowable/test/spring/boot/ActuatorApplicationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/actuate/info/FlowableInfoAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/actuate/info/FlowableInfoContributor.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories

We can add more stuff to the flowable info contributor, currently I can't think of something else

Add Flowable Info contributor displaying the current version of Flowable

---

modules/flowable-app-rest/pom.xml
modules/flowable-cmmn-rest/pom.xml
modules/flowable-common-rest/pom.xml
modules/flowable-content-rest/pom.xml
modules/flowable-dmn-rest/pom.xml
modules/flowable-rest/pom.xml
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/pom.xml
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/src/main/java/flowable/Application.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/src/main/resources/cases/one-task-model.cmmn
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/src/test/java/org/flowable/test/spring/boot/RestApiSecurityApplicationTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api/src/test/java/org/flowable/test/spring/boot/RestApiApplicationTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api/src/test/java/org/flowable/test/spring/boot/RestApiAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/SecurityAutoConfiguration.java

Flowable Security Auto Configuration should not configure an authentication provider

Rest modules should pull spring-security optionally

---

modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/cmd/GetFormInstanceModelCmd.java
modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/cmd/GetFormModelWithVariablesCmd.java
modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/FormInstanceTest.java
modules/flowable-form-engine/src/test/resources/org/flowable/form/engine/test/deployment/hyperlink.form
modules/flowable-ui-task/flowable-ui-task-app/src/main/webapp/workflow/views/templates/form-element-template.html

This update will allow JUEL expressions in hyperlink fields.
See this forum discussion for reference: https://forum.flowable.org/t/hyperlink-form-element-expressions/1506

Support using expressions in hyperlink form field

---

modules/flowable-cmmn-json-converter/src/main/java/org/flowable/cmmn/editor/json/converter/AssociationJsonConverter.java
modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/SentryOnPartAssociationsConverterTest.java
modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/SentryOnPartConverterTest.java
modules/flowable-cmmn-json-converter/src/test/resources/test.SentryOnPartAssociationsModel.json
modules/flowable-cmmn-json-converter/src/test/resources/test.sentryOnPartModel.json

Fix proposal for AssociationJsonConverter
Was not considering "Criterion" as targetRef, only PlanItems

Patch for AssociationJsonConverter

---

modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/persistence/entity/VariableScopeImpl.java

Fix NPE when attempting to retrieving a local transient variable that

---

modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/el/DefaultExpressionManager.java
modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/el/FlowableFunctionMapper.java

enables possibility to add FlowableFunctionMappers on existing parsing context

injectable JUEL function delegates

---

modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api/src/test/java/org/flowable/test/spring/boot/RestApiApplicationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/DispatcherServletConfiguration.java

When we moved the packages in the common rest module we forgot to update the component scan in the spring boot support.
I also added a test that would fail if something like this occurs again.
I am also using the class instead of a string for this

Use correct component scan for the common dispatcher

---

modules/flowable-ui-admin/flowable-ui-admin-app/src/main/resources/static/display/displaymodel.html

Fix diagrams with unknown elements aren't drawn

---

distro/src/notice.txt
modules/flowable-engine/src/test/java/org/flowable/engine/test/db/DatabaseTablePrefixTest.java
pom.xml

1.4.197 contains a lot of fixes and enhancements (more than the last several versions combined), see: http://www.h2database.com/html/changelog.html

Upgrade H2 version to 1.4.197

---

modules/flowable-app-rest/pom.xml
modules/flowable-app-rest/src/main/java/org/flowable/rest/app/FlowableRestApplication.java
modules/flowable-app-rest/src/main/java/org/flowable/rest/app/properties/BackwardsCompatiblePropertiesLoader.java
modules/flowable-app-rest/src/main/resources/META-INF/spring.factories
modules/flowable-app-rest/src/test/java/org/flowable/rest/app/FlowableRestApplicationTest.java
modules/flowable-app-rest/src/test/resources/db.properties
modules/flowable-app-rest/src/test/resources/engine.properties
modules/flowable-ui-admin/flowable-ui-admin-conf/src/main/java/org/flowable/admin/conf/ApplicationConfiguration.java
modules/flowable-ui-common/src/main/java/org/flowable/app/properties/BackwardsCompatiblePropertiesLoader.java
modules/flowable-ui-common/src/main/resources/META-INF/spring.factories
modules/flowable-ui-idm/flowable-ui-idm-app/pom.xml
modules/flowable-ui-idm/flowable-ui-idm-app/src/test/java/org/flowable/app/idm/application/FlowableIdmApplicationTest.java
modules/flowable-ui-idm/flowable-ui-idm-app/src/test/resources/META-INF/flowable-ui-app/flowable-ui-app.properties
modules/flowable-ui-idm/flowable-ui-idm-app/src/test/resources/flowable-ui-app.properties
modules/flowable-ui-idm/flowable-ui-idm-conf/src/main/java/org/flowable/app/conf/ApplicationConfiguration.java
modules/flowable-ui-modeler/flowable-ui-modeler-conf/src/main/java/org/flowable/app/conf/ApplicationConfiguration.java
modules/flowable-ui-task/flowable-ui-task-conf/src/main/java/org/flowable/app/conf/ApplicationConfiguration.java

Make sure that the old property sources are loaded before the spring boot application configuration

---

modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-process/pom.xml

* Updated the depdency of the Spring Boot sample to the new artifactId.

Updated dependency to process starter

---

modules/flowable-ui-admin/flowable-ui-admin-app/pom.xml
modules/flowable-ui-common/pom.xml
modules/flowable-ui-idm/flowable-ui-idm-app/pom.xml
modules/flowable-ui-modeler/flowable-ui-modeler-app/pom.xml
modules/flowable-ui-task/flowable-ui-task-app/pom.xml
pom.xml

removed duplicate slf4j dependencies from UI apps
(this keeps the bootiful colours active ;) )

fixes #983 multiple SLF4J binding warnings

---

modules/flowable-cmmn-spring/src/main/java/org/flowable/cmmn/spring/SpringCmmnExpressionManager.java
modules/flowable-dmn-spring/src/main/java/org/flowable/dmn/spring/SpringDmnExpressionManager.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/de/odysseus/el/util/SimpleResolver.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/el/DefaultExpressionManager.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/javax/el/BeanELResolver.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/javax/el/CouldNotResolvePropertyELResolver.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/scripting/JuelScriptEngine.java
modules/flowable-engine/src/main/java/org/flowable/engine/test/mock/MockExpressionManager.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskServiceTest.java
modules/flowable-form-spring/src/main/java/org/flowable/form/spring/SpringFormExpressionManager.java
modules/flowable-osgi/src/main/java/org/flowable/osgi/blueprint/ProcessEngineFactoryWithELResolver.java
modules/flowable-spring/src/main/java/org/flowable/spring/SpringExpressionManager.java

throw an exception when property is not resolved.

The last ELResolver in to row

---

modules/flowable-app-engine/src/main/java/org/flowable/app/engine/test/FlowableAppTestCase.java
modules/flowable-app-rest/src/main/java/org/flowable/rest/app/properties/BackwardsCompatiblePropertiesLoader.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/FlowableCmmnTestCase.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/el/util/DMNParseUtil.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/db/AbstractSqlScriptBasedDbSchemaManager.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/multiinstance/CounterExecutionListener.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/history/async/AbstractAsyncHistoryJobHandler.java
modules/flowable-ui-common/src/main/java/org/flowable/ui/common/properties/BackwardsCompatiblePropertiesLoader.java
modules/flowable-ui-common/src/main/java/org/flowable/ui/common/tenant/DefaultTenantProvider.java

Use parameterized log messages instead of concatenation

Periodic code cleanups: parameterized logging messages

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/scripting/VariableScopeResolver.java
modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/static/workflow/scripts/controllers/processes.js

Adding HistoryService conditional branch to "public Object get(Object key)" method.

1077 history service missing from variable scope resolver

---

modules/flowable5-compatibility/src/main/java/org/flowable/compatibility/DefaultProcessEngineFactory.java

added copy method to copy all variable types from the flowable 6 config

issue 1065 add copy method for custom variable types

---

modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/static/workflow/scripts/controllers/task.js

Resetting claimButtonDisabled when selectedTask changes

#1073 Claim button remains disabled on all tasks after one task is claimed

---

modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/process/ProcessAsyncHistoryExecutorTest.java

The test is extended to test:
* Explicit enable (as before)
* Explicit disable
* Property not set

Add more tests for the async history Spring Boot configuration

---

modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/fs/FileSystemContentStorage.java
modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/fs/SimpleFileSystemContentStorage.java

FileOutputStream not closed/released, files remained with 0 bytes until VM shutdown

FileOutputStream not closed/released

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/cmd/SaveContentItemCmd.java
modules/flowable-content-engine/src/test/java/org/flowable/content/engine/test/ContentItemTest.java
modules/flowable-content-rest/src/test/java/org/flowable/content/rest/service/api/content/ContentItemResourceTest.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/IdentityLinkEventHandler.java
modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/IdentityLinkServiceConfiguration.java
modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/impl/persistence/entity/IdentityLinkEntityManagerImpl.java

ContentItem lastModified timestamp should be updated always on Save

Update ContentItem lastModified timestamp during save

---

modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/DmnEngineConfiguration.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/el/FlowableAllOfFunctionDelegate.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/el/FlowableAnyOfFunctionDelegate.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/el/FlowableNoneOfFunctionDelegate.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/el/FlowableNotAllOfFunctionDelegate.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/el/util/CollectionUtil.java
modules/flowable-dmn-json-converter/src/main/java/org/flowable/editor/dmn/converter/DmnJsonConverterUtil.java
modules/flowable-dmn-json-converter/src/test/java/org/flowable/editor/dmn/converter/DmnJsonConverterTest.java
modules/flowable-dmn-json-converter/src/test/java/org/flowable/editor/dmn/converter/DmnJsonConverterUtilTest.java
modules/flowable-dmn-json-converter/src/test/resources/org/flowable/editor/dmn/converter/decisiontable_collections_collection_compare.json
modules/flowable-dmn-json-converter/src/test/resources/org/flowable/editor/dmn/converter/decisiontable_collections_collection_input.json
modules/flowable-dmn-json-converter/src/test/resources/org/flowable/editor/dmn/converter/decisiontable_regression_model_v2.json
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/child/InputEntryParser.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/util/DmnXMLUtil.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/CollectionsRegressionTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/ExtensionElementConverterTest.java
modules/flowable-dmn-xml-converter/src/test/resources/collectionsRegression.dmn
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/scripts/controllers/decision-table-editor.js
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/scripts/controllers/decision-table.js
modules/flowable-ui-modeler/flowable-ui-modeler-conf/src/main/java/org/flowable/ui/modeler/conf/Bootstrapper.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/properties/FlowableModelerAppProperties.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/AppDefinitionImportService.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/DecisionTableModelConversionUtil.java
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/FlowableDecisionTableService.java

* changed decision table editor collection related operators
* add DMN built in functions to reflect new operators
* added model migrate logic 
** bootstrapped on start modeler app
** on app import

decision table collection operators

---

modules/flowable-ui-common/src/main/java/org/flowable/ui/common/model/RemoteUser.java
modules/flowable-ui-common/src/main/java/org/flowable/ui/common/service/idm/RemoteIdmServiceImpl.java

Fixes compilation issue by implementing displayName in `RemoteUser`

Use displayName in ui common RemoteUser

---

modules/flowable-dmn-api/src/main/java/org/flowable/dmn/api/DmnRuleService.java
modules/flowable-spring/src/main/java/org/flowable/spring/SpringCallerRunsRejectedJobsHandler.java

Class and method have already been marked as deprecated in the Javadoc

Add missing Deprecated annotation to deprecated components

---

modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/fs/SimpleFileSystemContentStorage.java
modules/flowable-content-engine/src/test/java/org/flowable/content/engine/test/ContentItemTest.java

Ability to store unknown content types to separate folders

#1099 fs content storage

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/InclusiveGatewayActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/test/AbstractFlowableTestCase.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/gateway/InclusiveGatewayTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/gateway/InclusiveGatewayTest.inCalledActivityNestedInMultiInstanceParallelSubProcess.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/gateway/InclusiveGatewayTest.inSubProcessNestedInMultiInstanceParallelSubProcess.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/gateway/InclusiveGatewayTest.insideMultiInstanceParallelSubProcess.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/gateway/InclusiveGatewayTest.insideMultiInstanceSequentialSubProcess.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/gateway/InclusiveGatewayTest.simpleParallelFlow.bpmn20.xml

Inclusive gateway inside parallel multiInstance subProcess not working properly

test cases for inclusive gateway inside multInstance subprocess

---

modules/flowable-cmmn-engine-configurator/src/main/java/org/flowable/cmmn/engine/configurator/CmmnEngineConfigurator.java
modules/flowable-engine-configurator/src/main/java/org/flowable/engine/configurator/ProcessEngineConfigurator.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/app/AppEngineAutoConfigurationTest.java

setting taskId generator to the target engine generator

#1169 task id generator

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/ProcessTaskActivityBehavior.java
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/views/app-definition.html
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/views/popup/app-definition-save-model.html
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/AppDefinitionExportService.java

- Export Case model with process model
- Deploy an app with Case models only
- Support ProcessRef during deployment

Modeler App & cmmn engine : Various fix

---

docs/userguide/src/en/bpmn/ch03-Configuration.adoc
docs/userguide/src/en/bpmn/index-common.adoc

- Add isFireOnTransactionLifecycleEvent and getOnTransaction method to sample code.
- Replace switch statement with if-else
- Add short info about isFireOnTransactionLifecycleEvent and getOnTransaction methods
- Fix typo in index-common.adoc

Update Event Listener implementation section.

---

modules/flowable-app-engine-rest/src/test/java/org/flowable/app/rest/service/BaseSpringRestTestCase.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/BaseSpringRestTestCase.java
modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/test/AbstractContentTestCase.java
modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/test/AbstractFlowableTestCase.java
modules/flowable-content-rest/src/test/java/org/flowable/content/rest/service/api/BaseSpringContentRestTestCase.java
modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/playback/AbstractPlaybackTest.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/test/AbstractDmnTestCase.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/test/AbstractFlowableDmnTestCase.java
modules/flowable-dmn-rest/src/test/java/org/flowable/dmn/rest/service/api/BaseSpringDmnRestTestCase.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/test/AbstractFlowableTestCase.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/test/AbstractTestCase.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/test/TestHelper.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/FlowableEventDispatcherTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/VariableEventsTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/identity/IdentityServiceTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/ProcessInstanceIdentityLinksTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskIdentityLinksTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/StartTimerEventRepeatWithoutEndTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/timer/StartTimerEventRepeatWithoutEndTest.testStartTimerEventRepeatWithoutN.bpmn20.xml
modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/test/AbstractFlowableTestCase.java
modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/test/AbstractTestCase.java
modules/flowable-form-rest/src/test/java/org/flowable/form/rest/service/BaseSpringRestTestCase.java
modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/test/AbstractFlowableIdmTestCase.java
modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/test/AbstractTestCase.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/BaseSpringRestTestCase.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/persistence/entity/TaskEntityManagerImpl.java

Enable tests that have been disabled (by mistake) and replace `AssertionFailedError` from JUnit 3 with `java.lang.AssertionError`

Enable and fix some ignored tests

---

modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/editor-app/configuration/properties/event-listeners-popup.html

Add missing events that exist in FlowableEngineEventType enum

Extend event type list

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/agenda/ContinueProcessOperation.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/dynamic/DefaultDynamicStateManager.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/RuntimeServiceChangeStateTest.java

* Add missing ACTIVITY_CANCELLED events.
* Add missing ACTIVITY_STARTED event when embedded subprocess begins.
* Add missing ACTIVITY_STARTED event when call activity begins.

Fix: Events sent when changing the state of a process.

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/DecisionTaskActivityBehavior.java
modules/flowable-cmmn-json-converter/src/main/java/org/flowable/cmmn/editor/json/converter/ServiceTaskJsonConverter.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/DmnActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/InjectParallelUserTaskCmd.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/dynamic/DynamicSubProcessJoinInjectUtil.java

Redundant check as null returns false

Remove null check before instanceof check

---

modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/caze/HistoricCaseInstanceVariableDataResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/task/HistoricTaskInstanceVariableDataResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/variable/HistoricVariableInstanceDataResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/management/JobExceptionStacktraceResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/caze/CaseInstanceVariableDataResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskIdentityLinkCollectionResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskIdentityLinkResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskVariableDataResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskVariableResource.java
modules/flowable-content-rest/src/main/java/org/flowable/content/rest/service/api/content/ContentItemDataResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/identity/UserInfoResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/management/JobExceptionStacktraceResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/repository/ProcessDefinitionIdentityLinkCollectionResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/repository/ProcessDefinitionIdentityLinkResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/ExecutionVariableDataResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/ExecutionVariableResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/ProcessInstanceVariableDataResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskAttachmentContentResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskAttachmentResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskCommentResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskEventResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskIdentityLinkCollectionResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskIdentityLinkResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskVariableDataResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskVariableResource.java

Remove contractions so the next time the doc is generated there are no issues.  See [PR#1238](https://github.com/flowable/flowable-engine/pull/1238).

Remove contractions

---

modules/flowable-ui-admin/flowable-ui-admin-app/src/main/resources/static/display/bpmn-draw.js
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/DisplayJsonClientResource.java
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/display/bpmn-draw.js
modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/BpmnDisplayJsonConverter.java
modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/static/display/bpmn-draw.js
modules/flowable-ui-task/flowable-ui-task-rest/src/main/java/org/flowable/ui/task/rest/runtime/RuntimeDisplayJsonClientResource.java

In case the model contains a label for a sequence flow, it will be now added to the overview diagram. Furthermore, the label is also visible in the admin and the debug application.

Add the labels to sequence flow elements in BPMN diagram overview

---

modules/flowable-app-engine/src/main/java/org/flowable/app/engine/impl/db/AppDbSchemaManager.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/db/CmmnDbSchemaManager.java
modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/db/ContentDbSchemaManager.java
modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/db/DbSchemaDrop.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/db/DbSchemaDrop.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/db/DmnDbSchemaManager.java
modules/flowable-form-engine/src/main/java/org/flowable/form/engine/FormEngineConfiguration.java
modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/db/DbSchemaDrop.java
modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/db/FormDbSchemaManager.java
modules/flowable-ui-admin/flowable-ui-admin-conf/src/main/java/org/flowable/ui/admin/conf/DatabaseConfiguration.java
modules/flowable-ui-modeler/flowable-ui-modeler-conf/src/main/java/org/flowable/ui/modeler/conf/DatabaseConfiguration.java

No sure if the spring part of the fix (4fab177c76b3c09be50423e81d96a220ccbd76a9) is correct.
Are the `liquibase` beans supposed to be used, or are they just for initialization?

Close database connections used by Liquibase (#950)

---

docker/config/loadbalancer-rest-postgres.yml
docker/config/modeler-task-idm-admin-postgres.yml
docker/config/rest-idm-admin-postgres.yml
modules/flowable-app-rest/src/main/docker/docker-compose.yml
modules/flowable-ui-admin/flowable-ui-admin-app/src/main/docker/docker-compose.yml
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/docker/docker-compose.yml
modules/flowable-ui-task/flowable-ui-task-app/src/main/docker/docker-compose.yml

Replace dots in environment properties with underscore

Update docker compose config files.

---

docs/userguide/src/en/bpmn/ch04-API.adoc
docs/userguide/src/en/bpmn/ch05-Spring.adoc
docs/userguide/src/en/form/ch03-API.adoc
docs/userguide/src/en/form/ch04-Spring.adoc
modules/flowable-form-spring/pom.xml
modules/flowable-form-spring/src/main/java/org/flowable/form/spring/test/FlowableFormSpringExtension.java

Add a FlowableFormSpringExtension for using the Form engine in Spring tests

Add documentation for how to use the Process and Form engines with JUnit Jupiter

---

modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/resources/stencilset_bpmn.json

This change enables the category attribute for the UserTask in the modeler.

BPMN stencilset changed to add the category attribute to the UserTask

---

modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/static/workflow/i18n/zh-CN.json

modify ui-task-app zh-CN.json to Support Chinese language

modify ui-task-app zh-CN.json to Support Chinese language 

---

distro/src/notice.txt
pom.xml

Fixes some CVEs etc., see: https://www.xml.com/news/2018-05-apache-xerces-j-2120/ for details.

Update xercesImpl to version 2.12.0

---

docs/userguide/src/en/bpmn/ch04-API.adoc
docs/userguide/src/en/cmmn/ch03-API.adoc
docs/userguide/src/en/dmn/ch03-API.adoc

This fixes the forum request [https://forum.flowable.org/t/invalid-link-in-docs-website/2650](https://forum.flowable.org/t/invalid-link-in-docs-website/2650).

Correct the link to the JavaDoc

---

modules/flowable-ui-admin/flowable-ui-admin-app/src/main/resources/static/bower_components/sass-bootstrap/getting-started.html

Found another occurrence of 'the' doubled up.

Remove double "the the"

---

modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/FlowableProperties.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ProcessEngineAutoConfiguration.java

I plan to use Chinese fonts, but the default font is Arial

add customize font

---

modules/flowable-image-generator/src/main/java/org/flowable/image/impl/DefaultProcessDiagramCanvas.java
modules/flowable-image-generator/src/main/java/org/flowable/image/impl/DefaultProcessDiagramGenerator.java

ProcessDiagramGenerator should create appropriate symbols for each SubProcess

---

modules/flowable-entitylink-service-api/src/main/java/org/flowable/entitylink/api/history/HistoricEntityLinkService.java
modules/flowable-entitylink-service/src/main/java/org/flowable/entitylink/service/impl/HistoricEntityLinkServiceImpl.java
modules/flowable-entitylink-service/src/main/java/org/flowable/entitylink/service/impl/persistence/entity/HistoricEntityLinkEntityManager.java
modules/flowable-entitylink-service/src/main/java/org/flowable/entitylink/service/impl/persistence/entity/HistoricEntityLinkEntityManagerImpl.java
modules/flowable-entitylink-service/src/main/java/org/flowable/entitylink/service/impl/persistence/entity/data/HistoricEntityLinkDataManager.java
modules/flowable-entitylink-service/src/main/java/org/flowable/entitylink/service/impl/persistence/entity/data/impl/MybatisHistoricEntityLinkDataManager.java
modules/flowable-entitylink-service/src/main/resources/org/flowable/entitylink/service/db/mapping/entity/HistoricEntityLink.xml

Same as `findEntityLinksByReferenceScopeIdAndType`.

Add method `findHistoricEntityLinksByReferenceScopeIdAndType` to HistoricEntityLink

---

modules/flowable-json-converter/src/test/java/org/flowable/editor/language/BoundaryEventAssociationConverterTest.java
modules/flowable-json-converter/src/test/java/org/flowable/editor/language/PoolDataObjectTest.java

Replace import * with enumerated list of files

---

modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/i18n/zh-CN.json

Try this word for a better user experience

Chinese optimization

---

modules/flowable-engine/src/main/resources/org/flowable/db/create/flowable.hsql.create.engine.sql
modules/flowable-engine/src/main/resources/org/flowable/db/upgrade/flowable.hsql.upgradestep.6300.to.6301.engine.sql

Try again...
Add the fix made yesterday to the 6.4.0 branch (issue #1485, PR #1484 )

Add fix for issue #1485.

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/async/json/transformer/MilestoneReachedHistoryJsonTransformer.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/task/CmmnScriptTaskTest.java
modules/flowable5-compatibility-test/src/test/java/org/flowable/compatibility/test/ExpressionInJavaDelegateTest.java
modules/flowable5-compatibility-test/src/test/java/org/flowable/compatibility/test/JavaDelegateTest.java

Replaced packed imports with individual imports
Removed a few unused imports in the process
Ordering of imports per the idea-code-style-configuration.xml config
This took a little longer as the flowable5-compatibility tests took
extra work to verify.

Fix more package import statements

---

docs/userguide/src/en/bpmn/ch04-API.adoc
docs/userguide/src/en/bpmn/ch05a-Spring-Boot.adoc
docs/userguide/src/en/bpmn/ch07b-BPMN-Constructs.adoc
docs/userguide/src/en/bpmn/ch13-Designer.adoc
docs/userguide/src/en/bpmn/ch16-Cdi.adoc
docs/userguide/src/en/cmmn/ch03-API.adoc
docs/userguide/src/en/cmmn/ch04-Spring.adoc
docs/userguide/src/en/cmmn/ch06-cmmn.adoc
docs/userguide/src/en/dmn/ch02-Configuration.adoc

Miscellaneous spelling corrections.

Spelling changes

---

modules/flowable-ui-admin/flowable-ui-admin-app/src/main/resources/static/scripts/form-deployment-controllers.js

[admin ui] form deployment delete undefined fix

---

modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/Sentry.java

Changed:
return TRIGGER_MODE_ON_EVENT.equals(TRIGGER_MODE_ON_EVENT);
to
return TRIGGER_MODE_ON_EVENT.equals(triggerMode);
@jbarrez can you verify this is the correct change?  Thanks

Value on both sides of equals() is the same

---

modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/ValuedDataObject.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CaseInstanceHelperImpl.java
modules/flowable-cmmn-image-generator/src/main/java/org/flowable/cmmn/image/impl/DefaultCaseDiagramCanvas.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/AbstractEngineConfiguration.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/FlowableVersion.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/SequentialMultiInstanceBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/db/ProcessDbSchemaManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/async/AsyncHistoryManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/migration/ProcessInstanceMigrationManagerImpl.java
modules/flowable-image-generator/src/main/java/org/flowable/image/impl/DefaultProcessDiagramCanvas.java
modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/types/JPAEntityMappings.java

Hi. I'm an LGTM developer, and had some time to fix a few alerts flagged in Flowable by our analyses. I mostly focused on alerts flagging possible errors, or which were related to correctness.
There should be one commit per file, and the commit messages have links back to the original alerts to make it easy for you to check what each thing is about.
Let me know if this is helpful or not, what I can do better, or if there are any specific (types of) alerts you're interested in which I can look at in the future.

Fixes for several LGTM alerts

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/CmmnHistoryHelper.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/CaseDefinitionEntityManagerImpl.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/async/AsyncCmmnHistoryTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CaseTaskTest.java

Use shared method to delete historic case instances.

Delete cascade historic case entity links

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskServiceTest.java

ELResolver tests variable update with historic variable update

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/AbstractNeedsCaseInstanceCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/async/AsyncCmmnHistoryManager.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/async/AsyncCmmnHistoryTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/async/AsyncCmmnHistoryTest.createRootEntityLink.cmmn

Missing field for CMMN entity links.

Include hierarchy into CMMN history entity links

---

modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/AbstractConverterTest.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/repository/DmnDeploymentBuilderImpl.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/AbstractConverterTest.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/javax/el/ExpressionFactory.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/ShellActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/repository/DeploymentBuilderImpl.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/repository/ModelQueryTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/repository/RepositoryServiceTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/deployment/ParsedDeploymentTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/AttachmentsBean.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/ModelQueryEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/history/async/AsyncHistoryUpgradeTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/validation/DefaultProcessValidatorTest.java
modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/types/LongJsonType.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/ShellActivityBehavior.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/AbstractJobEntity.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/repository/DeploymentBuilderImpl.java

Use builtin java.nio.charset.StandardCharsets.UTF_8 in
place of character literal.

Use java.nio.charset.StandardCharsets.UTF_8

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/persistence/entity/TaskEntityImpl.java

When calling method in a loop (e.g. collection.add(x))
replace with calling a bulk method (e.g. collection.addAll(listOfX).

Performance: use addAll()

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskQueryTest.java
modules/flowable-task-service-api/src/main/java/org/flowable/task/api/TaskInfoQuery.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/HistoricTaskInstanceQueryImpl.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/TaskQueryImpl.java
modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/HistoricTaskInstance.xml
modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/Task.xml

add querying by formKey

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/async/AsyncHistoryManager.java

Fixes #1637
I have added an overloaded method for `getActivityStart` that takes the *runtimeActivityInstanceId* and finds the activity start object based on that. I have also refactored the common parts to a private method and used a Predicate logic to find the required activity start instance.

Adapt AsyncHistoryManager to use the new runtime ActivityInstance for getting activity start

---

modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/i18n/zh-CN.json

update  Chinese translation file

update translation file

---

modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/validate/CaseWithFormTest.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CaseInstanceHelperImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/StartProcessInstanceCmd.java
modules/flowable-form-engine-configurator/src/test/java/org/flowable/form/engine/test/ProcessWithFormTest.java

allow expression resolving for case/process start forms with NoExecutionVariableScope

allow expression resolving for case/process start forms 

---

modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/editor-app/editor.html
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/scripts/controllers/app-definitions.js
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/scripts/controllers/casemodels.js
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/scripts/controllers/processes.js

Flowable-modeller: Display Description of BPMN Elements as Tooltips

Flowable-modeller: Display Description of BPMN Elements as Tooltips and some bug fix

---

modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/static/i18n/zh-TW.json
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/i18n/zh-TW.json
modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/static/i18n/zh-TW.json
modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/static/workflow/i18n/zh-TW.json

Taiwan, China application has been added to the UI application.

Taiwan, China application has been added to the UI application.

---

docs/userguide/src/en/form/ch03-API.adoc

This is not JUnit 4 but JUnit 5.

Correct the wrong doc description

---

modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/repository/CaseDefinitionImageResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/repository/ProcessDefinitionImageResource.java

This is to address [issue 1599](https://github.com/flowable/flowable-engine/issues/1599).

Set the returned media type on the rest call.

---

modules/flowable-dmn-json-converter/src/test/java/org/flowable/editor/dmn/converter/DmnJsonConverterUtilTest.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/ResetExpiredJobsRunnable.java

Use the correct class
Use parameterized logging

Fix logger statements

---

modules/flowable5-spring-test/pom.xml

flowable5-spring-test: Declare hibernate-core test dependency only once.

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/history/HistoricTaskInstanceTest.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricTaskInstanceBaseResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricTaskInstanceQueryRequest.java
modules/flowable-task-service-api/src/main/java/org/flowable/task/api/TaskQuery.java
modules/flowable-task-service-api/src/main/java/org/flowable/task/api/history/HistoricTaskInstanceQuery.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/HistoricTaskInstanceQueryImpl.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/TaskQueryImpl.java
modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/HistoricTaskInstance.xml
modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/Task.xml

#1824 - Add "withoutDeleteReason" to query for null delete reasons.

---

modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/MapExceptionConverterTest.java
modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/ProcessTaskTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/async/AsyncTaskTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/cfg/ForceCloseMybatisConnectionPoolTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/CmmnHistoryServiceTaskLogTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/HistoricCaseInstanceQueryImplTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/ManualActivationRuleTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CaseInstanceQueryImplTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/EntryCriteriaTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/IfPartTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/PlanItemInstanceTransitionBuilderTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/VariablesTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/sentry/TriggerModeSentryTest.java
modules/flowable-cmmn-json-converter/src/main/java/org/flowable/cmmn/editor/json/converter/HumanTaskJsonConverter.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskVariableCollectionResource.java
modules/flowable-cmmn-spring/src/test/java/org/flowable/spring/test/jupiter/CmmnSpringJunitJupiterTest.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/el/util/DMNParseUtil.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryServiceTaskLogTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/callactivity/CallActivityAdvancedTest.java
modules/flowable-form-engine-configurator/src/test/java/org/flowable/form/engine/test/ProcessWithFormTest.java
modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/cmd/AbstractGetFormInstanceModelCmd.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/AcquireAsyncJobsDueRunnable.java
modules/flowable-json-converter/src/test/java/org/flowable/editor/language/SignalEventAsncConverterTest.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/BaseVariableCollectionResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskVariableCollectionResource.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/src/test/java/org/flowable/test/spring/boot/RestApiSecurityApplicationTest.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/transaction/SpringTransactionAndExceptionsTest.java

Unused imports
Unneeded null tests
Remove redundant condition in if stmt
Removed unused variable declarations
Remove dup semi-colon
Remove unneeded casts
Parameterized log message
etc.

Misc cleanups

---

modules/flowable-idm-rest/src/main/java/org/flowable/idm/rest/service/api/privilege/PrivilegeCollectionResource.java
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/ServerConfigsResource.java
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/AppDeploymentClientResource.java
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/BatchClientResource.java
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/CaseInstanceClientResource.java
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/CmmnDeploymentClientResource.java
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/CmmnJobClientResource.java
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/CmmnTaskClientResource.java
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/DecisionTableDeploymentClientResource.java
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/DeploymentClientResource.java
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/FormDeploymentClientResource.java
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/JobClientResource.java
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/ProcessDefinitionClientResource.java
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/ProcessInstanceClientResource.java
modules/flowable-ui-admin/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/TaskClientResource.java
modules/flowable-ui-idm/flowable-ui-idm-rest/src/main/java/org/flowable/ui/idm/rest/app/IdmGroupsResource.java
modules/flowable-ui-idm/flowable-ui-idm-rest/src/main/java/org/flowable/ui/idm/rest/app/IdmPrivilegesResource.java
modules/flowable-ui-idm/flowable-ui-idm-rest/src/main/java/org/flowable/ui/idm/rest/app/IdmUsersResource.java
modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/api/ApiModelResource.java
modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/app/AppDefinitionResource.java
modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/app/DecisionTableResource.java
modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/app/FormResource.java
modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/app/ModelResource.java
modules/flowable-ui-task/flowable-ui-task-rest/src/main/java/org/flowable/ui/task/rest/runtime/CaseInstanceResource.java
modules/flowable-ui-task/flowable-ui-task-rest/src/main/java/org/flowable/ui/task/rest/runtime/DebuggerResource.java
modules/flowable-ui-task/flowable-ui-task-rest/src/main/java/org/flowable/ui/task/rest/runtime/ProcessInstanceResource.java
modules/flowable-ui-task/flowable-ui-task-rest/src/main/java/org/flowable/ui/task/rest/runtime/RelatedContentResource.java
modules/flowable-ui-task/flowable-ui-task-rest/src/main/java/org/flowable/ui/task/rest/runtime/TaskActionResource.java
modules/flowable-ui-task/flowable-ui-task-rest/src/main/java/org/flowable/ui/task/rest/runtime/TaskResource.java

Specifically:
Replace 'RequestMethod.PUT' with @PutMapping
Replace 'RequestMethod.DELETE' with @DeleteMapping

Replace 'RequestMethod.XXX' with @XXXMapping

---

modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/i18n/zh-CN.json
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/i18n/zh-TW.json

Although "ad hoc" has the meaning of "temporary", it refers to ad hoc network, so it is more appropriate to translate it into "自组网" 子流程.

Some attribute description fixes:临时 to 自组网

---

.github/issue_template.md
.github/pull_request_template.md

These will be displayed when somebody creates an issue or a pull request.
This could improve the quality of submitted issues/pull-requests.
Feel free to suggest changes to the content.

Add github issue and pull request templates.

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/DurationTimeTimerEventTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/InstantTimeTimerEventTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/StartTimerEventRepeatWithEndExpressionTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/jobexecutor/JobExecutorTest.java
modules/flowable-ui-admin/flowable-ui-admin-app/src/main/resources/static/styles/style.css

Flowable-Admin: Fix logo size in navigation bar

---

docs/userguide/src/en/bpmn/ch04-API.adoc
docs/userguide/src/en/cmmn/ch03-API.adoc
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/el/VariableFunctionDelegatesTest.testVariableBase64.cmmn.xml
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/el/VariableFunctionDelegatesTest.testVariableBase64Binary.cmmn.xml
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/el/function/VariableBase64ExpressionFunction.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/el/function/VariableExpressionFunctionsTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/el/function/VariableExpressionFunctionsTest.testVariableBase64.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/el/function/VariableExpressionFunctionsTest.testVariableBase64Binary.bpmn20.xml

* Documentation: YES 
#1919 
Hope this is ok for you.

Base64 Encoding in Expression

---

modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/task/HistoricTaskInstanceBaseResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/caze/BaseCaseInstanceResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskBaseResource.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricTaskInstanceQueryResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/CaseInstanceQueryResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/TaskQueryResourceTest.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricTaskInstanceBaseResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/BaseProcessInstanceResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskBaseResource.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricTaskInstanceQueryResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/ProcessInstanceQueryResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/TaskQueryResourceTest.java

Fixes #1939
* Unit tests:  YES

Allow LIKE_IGNORE_CASE queries of variables

---

docs/userguide/src/en/bpmn/ch05a-Spring-Boot.adoc

Reference doc: https://spring.io/projects/spring-boot

Fix a syntax issue for document

---

distro/src/notice.txt
pom.xml

In case you do not want to update to Jackson `2.10.0` yet.

Update Jackson to version 2.9.10.

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceMigrationBatchTest.java

Remove duplicate semi-colon

---

pom.xml

Update HikariCP to version 3.4.1.

---

distro/src/notice.txt
pom.xml

Update Joda-Time to version 2.10.4.

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetTaskFormModelCmd.java

Fixes: #1743
* Unit tests:  NO

Pull form variables from taskService if task is active

---

modules/flowable-ui-task/flowable-ui-task-conf/pom.xml

Remove duplicated dependencies:
* flowable-content-engine
* spring-boot-configuration-processor

Remove duplicated dependencies

---

modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnXmlConstants.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/ExitCriterionXmlConverter.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/CriteriaExport.java
modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/ExitSentryExtendedAttributesConverterTest.java
modules/flowable-cmmn-converter/src/test/resources/org/flowable/test/cmmn/converter/exitSentryAttributesOnStageAndPlanModel.cmmn
modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/Criterion.java

Adding support to parse and write extended properties like exitType and exitEventType for exit sentries as well as adding those properties to the model.

adding extended properties to exit sentries

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/runtime/PlanItemInstanceState.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/CmmnEngineAgenda.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/DefaultCmmnEngineAgenda.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/AbstractCaseInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/AbstractChangePlanItemInstanceStateOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/AbstractMovePlanItemInstanceToTerminalStateOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/AbstractPlanItemInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/EvaluateCriteriaOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/ExitPlanItemInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/TerminateCaseInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/TerminatePlanItemInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/StageActivityBehavior.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/TerminatePlanItemInstanceCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/AbstractFlowableCmmnTestCase.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CaseCompletionExitSentryTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/PlanItemExitSentryTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/PlanItemNoRepetitionExitSentryTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/StageCompletionExitSentryTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/CaseCompletionExitSentryTest.testCompleteCaseThroughExitSentry.cmmn
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/PlanItemExitSentryTest.multipleTests.cmmn
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/PlanItemNoRepetitionExitSentryTest.multipleTests.cmmn
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/StageCompletionExitSentryTest.testCompleteStageThroughExitSentry.cmmn

Exit sentries with support for exit event type and exit type variations

---

modules/flowable-batch-service-api/src/main/java/org/flowable/batch/api/BatchBuilder.java
modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/export/MapExceptionExport.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/AbstractChildTaskExport.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/SetCaseInstanceBusinessKeyCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/interceptor/DefaultCmmnIdentityLinkInterceptor.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/AutoCompleteEvaluationTest.java
modules/flowable-cmmn-json-converter/src/main/java/org/flowable/cmmn/editor/json/converter/BaseChildTaskCmmnJsonConverter.java
modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/ChildTask.java
modules/flowable-content-engine-configurator/src/test/java/org/flowable/content/engine/configurator/test/TestAttachmentBean.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/DefaultTenantProvider.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/interceptor/DefaultIdentityLinkInterceptor.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/EventSubscriptionUtil.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/servicetask/TestVarargsBean.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricTaskLogEntryQueryRequest.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/BaseHistoricTaskLogEntryBuilderImpl.java

Re-ordered imports in one file also to match standards

Add missing license header

---

distro/src/notice.txt
pom.xml

Update MyBatis to version 3.5.3 and MyBatis-Spring to version 2.0.3.

---

modules/flowable-engine/src/main/java/org/flowable/engine/DynamicBpmnConstants.java
modules/flowable-engine/src/main/java/org/flowable/engine/DynamicBpmnService.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/DynamicBpmnServiceImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/CallActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/parser/factory/DefaultActivityBehaviorFactory.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/callactivity/CallActivityTest.java
modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/callactivity/calledChildProcess.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/callactivity/dynamicallyCalledChildProcess.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/callactivity/processWithDynamicCallActivity.bpmn20.xml

DynamicBpmnService support for changing Call Activity called element.
* Documentation:  NO

Call activity dynamic bpmn service

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/AbstractFlowableCmmnTestCase.java

make assertion function independent of the returned result order

---

modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/static/display/bpmn-draw.js

follows pattern similar to _drawStringDataObject()
Resolves #1997

Create stub methods for other Data Objects

---

.github/actions/scripts/install-jdk.sh
.github/workflows/db2.yml
.github/workflows/java-ea.yml
.github/workflows/main.yml
.github/workflows/mysql.yml
.github/workflows/postgres.yml
.github/workflows/sql-server.yml
modules/flowable-app-engine/src/main/java/org/flowable/app/engine/AppEngineConfiguration.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CaseInstanceQueryImplTest.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/CmmnRestResponseFactory.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/CaseInstanceVariableResourceTest.java
modules/flowable-common-rest/src/main/java/org/flowable/common/rest/variable/InstantRestVariableConverter.java
modules/flowable-dmn-rest/src/main/java/org/flowable/dmn/rest/service/api/DmnRestResponseFactory.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/ExecutionQueryTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/variables/InstantVariableTest.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/RestResponseFactory.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/ProcessInstanceVariableResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/TaskVariablesCollectionResourceTest.java
modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/types/InstantType.java

Additionally add JsonObjectRestVariableConverter for the CmnRestResponseFactory

Add VariableType support for java.time.Instant

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/EvaluateCriteriaOperation.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/MultiEntrySentryActivationTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/MultiEntrySentryActivationTest.testMultiSentryActivation.cmmn

Fixing the evaluation of satisfied on-parts of a sentry on a plan item having multiple sentries with on-parts.

Fix multi sentry multi on part with condition bug

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/impl/CmmnJobTestHelper.java

Added a method to execute the Cmmn Job Executor for a specific time, as it was missing from CmmnJobTestHelper.

Add executeJobExecutorForTime method to CmmnJobTestHelper

---

modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CaseInstanceQueryImplTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/ExecutionQueryTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/authorization/StartAuthorizationTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/ProcessInstanceVariableResourceTest.java

Removed unused imports from recent changes/additions to code
Remove duplicated license header too

More import updates

---

modules/flowable-engine/src/main/java/org/flowable/engine/InternalProcessLocalizationManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/DefaultProcessLocalizationManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/HistoricProcessInstanceQueryImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/ProcessDefinitionQueryImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/ProcessInstanceQueryImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ProcessDefinitionEntity.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ProcessDefinitionEntityImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/repository/DefaultProcessDefinitionLocalizationManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/repository/InternalProcessDefinitionLocalizationManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/repository/ProcessDefinitionQuery.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/repository/ProcessDefinitionQueryTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/repository/LocalizedProcess.bpmn20.xml

Better localization support for process instances and definitions

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/AddIdentityLinkCmd.java

Fix for  #[Jira-1942](https://github.com/flowable/flowable-engine/issues/1942).

Remove dead code (see Jira-1942)

---

modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/ExitSentryConditionWithSentryCombinationTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/ExitSentryConditionWithSentryCombinationTest.testSentryCombination.cmmn

add unit test for entry / exit sentry with condition combination testing

---

distro/src/notice.txt
pom.xml

Update SLF4J to version 1.7.30.

---

modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/ParentCompletionRule.java

Fix missorted modifiers

---

modules/flowable-json-converter/src/test/java/org/flowable/editor/language/MultiInstanceConverterTest.java
modules/flowable-json-converter/src/test/java/org/flowable/editor/language/ThrowCompensationEventTest.java

Fix misordered AssertEquals() arguments

---

docs/docusaurus/docs/bpmn/ch11-History.md
docs/docusaurus/docs/cmmn/ch03-API.md
docs/userguide/src/en/bpmn/ch11-History.adoc
docs/userguide/src/en/cmmn/ch03-API.adoc
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/util/CommandContextUtil.java
modules/flowable-engine/src/main/java/org/flowable/engine/ProcessEngineConfiguration.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/FlowableProperties.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ProcessEngineAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/cmmn/CmmnEngineAutoConfiguration.java

- Adds documentation for History Cleaning in BPMN and CMMN
- Adds Spring auto-configuration properties
- Migrates Configuration from the Impl to the Configuration classes and makes the setters chainable
- Corrects NPE issue with CommandContextUtil.getHistoricEntityLinkService()

History Cleaning Documentation and Spring Integration

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/BpmnXMLConverter.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/PoolsConverterTest.java
modules/flowable-bpmn-converter/src/test/resources/pool-with-extensions.bpmn

resolve #2065 NPE parsing collaboration extension elements

---

distro/src/notice.txt
pom.xml

Update guava to version 28.2

---

modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/persistence/entity/TableDataManagerImpl.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/persistence/entity/TableDataManagerImpl.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/db/DbSqlSession.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/TableDataManagerImpl.java
modules/flowable-event-registry/src/main/java/org/flowable/eventregistry/impl/persistence/entity/TableDataManagerImpl.java
modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/persistence/entity/TableDataManagerImpl.java
modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/impl/persistence/entity/TableDataManagerImpl.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/db/DbSqlSession.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/persistence/entity/TableDataManager.java

Remove leading whitespace in log statements.

---

modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/el/util/CollectionUtil.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/multiinstance/CounterExecutionListener.java

`containsAny()` handles null and add the correct the variable in the null test

Remove unnecessary 'null' check

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/agenda/ExecuteInactiveBehaviorsOperation.java

Use diamond operator (<>) in place of explicit type

---

README.md

Switch from Oracle licensed JDK to a freely usable one

---

distro/src/notice.txt
pom.xml

Update Jackson to version 2.10.2.

---

modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/ProcessTaskTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/HistoricPlanItemInstanceQueryTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/PlanItemInstanceCriterionTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/CaseInstanceVariableResourceTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/callactivity/CallActivityWithElementType.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/ProcessInstanceVariableResourceTest.java

Ran all the tests locally without error.

Simplified/use correct static imports of "assertThat" and "tuple"

---

docs/userguide/src/en/cmmn/ch03-API.adoc
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/PlanItemInjectionTest.java

General description of the new dynamic CMMN service including some examples.

Add documentation for the new dynamic CMMN service

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/delegate/DelegatePlanItemInstance.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/history/HistoricPlanItemInstance.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/history/HistoricPlanItemInstanceQuery.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/runtime/PlanItemInstance.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/runtime/PlanItemInstanceQuery.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/AbstractEvaluationCriteriaOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/CmmnOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/callback/DefaultInternalCmmnJobManager.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/CreateInjectedPlanItemInstanceCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/DefaultCmmnHistoryManager.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/HistoricPlanItemInstanceQueryImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/async/CmmnAsyncHistoryConstants.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/async/json/transformer/AbstractPlanItemInstanceHistoryJsonTransformer.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/HistoricPlanItemInstanceEntity.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/HistoricPlanItemInstanceEntityImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/PlanItemInstanceEntityBuilder.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/PlanItemInstanceEntityBuilderImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/PlanItemInstanceEntityImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/PlanItemInstanceEntityManagerImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/AbstractCmmnDynamicStateManager.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/PlanItemInstanceQueryImpl.java
modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/liquibase/flowable-cmmn-db-changelog-crdb.xml
modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/liquibase/flowable-cmmn-db-changelog.xml
modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/mapping/entity/CaseInstance.xml
modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/mapping/entity/HistoricPlanItemInstance.xml
modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/mapping/entity/PlanItemInstance.xml
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/PlanItemInjectionTest.java

Add derived case definition id property to injected plan item instances

---

pom.xml

Update HikariCP to version 3.4.2.

---

docs/docusaurus/docs/bpmn/ch18-Advanced.md

Adds documentation for LoggingSessions

Add LoggingSession Documentation

---

pom.xml

Update AssertJ to version 3.15.0.

---

modules/flowable-secure-javascript/src/main/java/org/flowable/scripting/secure/SecureJavascriptConfigurator.java
modules/flowable-secure-javascript/src/main/java/org/flowable/scripting/secure/behavior/SecureJavascriptTaskActivityBehavior.java
modules/flowable-secure-javascript/src/main/java/org/flowable/scripting/secure/impl/SecureJavascriptUtil.java
modules/flowable-secure-javascript/src/main/java/org/flowable/scripting/secure/impl/SecureScriptContextFactory.java
modules/flowable-secure-javascript/src/main/java/org/flowable/scripting/secure/impl/SecureScriptScope.java
modules/flowable-secure-javascript/src/test/java/org/flowable/test/scripting/secure/SecureScriptingBaseTest.java
modules/flowable-secure-javascript/src/test/java/org/flowable/test/scripting/secure/SecureScriptingTest.java
modules/flowable-secure-javascript/src/test/resources/test-secure-script-spring-bean-access.bpmn20.xml

Access to beans from Script Tasks with Secure Javascript
discussed [here](https://forum.flowable.org/t/access-to-spring-beans-in-script-task/5209)

Spring beans secure js

---

distro/src/notice.txt
pom.xml

Update java-uuid-generator to version 3.3.0.

---

modules/flowable-content-rest/src/test/java/org/flowable/content/rest/service/api/content/ContentItemResourceTest.java

Replace 'try finally' with 'try' with resources

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/util/PlanItemInstanceContainerUtil.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/RequiredRuleTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/itemcontrol/RequiredRuleTest.repetitiveStageWithRequiredItem.cmmn

make CMMN required items stage scoped

---

modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/async/AsyncCmmnHistoryTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/async/AsyncTaskTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/authorization/StartAuthorizationTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/cfg/ForceCloseMybatisConnectionPoolTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/dynamic/ChangeStateActivateHumanTaskTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/dynamic/ChangeStateEventListenerTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/dynamic/ChangeStateTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/el/CmmnExpressionManagerTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/el/IsStageCompletableExpressionEnhancerTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/el/PlanItemInstancesKeyWordInExpressionsTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/el/VariableComparatorExpressionEnhancerTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/el/VariableEqualsExpressionEnhancerTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/el/VariableExistsExpressionEnhancerTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/el/VariableFunctionDelegatesTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/el/VariableGetExpressionEnhancerTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/el/VariableNotEqualsExpressionEnhancerTest.java

Breaking the changes into groups to make review easier.
Also applied the latest code formatting style.

Use assertj fluent style in flowable-cmmn-engine (part 1)

---

modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-integration/src/test/java/org/flowable/test/spring/boot/IntegrationAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/src/test/java/org/flowable/test/spring/boot/SecurityAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/AllEnginesAutoConfigurationTest.java

Use assertj fluent style in flowable-spring-boot module.

---

modules/flowable-app-engine-spring/pom.xml
modules/flowable-cmmn-engine/pom.xml
modules/flowable-cmmn-json-converter/pom.xml
modules/flowable-cmmn-spring/pom.xml

Given the recent merges to modules using assertj fluent style remove unused dependencies.

Clean up dependencies now that modules use assertj fluent style

---

k8s/flowable/templates/admin.yaml
k8s/flowable/templates/idm.yaml
k8s/flowable/templates/modeler.yaml
k8s/flowable/templates/rest.yaml
k8s/flowable/templates/task.yaml
k8s/flowable/values.yaml

resolves #2177 move credentials to values.yaml

---

modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/BpmnJsonConverter.java
modules/flowable-json-converter/src/test/java/org/flowable/editor/language/AssociationLinkConverterTest.java
modules/flowable-json-converter/src/test/resources/test.association.json

Bug fix in JSON converter for compensation boundary event.

bug fix: JSON converter for boundary compensation event

---

distro/src/notice.txt
pom.xml

Update Groovy to version 2.5.10.

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/mgmt/JobQueryTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/mgmt/ManagementServiceTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/mgmt/TimerJobQueryTest.java

All files in the `org.flowable.engine.test.api.mgmt` package are included.

Use assertj fluent style in flowable-engine.

---

modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/itemcontrol/ManualActivationRuleTest.java

@jbarrez   Matches all other uses in the file.

Use assertThrownBy instead of Assert.fail()

---

modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/ServiceTaskTransientVariableTest.java
modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/CasePageTaskSameDeploymentCmmnXmlConverterTest.java
modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/SimpleDiCmmnXmlConverterTest.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CaseInstanceHelperImpl.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/db/DbSqlSession.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/interceptor/CommandContext.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/DmnActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/TaskHelper.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/gateway/InclusiveGatewayTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/el/ExpressionManagerTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/json/JsonTest.java
modules/flowable-secure-javascript/src/test/java/org/flowable/test/scripting/secure/SecureScriptingBaseTest.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/TaskQueryImpl.java

Remove unused imports

---

modules/flowable-app-engine/src/test/java/org/flowable/app/engine/test/repository/CaseDefinitionQueryTest.java

Remove duplicate semicolon

---

modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/el/util/DMNParseUtil.java
modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/CollectionsContainsTest.java
modules/flowable-dmn-engine/src/test/resources/org/flowable/dmn/engine/test/runtime/contains_IN.dmn
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/scripts/controllers/decision-table-editor.js
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/scripts/controllers/decision-table.js

fixes issues described in; https://forum.flowable.org/t/dmn-modeler-is-in-operator-functionality/5787/2
1) fixes decision table editor validation
2) fixes collection function delegates when using BigInteger as target type

Decision table collection related fixes

---

distro/src/notice.txt
pom.xml

Update MyBatis Spring to version 2.0.4.

---

.github/workflows/java-ea.yml
.github/workflows/main.yml

As discussed in: https://github.com/flowable/flowable-engine/pull/2234

Add Java 14 build.

---

modules/flowable-engine/src/test/java/org/flowable/standalone/calendar/AdvancedCycleBusinessCalendarTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/calendar/CycleBusinessCalendarTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/calendar/DurationBusinessCalendarTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/calendar/DurationHelperTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/cfg/AttachmentQuery.java
modules/flowable-engine/src/test/java/org/flowable/standalone/cfg/CustomMybatisMapperTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/cfg/CustomMybatisXMLMapperTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/deploy/CustomDeploymentCacheTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/deploy/CustomProcessDefinitionInfoCacheTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/deploy/DeploymentCacheLimitTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/el/ExpressionBeanAccessTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/DeploymentQueryEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/ExecutionQueryEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/HistoricActivityInstanceEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/HistoricProcessInstanceQueryEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/HistoricTaskQueryEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/HistoricVariableInstanceEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/JobQueryEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/ModelQueryEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/ProcessDefinitionQueryEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/ProcessInstanceQueryEscapeClauseTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/escapeclause/TaskQueryEscapeClauseTest.java

Various test files in the `org.flowable.standalone` directory.
Specifically test files in the `calendar`, `cfg`, `deploy`, `el`, and `escapeclause` packages.

Use assertj fluent style in flowable-engine module.

---

docs/public-api/references/swagger/cmmn/flowable-swagger-cmmn.yaml
docs/public-api/references/swagger/eventregistry/flowable-swagger-eventregistry.yaml
docs/public-api/references/swagger/process/flowable-swagger-process.yaml

Small swagger doc spelling fixes.

---

modules/flowable-spring/src/test/java/org/flowable/spring/test/autodeployment/DefaultAutoDeploymentStrategyTest.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/autodeployment/ResourceParentFolderAutoDeploymentStrategyTest.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/autodeployment/SingleResourceAutoDeploymentStrategyTest.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/autodeployment/SpringAutoDeployTest.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/email/JndiEmailTest.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/engine/SpringProcessEngineTest.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/eventregistry/EventWithSpringBeanTest.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/executionListener/ExecutionListenerOnTransactionTest.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/executionListener/TransactionDependentExecutionListenerSpringTest.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/expression/SpringLimitedExpressionsTest.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/expression/callactivity/CallActivityBasedOnSpringBeansExpressionTest.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/fieldinjection/ListenerFieldInjectionTest.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/fieldinjection/ServiceTaskFieldInjectionTest.java

Various test files in the `org.flowable.spring.test` directory.
Specifically test files in the `autodeployment`, `email`, `engine`, `eventregistry`, `executionListener`, `expression`, and `fieldinjection` packages.

Use assertj fluent style in flowable-spring module.

---

modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricCaseInstanceCollectionResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricCaseInstanceQueryResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricCaseInstanceResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricMilestoneInstanceResourcesTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricPlanItemInstanceResourcesTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricTaskInstanceCollectionResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricTaskInstanceQueryResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricTaskInstanceResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricVariableInstanceCollectionResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricVariableInstanceQueryResourceTest.java

All test files in the `org.flowable.cmmn.rest.service.api.history` sub-directory.

Use assertj fluent style in flowable-cmmn-rest module.

---

modules/flowable-app-engine-rest/pom.xml
modules/flowable-app-engine-rest/src/test/java/org/flowable/app/rest/service/BaseSpringRestTestCase.java
modules/flowable-app-engine-rest/src/test/java/org/flowable/app/rest/service/api/repository/AppDefinitionResourceTest.java
modules/flowable-app-engine-rest/src/test/java/org/flowable/app/rest/service/api/repository/DeploymentCollectionResourceTest.java
modules/flowable-app-engine-rest/src/test/java/org/flowable/app/rest/service/api/repository/DeploymentResourceResourceTest.java
modules/flowable-app-engine-rest/src/test/java/org/flowable/app/rest/service/api/repository/DeploymentResourceTest.java
modules/flowable-app-engine-rest/src/test/java/org/flowable/app/rest/service/api/repository/DeploymentResourcesResourceTest.java

All test files in the module are updated as needed.

Use assertj fluent style in flowable-app-engine-rest module.

---

modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/AbstractConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/AdhocSubprocessConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/AsyncEndEventConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/BpmnModelWithDataObjectTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/CallActivityConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/CallActivityWithFallbackValueFalseConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/CallActivityWithNoFallbackConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/CaseServiceTaskConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/ChineseConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/CollapsedSubProcessConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/CommaSplitterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/CompleteConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/ConditionalConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/CustomExtensionsConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/CustomNamespaceAttributeConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/DataObjectConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/DataStoreConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/EmptyModelTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/EncodingConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/EscalationConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/EventBasedGatewayConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/EventListenerConverterTest.java

This is parts 1 and 2 of 5 parts.

Use assertj fluent style in flowable-bpmn-converter module. 

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/ExitPlanItemInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/TerminateCaseInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/util/CompletionEvaluationResult.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/util/PlanItemInstanceContainerUtil.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/ExitSentryCompletionExceptionTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/ExitSentryCompletionExceptionTestCase.cmmn

add information about the plan item preventing the case or stage from being completed on an exit sentry with completion semantics within the exception

add information about the plan item preventing the case or stage from completion

---

modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/PoolsConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/ProcessWithCompensationConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/ScopedConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/SendEventServiceTaskConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/SendEventServiceTaskSynchronouslyConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/ServiceTaskConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/ServiceTaskFailedJobRetryTimeCycleConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/ServiceTaskTransientVariableTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/SignalConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/SignalExpressionConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/SimpleConverterTest.java

Use assertj fluent style in flowable-bpmn-converter module.

---

modules/flowable-bpmn-converter/src/main/resources/org/flowable/impl/bpmn/parser/flowable-bpmn-extensions.xsd

Add resultVariableName to flowable-bpmn-extensions.xsd for use with ServiceTask (fixes #2285)

Add resultVariableName to flowable-bpmn-extensions.xsd for use with ServiceTask (fixes #2285)

---

modules/flowable-dmn-spring/src/test/java/org/flowable/spring/test/autodeployment/DefaultAutoDeploymentStrategyTest.java
modules/flowable-dmn-spring/src/test/java/org/flowable/spring/test/autodeployment/ResourceParentFolderAutoDeploymentStrategyTest.java
modules/flowable-dmn-spring/src/test/java/org/flowable/spring/test/autodeployment/SingleResourceAutoDeploymentStrategyTest.java
modules/flowable-dmn-spring/src/test/java/org/flowable/spring/test/autodeployment/SpringAutoDeployTest.java
modules/flowable-dmn-spring/src/test/java/org/flowable/spring/test/el/SpringRuleBeanTest.java
modules/flowable-dmn-spring/src/test/java/org/flowable/spring/test/junit4/SpringJunit4Test.java

The module had a mix of assertion styles.

Use assertj fluent style in flowable-dmn-spring module.

---

modules/flowable-app-rest/src/main/resources/static/docs/index.html

Fixed routes to swagger generated files in Flowable App Rest

---

modules/flowable-rest/src/test/java/org/flowable/rest/api/engine/variable/QueryVariableTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/api/history/HistoricDetailCollectionResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/api/jpa/JpaRestTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/api/runtime/TaskSubTaskCollectionResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/BaseSpringRestTestCase.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/form/FormDataResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricActivityInstanceCollectionResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricActivityInstanceQueryResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricDetailQueryResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricProcessInstanceCollectionResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricProcessInstanceCommentResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricProcessInstanceIdentityLinkCollectionResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/TaskResourceTest.java

The module had a mix of assertion styles.  This is part 1 for this module.

Use assertj fluent style in flowable-rest module.

---

distro/src/notice.txt
pom.xml

Spring Boot to version 2.2.7
Spring Framework to version 5.2.6
Spring Security to version 5.2.4

Update Spring components

---

modules/flowable-event-registry-rest/src/test/java/org/flowable/eventregistry/rest/service/BaseSpringRestTestCase.java
modules/flowable-event-registry-rest/src/test/java/org/flowable/eventregistry/rest/service/api/repository/DeploymentResourceTest.java

Use assertj fluent style in flowable-event-registry-rest module.

---

modules/flowable-secure-javascript/src/test/java/org/flowable/test/scripting/secure/SecureScriptingTest.java

Use assertj fluent style in flowable-secure-javascript module.

---

modules/flowable-form-spring-configurator/src/test/java/org/flowable/form/spring/configurator/test/FormWithSpringBeanTest.java

Just a single test file that had a mix of assertion styles.

Use assertj fluent style in flowable-form-spring-configurator module.

---

modules/flowable-event-registry/src/test/java/org/flowable/eventregistry/test/AbstractFlowableEventTest.java
modules/flowable-event-registry/src/test/java/org/flowable/eventregistry/test/DefaultEventRegistryDataChangeDetectorShutdownTest.java
modules/flowable-event-registry/src/test/java/org/flowable/eventregistry/test/DefaultEventRegistryDataChangeDetectorTest.java
modules/flowable-event-registry/src/test/java/org/flowable/eventregistry/test/DefaultEventRegistryTest.java
modules/flowable-event-registry/src/test/java/org/flowable/eventregistry/test/deployment/DeploymentQueryTest.java
modules/flowable-event-registry/src/test/java/org/flowable/eventregistry/test/deployment/DeploymentTest.java

Made one last pass of all the files after I noticed one file was left undone; just minor cleanups including some formatting and unused import removal.

Use assertj fluent style in flowable-event-registry module.

---

modules/flowable-http/src/test/java/org/flowable/http/cmmn/CmmnHttpTaskTest.java

This was found in the validation steps of another PR that I submitted. 

Fix test to ignore order of entries.

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/migration/CaseInstanceMigrationManager.java
modules/flowable-external-job-rest/src/test/java/org/flowable/external/job/rest/service/ExternalJobBpmnRestSpringBootTest.java
modules/flowable-external-job-rest/src/test/java/org/flowable/external/job/rest/service/ExternalJobCmmnRestSpringBootTest.java
modules/flowable-external-job-rest/src/test/java/org/flowable/external/job/rest/service/ExternalJobRestSpringBootTest.java

Add missing license headers.

---

modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/DbSchemaDrop.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/DisablePlanItemInstanceCmd.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/cmd/GetTableNameCmd.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/agenda/TriggerExecutionOperation.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/GetTableNameCmd.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/jobexecutor/ClearProcessInstanceLocksTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/jobexecutor/RestExpiredTimerJobsTest.java
modules/flowable-external-job-rest/src/test/java/org/flowable/external/job/rest/conf/CmmnEngineTestConfiguration.java
modules/flowable-form-engine/src/main/java/org/flowable/form/engine/impl/cmd/GetTableNameCmd.java
modules/flowable-form-engine/src/test/java/org/flowable/form/engine/test/DeploymentTest.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/AcquireTimerJobsRunnable.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/TimerJobEntityManager.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/TimerJobEntityManagerImpl.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/data/TimerJobDataManager.java

Periodic removal of unused imports.

---

distro/src/notice.txt
pom.xml

Update Spring framework to 5.2.7.

---

modules/flowable-event-registry-rest/src/main/java/org/flowable/eventregistry/rest/service/api/repository/DeploymentCollectionResource.java

fix filename suffix check for event registry

---

modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/AdditionalConverterTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/CollectionsRegressionTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/EmptyExpressionsConverterTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/EmptyOutcomeConverterTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/ExtensionElementConverterTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/ForceDMN11Test.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/MultipleDecisionsConverterTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/SimpleConverterTest.java

Convert tests in `flowable-dmn-xml-converter` module to assertj.

Use assertj fluent style in flowable-dmn-xml-converter module.

---

modules/flowable-cdi/pom.xml
modules/flowable-cdi/src/test/java/org/flowable/cdi/test/api/BusinessProcessBeanTest.java
modules/flowable-cdi/src/test/java/org/flowable/cdi/test/bpmn/SignalEventTest.java
modules/flowable-cdi/src/test/java/org/flowable/cdi/test/impl/context/BusinessProcessContextTest.java
modules/flowable-cdi/src/test/java/org/flowable/cdi/test/impl/context/ThreadContextAssociationTest.java
modules/flowable-cdi/src/test/java/org/flowable/cdi/test/impl/el/ElTest.java
modules/flowable-cdi/src/test/java/org/flowable/cdi/test/impl/event/EventNotificationTest.java
modules/flowable-cdi/src/test/java/org/flowable/cdi/test/impl/event/MultiInstanceServiceTaskEventTest.java
modules/flowable-cdi/src/test/java/org/flowable/cdi/test/impl/event/MultiInstanceTaskCompleteEventTest.java
modules/flowable-cdi/src/test/java/org/flowable/cdi/test/impl/util/ProgrammaticBeanLookupTest.java
modules/flowable-cdi/src/test/java/org/flowable/experimental/ProcessVariablesTest.java

Use assertj fluent style in flowable-cdi module.

---

modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/history/HistoryTest.java
modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/drd/DecisionServiceTest.java

One file had a mix of assertion styles and there was one unused import statement in another.

Update assertj fluent style in flowable-dmn-engine module.

---

modules/flowable-dmn-json-converter/pom.xml
modules/flowable-dmn-json-converter/src/test/java/org/flowable/dmn/editor/converter/DmnJsonConverterTest.java
modules/flowable-dmn-json-converter/src/test/java/org/flowable/dmn/editor/converter/DmnJsonConverterUtilTest.java

For the most part a straightforward conversion of the module to assertj style once the jar was added to the POM.   It just looks big because one of the two java files is rather large.

Use assertj fluent style in flowable-dmn-json-converter module.

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/util/CmmnLoggingSessionUtil.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/BpmnLoggingSessionUtil.java

Issue: https://github.com/flowable/flowable-engine/issues/2458

Ensure scopeDefinitionId is always logged

---

modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/util/VariableLoggingSessionUtil.java

Issue: https://github.com/flowable/flowable-engine/issues/2461

fix logging value of variable with a null value

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/deployer/BpmnDeploymentHelper.java

add process definition key to duplicate process definition key error

---

modules/flowable-dmn-json-converter/src/main/java/org/flowable/dmn/editor/converter/DmnJsonConverter.java
modules/flowable-dmn-json-converter/src/test/java/org/flowable/dmn/editor/converter/DmnJsonConverterTest.java
modules/flowable-dmn-json-converter/src/test/resources/org/flowable/dmn/editor/converter/decisionservice_1_no_decisions.json
modules/flowable-dmn-json-converter/src/test/resources/org/flowable/dmn/editor/converter/decisionservice_1_no_info_reqs.json
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/xml/converter/DMNDIExport.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/xml/converter/DmnDiWaypointXmlConverter.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/xml/converter/DmnXMLConverter.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/DiagramDiEmptyDecisionServiceTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/DiagramDiNoEdgesTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/DiagramDiTest.java
modules/flowable-dmn-xml-converter/src/test/resources/dmndi.dmn
modules/flowable-dmn-xml-converter/src/test/resources/dmndiEmptyDecisionService.dmn
modules/flowable-dmn-xml-converter/src/test/resources/dmndiNoEdges.dmn

* fixed issue with decision service section DI conversion
* fixed issues with empty diagrams

Dev decision service fixes

---

modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/static/i18n/en.json
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/i18n/en.json
modules/flowable-ui-task/flowable-ui-task-frontend/src/main/resources/static/i18n/en.json
modules/flowable-ui-task/flowable-ui-task-frontend/src/main/resources/static/workflow/i18n/en.json

Changes in
- flowable-ui-idm-app
- flowable-ui-modeler-app
- flowable-ui-task-frontend

Various small spelling changes in flowable-ui-* modules

---

modules/flowable-ui/flowable-ui-admin-frontend/src/main/resources/static/admin/i18n/ja-JP.json
modules/flowable-ui/flowable-ui-idm-frontend/src/main/resources/static/idm/i18n/ja-JP.json
modules/flowable-ui/flowable-ui-modeler-frontend/src/main/resources/static/modeler/editor-app/editor/i18n/translation_ja_jp.js
modules/flowable-ui/flowable-ui-modeler-frontend/src/main/resources/static/modeler/editor-app/editor/i18n/translation_signavio_ja_jp.js
modules/flowable-ui/flowable-ui-modeler-frontend/src/main/resources/static/modeler/i18n/ja-JP.json
modules/flowable-ui/flowable-ui-task-frontend/src/main/resources/static/i18n/ja-JP.json
modules/flowable-ui/flowable-ui-task-frontend/src/main/resources/static/workflow/i18n/ja-JP.json

The very first version of Japanese messages

japanese-translation

---

modules/flowable-ui/flowable-ui-modeler-frontend/src/main/resources/static/modeler/i18n/en.json

Remove duplicate key in flowable-ui-modeler-frontend json file

---

modules/flowable-ui/flowable-ui-admin-conf/src/main/java/org/flowable/ui/admin/conf/DispatcherServletConfiguration.java
modules/flowable-ui/flowable-ui-common/src/main/java/org/flowable/ui/common/security/FlowableLoginUrlAuthenticationEntryPoint.java
modules/flowable-ui/flowable-ui-common/src/main/java/org/flowable/ui/common/security/FlowableUiCustomFormLoginConfigurer.java
modules/flowable-ui/flowable-ui-idm-app/src/test/java/org/flowable/ui/idm/application/FlowableIdmApplicationDefaultAuthenticationTest.java
modules/flowable-ui/flowable-ui-idm-logic/src/main/java/org/flowable/ui/idm/model/TokenRepresentation.java
modules/flowable-ui/flowable-ui-modeler-conf/src/main/java/org/flowable/ui/modeler/conf/ModelerBootstrapper.java
modules/flowable-ui/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/app/EditorGroupsResource.java
modules/flowable-ui/flowable-ui-task-conf/src/main/java/org/flowable/ui/task/conf/FlowableTaskDefaultPropertiesEnvironmentPostProcessor.java
modules/flowable-ui/flowable-ui-task-logic/src/main/java/org/flowable/ui/task/service/runtime/FlowableAppDefinitionService.java
modules/flowable-ui/flowable-ui-task-rest/src/main/java/org/flowable/ui/task/rest/runtime/RuntimeDisplayJsonClientResource.java

Remove unused import in `flowable-ui` module.  In the process also expanded a package import and ordered the imports to match project standards.

Remove unused imports in flowable-ui module.

---

modules/flowable-ui/flowable-ui-common/src/main/java/org/flowable/ui/common/security/CustomPersistentRememberMeServices.java

Remove the `if (token != null)` check as it was just done in the previous statement.

Remove redundant null check in flowable-ui module.

---

modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/BpmnDisplayJsonConverter.java
modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/ModelImageService.java

Instead of `Object.class.isInstance` use `instanceof Object` which is more natural and common in the code base.

Use instanceof instead of class.isInstance

---

modules/flowable-cxf/src/test/java/org/flowable/engine/impl/webservice/WebServiceTaskTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/variables/VariablesTest.java
modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/ModelServiceImpl.java

Explicit types can be replaces with <>

---

modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/repository/CaseDefinitionFormDefinitionCollectionResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/caze/CaseInstanceResource.java

correct @ApiOperations annotations: it was wrongly process instead of case

---

modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/HttpServiceTaskWithParallelInSameTransactionConverterTest.java
modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/HttpServiceTaskParallelInSameTransactionConverterTest.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/http/DefaultCmmnHttpActivityDelegate.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/ServiceTaskWithFuturesNoQueueCapacityTest.java
modules/flowable-content-engine/src/main/java/org/flowable/content/engine/test/FlowableContentRule.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/test/FlowableDmnRule.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/scripting/ScriptingEngines.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/http/DefaultBpmnHttpActivityDelegate.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/delegate/invocation/FutureJavaDelegateInvocation.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/callactivity/CallActivityAdvancedTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/error/BoundaryErrorEventTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/cfg/executioncount/VerifyDatabaseOperationsTest.java
modules/flowable-event-registry/src/main/java/org/flowable/eventregistry/test/FlowableEventRule.java
modules/flowable-form-engine/src/main/java/org/flowable/form/engine/test/FlowableFormRule.java
modules/flowable-http-common/src/test/java/org/flowable/http/common/api/HttpHeadersTest.java
modules/flowable-http/src/test/java/org/flowable/http/HttpResponseTest.java
modules/flowable-http/src/test/java/org/flowable/http/cmmn/CmmnHttpTaskTest.java
modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/test/FlowableIdmRule.java
modules/flowable-jms-spring-executor/src/test/java/org/flowable/test/spring/executor/jms/SpringJmsTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/process/ProcessAsyncHistoryExecutorTest.java

Periodic removal of unused imports

---

modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/db/AbstractSqlScriptBasedDbSchemaManager.java

Instead of `try` with `finally` use `try` with resources.

Use try with resources instead of try/finally

---

docs/docusaurus/docs/assets/static/userguide-5/index.html
docs/docusaurus/docs/bpmn/ch07b-BPMN-Constructs.md
docs/docusaurus/docs/bpmn/ch13-Designer.md
docs/docusaurus/docs/bpmn/ch15-REST.md
docs/docusaurus/docs/cmmn/ch08-REST.md
docs/docusaurus/docs/dmn/ch07-REST.md
docs/docusaurus/docs/eventregistry/ch02-Configuration.md
docs/docusaurus/docs/eventregistry/ch07-REST.md
docs/docusaurus/docs/form/ch07-REST.md

- tomcat -> Tomcat
- fix broken link to usage
- also fixed a few other small typos

Fix capitalization and link

---

modules/flowable-http-common/src/main/java/org/flowable/http/common/impl/BaseHttpActivityDelegate.java
modules/flowable-http-common/src/main/java/org/flowable/http/common/impl/apache/ApacheHttpComponentsFlowableHttpClient.java
modules/flowable-http-common/src/main/java/org/flowable/http/common/impl/spring/reactive/SpringWebClientFlowableHttpClient.java
modules/flowable-http/src/test/java/org/flowable/http/bpmn/HttpServiceTaskTest.java
modules/flowable-http/src/test/java/org/flowable/http/bpmn/HttpServiceTaskTestServer.java
modules/flowable-http/src/test/resources/org/flowable/http/bpmn/HttpServiceTaskTest.testHttpPatch2XX.bpmn20.xml

HTTP PATCH support

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/UserTaskXMLConverter.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/util/CommandContextUtil.java
modules/flowable-dmn-json-converter/src/main/java/org/flowable/dmn/editor/converter/DmnJsonConverter.java
modules/flowable-dmn-json-converter/src/test/java/org/flowable/dmn/editor/converter/DmnJsonConverterTest.java
modules/flowable-http/src/test/java/org/flowable/http/bpmn/HttpServiceTaskSpringWebClientTest.java

Periodic import cleanup

---

modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/management/JobBaseResource.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/VariableEventsTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskAndVariablesQueryTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskServiceTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/variables/DataObjectsTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/variables/VariablesTest.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/management/JobBaseResource.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/management/JobCollectionResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/management/JobResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/management/TableDataResourceTest.java

In the process fixed some comments and updated an exception message that was too specific given its usage.

Various unit tests to increase coverage

---

modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/GroupQueryTest.java
modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/PrivilegesTest.java
modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/TokenQueryTest.java
modules/flowable-idm-engine/src/test/java/org/flowable/idm/engine/test/api/identity/UserQueryTest.java

Add additional coverage of methods for IDM engine.

Add test coverage to IDM engine

---

modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/calendar/CronExpression.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/calendar/DurationHelper.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/db/DbSqlSessionFactory.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/de/odysseus/el/misc/TypeConverterImpl.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/lock/LockManagerImpl.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/util/ReflectUtil.java
modules/flowable-engine/src/main/java/org/flowable/engine/delegate/FlowableFutureJavaDelegate.java
modules/flowable-engine/src/main/java/org/flowable/engine/delegate/event/AbstractFlowableEngineEventListener.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ActivityInstanceEntityManagerImpl.java
modules/flowable-event-registry/src/main/java/org/flowable/eventregistry/impl/EventRegistryEngineConfiguration.java
modules/flowable-event-registry/src/main/java/org/flowable/eventregistry/impl/management/DefaultEventRegistryChangeDetectionExecutor.java

code check

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/XMLStreamReaderUtil.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/AbstractServiceTaskExport.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/cmd/GetJobExceptionStacktraceCmd.java
modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/AbstractVariableQueryImpl.java

case add default code blocker

---

modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/de/odysseus/el/misc/TypeConverterImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ActivityInstanceEntityManagerImpl.java

l replace L

---

modules/flowable-app-engine-spring/src/main/java/org/flowable/app/spring/SpringAppEngineConfiguration.java
modules/flowable-app-engine/src/main/java/org/flowable/app/engine/AppEngineConfiguration.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/delegate/FlowablePlanItemFutureJavaDelegate.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
modules/flowable-cmmn-spring/src/main/java/org/flowable/cmmn/spring/SpringCmmnEngineConfiguration.java
modules/flowable-content-engine/src/main/java/org/flowable/content/engine/ContentEngineConfiguration.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/DmnEngineConfiguration.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/ExecuteDecisionBuilderImpl.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/cmd/EvaluateDecisionCmd.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/cmd/ExecuteDecisionServiceCmd.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/eventregistry/MultiTenantBpmnEventRegistryConsumerTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/eventregistry/MultiTenantSendEventTaskTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/eventregistry/SendEventTaskTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/eventregistry/SendInternalEventTaskTest.java
modules/flowable-event-registry-spring/src/main/java/org/flowable/eventregistry/spring/management/DefaultSpringEventRegistryChangeDetectionExecutor.java
modules/flowable-form-engine/src/main/java/org/flowable/form/engine/FormEngineConfiguration.java
modules/flowable-http-common/src/main/java/org/flowable/http/common/api/client/FlowableAsyncHttpClient.java
modules/flowable-http/src/main/java/org/flowable/http/HttpResponse.java
modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/IdmEngineConfiguration.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/JobInfoEntity.java
modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/SendEventTaskJsonConverter.java
modules/flowable-spring/src/main/java/org/flowable/spring/SpringProcessEngineConfiguration.java

Add missing `@Override` annotation to code in the rest of the modules (UI modules done already). Some of the code already had the annotation this PR just finishes off the work.

Add missing @Override to rest of modules

---

modules/flowable-cmmn-json-converter/src/test/java/org/flowable/cmmn/editor/AbstractConverterTest.java
modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/SimpleSimulationRunTest.java
modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/SimulationEventComparatorTest.java
modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/playback/PlaybackRunTest.java
modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/replay/ReplayEventLogTest.java
modules/flowable-crystalball/src/test/java/org/flowable/crystalball/simulator/impl/replay/ReplayRunTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/AdditionalConverterTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/CollectionsRegressionTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/EmptyExpressionsConverterTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/EmptyOutcomeConverterTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/ExtensionElementConverterTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/ForceDMN11Test.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/MultipleDecisionsConverterTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/SimpleConverterTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/AllEnginesAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/FlowableJpaAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/FlowableSecurityAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/FormEngineAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/ProcessAndCmmnEngineAsyncExecutorTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/cmmn/CmmnEngineAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/content/ContentEngineAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/dmn/DmnEngineAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/eventregistry/EventRegistryAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/idm/IdmEngineAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/process/ProcessAsyncHistoryExecutorTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/process/ProcessEngineAutoConfigurationTest.java

Part 2 of conversion from JUnit4 to JUnit5.   One more to come.

Convert JUnit4 to JUnit5

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/ValuedDataObjectXMLConverter.java
modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/child/FlowableMapExceptionParser.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/util/ExpressionUtil.java
modules/flowable-cmmn-image-generator/src/main/java/org/flowable/cmmn/image/impl/DefaultCaseDiagramCanvas.java
modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/ScriptServiceTask.java
modules/flowable-http-common/src/main/java/org/flowable/http/common/impl/ExpressionUtils.java
modules/flowable-image-generator/src/main/java/org/flowable/image/impl/DefaultProcessDiagramCanvas.java
modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/impl/ExternalInvocationTaskValidator.java
modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/impl/SendTaskValidator.java

add equals

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/CmmnManagementService.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/CoreCmmnActivityBehavior.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/CoreCmmnTriggerableActivityBehavior.java
modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/ContentItemQueryProperty.java
modules/flowable-crystalball/src/main/java/org/flowable/crystalball/simulator/SimulationExpressionManager.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/test/FlowableDmnRule.java
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/test/FlowableDmnTest.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/cfg/multitenant/TenantInfoHolder.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/db/DbSqlSession.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/persistence/entity/ByteArrayRef.java
modules/flowable-engine/src/main/java/org/flowable/engine/ManagementService.java
modules/flowable-engine/src/main/java/org/flowable/engine/TaskService.java
modules/flowable-engine/src/main/java/org/flowable/engine/history/HistoricActivityInstanceQuery.java
modules/flowable-engine/src/main/java/org/flowable/engine/history/HistoricDetailQuery.java
modules/flowable-engine/src/main/java/org/flowable/engine/history/HistoricProcessInstanceQuery.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/agenda/DefaultFlowableEngineAgenda.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/HistoryManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/runtime/ExecutionQuery.java
modules/flowable-engine/src/main/java/org/flowable/engine/runtime/ProcessInstanceQuery.java
modules/flowable-event-registry-api/src/main/java/org/flowable/eventregistry/api/ChannelDefinitionQuery.java
modules/flowable-event-registry-api/src/main/java/org/flowable/eventregistry/api/EventDefinitionQuery.java
modules/flowable-event-registry-api/src/main/java/org/flowable/eventregistry/api/EventDeploymentBuilder.java
modules/flowable-event-registry-api/src/main/java/org/flowable/eventregistry/api/EventDeploymentQuery.java
modules/flowable-event-registry/src/main/java/org/flowable/eventregistry/impl/DeploymentQueryProperty.java
modules/flowable-form-api/src/main/java/org/flowable/form/api/FormDefinitionQuery.java
modules/flowable-form-api/src/main/java/org/flowable/form/api/FormDeploymentQuery.java
modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/delegate/event/impl/FlowableIdmEntityEventImpl.java

Attempted to fix the obvious issues.   More to come later once my eyes reset.

Updates to JavaDoc

---

distro/src/notice.txt
pom.xml

Update spring-security to 5.3.5

---

modules/flowable-engine/src/main/java/org/flowable/engine/history/HistoricProcessInstanceQuery.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/agenda/DefaultFlowableEngineAgenda.java
modules/flowable-engine/src/main/java/org/flowable/engine/runtime/ExecutionQuery.java
modules/flowable-engine/src/main/java/org/flowable/engine/runtime/ProcessInstanceQuery.java
modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/ModelImageService.java

One last unused import pass before the release

---

modules/flowable-camel/src/main/java/org/flowable/camel/ExchangeUtils.java
modules/flowable-cdi/src/main/java/org/flowable/cdi/BusinessProcess.java
modules/flowable-cdi/src/main/java/org/flowable/cdi/annotation/BusinessProcessScoped.java
modules/flowable-cdi/src/main/java/org/flowable/cdi/annotation/CompleteTask.java
modules/flowable-cdi/src/main/java/org/flowable/cdi/annotation/ProcessInstanceId.java
modules/flowable-cdi/src/main/java/org/flowable/cdi/annotation/ProcessVariable.java
modules/flowable-cdi/src/main/java/org/flowable/cdi/annotation/StartProcess.java
modules/flowable-cdi/src/main/java/org/flowable/cdi/annotation/TaskId.java
modules/flowable-cdi/src/main/java/org/flowable/cdi/impl/LocalProcessEngineLookup.java
modules/flowable-cdi/src/main/java/org/flowable/cdi/impl/ProcessVariableMap.java
modules/flowable-cdi/src/main/java/org/flowable/cdi/impl/context/ContextAssociationManager.java
modules/flowable-cdi/src/main/java/org/flowable/cdi/impl/context/DefaultContextAssociationManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/parser/FieldDeclaration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/FlowableProperties.java

JavaDoc changes; most from DocLint

---

modules/flowable-app-engine-rest/src/main/java/org/flowable/app/rest/service/api/repository/AppDefinitionResource.java
modules/flowable-app-engine-rest/src/main/java/org/flowable/app/rest/service/api/repository/AppDeploymentCollectionResource.java

Couple of tags in Open API (Swagger) referenced Case / Form when should be App

correct API tags

---

modules/flowable-http-common/src/main/java/org/flowable/http/common/impl/spring/reactive/SpringWebClientFlowableHttpClient.java
modules/flowable-ui/flowable-ui-common/src/main/java/org/flowable/ui/common/security/BasePersistentTokenService.java
modules/flowable-ui/flowable-ui-common/src/main/java/org/flowable/ui/common/security/PersistentTokenService.java

Add missing license headers

---

docker/base-image/Dockerfile
docker/base-image/build.sh
modules/flowable-app-rest/pom.xml
modules/flowable-app-rest/src/main/jib/flowable-entrypoint.sh
modules/flowable-ui/flowable-ui-app/pom.xml
modules/flowable-ui/flowable-ui-app/src/main/jib/flowable-entrypoint.sh
pom.xml

Docker root step down

---

modules/flowable-dmn-image-generator/src/main/java/org/flowable/dmn/image/impl/DefaultDecisionRequirementsDiagramGenerator.java

Definition specification of int array

---

tooling/archetypes/flowable-archetype-unittest/src/main/resources/archetype-resources/pom.xml
tooling/archetypes/flowable-archetype-unittest/src/main/resources/archetype-resources/src/test/java/MyUnitTest.java

Update to more current standards

---

modules/flowable-ui/flowable-ui-modeler-frontend/src/main/resources/static/modeler/i18n/zh-CN.json
modules/flowable-ui/flowable-ui-modeler-frontend/src/main/resources/static/modeler/i18n/zh-TW.json
modules/flowable-ui/flowable-ui-task-frontend/src/main/resources/static/i18n/zh-CN.json
modules/flowable-ui/flowable-ui-task-frontend/src/main/resources/static/i18n/zh-TW.json

fix(i18n): zh-CN,zh-TW Bugs

---

distro/src/notice.txt
pom.xml

Update to Spring 5.2.10.RELEASE

---

modules/flowable-cmmn-engine-configurator/src/test/java/org/flowable/cmmn/test/CaseTaskTest.java

Use more natural assertThatThrownBy

---

modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/planitem/PlanItemInstanceBaseResource.java
modules/flowable-dmn-rest/src/main/java/org/flowable/dmn/rest/service/api/repository/BaseDecisionResource.java

The exception message is attempting to output the id but is using the object that wasn't found and thus null.

Fix exception message text

---

modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/RuleEngineExecutorImpl.java

Move the logging statement after the null check and exception otherwise the logging statement may generate a NPE.

Move logging statement after null test

---

modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/BpmnModel.java
modules/flowable-event-registry/src/main/java/org/flowable/eventregistry/impl/keydetector/JsonFieldBasedInboundEventKeyDetector.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricProcessInstanceIdentityLinkCollectionResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricTaskInstanceIdentityLinkCollectionResourceTest.java
modules/flowable-ui/flowable-ui-task-rest/src/main/java/org/flowable/ui/task/rest/runtime/CaseInstanceDisplayJsonClientResource.java

Remove a few unused class variables.

Remove unused variable

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/AbstractEvaluationCriteriaOperation.java
modules/flowable-ui/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/ProcessDefinitionClientResource.java
modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/DecisionTableModelConversionUtil.java

Logger initialized with foreign class probably as a result of cut-n-paste or refactoring.
Changed to use the class in which the logger is defined.

Logger initialized with foreign class

---

modules/flowable-app-engine-spring/src/test/java/org/flowable/app/spring/test/junit4/SpringAppEngineJunit4Test.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/CaseInstanceCollectionResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/CaseInstanceVariablesCollectionResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/TaskVariablesCollectionResourceTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/compensate/CompensateEventTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/mgmt/ManagementServiceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/ProcessInstanceCollectionResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/TaskVariablesCollectionResourceTest.java

More assert test tweaks including the addition of a missing `@Test` annotation.

More unit test tweaks

---

modules/flowable-event-registry-spring/pom.xml
modules/flowable-jms-spring-executor/pom.xml

Ran the tests locally and they ran as expected.

Make versions of  org.awaitility:awaitility used match (and most current)

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/DeleteRelatedDataOfRemovedHistoricProcessInstancesCmd.java

NullPointerException in DeleteRelatedDataOfRemovedHistoricProcessInstancesCmd

---

modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/MapExceptionConverterTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/SubProcessConverterAutoLayoutTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/util/BpmnXmlConverterTestExtension.java

Remove unused imports in BPMN Converter tests after recent test updates

Remove unused imports in BPMN Converter tests

---

modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/authorization/StartAuthorizationTest.java
pom.xml

I had to update some assertions in order to make test pass with the new version.

Update AssertJ to version 3.18.0.

---

modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/BpmnJsonConverter.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-actuator/src/main/java/flowable/Application.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-app/src/main/java/flowable/AppSampleApplication.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-custom-mybatis-mapper/src/main/java/flowable/Application.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-jpa-all/src/main/java/flowable/Application.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-jpa/src/main/java/flowable/Application.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-process/src/main/java/flowable/Application.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api-security/src/main/java/flowable/Application.java
modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-api/src/main/java/flowable/Application.java
modules/flowable-ui/flowable-ui-admin-logic/src/main/java/org/flowable/ui/admin/service/engine/FlowableClientService.java

Use Java array style instead of C-style declarations

---

modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-rest-1.5.x/pom.xml

All tests ran locally without issue after update.

Update Spring Boot Rest 1.5 sample to latest compatible versions

---

distro/src/notice.txt
pom.xml

Upgrade to Spring 5.2.11.RELEASE

---

modules/flowable-event-registry-spring/pom.xml
modules/flowable-jms-spring-executor/pom.xml

From version 5.15.8 to 5.15.13

Upgrade ActiveMQ Broker jar

---

pom.xml

Upgrade to Spring Boot 2.3.6.RELEASE

---

docs/docusaurus/docs/bpmn/ch15-REST.md
docs/userguide/src/en/bpmn/ch15-REST.adoc

This addresses this reported [issue #2703].

Fix messy table in docs

---

docs/docusaurus/docs/assets/static/userguide-5/index.html
docs/docusaurus/docs/bpmn/ch07b-BPMN-Constructs.md
docs/userguide/src/en/bpmn/ch07b-BPMN-Constructs.adoc
docs/userguide/src/zh_CN/bpmn/ch07b-BPMN-Constructs.adoc

fix link to quartz-scheduler.org cron documentation

---

modules/flowable-job-service/src/main/resources/org/flowable/job/service/db/mapping/entity/Job.xml

Fixes [Issue 2774](https://github.com/flowable/flowable-engine/issues/2774).

Issue 2774: add missing comma

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/CaseInstanceMigrationBatchCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/CaseInstanceMigrationCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/CaseInstanceMigrationValidationCmd.java

Add **tenant** to exception message to make it different than prior exception message defined just above.

Add missing "tenant" to exception message

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/mgmt/ManagementServiceTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/process/ProcessEngineAutoConfigurationTest.java

Chore: remove unused imports in recent pushes

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/DecisionTableVariableManager.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/DecisionTaskActivityBehavior.java
modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/test/runtime/DecisionTaskTest.java
modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/test/runtime/DmnTaskTest.java
modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/bpmn/test/runtime/DmnTaskTest.multipleResults.dmn
modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/bpmn/test/runtime/DmnTaskTest.multipleTablesAsResult.dmn
modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/bpmn/test/runtime/DmnTaskTest.oneDecisionServiceTaskProcess.bpmn20.xml
modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/bpmn/test/runtime/DmnTaskTest.singleResult.dmn
modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/cmmn/test/runtime/DecisionTaskTest.multipleResults.dmn
modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/cmmn/test/runtime/DecisionTaskTest.multipleTablesAsResult.dmn
modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/cmmn/test/runtime/DecisionTaskTest.oneDecisionServiceTaskCase.cmmn
modules/flowable-dmn-engine-configurator/src/test/resources/org/flowable/cmmn/test/runtime/DecisionTaskTest.singleResult.dmn
modules/flowable-dmn-engine/src/main/java/org/flowable/dmn/engine/impl/DmnDecisionServiceImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/DecisionTableVariableManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/DmnActivityBehavior.java

add multiple results property from decision tables to the DecisionTableVariableManager

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/variable/CmmnAggregatedVariableType.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/variable/CmmnAggregation.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/DMNValidation.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/jobexecutor/ParallelMultiInstanceActivityCompletionJobHandler.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/variable/BpmnAggregatedVariableType.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/variable/BpmnAggregation.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/variable/ParallelMultiInstanceLoopVariable.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/variable/ParallelMultiInstanceLoopVariableType.java

Changes as a result of recent merges.

Remove unused imports and add license header

---

distro/src/notice.txt
pom.xml

Update mybatis to version 3.5.6 and mybatis-spring to version 2.0.6.

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoricProcessInstanceQueryTest.java

Changes code that was added December 8, 2020 given JDK > 6.

Chore: explicit type can be replaced with <>

---

modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/async/AsyncNonExclusiveJobsTest.testFiveNonExclusiveParallelJobs.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/async/AsyncNonExclusiveJobsTest.testFiveNonExclusiveParallelJobsThatCreateVariables.bpmn20.xml

I believe this fixes the issue raised here with package renaming;  https://github.com/flowable/flowable-engine/commit/68164a4b47d291de2ab3bdee6c6ecc512547373c#commitcomment-47283047

Adjust package name for SleepServiceTask in xml

---

docs/docusaurus/docs/bpmn/ch18-Advanced.md
docs/userguide/src/en/bpmn/ch18-Advanced.adoc
docs/userguide/src/zh_CN/bpmn/ch17-Advanced.adoc
docs/userguide/src/zh_CN/bpmn/ch18-Advanced.adoc

Per this [comment](https://forum.flowable.org/t/pagination-with-mybatis/7396/3) in the forum, replace `commandContext` with `CommandContextUtil` to match the code and examples.

Use CommandContextUtil instead of commandContext

---

modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-starter/src/test/java/flowable/CustomVariableTypesTestConfiguration.java

Chore: add missing license block

---

distro/src/notice.txt
modules/flowable-event-registry-spring/pom.xml
modules/flowable-jms-spring-executor/pom.xml
pom.xml

See release notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.4.3
I have included the update to Spring Security in this PR and attempted to find and upgrade all dependencies noted in the Release Notes.

Upgrade Spring Boot 2.4.3

---

docker/README.md
docker/config/ui-keycloak-postgres.yml

fix typo of the word `keycloak`

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/UserTaskActivityBehavior.java

refactored execute method; extracted if methods for receiving formKey, name etc. to make it overridable and to implement own handling e.g. for string length

Refactor execute method UserTaskActivityBehavior

---

docs/docusaurus/docs/bpmn/ch15-REST.md

Attempt to fix [Issue 2825](https://github.com/flowable/flowable-engine/issues/2825) re: broken doc links

Issue 2825 fix links to json query varaible format

---

modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/listener/PlanItemLifecycleListenerTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/listener/TaskListenerTest.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/listener/DelegateExpressionTaskListener.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/executionlistener/ExecutionListenerTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/tasklistener/TaskListenerTest.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/JobInfoEntityManager.java

Chore: remove unused imports

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/CmmnHistoryService.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/reactivation/CaseReactivationBuilder.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/CmmnHistoryServiceImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/ReactivateHistoricCaseInstanceCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/parser/handler/ReactivateEventListenerParseHandler.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/reactivation/CaseReactivationBuilderImpl.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/reactivation/SimpleCaseReactivationTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/reactivation/Reactivation_Test_Case.cmmn.xml

Refactoring to use a case reactivation builder instead of a single reactivation method for easier options like variables.

Case reactivation builder

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/reactivation/CaseReactivationBuilder.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/reactivation/CaseReactivationBuilderImpl.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/reactivation/SimpleCaseReactivationTest.java

Rename the variable methods on the reactivation builder to be in sync with other builders.

rename the variable methods on the reactivation builder

---

modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnXmlConstants.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/ExtensionElementsXMLConverter.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/PlanItemControlExport.java
modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/ReactivationRuleConverterTest.java
modules/flowable-cmmn-converter/src/test/resources/org/flowable/test/cmmn/converter/stage-reactivation-test-case.cmmn
modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/PlanItemControl.java
modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/PlanItemRule.java
modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/ReactivationRule.java

Implement parsing / exporting and importing of the new reactivation rule.

Reactivation rule converter

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/history/HistoricCaseInstance.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/history/HistoricCaseInstanceQuery.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/runtime/CaseInstance.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/runtime/CaseInstanceQuery.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/PlanItemControlExport.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/AbstractEvaluationCriteriaOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/ReactivateHistoricCaseInstanceCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/DefaultCmmnHistoryManager.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/HistoricCaseInstanceQueryImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/async/AsyncCmmnHistoryManager.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/async/CmmnAsyncHistoryConstants.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/async/json/transformer/CaseInstanceReactivateHistoryJsonTransformer.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/interceptor/DefaultCmmnIdentityLinkInterceptor.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/CaseInstanceEntity.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/CaseInstanceEntityImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/HistoricCaseInstanceEntity.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/HistoricCaseInstanceEntityImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CaseInstanceHelperImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CaseInstanceQueryImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/interceptor/CmmnIdentityLinkInterceptor.java
modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/liquibase/flowable-cmmn-db-changelog-crdb.xml
modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/liquibase/flowable-cmmn-db-changelog.xml
modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/mapping/entity/CaseInstance.xml
modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/mapping/entity/HistoricCaseInstance.xml
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/reactivation/SimpleCaseReactivationTest.java
modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/PlanItemRule.java
modules/flowable-identitylink-service-api/src/main/java/org/flowable/identitylink/api/IdentityLinkType.java
modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/impl/persistence/entity/data/impl/MybatisIdentityLinkDataManager.java

Add reactivation data like last reactivation time and user to both the runtime and history of case instances.

Add reactivation data to case instance

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/history/HistoricCaseInstanceQuery.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/interceptor/DefaultCmmnIdentityLinkInterceptor.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CaseInstanceHelperImpl.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/reactivation/SimpleCaseReactivationTest.java
modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/IdentityLinkService.java
modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/impl/IdentityLinkServiceImpl.java
modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/impl/persistence/entity/IdentityLinkEntityImpl.java
modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/impl/persistence/entity/IdentityLinkEntityManager.java
modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/impl/persistence/entity/IdentityLinkEntityManagerImpl.java
modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/impl/persistence/entity/data/IdentityLinkDataManager.java
modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/impl/persistence/entity/data/impl/MybatisIdentityLinkDataManager.java

Copy identity links back from history to runtime on case reactivation.

Reactivate identity links on case reactivation

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/AbstractMovePlanItemInstanceToTerminalStateOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/CompleteCaseInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/CompletePlanItemInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/ExitPlanItemInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/TerminateCaseInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/OnParentEndDependantActivityBehavior.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/CasePageTaskActivityBehaviour.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CasePageTaskTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/PropagatedCasePageEndingStateTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/Case_Page_Ending_State_Test_Case.cmmn.xml

fixing and testing bug where case page items don't get ended the same way for a stage or the plan model

Parent end dependant activity behavior

---

modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnXmlConstants.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/ExtensionElementsXMLConverter.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/GenericEventListenerXmlConverter.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/PlanItemControlExport.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/PlanItemDefinitionExport.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/ReactivationEventListenerExport.java
modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/ReactivationRuleConverterTest.java
modules/flowable-cmmn-converter/src/test/resources/org/flowable/test/cmmn/converter/stage-reactivation-test-case.cmmn
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/CmmnEngineAgenda.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/DefaultCmmnEngineAgenda.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/CmmnOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/InitStageInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/PlanItemCreationType.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/ReactivateCaseInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/ReactivatePlanModelInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/function/IsPlanItemCompletedExpressionFunction.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/reactivation/StageReactivationTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/reactivation/Reactivation_Test_Case.cmmn.xml
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/reactivation/Simple_Reactivation_Test_Case.cmmn.xml
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/reactivation/Stage_Reactivation_Test_Case.cmmn.xml
modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/ReactivateEventListener.java
modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/ReactivationRule.java

Recreate plan items according their reactivation rules and evaluate after that stage of reactivation to continue the case execution.

Case reactivation phase 2 implementation

---

docker/base-image/Dockerfile
modules/flowable-ui/flowable-ui-app/pom.xml
modules/flowable-ui/flowable-ui-app/src/main/jib/flowable-entrypoint.sh

The changes are to allow image to run on Openshift container platform

flowable entrypoint script and permission changes

---

docs/userguide/src/zh_CN/bpmn/ch12-IDM.adoc
docs/userguide/src/zh_CN/bpmn/ch19-tooling.adoc

jmx ldap describe

---

modules/flowable-cxf/src/main/java/org/flowable/engine/impl/webservice/WSDLImporter.java

The motivation for the fix can be found in [Issue 2907](https://github.com/flowable/flowable-engine/issues/2907).

Fix for Issue 2907

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/DefaultHistoryManager.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/ChangeHistoryLevelTest.java

#2953 History level change NONE -> ACTIVITY causes NPE

---

modules/flowable-cxf/src/test/java/org/flowable/engine/impl/webservice/WebServiceMock.java
modules/flowable-cxf/src/test/java/org/flowable/engine/impl/webservice/WebServiceMockImpl.java
modules/flowable-cxf/src/test/java/org/flowable/engine/impl/webservice/WebServiceTaskTest.java
modules/flowable-cxf/src/test/java/org/flowable/engine/impl/webservice/wrappers/ReturnsSeveralParams.java
modules/flowable-cxf/src/test/java/org/flowable/engine/impl/webservice/wrappers/ReturnsSeveralParamsResponse.java
modules/flowable-cxf/src/test/resources/org/flowable/engine/impl/webservice/WebServiceTaskTest.testWebServiceInvocationReturningSeveralParams.bpmn20.xml
modules/flowable-cxf/src/test/resources/org/flowable/engine/impl/webservice/webservicemock.wsdl
modules/flowable-engine/src/main/java/org/flowable/engine/impl/webservice/WSOperation.java

Hi team Flowable,
Please find here the fix of issue #2871

issue #2871: error on ws invocation with 3 or more output parameters

---

modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/Task.xml

Issue #2966: ibatis ReflectionException when calling CmmnTaskService.saveTask()

---

docs/userguide/src/en/cmmn/ch06-cmmn.adoc

adding documentation about case reactivation support in CMMN

---

modules/flowable-engine/src/test/java/org/flowable/standalone/validation/CustomServiceTaskProcessValidatorTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/validation/customServiceTaskProcess.bpmn20.xml
modules/flowable-process-validation/src/main/java/org/flowable/validation/ProcessValidatorFactory.java
modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/ValidatorSetFactory.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java

add support for pluggable ServiceTaskValidator

---

modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/ServiceTask.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-engine/src/test/java/org/flowable/standalone/validation/CustomServiceTaskProcessValidatorTest.java
modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/ValidatorSetFactory.java
modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/impl/ServiceTaskValidator.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java

changes were applied to version 5 not the current engine configuration

fixed modification of wrong engine configuration

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/constants/BpmnXMLConstants.java
modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/child/MultiInstanceParser.java
modules/flowable-bpmn-converter/src/main/resources/org/flowable/impl/bpmn/parser/flowable-bpmn-extensions.xsd
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/MultiInstanceLoopCharacteristics.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/agenda/EndExecutionOperation.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/ParallelMultiInstanceBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/jobexecutor/ParallelMultiInstanceWithNoWaitStatesAsyncLeaveJobHandler.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/data/ExecutionDataManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/data/impl/MybatisExecutionDataManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/test/AbstractFlowableTestCase.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/ExecutionGraphUtil.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/variable/ParallelMultiInstanceLoopVariableType.java
modules/flowable-engine/src/main/resources/org/flowable/db/mapping/entity/Execution.xml
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceNoWaitStatesTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceNoWaitStatesTest.allServiceTasksProcess.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceNoWaitStatesTest.testNestedParallelAsyncAndExclusiveCallActivity.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceNoWaitStatesTest.testNestedParallelAsyncAndExclusiveSubProcess.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceNoWaitStatesTest.testParallelAsyncAndExclusiveServiceTasks.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceNoWaitStatesTest.testParallelAsyncAndExclusiveServiceTasksWithBoundaryEvent.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceNoWaitStatesTest.testParallelAsyncAndExclusiveServiceTasksWithBoundaryEventFiring.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceNoWaitStatesTest.testParallelAsyncAndExclusiveSubProcess.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceTest.testParallelAsyncServiceTasks.bpmn20.xml
modules/flowable-job-service/src/main/java/org/flowable/job/service/JobService.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/JobServiceImpl.java

Add support for 'noWaitStatesAsyncLeave' flag for MI

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/ReactivateHistoricCaseInstanceCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/parser/handler/ReactivateEventListenerParseHandler.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/reactivation/CaseReactivateEventListenerAvailableConditionTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/reactivation/Case_Reactivation_Condition_Test.cmmn.xml
modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/ReactivateEventListener.java

Support CMMN reactivate event listener available condition

---

k8s/flowable/templates/ui.yaml

Use postgres image variable for init container

---

modules/flowable-app-engine-rest/src/main/java/org/flowable/app/rest/service/api/repository/AppDeploymentResourceResource.java
modules/flowable-common-rest/src/main/java/org/flowable/common/rest/resolver/DefaultContentTypeResolver.java

resolves #3003 form content type

---

modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/util/BpmnEventModelUtil.java

Create Event Model should add the payload params whether the send event task is triggable or not

Minor Fix to Modeler - Create Event Model Logic

---

k8s/README.md
k8s/flowable/Chart.yaml
k8s/flowable/README.md
k8s/flowable/requirements.yaml
k8s/flowable/templates/_helpers.tpl
k8s/flowable/templates/ingress.yaml
k8s/flowable/values.yaml

implemented changes for: 
* Kubernetes v1.16+
* Helm 3
changes:
* removed Chart dependency on nginx-ingress

Upgrade Helm chart 

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/repository/CmmnDeploymentBuilder.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/repository/CmmnDeploymentBuilderImpl.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/repository/DeploymentCollectionResource.java

#2758 Documentation says it is possible to POST a zip file to cmmn-repository/deployments endpoint but the CMMN REST API does not allow that. 

Added the posibility to deploy zip or bar files for CMMN engine

---

modules/flowable-engine/src/main/resources/org/flowable/db/mapping/entity/HistoricActivityInstance.xml
modules/flowable-engine/src/main/resources/org/flowable/db/mapping/entity/HistoricDetail.xml
modules/flowable-identitylink-service/src/main/resources/org/flowable/identitylink/service/db/mapping/entity/HistoricIdentityLink.xml
modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/HistoricTaskInstance.xml
modules/flowable-variable-service/src/main/resources/org/flowable/variable/service/db/mapping/entity/HistoricVariableInstance.xml

Fixes various bulk delete operations to work with 'hsql' (http://www.hsqldb.org) database

support for hsql in bulk delete operations

---

modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/task/HistoricTaskInstanceBaseResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/task/HistoricTaskInstanceCollectionResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/task/HistoricTaskInstanceQueryRequest.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskBaseResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskCollectionResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskQueryRequest.java

Add includeProcessVariables in CMMN rest api

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CmmnRuntimeServiceImpl.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/StageTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/StageTest.testForceComplete.cmmn

Fix stage force complete

---

modules/flowable5-spring-test/src/test/java/org/activiti/spring/test/jpa/LoanRequest.java

remove import *

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/deployer/CmmnDeployer.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/util/CmmnCorrelationUtil.java

Periodic check found a few instances

Unused imports in recent pushes

---

modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/HitPolicyOutputOrderTest.java
modules/flowable-dmn-engine/src/test/resources/org/flowable/dmn/engine/test/runtime/HitPolicyOutputOrderTest.outputOrderHitPolicyBoolean.dmn
modules/flowable-dmn-engine/src/test/resources/org/flowable/dmn/engine/test/runtime/HitPolicyOutputOrderTest.outputOrderHitPolicyDate.dmn
modules/flowable-dmn-engine/src/test/resources/org/flowable/dmn/engine/test/runtime/HitPolicyOutputOrderTest.outputOrderHitPolicyNumber.dmn
modules/flowable-dmn-engine/src/test/resources/org/flowable/dmn/engine/test/runtime/HitPolicyOutputOrderTest.outputOrderHitPolicyNumberAsString.dmn
modules/flowable-dmn-json-converter/src/main/java/org/flowable/dmn/editor/converter/DmnJsonConverter.java
modules/flowable-dmn-json-converter/src/test/java/org/flowable/dmn/editor/converter/DmnJsonConverterTest.java
modules/flowable-dmn-json-converter/src/test/resources/org/flowable/dmn/editor/converter/decisiontable_entries.json
modules/flowable-dmn-model/src/main/java/org/flowable/dmn/model/UnaryTests.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/child/BaseChildElementParser.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/child/InputValuesParser.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/child/OutputValuesParser.java
modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/util/DmnXMLUtil.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/AdditionalConverterTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/OutputValuesParserTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/SimpleConverterTest.java
modules/flowable-dmn-xml-converter/src/test/resources/simple.dmn

* added missing input values to DMN XML converter
* fixed input output values formatting to avoid 'surrounded quotes' in all cases
* added missing input / output values to DMN JSON converter
* added additional unit tests

Dev dmn converter output values

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/data/impl/MybatisHistoricDetailDataManager.java
modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/persistence/entity/data/impl/MybatisHistoricVariableInstanceDataManager.java

Remove imports no longer needed after [PR 3076](https://github.com/flowable/flowable-engine/pull/3076)

Remove unused imports introduced in PR 3076

---

modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/caze/HistoricCaseInstanceBaseResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/caze/HistoricCaseInstanceCollectionResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/caze/HistoricCaseInstanceQueryRequest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricCaseInstanceCollectionResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricCaseInstanceQueryResourceTest.java

Extend case history instance query

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/mgmt/ExternalWorkerJobQueryTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/mgmt/JobQueryTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/mgmt/TimerJobQueryTest.java
modules/flowable-job-service-api/src/main/java/org/flowable/job/api/BaseJobQuery.java
modules/flowable-job-service-api/src/main/java/org/flowable/job/api/DeadLetterJobQuery.java
modules/flowable-job-service-api/src/main/java/org/flowable/job/api/ExternalWorkerJobQuery.java
modules/flowable-job-service-api/src/main/java/org/flowable/job/api/HistoryJobQuery.java
modules/flowable-job-service-api/src/main/java/org/flowable/job/api/JobQuery.java
modules/flowable-job-service-api/src/main/java/org/flowable/job/api/SuspendedJobQuery.java
modules/flowable-job-service-api/src/main/java/org/flowable/job/api/TimerJobQuery.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/DeadLetterJobQueryImpl.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/ExternalWorkerJobQueryImpl.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/HistoryJobQueryImpl.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/JobQueryImpl.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/SuspendedJobQueryImpl.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/TimerJobQueryImpl.java
modules/flowable-job-service/src/main/resources/org/flowable/job/service/db/mapping/entity/DeadLetterJob.xml
modules/flowable-job-service/src/main/resources/org/flowable/job/service/db/mapping/entity/ExternalWorkerJob.xml
modules/flowable-job-service/src/main/resources/org/flowable/job/service/db/mapping/entity/HistoryJob.xml
modules/flowable-job-service/src/main/resources/org/flowable/job/service/db/mapping/entity/Job.xml
modules/flowable-job-service/src/main/resources/org/flowable/job/service/db/mapping/entity/SuspendedJob.xml
modules/flowable-job-service/src/main/resources/org/flowable/job/service/db/mapping/entity/TimerJob.xml

Extend job handler type query

---

modules/flowable-app-rest/src/test/java/org/flowable/rest/app/FlowableRestApplicationTest.java
modules/flowable-ui/flowable-ui-app/src/test/java/org/flowable/ui/application/FlowableUiApplicationTest.java
modules/flowable-ui/flowable-ui-app/src/test/java/org/flowable/ui/application/FlowableUiApplicationWithEnabledJmsKafkaAndRabbitTest.java
modules/flowable-ui/flowable-ui-app/src/test/java/org/flowable/ui/application/FlowableUiApplicationWithEnabledJmsTest.java
modules/flowable-ui/flowable-ui-app/src/test/java/org/flowable/ui/application/FlowableUiApplicationWithEnabledKafkaTest.java
modules/flowable-ui/flowable-ui-app/src/test/java/org/flowable/ui/application/FlowableUiApplicationWithEnabledRabbitTest.java
pom.xml

Updated dependencies as outlined in release notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.5.7

Upgrade to SpringBoot 2.5.7

---

modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/task/CmmnTaskQueryCaseVariablesTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/task/CmmnTaskQueryTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskQueryTest.java
modules/flowable-task-service-api/src/main/java/org/flowable/task/api/TaskInfo.java
modules/flowable-task-service-api/src/main/java/org/flowable/task/api/TaskInfoQuery.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/HistoricTaskInstanceQueryImpl.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/TaskQueryImpl.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/persistence/entity/HistoricTaskInstanceEntityImpl.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/persistence/entity/TaskEntityImpl.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/util/TaskVariableUtils.java
modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/HistoricTaskInstance.xml
modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/Task.xml
modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/AbstractVariableQueryImpl.java
modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/QueryVariableValue.java
modules/flowable5-compatibility/src/main/java/org/flowable/compatibility/wrapper/Flowable5TaskWrapper.java

Added support for querying Tasks by case instance variables

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/NeedsActiveTaskCmd.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskIdentityLinksTest.java
modules/flowable-identitylink-service/src/main/java/org/flowable/identitylink/service/impl/persistence/entity/data/impl/MybatisIdentityLinkDataManager.java

* Documentation: not needed, bugfix

Fix and unit tests for adding identityLink and complete Task in same transaction

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/dynamic/AbstractDynamicStateManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/migration/ProcessInstanceMigrationManagerImpl.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceMigrationCallActivityTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/runtime/migration/two-tasks-with-call-activity-with-timer.bpmn20.xml

Fix migration of call activities and boundary events

---

docs/userguide/README.md

Some little changes of a beginner  contributor.

Updated Readme.md under Userguide of Docs.

---

modules/flowable-job-service-api/src/main/java/org/flowable/job/api/TimerJobQuery.java

 @Override

---

docs/userguide/src/en/dmn/ch02-Configuration.adoc

fix: DMM->DMN

---

docs/userguide/src/zh_CN/single/ch01-Introduction.adoc
docs/userguide/src/zh_CN/single/ch01b-Concepts.adoc
docs/userguide/src/zh_CN/single/ch02-Engine.adoc
docs/userguide/src/zh_CN/single/ch04-Modeler.adoc

doc Chinese support

---

distro/src/notice.txt
modules/flowable-app-rest/src/test/java/org/flowable/rest/app/FlowableRestApplicationTest.java
modules/flowable-ui/flowable-ui-app/src/test/java/org/flowable/ui/application/FlowableUiApplicationTest.java
modules/flowable-ui/flowable-ui-app/src/test/java/org/flowable/ui/application/FlowableUiApplicationWithEnabledJmsKafkaAndRabbitTest.java
modules/flowable-ui/flowable-ui-app/src/test/java/org/flowable/ui/application/FlowableUiApplicationWithEnabledJmsTest.java
modules/flowable-ui/flowable-ui-app/src/test/java/org/flowable/ui/application/FlowableUiApplicationWithEnabledKafkaTest.java
modules/flowable-ui/flowable-ui-app/src/test/java/org/flowable/ui/application/FlowableUiApplicationWithEnabledRabbitTest.java
pom.xml

All in one PR; update SpringFramework to 5.3.14; Spring Security to 5.5.4; and SpringBoot to 2.6..2
Here are the release notes:
Spring Framework
5.3.14 https://github.com/spring-projects/spring-framework/releases/tag/v5.3.14
Spring Security
5.5.4 https://github.com/spring-projects/spring-security/releases/tag/5.5.4
Spring Boot
2.6.0 https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes
2.6.1 https://github.com/spring-projects/spring-boot/releases/tag/v2.6.1
2.6.2 https://github.com/spring-projects/spring-boot/releases/tag/v2.6.2

Upgrade Spring Framework/Security/Boot

---

modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/xml/converter/DMNDIExport.java

Remove unused import from today's commits

---

k8s/flowable/templates/ingress.yaml

Resolve #3163

---

modules/flowable5-spring-test/src/main/java/org/activiti/spring/impl/test/SpringFlowableTestCase.java

add @Override

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/HistoricPlanItemInstanceQueryProperty.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/async/AsyncCmmnHistoryTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/subprocess/CallActivityTest.java

Part of the periodic check of the code base.

Remove collections whose contents were updated but never queried.

---

modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/BaseBpmnJsonConverter.java
modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/BpmnJsonConverter.java
modules/flowable-json-converter/src/main/java/org/flowable/editor/language/json/converter/BpmnJsonConverterUtil.java

add if block with Code verification

---

distro/src/notice.txt
pom.xml

Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.6.3
FWIW, once again I didn't update MySQL to version 8.0.28 given previous comments about issues with newer versions.

Upgrade to SpringBoot 2.6.3

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/DeleteHistoricTaskInstanceCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/CmmnHistoryConfigurationSettings.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/CmmnHistoryManager.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/CompositeCmmnHistoryManager.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/DefaultCmmnHistoryConfigurationSettings.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/DefaultCmmnHistoryManager.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/async/AsyncCmmnHistoryManager.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/async/CmmnAsyncHistoryConstants.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/async/json/transformer/TaskDeletedHistoryJsonTransformer.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/async/AsyncCmmnHistoryTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/CmmnHistoryServiceDisableTaskLogTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/CmmnHistoryServiceTaskLogTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/api/runtime/TaskSubTaskCollectionResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricTaskInstanceResourceTest.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/DeleteHistoricTaskInstanceCmd.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/CompositeHistoryManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/DefaultHistoryConfigurationSettings.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/DefaultHistoryManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/HistoryConfigurationSettings.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/HistoryManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/async/AsyncHistoryManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/async/HistoryJsonConstants.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/async/json/transformer/TaskDeletedHistoryJsonTransformer.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskServiceTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/history/HistoricTaskInstanceTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/history/async/AsyncHistoryTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricTaskInstanceResourceTest.java

change deletion of historic task to go through the history manager

---

modules/flowable-engine/src/main/java/org/flowable/engine/ProcessEngine.java

Correct spelling errors in the comments.

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/AttachmentEventsTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/TaskEventsTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskServiceTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/history/HistoricTaskInstanceTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/task/StandaloneTaskTest.java
modules/flowable5-test/src/test/java/org/activiti/engine/test/api/event/StandaloneAttachmentEventsTest.java
modules/flowable5-test/src/test/java/org/activiti/engine/test/api/task/TaskServiceTest.java
modules/flowable5-test/src/test/java/org/activiti/engine/test/history/HistoricTaskInstanceTest.java

fix unit tests because of new checks in DeleteHistoricTaskInstanceCmd

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/DeleteHistoricTaskInstanceCmd.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/history/HistoricTaskInstanceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/history/HistoricTaskInstanceResourceTest.java

Remove unnecessary imports from recent commits

---

modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/db/ContentDbSchemaManager.java
modules/flowable-content-engine/src/test/java/org/flowable/content/engine/test/mgmt/ContentManagementServiceTest.java
modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/mgmt/DmnManagementServiceTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/mgmt/ManagementServiceTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/jpa/FieldAccessJPAEntity.java
modules/flowable-engine/src/test/java/org/flowable/standalone/jpa/PropertyAccessJPAEntity.java
modules/flowable-spring/src/test/java/org/flowable/spring/test/jpa/LoanRequest.java
modules/flowable5-spring-test/src/test/java/org/activiti/spring/test/jpa/LoanRequest.java
modules/flowable5-test/src/test/java/org/activiti/examples/mgmt/ManagementServiceTest.java
modules/flowable5-test/src/test/java/org/activiti/standalone/jpa/FieldAccessJPAEntity.java
modules/flowable5-test/src/test/java/org/activiti/standalone/jpa/PropertyAccessJPAEntity.java
pom.xml

fixes CVE-2021-42392 vulnerability

h2 update 2.0.206

---

docs/docusaurus/website/core/Footer.js

update javadoc link in documentation footer

---

modules/flowable-event-registry-rest/src/main/java/org/flowable/eventregistry/rest/service/api/runtime/EventInstanceCollectionResource.java
modules/flowable-event-registry-rest/src/test/java/org/flowable/eventregistry/rest/service/api/runtime/EventInstanceCollectionResourceTest.java

Fix bug of POST event with multiple definitions

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/CompleteTaskCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/event/FlowableCmmnEventBuilder.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/event/TaskAssignedEventTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/event/TaskCompletedEventTest.java

Add the task complete event support for CMMN based user tasks similar to process based tasks.

Add support for 'task complete' events within a CMMN based case

---

distro/src/notice.txt
pom.xml

Release notes are here: https://github.com/spring-projects/spring-framework/releases/tag/v5.3.17

Upgrade to Spring Framework 5.3.17

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/event/FlowableCaseEndedEvent.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/AbstractChangeCaseInstanceStateOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/CompleteCaseInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/TerminateCaseInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/event/FlowableCaseEndedEventImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/event/FlowableCmmnEventBuilder.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/event/CaseEndedEventTests.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/event/CaseStartedEventTest.java
modules/flowable-engine-common-api/src/main/java/org/flowable/common/engine/api/delegate/event/FlowableEngineEventType.java

whenever a case is ended either through completion or termination, a case ended event is created

add support for case ended events

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/HumanTaskActivityBehavior.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/event/FlowableCmmnEventBuilder.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/event/TaskCreatedEventTest.java

add event support for human task creation in the CMMN engine similar to the process engine

add support for task creation events in the CMMN engine

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/EventSubProcessEventRegistryStartEventActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/EventSubProcessMessageStartEventActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/EventSubProcessSignalStartEventActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/EventSubProcessTimerStartEventActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/EventSubProcessVariableListenerlStartEventActivityBehavior.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/event/ActivityEventsTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/message/MessageEventSubprocessTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/signal/SignalEventSubprocessTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/timer/TimerEventSubprocessTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/variable/VariableListenerEventSubprocessTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/eventregistry/EventRegistryEventSubprocessTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/message/MessageStartEventTest.MessageEventSubprocessAndCallActivity.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/signal/SignalEventSubprocessTest.SignalEventSubprocessAndCallActivity.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/signal/SignalEventSubprocessTest.SignalThrowProcess.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/timer/StartTimerEventTest.TimerEventSubprocessAndCallAvtivity.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/variable/VariableListenerEventTest.VariableEventSubprocessAndCallActivity.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/eventregistry/EventRegistryEventSubprocessTest.EventRegistryEventSubprocessAndCallActivity.bpmn20.xml

bug: CallActivity subprocess not ended properly when interrupted by EventSubprocess

fix interrupting EventSubprocess bug

---

modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/caze/CaseInstanceCollectionResource.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/CaseInstanceCollectionResourceTest.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/ProcessInstanceCollectionResource.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/ProcessInstanceCollectionResourceTest.java

InstanceCollectionResource throws exception for unkown action

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/CmmnHistoryService.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/CmmnHistoryServiceImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/BulkDeleteHistoricCaseInstancesCmd.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/async/AsyncCmmnHistoryTest.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/CmmnRestApiInterceptor.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/caze/HistoricCaseInstanceCollectionResource.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricCaseInstanceCollectionResourceTest.java

Bulk delete historic case instances

---

docker/base-image/Dockerfile
docker/base-image/README.md
docker/base-image/build.sh
docker/base-image/push.sh

Based on [eclipse-temurin:11.0.15_10-jre-alpine](https://hub.docker.com/layers/eclipse-temurin/library/eclipse-temurin/11.0.15_10-jre-alpine/images/sha256-37c5e98456f7a9a36d4e385a2d068963b82c1c8e2d4943610d93d13c5f65324a?context=explore)
Solves various security vulnerabilities.

Docker base image upgrade

---

.github/workflows/docker-release-with-latest.yml
.github/workflows/docker-release.yml
modules/flowable-app-rest/pom.xml
modules/flowable-ui/flowable-ui-app/pom.xml
pom.xml

* added 2 manual GH actions for releasing Docker images to DockerHub (with and without latest tag)
* added root pom profile for modules with Docker images
* added authentication config to Docker module poms (for injecting when running CI)

GitHub actions for releasing Docker images

---

modules/flowable-rest/src/main/java/org/flowable/rest/service/api/BpmnRestApiInterceptor.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/management/JobCollectionResource.java

added missing bpmn bulk move dead letter jobs rest api interceptor call

---

modules/flowable-ui/flowable-ui-admin-frontend/src/main/resources/static/admin/display-cmmn/cmmn-draw.js
modules/flowable-ui/flowable-ui-admin-frontend/src/main/resources/static/admin/display/bpmn-draw.js
modules/flowable-ui/flowable-ui-task-frontend/src/main/resources/static/display-cmmn/cmmn-draw.js

Added missing functions for rendering external worker service tasks in flowable ui-admin and ui-task.
Closes #3241

Added missing functions for rendering external worker service tasks

---

modules/flowable-app-engine/src/main/java/org/flowable/app/engine/impl/persistence/entity/AppDeploymentEntityImpl.java

toString has wrong entity name "CmmnDeploymentEntity" instead of "AppDeploymentEntity"

Wrong entity name

---

distro/src/notice.txt
pom.xml

Spring Boot 2.7.1
Spring Security 5.7.2

Update to Spring dependencies

---

modules/flowable-ui/flowable-ui-admin-frontend/src/main/resources/static/admin/display/bpmn-draw.js

Corrected the icon offset of the external worker service task icon in the flowable ui-admin.
Fixes #3383

Corrected position of external worker service task icon in flowable ui-admin

---

docs/docusaurus/docs/bpmn/ch02-GettingStarted.md

The curl example for creating deployment in rest mode should be post

Fix ch02-GettingStarted.adoc doc error

---

docs/docusaurus/docs/bpmn/ch15-REST.md

Create documentation for the deleteReason parameter of the DELETE process instance action
Also Fix '&gt;' character typo

Add deleteReason param to DELETE process instance

---

modules/flowable-ui/flowable-ui-admin-logic/src/main/java/org/flowable/ui/admin/service/engine/CaseInstanceService.java

Corrected the migration URL for CaseInstances.

---

modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/EventListenerConverterTest.java
modules/flowable-bpmn-converter/src/test/resources/eventlistenerscript.bpmn20.xml
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/scripting/AbstractScriptEvaluator.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/listener/ListenerNotificationHelper.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/listener/ScriptExecutingListener.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/listener/ScriptExecutionListener.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/listener/ScriptTaskListener.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/listener/ScriptTypeExecutionListener.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/listener/ScriptTypeTaskListener.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/parser/factory/DefaultListenerFactory.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/parser/factory/ListenerFactory.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/executionlistener/ScriptTypeExecutionListenerTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/tasklistener/TaskListenerTest.java
modules/flowable-engine/src/test/java/org/flowable/standalone/validation/DefaultProcessValidatorTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/validation/invalidProcess.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/executionlistener/ScriptTypeExecutionListenerTest.testExecutionListener.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/executionlistener/ScriptTypeExecutionListenerTest.testThrowFlowableIllegalArgumentException.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/executionlistener/ScriptTypeExecutionListenerTest.testThrowNonFlowableException.bpmn20.xml
modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/impl/ExecutionListenerValidator.java
modules/flowable-secure-javascript/src/main/java/org/flowable/scripting/secure/listener/SecureJavascriptExecutionListener.java

The executionListener extensions has been adapted to also support scripting natively.

Support script type executionListener (BPMN)

---

pom.xml

Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.7.2

Update to Spring Boot 2.7.2

---

modules/flowable-app-engine/src/test/java/org/flowable/bpmn/model/AbstractFlowableHttpHandlerTest.java
modules/flowable-app-engine/src/test/java/org/flowable/bpmn/model/FlowableListenerTest.java
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/AbstractFlowableHttpHandler.java
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/FlowableListener.java

Fixed clone glitch and added tests

---

modules/flowable-engine-common-api/src/main/java/org/flowable/common/engine/api/variable/EmptyVariableContainer.java
modules/flowable-engine-common-api/src/main/java/org/flowable/common/engine/api/variable/VariableContainer.java
modules/flowable-engine-common/pom.xml
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/scripting/AbstractScriptEvaluator.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/scripting/MapResolver.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/scripting/ScriptBindingsFactory.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/scripting/ScriptEngineRequest.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/scripting/ScriptingEngines.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/variable/MapDelegateVariableContainer.java
modules/flowable-engine-common/src/test/java/org/flowable/common/engine/impl/ScriptingEnginesTest.java
modules/flowable-engine-common/src/test/java/org/flowable/common/engine/impl/variable/MapDelegateVariableContainerTest.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/http/handler/ScriptHttpHandler.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/listener/ScriptExecutionListener.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/listener/ScriptTaskListener.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/listener/ScriptTypeExecutionListener.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/listener/ScriptTypeTaskListener.java
modules/flowable-http/src/test/java/org/flowable/http/bpmn/HttpServiceTaskTest.java
modules/flowable-osgi/src/main/java/org/flowable/osgi/OsgiScriptingEngines.java
modules/flowable-secure-javascript/src/main/java/org/flowable/scripting/secure/impl/SecureJavascriptUtil.java
modules/flowable-secure-javascript/src/main/java/org/flowable/scripting/secure/impl/SecureScriptScope.java
modules/flowable-secure-javascript/src/main/java/org/flowable/scripting/secure/listener/SecureJavascriptExecutionListener.java
modules/flowable-variable-service-api/src/main/java/org/flowable/variable/api/delegate/EmptyVariableScope.java
modules/flowable-variable-service-api/src/main/java/org/flowable/variable/api/delegate/VariableScope.java

* Introduce ScriptEngineRequest and Builder for ScriptingEngines
* Allow to contribute additional script Resolvers in ScriptEngineRequest 
* Fix typo in AbstractScriptEvaluator

Provide additional Resolver for script evaluation

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/mgmt/JobQueryTest.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/DeadLetterJobQueryImpl.java

Corrected dead letter job query external worker filter (#3415)

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/child/FlowableListenerParser.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/util/ListenerXmlConverterUtil.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/scripting/CmmnVariableScopeResolverFactory.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricTaskInstanceCollectionResourceTest.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/scripting/ResolverFactory.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/helper/ClassDelegate.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/executionlistener/ExecutionListenerTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/executionlistener/JavaDelegateTestExecutionListener.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/tasklistener/TaskListenerTest.java

Chore: Periodic removal of unused imports

---

pom.xml

Release Notes:  https://github.com/spring-projects/spring-security/releases/tag/5.7.3

Chore: Upgrade to Spring Security 5.7.3

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/CmmnRuntimeService.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/HasPlanItemInstanceVariableCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CmmnRuntimeServiceImpl.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/PlanItemInstanceQueryTest.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/CmmnRestResponseFactory.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/CmmnRestUrls.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/caze/BaseVariableResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/caze/CaseInstanceVariableResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/caze/PlanItemInstanceVariableDataResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/caze/PlanItemVariableResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskVariableBaseResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/variable/VariableInstanceQueryRequest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/CaseInstanceVariableResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/CaseInstanceVariablesCollectionResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/PlanItemVariableResourceTest.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/ExecutionVariableResource.java

added endpoint to expose update and delete actions for plan item instance variables

---

modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/JobQueryImpl.java

* Added getter for handlerTypes in JobQueryImpl
* fixes #3437

fix: added getHandlerTypes()

---

distro/src/notice.txt
pom.xml

Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.7.3

Update to Spring Boot 2.7.3

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/scripting/CmmnEngineScriptTraceEnhancer.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/scripting/CompositeScriptTraceListener.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/scripting/ScriptTraceEnhancer.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/scripting/ProcessEngineScriptTraceEnhancer.java

* Unit tests: not required (available)

Improve ScriptTraceEnhancer implementation to be more flexible

---

modules/flowable-ui/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/DisplayJsonClientResource.java
modules/flowable-ui/flowable-ui-common/src/main/java/org/flowable/ui/common/model/UserRepresentation.java
modules/flowable-ui/flowable-ui-idm-logic/src/main/java/org/flowable/ui/idm/model/UpdateUsersRepresentation.java
modules/flowable-ui/flowable-ui-idm-rest/src/main/java/org/flowable/ui/idm/rest/app/IdmProfileResource.java
modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/BpmnDisplayJsonConverter.java
modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/CmmnDisplayJsonConverter.java
modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/DmnDisplayJsonConverter.java
modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/FlowableDecisionServiceService.java
modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/FlowableDecisionTableService.java
modules/flowable-ui/flowable-ui-task-logic/src/main/java/org/flowable/ui/task/model/debugger/BreakpointRepresentation.java

add if block

---

modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/task/HistoricTaskInstanceBaseResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/task/HistoricTaskInstanceCollectionResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/task/HistoricTaskInstanceQueryRequest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricTaskInstanceCollectionResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricTaskInstanceQueryResourceTest.java

exposed planItemInstanceID for historic task instance queries

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/StartEventXMLConverter.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/StartEventRegistryEventConverterTest.java
modules/flowable-bpmn-converter/src/test/resources/startEventRegistryEvent.bpmn

Fixed export of start event registry event isInterrupting flag (#3476)

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/runtime/PlanItemDefinitionType.java

added missing PlanItemDefiintionTypes.

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/dynamic/AbstractDynamicStateManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/migration/ProcessInstanceMigrationManagerImpl.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceDirectExecutionMigrationExternalWorkerTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/runtime/migration/one-external-worker-simple-process.bpmn20.xml
modules/flowable-job-service/src/main/resources/org/flowable/job/service/db/mapping/entity/DeadLetterJob.xml
modules/flowable-job-service/src/main/resources/org/flowable/job/service/db/mapping/entity/SuspendedJob.xml

Added support for direct execution migration of external worker service tasks (#3461)

---

docs/docusaurus/website/package.json

Without this dependency the website won't work locally

Add missing react dependency to docusaurus

---

modules/flowable-ui/flowable-ui-modeler-frontend/src/main/resources/static/modeler/i18n/en.json

Improve wording to make clear those settings belong together.

Tiny ui improvement for error variable name and related

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/ServiceTaskWithFuturesNoQueueCapacityTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/ServiceTaskWithFuturesTest.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/async/AsyncTaskExecutorConfiguration.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/async/DefaultAsyncTaskExecutor.java
modules/flowable-engine/src/main/java/org/flowable/engine/ProcessEngineConfiguration.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/servicetask/ServiceTaskWithFuturesNoQueueCapacityTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/servicetask/ServiceTaskWithFuturesTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/FlowableJobConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ProcessEngineAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/cmmn/CmmnEngineAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/cmmn/CmmnEngineAutoConfigurationTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/process/ProcessEngineAutoConfigurationTest.java

Add dedicated task executor for the task invoker

---

modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/history/HistoricTaskInstanceQueryResourceTest.java
modules/flowable-engine/src/main/java/org/flowable/engine/ProcessEngineConfiguration.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/dynamic/AbstractDynamicStateManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/migration/ProcessInstanceMigrationManagerImpl.java
modules/flowable-http/src/main/java/org/flowable/http/HttpRequest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/cmmn/CmmnEngineAutoConfiguration.java

Chore: Periodic check for unused imports

---

modules/flowable-dmn-engine/src/main/resources/org/flowable/dmn/db/mapping/entity/HistoricDecisionExecution.xml
modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/history/HistoryTest.java

Fix HistoricDecisionExecution.xml native query typo + unit test

---

docs/docusaurus/docs/bpmn/ch07b-BPMN-Constructs.md
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/UserTaskActivityBehavior.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/TaskHelper.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/tasklistener/TaskListenerTest.java
modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/tasklistener/TaskListenerTest.throwBpmnErrorCatchEventSubProcess.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/tasklistener/TaskListenerTest.throwBpmnErrorCatchEventSubProcessMultiInstance.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/examples/bpmn/tasklistener/TaskListenerTest.throwBpmnErrorCatchParentBoundaryEvent.bpmn20.xml

#3452 support throwing bpmn exception in task listeners

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/event/signal/SignalEventTest.java

Add missing history level check

---

modules/flowable5-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricTaskInstance.xml

Fix a SQL error in HistorictaskInstance.xml

Fix sql error.

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/IdentityLinkUtil.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/usertask/TestListener.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/usertask/UserTaskTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/cfg/executioncount/VerifyDatabaseOperationsTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/usertask/UserTaskTest.testIdentityLinkNotDuplicate.bpmn20.xml
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/persistence/entity/TaskEntity.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/persistence/entity/TaskEntityImpl.java

Not sure if my fix is the proper way to fix this issue. For now, it just makes the testcase pass.

#3467 Fix duplicate addition of same identity link in IdentityLinkUtil

---

distro/src/notice.txt
pom.xml

Release Notes: https://github.com/spring-projects/spring-security/releases/tag/5.8.1

Upgrade to Spring Security 5.8.1

---

modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/BaseSpringRestTestCase.java
modules/flowable-event-registry-spring/src/test/java/org/flowable/eventregistry/spring/test/jms/JmsChannelDefinitionProcessorTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ProcessEngineServicesAutoConfiguration.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/app/AppEngineAutoConfiguration.java

Remove unused imports that occurred as a result of pushed in late November/early December of last year.

Chore: removed unused imports

---

modules/flowable-batch-service-api/src/main/java/org/flowable/batch/api/Batch.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/CaseInstanceBatchMigrationPartResult.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/CaseInstanceBatchMigrationResult.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/CaseInstanceMigrationBatchCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/GetCaseInstanceMigrationBatchResultCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/job/AbstractCaseInstanceMigrationJobHandler.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/job/CaseInstanceMigrationJobHandler.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/job/CaseInstanceMigrationStatusJobHandler.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/migration/CaseInstanceMigrationManagerImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/impl/CmmnJobTestHelper.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/migration/AbstractCaseMigrationTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/migration/CaseInstanceMigrationBatchTest.java

Support batch migration for CMMN

---

modules/flowable-batch-service-api/src/main/java/org/flowable/batch/api/Batch.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/CaseInstanceBatchMigrationPartResult.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/CaseInstanceBatchMigrationResult.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/CaseInstanceMigrationBatchCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/GetCaseInstanceMigrationBatchResultCmd.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/job/AbstractCaseInstanceMigrationJobHandler.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/job/CaseInstanceMigrationJobHandler.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/job/CaseInstanceMigrationStatusJobHandler.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/migration/CaseInstanceMigrationManagerImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/impl/CmmnJobTestHelper.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/migration/AbstractCaseMigrationTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/migration/CaseInstanceMigrationBatchTest.java

* Support Batch Migration for CaseInstances
Backport to flowable6.x

Support batch migration for CMMN (#3588)

---

distro/src/notice.txt
pom.xml

Release Notes: https://github.com/spring-projects/spring-framework/releases/tag/v6.0.4

Upgrade to Spring Framework 6.0.4

---

modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/persistence/entity/ByteArrayEntityManager.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/persistence/entity/ByteArrayEntityManagerImpl.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/persistence/entity/data/ByteArrayDataManager.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/persistence/entity/data/impl/MybatisByteArrayDataManager.java
modules/flowable-engine-common/src/main/resources/org/flowable/common/db/mapping/entity/ByteArray.xml
modules/flowable-engine/src/test/java/org/flowable/engine/test/jobexecutor/BulkMoveTimerJobsToExecutableJobsTest.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/AbstractJobServiceEngineEntityManager.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/TimerJobEntityManagerImpl.java

fix byte arrays not being deleted when bulk deleting timer jobs

---

pom.xml

Release Notes for 2.7.7 https://github.com/spring-projects/spring-boot/releases/tag/v2.7.7
Release Notes for 2.7.8  https://github.com/spring-projects/spring-boot/releases/tag/v2.7.8
**NOTE:**  I did **not** update the JDBC dependencies (MariaDB, MS SQL, etc.) because I think there were issues with such changes previously.  Please review and if corrections are needed please let me know.
Thanks.

Upgrade to Spring Boot 2.7.8 for flowable6.x branch

---

modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/agenda/CommonAgenda.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/CountingEntityUtil.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/mgmt/ManagementServiceTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/cmd/FailedJobRetryCmdTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/cmd/FailingDelegate.java
modules/flowable-http-common/src/main/java/org/flowable/http/common/impl/apache/client5/ApacheHttpComponents5FlowableHttpClient.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/cmd/ExecuteJobCmd.java
modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/persistence/entity/AbstractJobServiceEngineEntityManager.java

Chore: remove unused imports from recent commits

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/MailActivityBehavior.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/task/CmmnMailTaskTest.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/MailActivityBehavior.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailServiceTaskTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/mail/EmailServiceTaskTest.testDynamicRecipients.bpmn20.xml

Accept Collection and JsonArray as mail recipients in MailActivityBehavior

---

modules/flowable-form-api/src/main/java/org/flowable/form/api/FormDefinitionQuery.java

Fixed typo in the comment of FormDefinitionQuery.latestVersion()

---

distro/src/notice.txt
pom.xml

Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v3.1.2

Upgrade to Spring Boot 3.1.2 and updated dependencies

---

modules/flowable-app-engine-rest/src/main/java/org/flowable/app/rest/AppRestResponseFactory.java
modules/flowable-app-engine-rest/src/test/java/org/flowable/app/rest/service/api/repository/AppDefinitionResourceTest.java
modules/flowable-app-engine-rest/src/test/java/org/flowable/app/rest/service/api/repository/DeploymentResourcesResourceTest.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/CmmnRestResponseFactory.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/repository/BaseDeploymentResourceDataResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/repository/DeploymentResourceResource.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/repository/DeploymentResourcesResourceTest.java
modules/flowable-common-rest/src/main/java/org/flowable/common/rest/resolver/DefaultContentTypeResolver.java
modules/flowable-common-rest/src/test/java/org/flowable/common/rest/resolver/DefaultContentTypeResolverTest.java
modules/flowable-event-registry-rest/src/main/java/org/flowable/eventregistry/rest/service/api/EventRegistryRestResponseFactory.java
modules/flowable-event-registry-rest/src/main/java/org/flowable/eventregistry/rest/service/api/repository/BaseDeploymentResourceDataResource.java
modules/flowable-event-registry-rest/src/main/java/org/flowable/eventregistry/rest/service/api/repository/DeploymentResourceResource.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/repository/DeploymentResourcesResourceTest.java

Make it easier to provide custom extensions for the ContentTypeResolver

---

docs/docusaurus/docs/bpmn/ch04-API.md
docs/userguide/src/zh_CN/bpmn/ch04-API.adoc

Fix typo in docs

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoricProcessInstanceAndVariablesQueryTest.java

Old style JUnit test method in JUnit 4 class; add missing annoation

Chore: add missing @Test annotation

---

modules/flowable-app-engine-rest/src/main/java/org/flowable/app/rest/service/api/repository/AppDeploymentCollectionResource.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/http/DefaultCmmnHttpActivityDelegate.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/history/task/HistoricTaskInstanceResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/management/JobCollectionResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/repository/DeploymentResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/caze/CaseInstanceIdentityLinkCollectionResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskVariableDataResource.java
modules/flowable-engine/src/main/java/org/flowable/engine/ProcessEngineConfiguration.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/http/DefaultBpmnHttpActivityDelegate.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailServiceTaskTest.java
modules/flowable-event-registry-spring/src/main/java/org/flowable/eventregistry/spring/management/DefaultSpringEventRegistryChangeDetectionExecutor.java
modules/flowable-event-registry-spring/src/test/java/org/flowable/eventregistry/spring/test/rabbit/EventRegistryRabbitConfiguration.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/history/HistoricTaskInstanceResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/SignalResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/ExecutionVariableDataResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskVariableCollectionResource.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/handler/AbstractActivityBpmnParseHandler.java
modules/flowable5-test/src/test/java/org/activiti/engine/test/bpmn/mail/EmailServiceTaskTest.java

Remove unused imports and occasionally reorder them too so as to match project standards.

Chore: remove 23 unused imports

---

modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/CaseInstanceCollectionResourceTest.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/el/function/AbstractVariableComparatorExpressionFunction.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/IntermediateThrowSignalEventActivityBehavior.java
modules/flowable-event-registry-spring/src/test/java/org/flowable/eventregistry/spring/test/jms/JmsChannelDefinitionProcessorTest.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/HistoricTaskInstanceQueryImpl.java
modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/TaskQueryImpl.java

Chore: remove duplicated semicolon

---

distro/src/notice.txt
pom.xml

Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v3.1.3

Upgrade to Spring Boot 3.1.3

---

modules/flowable-event-registry-integration-test/src/test/java/org/flowable/eventregistry/integrationtest/CaseWithEventRegistryTest.java
modules/flowable-event-registry-integration-test/src/test/resources/org/flowable/eventregistry/integrationtest/oneJson.event
modules/flowable-event-registry-integration-test/src/test/resources/org/flowable/eventregistry/integrationtest/testSendEventTaskWithJson.cmmn
modules/flowable-event-registry/src/main/java/org/flowable/eventregistry/impl/serialization/EventPayloadToJsonStringSerializer.java

Handle Supplier<JsonNode> for EventPayloadToJsonStringSerializer

---

modules/flowable-event-registry-integration-test/src/test/java/org/flowable/eventregistry/integrationtest/CaseWithEventRegistryTest.java
modules/flowable-event-registry-integration-test/src/test/resources/org/flowable/eventregistry/integrationtest/oneJson.event
modules/flowable-event-registry-integration-test/src/test/resources/org/flowable/eventregistry/integrationtest/testSendEventTaskWithJson.cmmn
modules/flowable-event-registry/src/main/java/org/flowable/eventregistry/impl/serialization/EventPayloadToJsonStringSerializer.java

Handle Supplier<JsonNode> for EventPayloadToJsonStringSerializer (#3722)

---

distro/src/notice.txt
pom.xml

Release Notes: https://github.com/spring-projects/spring-framework/releases/tag/v6.0.12

Upgrade to Spring Framework 6.0.12

---

distro/src/notice.txt
pom.xml

Release Notes: https://github.com/spring-projects/spring-framework/releases/tag/v5.3.30

Upgrade to Spring Framework 5.3.30 for 6.x branch

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/runtime/CaseInstanceQuery.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CaseInstanceQueryImpl.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CaseInstanceQueryImplTest.java

Expose filtering by caseDefinitionIds

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/DeleteRelatedDataOfRemovedHistoricCaseInstancesCmd.java

Added condition check for enabled entity link before deleting

---

modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskBaseResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskCollectionResource.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/task/TaskQueryRequest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/TaskCollectionResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/TaskQueryResourceTest.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskBaseResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskCollectionResource.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskQueryRequest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/TaskCollectionResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/TaskQueryResourceTest.java

exposed taskId to query for runtime tasks

---

modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/StageXmlConverter.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/StageExport.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/StageActivityBehavior.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/StageTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/StageTest.testStageBusinessStatus.cmmn
modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/Stage.java

Add property to update case business status when stage becomes active

---

distro/src/notice.txt
pom.xml

Release Notes:  https://github.com/spring-projects/spring-boot/releases/tag/v3.1.6

Upgrade to Spring Boot 3.1.6 and Spring Framework 6.0.14

---

modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/planitem/PlanItemInstanceBaseResource.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/PlanItemInstanceResourceTest.java
modules/flowable-cmmn-rest/src/test/resources/org/flowable/cmmn/rest/service/api/runtime/twoHumanTaskCase.cmmn

Plan item instance resource fix

---

modules/flowable-engine/src/test/java/org/flowable/engine/test/eventregistry/DynamicProcessStartEventRegistryDeploymentTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/eventregistry/DynamicProcessStartEventRegistryDeploymentTest.testStaticEventRegistryProcessWithCorrelationParameter.bpmn20.xml
modules/flowable-engine/src/test/resources/org/flowable/engine/test/eventregistry/DynamicProcessStartEventRegistryDeploymentTest.testStaticEventRegistryProcessWithCorrelationParameters.bpmn20.xml

Add test for correlation parameters directly defined in event registry start event

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/job/CmmnHistoryCleanupJobHandler.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/CmmnHistoryServiceTaskLogTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/prefix/CmmnPrefixTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CaseInstanceInvolvementTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/VariablesTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/task/CmmnTaskServiceTest.java
modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/engine/test/MixedDeploymentTest.java
modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/test/runtime/DecisionTaskTest.java
modules/flowable-dmn-engine/src/test/java/org/flowable/dmn/engine/test/runtime/DecisionTableExecutionFallBackTest.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/jobexecutor/BpmnHistoryCleanupJobHandler.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryServiceTaskLogTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/AbstractProcessInstanceMigrationTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceMigrationCallActivityTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceMigrationDocumentTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceMigrationTest.java
modules/flowable-http/src/test/java/org/flowable/http/bpmn/HttpServiceTaskTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/spring/boot/ldap/FlowableLdapPropertiesTest.java
modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/test/java/org/flowable/test/spring/boot/process/ProcessEngineAutoConfigurationTest.java

* Use `BatchQuery#delete` instead of `BatchQuery#deleteWithRelatedData`
* Use AssertJ `assertThatThrownBy` instead of JUnit 4 `ExpectedException` rule
* Use AssertJ recursive assertion instead of `isEqualToComparingFieldByField` and replace `getCause` with `cause`

Change usage of some deprecated code

---

modules/flowable-dmn-rest/src/main/java/org/flowable/dmn/rest/service/api/history/BaseHistoricDecisionExecutionResource.java

Make sure NotFoundException for decision execution is thrown before possible NPE in restApiInterceptor

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/DefaultHistoryConfigurationSettings.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/DefaultHistoryManager.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/HistoryConfigurationSettings.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/HistoricProcessInstanceEntityManagerImpl.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/history/DeleteHistoricProcessInstanceTest.java

added check of definition level for deleting varaibles.

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/CaseInstanceQueryProperty.java
modules/flowable-cmmn-rest/src/main/java/org/flowable/cmmn/rest/service/api/runtime/caze/BaseCaseInstanceResource.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/CaseInstanceCollectionResourceTest.java
modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/CaseInstanceQueryResourceTest.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/ProcessInstanceQueryProperty.java
modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/BaseProcessInstanceResource.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/ProcessInstanceCollectionResourceTest.java
modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/ProcessInstanceQueryResourceTest.java

Sort runtime instances by business key

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/ActivatePlanItemDefinitionMapping.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/MoveToAvailablePlanItemDefinitionMapping.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/PlanItemDefinitionMapping.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/PlanItemDefinitionMappingBuilder.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/RemoveWaitingForRepetitionPlanItemDefinitionMapping.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/TerminatePlanItemDefinitionMapping.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/WaitingForRepetitionPlanItemDefinitionMapping.java
modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/runtime/ChangePlanItemStateBuilder.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/el/PlanItemInstancesWrapper.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/migration/CaseInstanceMigrationDocumentConstants.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/migration/CaseInstanceMigrationDocumentConverter.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/migration/CaseInstanceMigrationManagerImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/AbstractCmmnDynamicStateManager.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/ChangePlanItemStateBuilderImpl.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/migration/CaseInstanceMigrationTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/stage-three-tasks-two-new.cmmn.xml
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/stage-three-tasks.cmmn.xml
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/stage-with-event-listener-inside.cmmn.xml
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/stage-with-user-event-listener-and-task-with-repetition.cmmn.xml
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/stage-with-user-event-listener-and-task.cmmn.xml
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/stage-without-event-listener-inside.cmmn.xml
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/two-task-repetition.cmmn.xml
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/user-event-listener-with-repetition.cmmn.xml
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/user-event-listener-without-repetition.cmmn.xml

add the option to add conditional to the specific case migration steps to make them optional during running through case migration

add condition attribute for case migration mappings

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/AbstractCmmnDynamicStateManager.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/migration/CaseInstanceMigrationTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/case-with-subcase.cmmn.xml
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/case-without-subcase.cmmn.xml

terminate sub-cases with terminate mapping during case migration

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/AbstractCmmnDynamicStateManager.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/migration/CaseInstanceMigrationTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/task-followed-by-stage.cmmn.xml

allow to move already available plan items to available without failing

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/migration/CaseInstanceMigrationBuilderImpl.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/migration/CaseInstanceMigrationTest.java

add pre- and post upgrade expressions to migration builder

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/AbstractCmmnDynamicStateManager.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/migration/CaseInstanceMigrationTest.java

add support for conditional during move to available when plan items already active

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/migration/CaseInstanceMigrationDocumentBuilder.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/migration/CaseInstanceMigrationBuilderImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/migration/CaseInstanceMigrationDocumentBuilderImpl.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/migration/CaseInstanceMigrationTest.java

add change plan item id (with definition) mapping to migration builder

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/DefaultCmmnHistoryManager.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/HistoryLevelServiceTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/history/testOneSimpleHumanTaskWithHistoryLevelNone.cmmn
modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/DefaultHistoryManager.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/history/HistoryLevelServiceTest.java

task log entries are no longer created if the history level is NONE

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/child/VariableListenerEventDefinitionParser.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/VariableListenerEventDefinitionParserTest.java
modules/flowable-bpmn-converter/src/test/resources/missingVariableListenerVariableName.bpmn
modules/flowable-engine/src/test/java/org/flowable/standalone/validation/DefaultProcessValidatorTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/validation/missingVariableEventListenerVariableName.xml
modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/Problems.java
modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/impl/EventSubprocessValidator.java

refactored validation check for event variable listeners variable name

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/dynamic/AbstractDynamicStateManager.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/migration/ProcessInstanceDirectExecutionMigrationExternalWorkerTest.java
modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/runtime/migration/one-async-external-worker-simple-process.bpmn20.xml

Fixed update of a migrated async external worker job with the new process definition id (#3894)

---

modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/BaseBpmnXMLConverter.java
modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/BpmnXMLConverter.java
modules/flowable-bpmn-converter/src/main/java/org/flowable/bpmn/converter/BpmnXMLConverterOptions.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/NameWithNewLineTest.java
modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/util/XmlTestUtils.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnXmlConverter.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/CmmnXmlConverterOptions.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/AbstractPlanItemDefinitionExport.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/AbstractServiceTaskExport.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/CaseTaskExport.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/DecisionTaskExport.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/PlanFragmentExport.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/PlanItemDefinitionExport.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/ProcessTaskExport.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/StageExport.java
modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/TimerEventListenerExport.java
modules/flowable-cmmn-converter/src/test/java/org/flowable/test/cmmn/converter/util/XmlTestUtils.java

Make the element name extension element (PR #3946) that is added in case the name has any new lines optional

Make element name extension element in case of new line optional

---

modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/runtime/PlanItemInstanceQuery.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/persistence/entity/data/impl/MybatisPlanItemInstanceDataManagerImpl.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/runtime/PlanItemInstanceQueryImpl.java
modules/flowable-cmmn-engine/src/main/resources/org/flowable/cmmn/db/mapping/entity/PlanItemInstance.xml
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/history/PlanItemInstanceHistoryServiceTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/CasePageTaskTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/PlanItemInstanceQueryTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/RuntimeServiceTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/tenant/MultiTenantTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/PlanItemInstanceQueryTest.testOrQueryByCompletable.cmmn
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/PlanItemInstanceQueryTest.testOrQueryByStages.cmmn
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/runtime/PlanItemInstanceQueryTest.testQueryByDerivedCaseDefinitionId.cmmn

added or query filter for PlanItemInstanceQueries

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/migration/CaseInstanceMigrationDocumentConverter.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/migration/CaseInstanceMigrationTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/migration/three-tasks-with-sentry.cmmn.xml

Parse localVariables from json CaseInstanceMigrationDocument

---

modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/HasValidateFormFields.java
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/UserTask.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/CompleteTaskWithFormCmd.java
modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/HasValidateFormFields.java
modules/flowable-cmmn-model/src/main/java/org/flowable/cmmn/model/HumanTask.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/CompleteTaskWithFormCmd.java

added HasValidateFormFields interface

---

modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/CompleteTaskWithFormCmd.java

Not too bad; the only unused import in about the last 45 days

Chore: remove unused import

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/test/AbstractFlowableCmmnTestCase.java

Chore: arguments in wrong order

---

modules/flowable-bpmn-converter/src/test/java/org/flowable/editor/language/xml/FormAwareServiceTaskConverterTest.java
modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/FormAwareServiceTask.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/parser/handler/FormAwareServiceTaskParseHandler.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/parser/handler/ServiceTaskParseHandler.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/el/VariableContainerWrapper.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/parser/handler/FormAwareServiceTaskParseHandler.java

Chore: remove 31 unused imports from recent commits

Chore: remove 31 unused imports from recent commits

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/VariableEventListenerActivityBehaviour.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/eventlistener/VariableEventListenerTest.java
modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/eventlistener/VariableEventListenerTest.testVariableEventListenerWithAvailableCondition.cmmn

Consider available conditions when creating variable event listeners

---

modules/flowable-http-common/src/main/java/org/flowable/http/common/impl/apache/client5/ApacheHttpComponents5FlowableHttpClient.java
modules/flowable-http/src/test/java/org/flowable/http/bpmn/HttpServiceTaskApacheHttpClient5Test.java
modules/flowable-http/src/test/java/org/flowable/http/bpmn/HttpServiceTaskSpringWebClientTest.java
modules/flowable-http/src/test/java/org/flowable/http/bpmn/HttpServiceTaskTest.java
modules/flowable-http/src/test/java/org/flowable/http/bpmn/HttpServiceTaskTestServer.java
modules/flowable-http/src/test/resources/org/flowable/http/bpmn/HttpServiceTaskTest.testHttpGetNonSpecStatusCode.bpmn20.xml

Make sure that non spec HTTP status code does not fail when using Apache HttpClient 5

---

modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/eventregistry/DynamicCaseStartEventRegistryDeploymentTest.java
modules/flowable-common-rest/src/test/java/org/flowable/common/rest/api/DateFormattingTest.java
modules/flowable-dmn-xml-converter/src/test/java/org/flowable/dmn/xml/DMNValidation.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/eventregistry/DynamicProcessStartEventRegistryDeploymentTest.java

removed org.junit.jupiter.api.Assertions from tests

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/scripting/CmmnVariableScopeResolver.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/scripting/VariableScopeResolver.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/tasklistener/ScriptTaskListenerTest.java
modules/flowable-engine/src/test/java/org/flowable/examples/bpmn/tasklistener/TaskListenerTest.java

Add option to disable access to services in scripts

---

modules/flowable-event-registry-spring/src/test/java/org/flowable/eventregistry/spring/test/kafka/EventRegistryKafkaConfiguration.java
modules/flowable-event-registry-spring/src/test/java/org/flowable/eventregistry/spring/test/kafka/KafkaChannelDefinitionProcessorTest.java
modules/flowable-event-registry-spring/src/test/java/org/flowable/eventregistry/spring/test/kafka/KafkaChannelRebootEngineTest.java

Change Kafka container to apache/kafka-native and enable tests

---

modules/flowable-app-engine/src/main/java/org/flowable/app/engine/AppEngineConfiguration.java
modules/flowable-app-rest/src/test/java/org/flowable/rest/app/variable/MaxAllowedShortStringVariableLengthTest.java
modules/flowable-app-rest/src/test/java/org/flowable/rest/app/variable/MaxAllowedVariableLengthTest.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/CmmnEngineConfiguration.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/MaxAllowedShortStringVariableLengthTest.java
modules/flowable-cmmn-engine/src/test/java/org/flowable/cmmn/test/runtime/MaxAllowedVariableLengthTest.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/AbstractEngineConfiguration.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/variable/MaxAllowedLengthVariableVerifier.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/variable/NoopVariableLengthVerifier.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/variable/VariableLengthVerifier.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/variable/MaxAllowedShortStringVariableLengthTest.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/variable/MaxAllowedVariableLengthTest.java
modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/types/ByteArrayType.java
modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/types/JsonType.java
modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/types/LongStringType.java
modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/types/SerializableType.java
modules/flowable-variable-service/src/main/java/org/flowable/variable/service/impl/types/StringType.java
modules/flowable5-engine/src/main/java/org/activiti/engine/impl/variable/SerializableType.java

Add an interface that can be customized for the variable length verifier

---

.github/workflows/docker-flowable-base-image-java.yml

removed test tag postfix

---

modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/CompleteCaseInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/agenda/operation/TerminateCaseInstanceOperation.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/CmmnHistoryManager.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/CompositeCmmnHistoryManager.java
modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/history/DefaultCmmnHistoryManager.java

Chore: remove more unneeded import statements

---

modules/flowable-dmn-xml-converter/src/main/java/org/flowable/dmn/converter/child/InputEntryParser.java
modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/calendar/CronExpression.java
modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/CallActivityBehavior.java
modules/flowable-engine/src/test/java/org/flowable/engine/test/concurrency/SetRandomVariablesTaskListener.java
modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/impl/authentication/ApacheDigester.java
modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/impl/persistence/entity/AbstractIdmEngineEntityManager.java

Chore: use enhanced switch syntax
